# Generated by Django 4.1.3 on 2023-02-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companyuseremployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuseremployee',
            name='is_created_company',
            field=models.BooleanField(default=False, verbose_name='company user created'),
        ),
    ]
