# Generated by Django 4.1.3 on 2023-04-12 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuseremployee',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_user_employee_set_employee', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='companyuseremployee',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_user_employee_set_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
