# Generated by Django 4.1.3 on 2023-11-15 17:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('tenant', '0001_initial'),
        ('base', '0001_initial'),
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='fax'),
        ),
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('definition_inventory_valuation', models.SmallIntegerField(choices=[(0, 'Perpetual inventory'), (1, 'Periodic inventory')], default=0)),
                ('default_inventory_value_method', models.SmallIntegerField(choices=[(0, 'FIFO'), (1, 'Cumulative weighted average'), (2, 'Weighted average'), (3, 'Specific identification method')], default=0)),
                ('cost_per_warehouse', models.BooleanField(default=False)),
                ('cost_per_lot_batch', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_setting', to='company.company')),
                ('primary_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.currency')),
            ],
            options={
                'verbose_name': 'Company Setting',
                'verbose_name_plural': 'Company Settings',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CompanyFunctionNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('function', models.SmallIntegerField(choices=[(0, 'Opportunity'), (1, 'Sale quotation'), (2, 'Sale order'), (3, 'Picking'), (4, 'Delivery'), (5, 'Task'), (6, 'Advance payment'), (7, 'Payment'), (8, 'Return payment'), (9, 'Purchase request')])),
                ('numbering_by', models.SmallIntegerField(choices=[(0, 'System'), (1, 'User defined')], default=0)),
                ('schema', models.CharField(max_length=500, null=True)),
                ('schema_text', models.CharField(max_length=500, null=True)),
                ('first_number', models.IntegerField(null=True)),
                ('last_number', models.IntegerField(null=True)),
                ('reset_frequency', models.SmallIntegerField(choices=[(0, 'Yearly'), (1, 'Monthly'), (2, 'Weekly'), (3, 'Daily'), (4, 'Never')], null=True)),
                ('latest_number', models.IntegerField(null=True)),
                ('year_reset', models.IntegerField(null=True)),
                ('month_reset', models.IntegerField(null=True)),
                ('week_reset', models.IntegerField(null=True)),
                ('day_reset', models.IntegerField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_function_number', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Company Function Number',
                'verbose_name_plural': 'Company Functions Number',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
