# Generated by Django 4.1.3 on 2023-11-17 10:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cost_per_lot_batch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='cost_per_warehouse',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='default_inventory_value_method',
            field=models.SmallIntegerField(choices=[(0, 'FIFO'), (1, 'Cumulative weighted average'), (2, 'Weighted average'), (3, 'Specific identification method')], default=2),
        ),
        migrations.AddField(
            model_name='company',
            name='definition_inventory_valuation',
            field=models.SmallIntegerField(choices=[(0, 'Perpetual inventory'), (1, 'Periodic inventory')], default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='fax'),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.currency'),
        ),
        migrations.CreateModel(
            name='CompanyFunctionNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('function', models.SmallIntegerField(choices=[(0, 'Opportunity'), (1, 'Sale quotation'), (2, 'Sale order'), (3, 'Picking'), (4, 'Delivery'), (5, 'Task'), (6, 'Advance payment'), (7, 'Payment'), (8, 'Return payment'), (9, 'Purchase request')])),
                ('numbering_by', models.SmallIntegerField(choices=[(0, 'System'), (1, 'User defined')], default=0)),
                ('schema', models.CharField(max_length=500, null=True)),
                ('schema_text', models.CharField(max_length=500, null=True)),
                ('first_number', models.IntegerField(null=True)),
                ('last_number', models.IntegerField(null=True)),
                ('reset_frequency', models.SmallIntegerField(choices=[(0, 'Yearly'), (1, 'Monthly'), (2, 'Weekly'), (3, 'Daily'), (4, 'Never')], null=True)),
                ('latest_number', models.IntegerField(null=True)),
                ('year_reset', models.IntegerField(null=True)),
                ('month_reset', models.IntegerField(null=True)),
                ('week_reset', models.IntegerField(null=True)),
                ('day_reset', models.IntegerField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_function_number', to='company.company')),
            ],
            options={
                'verbose_name': 'Company Function Number',
                'verbose_name_plural': 'Company Functions Number',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
