# Generated by Django 4.1.3 on 2023-05-04 10:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_currency'),
        ('company', '0003_alter_companyuseremployee_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese')], default='vi', help_text='Using language for company create in company', max_length=10, verbose_name='Default language of Company')),
                ('currency_rule', models.JSONField(default=dict, help_text='{"prefix": "", "suffix": " VND", "affixesStay": true, "thousands": ".", "decimal": ",", "precision": 0, "allowZero": true, "allowNegative": false}', verbose_name='Config display currency')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.currency', verbose_name='Currency was used by Company')),
            ],
            options={
                'verbose_name': 'Currency was used by Company',
                'verbose_name_plural': 'Currency was used by Company',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
