# Generated by Django 4.1.3 on 2023-11-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_fax_companysetting_companyfunctionnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyfunctionnumber',
            name='code',
        ),
        migrations.RemoveField(
            model_name='companyfunctionnumber',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='companyfunctionnumber',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='companyfunctionnumber',
            name='employee_created',
        ),
        migrations.RemoveField(
            model_name='companyfunctionnumber',
            name='employee_modified',
        ),
        migrations.RemoveField(
            model_name='companyfunctionnumber',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='companyfunctionnumber',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='companyfunctionnumber',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='companyfunctionnumber',
            name='title',
        ),
    ]
