# Generated by Django 4.1.3 on 2023-11-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_cost_per_lot_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfunctionnumber',
            name='min_number_char',
            field=models.IntegerField(null=True),
        ),
    ]
