# Generated by Django 4.1.3 on 2023-03-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_is_active_company_is_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companylicensetracking',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'Company License Tracking', 'verbose_name_plural': 'Company License Tracking'},
        ),
        migrations.AlterModelOptions(
            name='companyuseremployee',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'Company Map Employee Map User', 'verbose_name_plural': 'Company Map Employee Map User'},
        ),
        migrations.AlterModelManagers(
            name='companylicensetracking',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='companyuseremployee',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='company',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='company',
            name='user_modified',
        ),
        migrations.RemoveField(
            model_name='companylicensetracking',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='companylicensetracking',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='companyuseremployee',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='companyuseremployee',
            name='extras',
        ),
    ]
