# Generated by Django 4.1.3 on 2023-07-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companyconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='media_company_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='media_company_id',
            field=models.UUIDField(null=True),
        ),
    ]
