# Generated by Django 4.1.3 on 2023-12-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companyfunctionnumber_min_number_char'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='cost_per_lot_batch',
        ),
        migrations.RemoveField(
            model_name='company',
            name='cost_per_warehouse',
        ),
        migrations.RemoveField(
            model_name='company',
            name='default_inventory_value_method',
        ),
        migrations.RemoveField(
            model_name='company',
            name='definition_inventory_valuation',
        ),
        migrations.RemoveField(
            model_name='company',
            name='primary_currency',
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='cost_per_lot_batch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='cost_per_warehouse',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='default_inventory_value_method',
            field=models.SmallIntegerField(choices=[(0, 'FIFO'), (1, 'Cumulative weighted average'), (2, 'Weighted average'), (3, 'Specific identification method')], default=2),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='definition_inventory_valuation',
            field=models.SmallIntegerField(choices=[(0, 'Perpetual inventory'), (1, 'Periodic inventory')], default=0),
        ),
    ]
