# Generated by Django 4.1.3 on 2023-09-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='language',
            field=models.CharField(default='vi', max_length=25, verbose_name='language'),
        ),
    ]
