# Generated by Django 4.2.8 on 2024-01-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email_app_password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='email app password'),
        ),
    ]
