# Generated by Django 4.1.3 on 2023-09-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='language',
        ),
    ]
