# Generated by Django 4.1.3 on 2023-10-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_remove_company_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='fax'),
        ),
    ]
