# Generated by Django 4.1.3 on 2023-11-08 16:27
import random

from django.db import migrations, models


def unique_code_company(apps, schema_editor):
    company_cls = apps.get_model('company', 'company')
    for obj in company_cls.objects.all():
        if company_cls.objects.filter(code=obj.code, tenant=obj.tenant).exists():
            obj.code += str(random.randint(0, 1000))
            obj.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_alter_tenant_unique_together'),
        ('company', '0008_remove_company_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sub_domain',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RunPython(unique_code_company, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('tenant', 'code')},
        ),
    ]
