# Generated by Django 4.2.8 on 2024-06-19 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_software_start_using_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyconfig',
            old_name='cost_per_lot_batch',
            new_name='cost_per_lot',
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='cost_per_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companyconfig',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_config', to='company.company'),
        ),
    ]
