# Generated by Django 4.2.8 on 2024-07-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_rename_cost_per_lot_batch_companyconfig_cost_per_lot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email_app_password',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email_app_password_status',
        ),
    ]
