# Generated by Django 4.1.3 on 2023-11-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_populate_sub_domain_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sub_domain',
            field=models.CharField(default=None, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
