# Generated by Django 4.2.8 on 2024-09-16 15:24

import apps.core.attachments.storages.aws.storages_backend
import apps.core.company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_remove_company_email_app_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='icon',
            field=models.ImageField(null=True, storage=apps.core.attachments.storages.aws.storages_backend.PublicMediaStorage, upload_to=apps.core.company.models.generate_company_icon_path),
        ),
    ]
