# Generated by Django 4.1.3 on 2023-11-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_company_sub_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sub_domain',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
