# Generated by Django 4.1.3 on 2023-10-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_companysetting_primary_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfunctionnumber',
            name='schema_text',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
