# Generated by Django 4.2.8 on 2024-10-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_company_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyconfig',
            name='default_inventory_value_method',
            field=models.SmallIntegerField(choices=[(0, 'FIFO'), (1, 'Weighted average'), (2, 'Specific identification method')], default=1),
        ),
    ]
