# Generated by Django 4.1.3 on 2023-11-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_companyfunctionnumber_schema_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysetting',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companysetting',
            name='primary_currency',
        ),
        migrations.RemoveField(
            model_name='company',
            name='fax',
        ),
        migrations.DeleteModel(
            name='CompanyFunctionNumber',
        ),
        migrations.DeleteModel(
            name='CompanySetting',
        ),
    ]
