# Generated by Django 4.2.8 on 2025-02-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_companybankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='accounting_policies',
            field=models.SmallIntegerField(choices=[(0, 'VAS'), (1, 'IAS')], default=0),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='applicable_circular',
            field=models.SmallIntegerField(choices=[(0, '200/2014/TT-BTC'), (1, '133/2015/TT-BTC')], default=0),
        ),
    ]
