# Generated by Django 4.2.8 on 2025-03-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_companyconfig_accounting_policies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companybankaccount',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companybankaccount',
            name='country',
        ),
    ]
