# Generated by Django 4.2.8 on 2025-03-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financialcashflow', '0004_alter_cashinflowitem_options_and_more'),
        ('company', '0017_remove_companybankaccount_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyBankAccount',
        ),
    ]
