# Generated by Django 4.2.8 on 2025-04-18 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0065_periods_currency_mapped'),
        ('base', '0018_applicationproperty_is_filter_condition'),
        ('company', '0018_delete_companybankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='master_data_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='saledata.currency', verbose_name='Master data currency'),
        ),
        migrations.AlterField(
            model_name='companyconfig',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.currency', verbose_name='Base currency was used by Company'),
        ),
    ]
