# Generated by Django 4.2.8 on 2025-05-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_remove_companyfunctionnumber_function_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfunctionnumber',
            name='app_type',
            field=models.SmallIntegerField(choices=[(0, 'Application'), (1, 'Master data')], default=0),
        ),
        migrations.AlterField(
            model_name='companyfunctionnumber',
            name='day_reset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyfunctionnumber',
            name='first_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyfunctionnumber',
            name='last_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyfunctionnumber',
            name='latest_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyfunctionnumber',
            name='min_number_char',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyfunctionnumber',
            name='month_reset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyfunctionnumber',
            name='week_reset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyfunctionnumber',
            name='year_reset',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
