# Generated by Django 4.2.8 on 2025-05-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_companyfunctionnumber_app_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='function_number_data',
            field=models.JSONField(default=list),
        ),
    ]
