# Generated by Django 4.2.8 on 2025-07-15 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('company', '0022_company_function_number_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.shiftinfo'),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='shift_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='shift_mode',
            field=models.SmallIntegerField(choices=[(0, 'Single'), (1, 'Multiple')], default=1),
        ),
    ]
