# Generated by Django 4.1.3 on 2023-12-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitymeeting',
            name='meeting_from_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='opportunitymeeting',
            name='meeting_to_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
