# Generated by Django 4.1.3 on 2023-06-17 23:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0031_productwarehouse_picked_ready'),
        ('company', '0004_companyconfig'),
        ('hr', '0001_initial'),
        ('opportunity', '0002_opportunity_workflow_runtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDecisionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_opportunity_customer_decision_factor', to='company.company')),
            ],
            options={
                'verbose_name': 'Opportunity Customer Decision Factor',
                'verbose_name_plural': 'Opportunity Customer Decision Factors',
                'ordering': ('-title',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='budget_value',
            field=models.FloatField(default=0, verbose_name='expected budget'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='close_date',
            field=models.DateTimeField(default=None, help_text='Opportunity close at value', null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='decision_maker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_decision_maker', to='saledata.contact'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='end_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_end_customer', to='saledata.account', verbose_name='end customer buy from customer'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='is_input_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='open_date',
            field=models.DateTimeField(default=None, help_text='Opportunity open at value', null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='opportunity_competitors_datas',
            field=models.JSONField(default=list, help_text='read data competitors, use for get list or detail opportunity'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='opportunity_contact_role_datas',
            field=models.JSONField(default=list, help_text='read data contact role, use for get list or detail opportunity'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='opportunity_product_datas',
            field=models.JSONField(default=list, help_text='read data product, use for get list or detail opportunity'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='sale_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_sale_person', to='hr.employee', verbose_name='sale person'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='total_product',
            field=models.FloatField(default=0, help_text='total amount of tab product'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='total_product_pretax_amount',
            field=models.FloatField(default=0, help_text='total pretax amount of tab product'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='total_product_tax',
            field=models.FloatField(default=0, help_text='total tax of tab product'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='win_rate',
            field=models.FloatField(default=0, help_text='possibility of win deal of opportunity'),
        ),
        migrations.CreateModel(
            name='OpportunityProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_product_category_opportunity', to='opportunity.opportunity')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_product_category_product_category', to='saledata.productcategory')),
            ],
            options={
                'verbose_name': 'OpportunityProductCategory',
                'verbose_name_plural': 'OpportunitiesProductsCategory',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OpportunityProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_quantity', models.FloatField(default=0)),
                ('product_unit_price', models.FloatField(default=0)),
                ('product_subtotal_price', models.FloatField(default=0)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_product_opportunity', to='opportunity.opportunity')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_product_product', to='saledata.product')),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_product_product_category', to='saledata.productcategory')),
                ('tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_product_tax', to='saledata.tax')),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_product_uom', to='saledata.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Opportunity Product Category',
                'verbose_name_plural': 'Opportunity Products Category',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OpportunityCustomerDecisionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='opportunity_customer_decision_factor_factor', to='opportunity.customerdecisionfactor', verbose_name='reason why customer buy product')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_customer_decision_factor_opportunity', to='opportunity.opportunity')),
            ],
            options={
                'verbose_name': 'Opportunity Contact Role',
                'verbose_name_plural': 'Opportunity Contacts Role',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OpportunityContactRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_customer', models.SmallIntegerField(choices=[(0, 'Direct Customer'), (1, 'End Customer')], default=0, help_text='0 is Direct, 1 is End')),
                ('job_title', models.CharField(default='', max_length=100, verbose_name='job title of contact')),
                ('role', models.SmallIntegerField(choices=[(0, 'Decision maker'), (1, 'Influence'), (2, 'Contact involved')], default=0, help_text='0 is Direct, 1 is End')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_contact_role_contact', to='saledata.contact', verbose_name='Contact of customer or end customer')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_contact_role_opportunity', to='opportunity.opportunity')),
            ],
            options={
                'verbose_name': 'Opportunity Contact Role',
                'verbose_name_plural': 'Opportunity Contacts Role',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OpportunityConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_select_stage', models.BooleanField(default=False, verbose_name='user select stage of Opp')),
                ('is_input_win_rate', models.BooleanField(default=False, verbose_name='user input win rate of Opp')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_opportunity_config_detail', to='company.company')),
            ],
            options={
                'verbose_name': 'Opportunity Config of Company',
                'verbose_name_plural': 'Opportunity Config of Company',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OpportunityCompetitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strength', models.CharField(blank=True, max_length=100, null=True)),
                ('weakness', models.CharField(blank=True, max_length=100, null=True)),
                ('win_deal', models.BooleanField(default=False, verbose_name='customer is win deal')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_competitor_competitor', to='saledata.account', verbose_name='competitor with customer')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_competitor_opportunity', to='opportunity.opportunity')),
            ],
            options={
                'verbose_name': 'Opportunity Competitor',
                'verbose_name_plural': 'Opportunity Competitors',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='customer_decision_factor',
            field=models.ManyToManyField(blank=True, default=None, related_name='decision_factor_map_opportunity', through='opportunity.OpportunityCustomerDecisionFactor', to='opportunity.customerdecisionfactor', verbose_name='reason why customer buy product'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='product_category',
            field=models.ManyToManyField(blank=True, default=None, related_name='product_category_map_opportunity', through='opportunity.OpportunityProductCategory', to='saledata.productcategory'),
        ),
    ]
