# Generated by Django 4.1.3 on 2023-06-20 16:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('opportunity', '0003_customerdecisionfactor_opportunity_budget_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunitycustomerdecisionfactor',
            options={'default_permissions': (), 'ordering': (), 'permissions': (), 'verbose_name': 'Opportunity Customer Decision Factor', 'verbose_name_plural': 'Opportunity Customer Decision Factors'},
        ),
        migrations.AddField(
            model_name='opportunity',
            name='opportunity_sale_team_datas',
            field=models.JSONField(default=list, help_text='read data sale team member, use for get list or detail opportunity'),
        ),
        migrations.AlterField(
            model_name='opportunitycustomerdecisionfactor',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_customer_decision_factor_factor', to='opportunity.customerdecisionfactor', verbose_name='reason why customer buy product'),
        ),
        migrations.CreateModel(
            name='OpportunitySaleTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_sale_team_member_member', to='hr.employee', verbose_name='Member of Sale Team of Opportunity')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_sale_team_member_opportunity', to='opportunity.opportunity')),
            ],
            options={
                'verbose_name': 'Opportunity Sale Team Member',
                'verbose_name_plural': 'Opportunity Sale Team Members',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
