# Generated by Django 4.1.3 on 2023-12-18 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0003_opportunityactivitylogs_app_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitymeeting',
            name='meeting_from_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunitymeeting',
            name='meeting_to_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
