# Generated by Django 4.1.3 on 2023-06-28 10:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companyconfig'),
        ('base', '0007_applicationproperty_opp_stage_operator_and_more'),
        ('opportunity', '0005_opportunity_quotation_opportunity_sale_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityConfigStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indicator', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('win_rate', models.FloatField(default=0, verbose_name='win rate of stage')),
                ('logical_operator', models.SmallIntegerField(choices=[(0, 'and'), (1, 'or')], default=0)),
                ('condition_datas', models.JSONField(default=list, help_text='condition in stage of Opportunity Config')),
                ('is_default', models.BooleanField(default=False)),
                ('is_deal_closed', models.BooleanField(default=False)),
                ('is_delivery', models.BooleanField(default=False)),
                ('is_closed_lost', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_opportunity_config_stage', to='company.company')),
            ],
            options={
                'verbose_name': 'Opportunity Config Stage',
                'verbose_name_plural': 'Opportunity Config Stages',
                'ordering': ('indicator',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lost_by_other_reason',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunityconfig',
            name='is_account_manager_create',
            field=models.BooleanField(default=False, verbose_name='only Am of Customer is allowed create Opportunity for Customer'),
        ),
        migrations.CreateModel(
            name='StageCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comparison_operator', models.CharField(choices=[('=', 'equal'), ('≠', 'different')], default='=', max_length=10)),
                ('compare_data', models.SmallIntegerField(default=0)),
                ('condition_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_stage_condition', to='base.applicationproperty')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_condition', to='opportunity.opportunityconfigstage')),
            ],
            options={
                'verbose_name': 'Opportunity Config Stage Condition',
                'verbose_name_plural': 'Opportunity Config Stage Conditions',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_stage', to='opportunity.opportunityconfigstage'),
        ),
    ]
