# Generated by Django 4.2.8 on 2024-01-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0005_opportunity_next_node_collab'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunityactivitylogs',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunitycalllog',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunitymeeting',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
