# Generated by Django 4.1.3 on 2023-06-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0006_opportunityconfigstage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunityconfigstage',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
