# Generated by Django 4.1.3 on 2023-07-05 17:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0008_opportunitycalllog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='stage',
        ),
        migrations.CreateModel(
            name='OpportunityStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_current', models.BooleanField(default=False)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_stage_opportunity', to='opportunity.opportunity')),
                ('stage', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_stage_stage', to='opportunity.opportunityconfigstage')),
            ],
            options={
                'verbose_name': 'Opportunity Stage',
                'verbose_name_plural': 'Opportunity Stages',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage',
            field=models.ManyToManyField(blank=True, related_name='opportunity_map_stage', through='opportunity.OpportunityStage', to='opportunity.opportunityconfigstage'),
        ),
    ]
