# Generated by Django 4.1.3 on 2023-07-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0009_remove_opportunity_stage_opportunitystage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='is_close',
            field=models.BooleanField(default=False),
        ),
    ]
