# Generated by Django 4.2.8 on 2024-08-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0010_alter_opportunityactivitylogs_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
    ]
