# Generated by Django 4.1.3 on 2023-07-14 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_orderdeliverysub_attachments_and_more'),
        ('opportunity', '0011_rename_result_opportunitycalllog_input_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='is_close',
            new_name='is_close_lost',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='delivery',
            field=models.OneToOneField(help_text='Delivery use this opportunity', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_map_delivery', to='delivery.orderdelivery'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='is_deal_close',
            field=models.BooleanField(default=False),
        ),
    ]
