# Generated by Django 4.1.3 on 2023-07-14 17:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0034_remove_expense_general_information_and_more'),
        ('opportunity', '0012_rename_is_close_opportunity_is_close_lost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunitycalllog',
            options={'default_permissions': (), 'ordering': ('-call_date', '-date_created'), 'permissions': (), 'verbose_name': 'OpportunityCallLog', 'verbose_name_plural': 'OpportunitiesCallLogges'},
        ),
        migrations.AddField(
            model_name='opportunitycalllog',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value'),
        ),
        migrations.CreateModel(
            name='OpportunityEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=250)),
                ('email_to', models.CharField(max_length=250)),
                ('email_cc_list', models.JSONField(default=list)),
                ('content', models.CharField(max_length=500, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('email_to_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_email_contact', to='saledata.contact')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_send_email', to='opportunity.opportunity')),
            ],
            options={
                'verbose_name': 'OpportunityEmail',
                'verbose_name_plural': 'OpportunitiesEmails',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
