# Generated by Django 4.1.3 on 2023-07-17 17:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0034_remove_expense_general_information_and_more'),
        ('hr', '0002_employee_media_access_token_and_more'),
        ('opportunity', '0013_alter_opportunitycalllog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=250)),
                ('meeting_date', models.DateTimeField()),
                ('meeting_address', models.CharField(max_length=250)),
                ('room_location', models.CharField(max_length=250, null=True)),
                ('input_result', models.CharField(max_length=250, null=True)),
                ('repeat', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'OpportunityMeeting',
                'verbose_name_plural': 'OpportunitiesMeetings',
                'ordering': ('-meeting_date',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='opportunitycalllog',
            name='customer',
        ),
        migrations.CreateModel(
            name='OpportunityMeetingEmployeeAttended',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_attended_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('meeting_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunity.opportunitymeeting')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OpportunityMeetingCustomerMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_member_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.contact')),
                ('meeting_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunity.opportunitymeeting')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='opportunitymeeting',
            name='customer_member_list',
            field=models.ManyToManyField(related_name='all_customer_member', through='opportunity.OpportunityMeetingCustomerMember', to='saledata.contact'),
        ),
        migrations.AddField(
            model_name='opportunitymeeting',
            name='employee_attended_list',
            field=models.ManyToManyField(related_name='all_employee_attended', through='opportunity.OpportunityMeetingEmployeeAttended', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='opportunitymeeting',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_meeting', to='opportunity.opportunity'),
        ),
    ]
