# Generated by Django 4.1.3 on 2023-07-26 20:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
        ('hr', '0003_employee_permissions_parsed_role_permissions_parsed_and_more'),
        ('opportunity', '0014_opportunitymeeting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=250)),
                ('request_completed_date', models.DateTimeField()),
                ('kind_of_product', models.CharField(max_length=250)),
                ('data_documents', models.JSONField(default=list)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_document', to='opportunity.opportunity')),
            ],
            options={
                'verbose_name': 'OpportunityDocument',
                'verbose_name_plural': 'OpportunityDocuments',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OpportunitySubDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_file', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('attachment', models.OneToOneField(help_text='Sub Opportunity document had one/many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='sub_document_attachment_file', to='attachments.files', verbose_name='Sub Opportunity document attachment files')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_document', to='opportunity.opportunitydocument')),
            ],
            options={
                'verbose_name': 'OpportunitySubDocument',
                'verbose_name_plural': 'OpportunitySubsDocument',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OpportunityDocumentPersonInCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_document_1', to='opportunity.opportunitydocument')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='hr.employee')),
            ],
            options={
                'verbose_name': 'OpportunityDocumentPersonInCharge',
                'verbose_name_plural': 'OpportunityDocumentPersonsInCharge',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='opportunitydocument',
            name='person_in_charge',
            field=models.ManyToManyField(related_name='opp_document_map_employees', through='opportunity.OpportunityDocumentPersonInCharge', to='hr.employee'),
        ),
    ]
