# Generated by Django 4.2.8 on 2025-01-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0016_opportunitycalllog_current_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunityemail',
            name='just_log',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunitymeeting',
            name='email_notify',
            field=models.BooleanField(default=False),
        ),
    ]
