# Generated by Django 4.1.3 on 2023-07-28 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0016_opportunityactivitylogtask_opportunityactivitylogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunityactivitylogs',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_activity_log_document', to='opportunity.opportunitydocument'),
        ),
    ]
