# Generated by Django 4.2.8 on 2025-01-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0017_opportunityemail_just_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunityemail',
            name='email_bcc_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='opportunityemail',
            name='from_email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='from_email'),
        ),
        migrations.AddField(
            model_name='opportunityemail',
            name='send_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunitymeeting',
            name='send_success',
            field=models.BooleanField(default=False),
        ),
    ]
