# Generated by Django 4.2.8 on 2025-01-16 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_alter_leadopportunity_options'),
        ('saledata', '0053_product_lease_code_product_lease_depreciation_price_and_more'),
        ('opportunity', '0018_opportunityemail_email_bcc_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitycalllog',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_calllog_lead', to='lead.lead'),
        ),
        migrations.AddField(
            model_name='opportunityemail',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_email_lead', to='lead.lead'),
        ),
        migrations.AddField(
            model_name='opportunitymeeting',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_meeting_lead', to='lead.lead'),
        ),
        migrations.AlterField(
            model_name='opportunityactivitylogs',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_activity_log_opportunity', to='opportunity.opportunity'),
        ),
        migrations.AlterField(
            model_name='opportunitycalllog',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_calllog_contact', to='saledata.contact'),
        ),
        migrations.AlterField(
            model_name='opportunitycalllog',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_calllog', to='opportunity.opportunity'),
        ),
        migrations.AlterField(
            model_name='opportunityemail',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_send_email', to='opportunity.opportunity'),
        ),
        migrations.AlterField(
            model_name='opportunitymeeting',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_meeting', to='opportunity.opportunity'),
        ),
    ]
