# Generated by Django 4.1.3 on 2023-08-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0018_alter_opportunitydocument_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunityemail',
            name='email_to',
        ),
        migrations.RemoveField(
            model_name='opportunityemail',
            name='email_to_contact',
        ),
        migrations.AddField(
            model_name='opportunityemail',
            name='email_to_list',
            field=models.JSONField(default=list),
        ),
    ]
