# Generated by Django 4.2.8 on 2025-02-11 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_alter_leadopportunity_options'),
        ('opportunity', '0019_opportunitycalllog_lead_opportunityemail_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunityactivitylogs',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_activity_log_lead', to='lead.lead'),
        ),
    ]
