# Generated by Django 4.1.3 on 2023-08-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0019_remove_opportunityemail_email_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='system_status',
            field=models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))"),
        ),
    ]
