# Generated by Django 4.2.2 on 2023-08-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0020_alter_opportunity_system_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunitydocument',
            options={'default_permissions': (), 'ordering': ('-request_completed_date',), 'permissions': (), 'verbose_name': 'OpportunityDocument', 'verbose_name_plural': 'OpportunityDocuments'},
        ),
    ]
