# Generated by Django 4.2.8 on 2025-03-26 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0064_remove_account_parent_account_and_more'),
        ('opportunity', '0021_alter_customerdecisionfactor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='current_stage_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='customer_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='decision_maker_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='delivery_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='end_customer_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='quotation_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='sale_order_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='sale_person_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='opportunitycompetitor',
            name='competitor_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='opportunitycontactrole',
            name='contact_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='opportunitycustomerdecisionfactor',
            name='factor_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='opportunityproduct',
            name='product_category_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='opportunityproduct',
            name='product_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='opportunityproduct',
            name='tax_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='opportunityproduct',
            name='uom_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='opportunityproductcategory',
            name='product_category_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='opportunitysaleteammember',
            name='member_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='opportunitystage',
            name='stage_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='planmemberopportunity',
            name='plan_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='current_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_current_stage', to='opportunity.opportunityconfigstage'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='decision_maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_decision_maker', to='saledata.contact'),
        ),
    ]
