# Generated by Django 4.1.3 on 2023-09-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0021_alter_opportunitydocument_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitysaleteammember',
            name='permit_add_member',
            field=models.BooleanField(default=False, verbose_name='member can add other member but can not set permission for member'),
        ),
        migrations.AddField(
            model_name='opportunitysaleteammember',
            name='permit_app',
            field=models.JSONField(default=dict, help_text='{"app_id": {"is_create": false, "is_edit": false, "is_view_own_activity": false, "is_view_team_activity": false}}', verbose_name='permission for member in Tenant App'),
        ),
        migrations.AddField(
            model_name='opportunitysaleteammember',
            name='permit_view_this_opp',
            field=models.BooleanField(default=False, verbose_name='member can view this Opportunity'),
        ),
    ]
