# Generated by Django 4.2.8 on 2025-09-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0022_opportunity_current_stage_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='active_go_to_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='active_input_winrate',
            field=models.BooleanField(default=False),
        ),
    ]
