# Generated by Django 4.2.8 on 2025-12-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0024_remove_opportunity_active_input_winrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='is_deal_close',
            new_name='is_deal_closed',
        ),
    ]
