# Generated by Django 4.1.3 on 2023-10-09 17:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('company', '0008_remove_company_language'),
        ('base', '0011_application_app_depend_on_application_permit_mapping'),
        ('hr', '0007_employee_permission_by_opp_and_more'),
        ('opportunity', '0025_rename_kind_of_product_opportunitydocument_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_of_opp', through='opportunity.OpportunitySaleTeamMember', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='opportunitysaleteammember',
            name='permission_by_configured',
            field=models.JSONField(default=list, verbose_name='Permissions was configured by Administrator'),
        ),
        migrations.AddField(
            model_name='opportunitysaleteammember',
            name='permission_by_id',
            field=models.JSONField(default=dict, verbose_name='Special Permissions with ID Doc'),
        ),
        migrations.AddField(
            model_name='opportunitysaleteammember',
            name='permission_by_opp',
            field=models.JSONField(default=dict, verbose_name='Permission was configured at Opportunity'),
        ),
        migrations.AddField(
            model_name='opportunitysaleteammember',
            name='permission_by_project',
            field=models.JSONField(default=dict, verbose_name='Permission was configured at Project'),
        ),
        migrations.AddField(
            model_name='opportunitysaleteammember',
            name='permissions_parsed',
            field=models.JSONField(default=dict, verbose_name='Data was parsed'),
        ),
        migrations.AlterUniqueTogether(
            name='opportunitysaleteammember',
            unique_together={('tenant', 'company', 'opportunity', 'member')},
        ),
        migrations.CreateModel(
            name='PlanMemberOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application', models.JSONField(default=list)),
                ('opportunity_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_opp_plan', to='opportunity.opportunitysaleteammember')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Plan of Employee At Opportunity',
                'verbose_name_plural': 'Plan of Employee At Opportunity',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='opportunitysaleteammember',
            name='plan',
            field=models.ManyToManyField(blank=True, related_name='member_opp_map_plan', through='opportunity.PlanMemberOpportunity', to='base.subscriptionplan'),
        ),
    ]
