# Generated by Django 4.1.3 on 2023-10-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0026_opportunity_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunityemail',
            name='content',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
