# Generated by Django 4.2.8 on 2024-03-22 16:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_software_start_using_time'),
        ('tenant', '0001_initial'),
        ('hr', '0002_employee_avatar_img'),
        ('base', '0009_applicationproperty_system_code'),
        ('mailer', '0002_mailtemplatesystem_subject_mailconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('system_code', models.CharField(help_text='MAIL_TEMPLATE_SYSTEM_CODE', max_length=2)),
                ('doc_id', models.UUIDField(null=True, verbose_name='Document ID related')),
                ('subject', models.TextField(blank=True, verbose_name='Subject of mail')),
                ('address_sender', models.TextField(blank=True, verbose_name='Sender Mail')),
                ('address_to', models.JSONField(default=list, verbose_name='Receiver Mail')),
                ('address_cc', models.JSONField(default=list, verbose_name='CC Mail')),
                ('address_bcc', models.JSONField(default=list, verbose_name='BCC Mail')),
                ('status_code', models.SmallIntegerField(default=0, verbose_name='Status code for filter: MAIL_LOG_STATUS_CODE')),
                ('status_remark', models.TextField(blank=True, verbose_name='Status mail')),
                ('errors_data', models.TextField(blank=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.application')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
            ],
            options={
                'verbose_name': 'Mail Log',
                'verbose_name_plural': 'Mail Log',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='mailconfig',
            name='bcc_email',
            field=models.JSONField(default=list, verbose_name='Email BCC sent'),
        ),
        migrations.AddField(
            model_name='mailconfig',
            name='cc_email',
            field=models.JSONField(default=list, verbose_name='Email CC sent'),
        ),
        migrations.AddField(
            model_name='mailconfig',
            name='from_email',
            field=models.TextField(blank=True, verbose_name='From Email sent'),
        ),
        migrations.AddField(
            model_name='mailconfig',
            name='reply_email',
            field=models.TextField(blank=True, verbose_name='Reply To sent'),
        ),
        migrations.CreateModel(
            name='MailLogEmployeeTo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('mail_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.maillog')),
            ],
            options={
                'verbose_name': 'Mail Log Receiver',
                'verbose_name_plural': 'Mail Log Receiver',
                'permissions': (),
                'default_permissions': (),
                'unique_together': {('mail_log', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='MailLogEmployeeCC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('mail_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.maillog')),
            ],
            options={
                'verbose_name': 'Mail Log CC',
                'verbose_name_plural': 'Mail Log CC',
                'permissions': (),
                'default_permissions': (),
                'unique_together': {('mail_log', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='MailLogEmployeeBCC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('mail_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.maillog')),
            ],
            options={
                'verbose_name': 'Mail Log BCC',
                'verbose_name_plural': 'Mail Log BCC',
                'permissions': (),
                'default_permissions': (),
                'unique_together': {('mail_log', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='MailLogData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('host', models.TextField(blank=True, verbose_name='Host - encrypted')),
                ('port', models.TextField(blank=True, verbose_name='Port - encrypted')),
                ('username', models.TextField(blank=True, verbose_name='Username - encrypted')),
                ('password', models.TextField(blank=True, verbose_name='Password - encrypted')),
                ('use_tls', models.BooleanField(default=False, verbose_name='Use TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Use SSL')),
                ('ssl_key_path', models.TextField(blank=True, verbose_name='Path to SSL Key file')),
                ('ssl_cert_path', models.TextField(blank=True, verbose_name='Path to SSL Cert file')),
                ('ident_mail', models.TextField(blank=True, verbose_name='Ident Mail - ID')),
                ('headers', models.JSONField(default=dict, verbose_name='Header Mail')),
                ('body_text', models.TextField(blank=True, verbose_name='Body Mail Text Plain')),
                ('body_html', models.TextField(blank=True, verbose_name='Body Mail HTML')),
                ('reply_to', models.TextField(blank=True, verbose_name='Address Mail Reply')),
                ('doc_data', models.JSONField(default=dict, verbose_name='Document Data')),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailer.maillog')),
            ],
            options={
                'verbose_name': 'Mail Log Data',
                'verbose_name_plural': 'Mail Log Data',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='maillog',
            name='employee_bcc',
            field=models.ManyToManyField(blank=True, related_name='bcc_of_mail', through='mailer.MailLogEmployeeBCC', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='maillog',
            name='employee_cc',
            field=models.ManyToManyField(blank=True, related_name='cc_of_mail', through='mailer.MailLogEmployeeCC', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='maillog',
            name='employee_to',
            field=models.ManyToManyField(blank=True, related_name='to_of_mail', through='mailer.MailLogEmployeeTo', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='maillog',
            name='reply_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_from_mail_log', to='mailer.maillog'),
        ),
        migrations.AddField(
            model_name='maillog',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_to_mail_log', to='mailer.maillog'),
        ),
        migrations.AddField(
            model_name='maillog',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
    ]
