# Generated by Django 4.2.8 on 2025-09-30 14:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_nprovince_nward'),
        ('documentapproval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmsdocumenttype',
            name='applications_data',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='KMSDocumentTypeApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_type_application_application', to='base.application', verbose_name='application')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_type_application_document_type', to='documentapproval.kmsdocumenttype', verbose_name='document type')),
            ],
            options={
                'verbose_name': 'Document Type Application',
                'verbose_name_plural': 'Document Type Applications',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='kmsdocumenttype',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='document_type_m2m_application', through='documentapproval.KMSDocumentTypeApplication', to='base.application'),
        ),
    ]
