# Generated by Django 4.1.3 on 2023-11-11 23:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailServerConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creds_data', models.JSONField(default=dict)),
                ('token_data', models.JSONField()),
                ('token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_uri', models.TextField()),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('scopes', models.JSONField()),
                ('expiry', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Mail Server Config',
                'verbose_name_plural': 'Mail Server Config',
                'ordering': ('-expiry',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
