# Generated by Django 4.2.8 on 2024-11-11 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0004_processdoc_date_status_processdoc_system_status_and_more'),
        ('opportunity', '0013_opportunitycalllog_code_opportunitycalllog_company_and_more'),
        ('company', '0013_alter_companyconfig_default_inventory_value_method'),
        ('tenant', '0001_initial'),
        ('saledata', '0044_documenttype'),
        ('project', '0018_project_date_close'),
        ('workflow', '0006_alter_association_date_modified_and_more'),
        ('attachments', '0009_alter_files_file_type_alter_publicfiles_file_type'),
        ('bidding', '0001_initial'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biddingdocument',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidding_document_document_type', to='saledata.documenttype', verbose_name='document type'),
        ),
        migrations.AddField(
            model_name='biddingdocument',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='biddingdocument',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='biddingdocument',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='biddingbidderaccount',
            name='bidder_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_bidder_account_bidder_account', to='saledata.account', verbose_name='bidding bidder account'),
        ),
        migrations.AddField(
            model_name='biddingbidderaccount',
            name='bidding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_bidder_account_bidding', to='bidding.bidding', verbose_name='bidding bidder account bidding'),
        ),
        migrations.AddField(
            model_name='biddingattachment',
            name='attachment',
            field=models.OneToOneField(help_text='Many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_files', to='attachments.files', verbose_name='Attachment files'),
        ),
        migrations.AddField(
            model_name='biddingattachment',
            name='bidding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_attachment_bidding', to='bidding.bidding', verbose_name='bidding'),
        ),
        migrations.AddField(
            model_name='biddingattachment',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidding_attachment_bidding_document', to='bidding.biddingdocument', verbose_name='document'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='attachment_m2m',
            field=models.ManyToManyField(blank=True, related_name='file_of_bidding', through='bidding.BiddingAttachment', to='attachments.files'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='current_stage',
            field=models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='customer',
            field=models.ForeignKey(help_text='sale data Accounts have type customer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidding_customer', to='saledata.account', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='next_node_collab',
            field=models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidding_opportunity', to='opportunity.opportunity', verbose_name='opportunity'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='other_bidder',
            field=models.ManyToManyField(blank=True, related_name='bidding_other_bidder', through='bidding.BiddingBidderAccount', to='saledata.account'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='project',
            field=models.ForeignKey(help_text='Relate to Project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_prj', to='project.project'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='venture_partner',
            field=models.ManyToManyField(blank=True, related_name='bidding_venture_partner', through='bidding.BiddingPartnerAccount', to='saledata.account'),
        ),
        migrations.AddField(
            model_name='bidding',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
    ]
