# Generated by Django 4.2.8 on 2024-11-18 15:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_companyconfig_default_inventory_value_method'),
        ('tenant', '0001_initial'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('bidding', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingResultConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('employee', models.JSONField(blank=True, default=list, null=True)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'BiddingResultConfig',
                'verbose_name_plural': 'BiddingResultConfigs',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='biddingattachment',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bidding_attachment_bidding_document', to='bidding.biddingdocument', verbose_name='document'),
        ),
        migrations.CreateModel(
            name='BiddingResultConfigEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bidding_result_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_result_config_employee_bid_config', to='bidding.biddingresultconfig', verbose_name='bidding result config')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_result_config_employee_employee', to='hr.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'BiddingResultConfigEmployee',
                'verbose_name_plural': 'BiddingResultConfigEmployeeList',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
