# Generated by Django 4.2.8 on 2024-11-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_biddingresultconfig_alter_biddingattachment_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biddingbidderaccount',
            options={'default_permissions': (), 'ordering': ('order',), 'permissions': (), 'verbose_name': 'Bidding bidder account', 'verbose_name_plural': 'Bidding bidder accounts'},
        ),
        migrations.AlterModelOptions(
            name='biddingpartneraccount',
            options={'default_permissions': (), 'ordering': ('order',), 'permissions': (), 'verbose_name': 'Bidding partner account', 'verbose_name_plural': 'Bidding partner accounts'},
        ),
        migrations.AddField(
            model_name='biddingbidderaccount',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='biddingpartneraccount',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
