# Generated by Django 4.1.3 on 2022-12-08 17:11

import apps.core.account.manager
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username_auth', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=182, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Account Username for Authenticate, \n        format: "{username}-{TenantCode|upper}", slugify before call authenticate')),
                ('username', models.CharField(max_length=150, verbose_name='Account Username')),
                ('first_name', models.CharField(blank=True, max_length=80, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone number')),
                ('language', models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese')], default='vi', max_length=2, verbose_name='language favorite: vi, en')),
                ('is_phone', models.BooleanField(default=False, verbose_name='phone is valid')),
                ('is_email', models.BooleanField(default=False, verbose_name='email is valid')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser')),
                ('user_created', models.UUIDField(default=None, null=True, verbose_name='User ID created record')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('date_joined', models.DateTimeField(default=None, null=True, verbose_name='date joined, first login time')),
                ('extras', jsonfield.fields.JSONField(blank=True, default={}, null=True)),
                ('last_login', models.DateTimeField(null=True, verbose_name='Last Login')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('full_name_search', models.CharField(blank=True, max_length=200, null=True, verbose_name='full name')),
                ('is_admin_tenant', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Account User',
                'verbose_name_plural': 'Account User',
                'ordering': ('username',),
                'permissions': (),
                'default_permissions': (),
            },
            managers=[
                ('objects', apps.core.account.manager.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='VerifyContact',
            fields=[
                ('email_or_phone', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False)),
                ('is_email', models.BooleanField(default=False)),
                ('is_phone', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True, verbose_name='Valid email or phone after login')),
                ('counter', models.IntegerField(default=0, verbose_name='Counter user')),
                ('date_valid', models.DateTimeField(default=django.utils.timezone.now)),
                ('extras', jsonfield.fields.JSONField(blank=True, default={}, null=True)),
            ],
            options={
                'verbose_name': 'Verify Contact Account',
                'verbose_name_plural': 'Verify Contact Account',
                'ordering': ('-date_valid',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
