# Generated by Django 4.1.3 on 2023-01-06 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space', '0001_initial'),
        ('company', '0001_initial'),
        ('hr', '0001_initial'),
        ('tenant', '0001_initial'),
        ('account', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_current',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_current', to='company.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_current',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_current', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='space_current',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='space_current', to='space.space'),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant_current',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_current', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
