# Generated by Django 4.1.3 on 2023-03-09 10:09

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_username_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username_auth',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=182, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Account Username for Authenticate,\n        format: "{username}-{TenantCode|upper}" , slugify before call authenticate'),
        ),
    ]
