# Generated by Django 4.1.3 on 2023-03-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_companylicensetracking_options_and_more'),
        ('account', '0004_alter_user_username_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='all_company_of_user', through='company.CompanyUserEmployee', to='company.company'),
        ),
    ]
