# Generated by Django 4.1.3 on 2023-03-29 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space', '0001_initial'),
        ('base', '0001_initial'),
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('permission_by_id', jsonfield.fields.JSONField(default={})),
                ('permission_by_configured', jsonfield.fields.JSONField(default={})),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('search_content', models.CharField(blank=True, max_length=300, null=True, verbose_name='Support Search Content')),
                ('avatar', models.TextField(null=True, verbose_name='avatar path')),
                ('date_joined', models.DateTimeField(null=True, verbose_name='joining day')),
                ('dob', models.DateField(null=True, verbose_name='birthday')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True, verbose_name='gender male or female')),
                ('plan_application', jsonfield.fields.JSONField(default={})),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employee',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('permission_by_id', jsonfield.fields.JSONField(default={})),
                ('permission_by_configured', jsonfield.fields.JSONField(default={})),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True, verbose_name='abbreviation of role (Business analysis -> BA)')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SpaceEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application', jsonfield.fields.JSONField(default=[])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.space')),
            ],
            options={
                'verbose_name': 'Space of Employee',
                'verbose_name_plural': 'Space of Employee',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RoleHolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.role')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='role',
            name='employee',
            field=models.ManyToManyField(blank=True, related_name='role_map_employee', through='hr.RoleHolder', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.CreateModel(
            name='PlanEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application', jsonfield.fields.JSONField(default=[])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Plan of Employee',
                'verbose_name_plural': 'Plan of Employee',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GroupLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('level', models.IntegerField(null=True, verbose_name='group level')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='group level description')),
                ('first_manager_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='first manager description')),
                ('second_manager_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='second manager description')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Group Level',
                'verbose_name_plural': 'Group Levels',
                'ordering': ('level',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('description', models.CharField(blank=True, max_length=600, null=True, verbose_name='group description')),
                ('group_employee', jsonfield.fields.JSONField(default=[], null=True, verbose_name='group employee')),
                ('first_manager_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='first manager title')),
                ('second_manager_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='second manager title')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('first_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_first_manager', to='hr.employee')),
                ('group_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.grouplevel')),
                ('parent_n', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_parent_n', to='hr.group', verbose_name='parent group')),
                ('second_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_second_manager', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_group', to='hr.group', verbose_name='department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='plan',
            field=models.ManyToManyField(blank=True, related_name='employee_map_plan', through='hr.PlanEmployee', to='base.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='employee_map_role', through='hr.RoleHolder', to='hr.role'),
        ),
        migrations.AddField(
            model_name='employee',
            name='space',
            field=models.ManyToManyField(blank=True, related_name='employee_map_space', through='hr.SpaceEmployee', to='space.space'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
