# Generated by Django 4.1.3 on 2023-01-06 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('space', '0001_initial'),
        ('company', '0001_initial'),
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('user_created', models.UUIDField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_modified', models.UUIDField(null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('mode', models.IntegerField(choices=[(0, 'Global'), (1, 'Private'), (2, 'Team')], default=0)),
                ('mode_id', models.UUIDField(null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('search_content', models.CharField(blank=True, max_length=300, null=True, verbose_name='Support Search Content')),
                ('avatar', models.TextField(null=True, verbose_name='avatar path')),
                ('date_joined', models.DateTimeField(null=True, verbose_name='joining day')),
                ('dob', models.DateField(null=True, verbose_name='birthday')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True, verbose_name='gender male or female')),
                ('plan_application', jsonfield.fields.JSONField(default={})),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employee',
                'ordering': ('code',),
                'permissions': (),
                'default_permissions': (),
            },
            managers=[
                ('object_global', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('user_created', models.UUIDField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_modified', models.UUIDField(null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('mode', models.IntegerField(choices=[(0, 'Global'), (1, 'Private'), (2, 'Team')], default=0)),
                ('mode_id', models.UUIDField(null=True)),
                ('description', models.CharField(blank=True, max_length=600, null=True, verbose_name='group description')),
                ('group_employee', jsonfield.fields.JSONField(default=[], null=True, verbose_name='group employee')),
                ('first_manager_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='first manager title')),
                ('second_manager_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='second manager title')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('first_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_first_manager', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
            managers=[
                ('object_global', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('user_created', models.UUIDField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_modified', models.UUIDField(null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('mode', models.IntegerField(choices=[(0, 'Global'), (1, 'Private'), (2, 'Team')], default=0)),
                ('mode_id', models.UUIDField(null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True, verbose_name='abbreviation of role (Business analysis -> BA)')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
            managers=[
                ('object_global', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SpaceEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('application', jsonfield.fields.JSONField(default=[])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.space')),
            ],
            options={
                'verbose_name': 'Space of Employee',
                'verbose_name_plural': 'Space of Employee',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
            managers=[
                ('object_normal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RoleHolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.role')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
            managers=[
                ('object_normal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PlanEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('application', jsonfield.fields.JSONField(default=[])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Plan of Employee',
                'verbose_name_plural': 'Plan of Employee',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
            managers=[
                ('object_normal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GroupLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('user_created', models.UUIDField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_modified', models.UUIDField(null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('mode', models.IntegerField(choices=[(0, 'Global'), (1, 'Private'), (2, 'Team')], default=0)),
                ('mode_id', models.UUIDField(null=True)),
                ('level', models.IntegerField(null=True, verbose_name='group level')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='group level description')),
                ('first_manager_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='first manager description')),
                ('second_manager_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='second manager description')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Group Level',
                'verbose_name_plural': 'Group Levels',
                'ordering': ('level',),
                'permissions': (),
                'default_permissions': (),
            },
            managers=[
                ('object_global', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GroupEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('role', jsonfield.fields.JSONField(default=[], null=True, verbose_name='role')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_employee_employee', to='hr.employee')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_employee_group', to='hr.group')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
            managers=[
                ('object_normal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='group_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.grouplevel'),
        ),
        migrations.AddField(
            model_name='group',
            name='parent_n',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_parent_n', to='hr.group', verbose_name='parent group'),
        ),
        migrations.AddField(
            model_name='group',
            name='second_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_second_manager', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='group',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='employee',
            name='space',
            field=models.ManyToManyField(blank=True, related_name='employee_map_space', through='hr.SpaceEmployee', to='space.space'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
