# Generated by Django 4.1.3 on 2023-07-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='media_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='media_access_token_expired',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='media_avatar_hash',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='media_password',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='media_refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='media_refresh_token_expired',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='media_user_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='media_username',
            field=models.TextField(blank=True),
        ),
    ]
