# Generated by Django 4.2.8 on 2023-12-27 14:23

import apps.core.attachments.storages.aws.storages_backend
import apps.core.hr.models.employee
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar_img',
            field=models.ImageField(null=True, storage=apps.core.attachments.storages.aws.storages_backend.PublicMediaStorage, upload_to=apps.core.hr.models.employee.generate_employee_avatar_path),
        ),
    ]
