# Generated by Django 4.1.3 on 2022-12-15 15:12

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_application_subscriptionplan_tenant_plan_tenantplan'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_joined',
            field=models.DateTimeField(null=True, verbose_name='joining day'),
        ),
        migrations.AddField(
            model_name='employee',
            name='plan_application',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.CreateModel(
            name='PlanEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('application', jsonfield.fields.JSONField(default=[])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Plan of Employee',
                'verbose_name_plural': 'Plan of Employee',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
            managers=[
                ('object_normal', django.db.models.manager.Manager()),
            ],
        ),
    ]
