# Generated by Django 4.1.3 on 2023-07-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_media_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='permissions_parsed',
            field=models.JSONField(default=dict, verbose_name='Data was parsed'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions_parsed',
            field=models.JSONField(default=dict, verbose_name='Data was parsed'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='permission_by_configured',
            field=models.JSONField(default=list, verbose_name='Permissions was configured by Administrator'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='permission_by_id',
            field=models.JSONField(default=dict, verbose_name='Special Permissions with ID Doc'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='plan_application',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_employee',
            field=models.JSONField(default=list, null=True, verbose_name='group employee'),
        ),
        migrations.AlterField(
            model_name='planemployee',
            name='application',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='role',
            name='permission_by_configured',
            field=models.JSONField(default=list, verbose_name='Permissions was configured by Administrator'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permission_by_id',
            field=models.JSONField(default=dict, verbose_name='Special Permissions with ID Doc'),
        ),
        migrations.AlterField(
            model_name='spaceemployee',
            name='application',
            field=models.JSONField(default=list),
        ),
    ]
