# Generated by Django 4.1.3 on 2023-01-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'default_permissions': (), 'ordering': ('-date_created',), 'permissions': (), 'verbose_name': 'Employee', 'verbose_name_plural': 'Employee'},
        ),
    ]
