# Generated by Django 4.2.8 on 2024-04-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_software_start_using_time'),
        ('hr', '0002_employee_avatar_img'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='grouplevel',
            unique_together={('company', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('company', 'code')},
        ),
    ]
