# Generated by Django 4.1.3 on 2023-01-03 15:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_alter_tenant_sub_domain'),
        ('hr', '0003_employee_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('user_created', models.UUIDField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_modified', models.UUIDField(null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('mode', models.IntegerField(choices=[(0, 'Global'), (1, 'Private'), (2, 'Team')], default=0)),
                ('mode_id', models.UUIDField(null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True, verbose_name='abbreviation of role (Business analysis -> BA)')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.company')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
            managers=[
                ('object_global', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RoleHolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.role')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
            managers=[
                ('object_normal', django.db.models.manager.Manager()),
            ],
        ),
    ]
