# Generated by Django 4.2.8 on 2024-04-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_software_start_using_time'),
        ('hr', '0003_alter_group_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('company', 'abbreviation')},
        ),
    ]
