# Generated by Django 4.2.8 on 2024-07-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_group_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email_app_password',
            field=models.TextField(null=True, verbose_name='email app password'),
        ),
        migrations.AddField(
            model_name='employee',
            name='email_app_password_status',
            field=models.BooleanField(default=False),
        ),
    ]
