# Generated by Django 4.1.3 on 2023-02-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='employee_map_role', through='hr.RoleHolder', to='hr.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='employee',
            field=models.ManyToManyField(blank=True, related_name='role_map_employee', through='hr.RoleHolder', to='hr.employee'),
        ),
    ]
