# Generated by Django 4.1.3 on 2023-07-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_employee_permissions_parsed_role_permissions_parsed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_admin_company',
            field=models.BooleanField(default=False, verbose_name='Is Admin Company'),
        ),
    ]
