# Generated by Django 4.1.3 on 2023-02-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_planapplication'),
        ('hr', '0004_employee_role_role_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='plan',
            field=models.ManyToManyField(blank=True, related_name='employee_map_plan', through='hr.PlanEmployee', to='base.subscriptionplan'),
        ),
    ]
