# Generated by Django 4.1.3 on 2023-10-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_employee_code_alter_employee_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='permission_by_opp',
            field=models.JSONField(default=dict, verbose_name='Permission was configured at Opportunity'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permission_by_project',
            field=models.JSONField(default=dict, verbose_name='Permission was configured at Project'),
        ),
        migrations.AddField(
            model_name='role',
            name='permission_by_opp',
            field=models.JSONField(default=dict, verbose_name='Permission was configured at Opportunity'),
        ),
        migrations.AddField(
            model_name='role',
            name='permission_by_project',
            field=models.JSONField(default=dict, verbose_name='Permission was configured at Project'),
        ),
    ]
