# Generated by Django 4.1.3 on 2023-02-27 00:07

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_grouplevel_is_active_grouplevel_is_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='permission_by_configured',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='employee',
            name='permission_by_id',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='role',
            name='permission_by_configured',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='role',
            name='permission_by_id',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
