# Generated by Django 4.1.3 on 2023-03-10 17:15

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_companylicensetracking_options_and_more'),
        ('tenant', '0003_remove_tenant_extras_remove_tenant_is_active_and_more'),
        ('hr', '0007_employee_permission_by_configured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planemployee',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'Plan of Employee', 'verbose_name_plural': 'Plan of Employee'},
        ),
        migrations.AlterModelOptions(
            name='spaceemployee',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'Space of Employee', 'verbose_name_plural': 'Space of Employee'},
        ),
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='group',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='grouplevel',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='planemployee',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='role',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='roleholder',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='spaceemployee',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mode_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_modified',
        ),
        migrations.RemoveField(
            model_name='group',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='group',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='group',
            name='mode_id',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user_modified',
        ),
        migrations.RemoveField(
            model_name='grouplevel',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='grouplevel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='grouplevel',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='grouplevel',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='grouplevel',
            name='mode_id',
        ),
        migrations.RemoveField(
            model_name='grouplevel',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='grouplevel',
            name='user_modified',
        ),
        migrations.RemoveField(
            model_name='planemployee',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='planemployee',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='role',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='role',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='role',
            name='mode_id',
        ),
        migrations.RemoveField(
            model_name='role',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='role',
            name='user_modified',
        ),
        migrations.RemoveField(
            model_name='roleholder',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='roleholder',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='spaceemployee',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='spaceemployee',
            name='extras',
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='group',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AlterField(
            model_name='group',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value'),
        ),
        migrations.AlterField(
            model_name='group',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last'),
        ),
        migrations.AlterField(
            model_name='group',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='grouplevel',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AlterField(
            model_name='grouplevel',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value'),
        ),
        migrations.AlterField(
            model_name='grouplevel',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last'),
        ),
        migrations.AlterField(
            model_name='grouplevel',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='role',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AlterField(
            model_name='role',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value'),
        ),
        migrations.AlterField(
            model_name='role',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last'),
        ),
        migrations.AlterField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.DeleteModel(
            name='GroupEmployee',
        ),
    ]
