# Generated by Django 4.1.3 on 2023-03-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_planemployee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='group',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='grouplevel',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='role',
            managers=[
            ],
        ),
    ]
