# Generated by Django 4.2.8 on 2025-02-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliation',
            name='system_auto_create',
            field=models.BooleanField(default=False, help_text='flag to know this record is created by system'),
        ),
    ]
