# Generated by Django 4.2.8 on 2025-07-15 14:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0022_company_function_number_data'),
        ('tenant', '0001_initial'),
        ('hr', '0004_employee_email_app_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('checkin_time', models.TimeField(verbose_name='The start time')),
                ('checkin_gr_start', models.TimeField(null=True)),
                ('checkin_gr_end', models.TimeField(null=True)),
                ('checkin_threshold', models.FloatField(default=0, null=True)),
                ('break_in_time', models.TimeField(verbose_name='The break start time')),
                ('break_in_gr_start', models.TimeField(null=True)),
                ('break_in_gr_end', models.TimeField(null=True)),
                ('break_in_threshold', models.FloatField(default=0, null=True)),
                ('break_out_time', models.TimeField(verbose_name='The break end time')),
                ('break_out_gr_start', models.TimeField(null=True)),
                ('break_out_gr_end', models.TimeField(null=True)),
                ('break_out_threshold', models.FloatField(default=0, null=True)),
                ('checkout_time', models.TimeField(verbose_name='The end time')),
                ('checkout_gr_start', models.TimeField(null=True)),
                ('checkout_gr_end', models.TimeField(null=True)),
                ('checkout_threshold', models.FloatField(default=0, null=True)),
                ('working_day_list', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Shift information',
                'verbose_name_plural': 'Shift information',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
