# Generated by Django 4.2.8 on 2025-07-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_shiftassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftinfo',
            name='break_in_threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shiftinfo',
            name='break_in_time',
            field=models.TimeField(null=True, verbose_name='The break start time'),
        ),
        migrations.AlterField(
            model_name='shiftinfo',
            name='break_out_threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shiftinfo',
            name='break_out_time',
            field=models.TimeField(null=True, verbose_name='The break end time'),
        ),
        migrations.AlterField(
            model_name='shiftinfo',
            name='checkin_threshold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shiftinfo',
            name='checkout_threshold',
            field=models.IntegerField(default=0),
        ),
    ]
