# Generated by Django 4.2.8 on 2025-08-04 14:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('businesstrip', '0010_businessrequest_process_stage_app'),
        ('company', '0023_companyconfig_shift_companyconfig_shift_data_and_more'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('leave', '0011_alter_leaverequest_options'),
        ('attendance', '0003_alter_shiftinfo_break_in_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceIntegrateEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('device_employee_id', models.CharField(blank=True, max_length=50)),
                ('device_employee_name', models.CharField(blank=True, max_length=100)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_integrate_employee', to='hr.employee', verbose_name='employee')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Device Integrate Employee',
                'verbose_name_plural': 'Device Integrate Employees',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('checkin_time', models.TimeField(null=True)),
                ('checkout_time', models.TimeField(null=True)),
                ('date', models.DateField(help_text='date log attendance', null=True)),
                ('attendance_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Absent'), (1, 'Present'), (2, 'Leave'), (3, 'Business'), (4, 'Weekend'), (5, 'Holiday'), (6, 'Overtime'), (7, 'Overtime on business trip'))")),
                ('leave_data', models.JSONField(default=dict, help_text='read data leave, back-up for getting list or detail')),
                ('business_trip_data', models.JSONField(default=dict, help_text='read data business trip, backup for getting list or detail')),
                ('is_late', models.BooleanField(default=False, help_text='check if the attendance is marked as late after checking logic')),
                ('is_early_leave', models.BooleanField(default=False, help_text='check if the attendance is marked as early leave after checking logic')),
                ('business_trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_business_trip', to='businesstrip.businessrequest', verbose_name='business trip')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_employee', to='hr.employee', verbose_name='employee')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('leave', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_leave', to='leave.leaverequest', verbose_name='leave')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_shift', to='attendance.shiftinfo', verbose_name='shift')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ('-date',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
