# Generated by Django 4.2.8 on 2025-08-07 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancedevice_accesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_shift', to='attendance.shiftinfo', verbose_name='shift'),
        ),
    ]
