# Generated by Django 4.2.8 on 2025-12-16 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_shiftassignmentappconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftassignment',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignment_shift', to='attendance.shiftinfo', verbose_name='shift'),
        ),
    ]
