# Generated by Django 4.2.8 on 2024-01-22 16:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_collabinworkflow_is_edit_all_zone_and_more'),
        ('tenant', '0001_initial'),
        ('opportunity', '0006_opportunityactivitylogs_is_cancelled_and_more'),
        ('process', '0001_initial'),
        ('company', '0008_company_email_app_password_status_and_more'),
        ('saleorder', '0010_saleorder_sale_order_payment_stage_and_more'),
        ('saledata', '0011_productwarehouse_used_amount'),
        ('hr', '0002_employee_avatar_img'),
        ('purchasing', '0003_purchaseorder_purchase_order_payment_stage_and_more'),
        ('space', '0001_initial'),
        ('report', '0003_reportpipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcustomer',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_customer_customer', to='saledata.account'),
        ),
        migrations.AlterField(
            model_name='reportpipeline',
            name='opportunity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_pipeline_opportunity', to='opportunity.opportunity'),
        ),
        migrations.AlterField(
            model_name='reportproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_product_product', to='saledata.product'),
        ),
        migrations.AlterField(
            model_name='reportrevenue',
            name='sale_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_revenue_sale_order', to='saleorder.saleorder'),
        ),
        migrations.CreateModel(
            name='ReportCashflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('cashflow_type', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Sale order'), (1, 'Purchase order'))")),
                ('due_date', models.DateTimeField(null=True)),
                ('value_estimate_sale', models.FloatField(default=0)),
                ('value_actual_sale', models.FloatField(default=0)),
                ('value_variance_sale', models.FloatField(default=0)),
                ('value_estimate_purchase', models.FloatField(default=0)),
                ('value_actual_purchase', models.FloatField(default=0)),
                ('value_variance_purchase', models.FloatField(default=0)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('current_stage', models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('group_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_cashflow_group_inherit', to='hr.group')),
                ('next_node_collab', models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee')),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
                ('purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_cashflow_purchase_order', to='purchasing.purchaseorder')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cashflow_sale_order', to='saleorder.saleorder')),
                ('space', models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('workflow_runtime', models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc')),
            ],
            options={
                'verbose_name': 'Report Cashflow',
                'verbose_name_plural': 'Report Cashflows',
                'ordering': ('-due_date',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
