# Generated by Django 4.2.8 on 2024-01-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_reportcustomer_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportcashflow',
            old_name='value_actual_purchase',
            new_name='value_actual_cost',
        ),
        migrations.RenameField(
            model_name='reportcashflow',
            old_name='value_estimate_purchase',
            new_name='value_estimate_cost',
        ),
        migrations.RenameField(
            model_name='reportcashflow',
            old_name='value_variance_purchase',
            new_name='value_variance_cost',
        ),
        migrations.AlterField(
            model_name='reportcashflow',
            name='cashflow_type',
            field=models.SmallIntegerField(default=0, help_text="choices= ((0, 'Operation'), (1, 'Beginning balance'), (2, 'Cash sales'), (3, 'Product/ service costs'), (4, 'Net cash flow'), (5, 'Ending balance'))"),
        ),
    ]
