# Generated by Django 4.2.8 on 2024-03-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_reportinventory_period_mapped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='is_close',
            field=models.BooleanField(default=False),
        ),
    ]
