# Generated by Django 4.2.8 on 2024-03-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_reportinventoryproductwarehouse_is_close'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportinventory',
            options={'default_permissions': (), 'ordering': ('product__code',), 'permissions': (), 'verbose_name': 'Report Inventory', 'verbose_name_plural': 'Report Inventories'},
        ),
        migrations.AddField(
            model_name='reportinventorysub',
            name='lot_data',
            field=models.JSONField(default=list),
        ),
    ]
