# Generated by Django 4.2.8 on 2024-03-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0012_remove_saleorderpaymentstage_date_type_and_more'),
        ('report', '0010_alter_reportinventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcashflow',
            name='sale_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_cashflow_sale_order', to='saleorder.saleorder'),
        ),
    ]
