# Generated by Django 4.2.8 on 2024-03-19 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0014_alter_subperiods_options'),
        ('report', '0011_alter_reportcashflow_sale_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinventory',
            name='sub_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_inventory_product_sub_period', to='saledata.subperiods'),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='sub_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_inventory_product_warehouse_sub_period', to='saledata.subperiods'),
        ),
    ]
