# Generated by Django 4.2.8 on 2024-03-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0012_remove_saleorderpaymentstage_date_type_and_more'),
        ('report', '0012_reportinventory_sub_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrevenue',
            name='is_initial',
            field=models.BooleanField(default=False, help_text='flag to know this is record created by revenue plan'),
        ),
        migrations.AlterField(
            model_name='reportrevenue',
            name='sale_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_revenue_sale_order', to='saleorder.saleorder'),
        ),
    ]
