# Generated by Django 4.2.8 on 2024-03-27 17:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_collabinworkflow_is_edit_all_zone_and_more'),
        ('hr', '0002_employee_avatar_img'),
        ('process', '0001_initial'),
        ('company', '0009_company_software_start_using_time'),
        ('tenant', '0001_initial'),
        ('space', '0001_initial'),
        ('report', '0013_reportrevenue_is_initial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportinventorysub',
            options={'default_permissions': (), 'ordering': ('-system_date',), 'permissions': (), 'verbose_name': 'Report Inventory By Month', 'verbose_name_plural': 'Report Inventory By Months'},
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='current_stage',
            field=models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc'),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='current_stage_title',
            field=models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='date_approved',
            field=models.DateTimeField(help_text='The record created when WF of document is finished', null=True),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value'),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date modified this record in last'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='next_node_collab',
            field=models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='system_remarks',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='system_status',
            field=models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))"),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
    ]
