# Generated by Django 4.2.8 on 2024-04-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_alter_reportinventorysub_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcashflow',
            name='document_change_order',
            field=models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True),
        ),
        migrations.AddField(
            model_name='reportcashflow',
            name='document_root_id',
            field=models.UUIDField(help_text='this is id of root document of the changed documents', null=True),
        ),
        migrations.AddField(
            model_name='reportcashflow',
            name='is_change',
            field=models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents'),
        ),
        migrations.AddField(
            model_name='reportcustomer',
            name='document_change_order',
            field=models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True),
        ),
        migrations.AddField(
            model_name='reportcustomer',
            name='document_root_id',
            field=models.UUIDField(help_text='this is id of root document of the changed documents', null=True),
        ),
        migrations.AddField(
            model_name='reportcustomer',
            name='is_change',
            field=models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents'),
        ),
        migrations.AddField(
            model_name='reportinventory',
            name='document_change_order',
            field=models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True),
        ),
        migrations.AddField(
            model_name='reportinventory',
            name='document_root_id',
            field=models.UUIDField(help_text='this is id of root document of the changed documents', null=True),
        ),
        migrations.AddField(
            model_name='reportinventory',
            name='is_change',
            field=models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents'),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='document_change_order',
            field=models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='document_root_id',
            field=models.UUIDField(help_text='this is id of root document of the changed documents', null=True),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='is_change',
            field=models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents'),
        ),
        migrations.AddField(
            model_name='reportinventorysub',
            name='document_change_order',
            field=models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True),
        ),
        migrations.AddField(
            model_name='reportinventorysub',
            name='document_root_id',
            field=models.UUIDField(help_text='this is id of root document of the changed documents', null=True),
        ),
        migrations.AddField(
            model_name='reportinventorysub',
            name='is_change',
            field=models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents'),
        ),
        migrations.AddField(
            model_name='reportpipeline',
            name='document_change_order',
            field=models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True),
        ),
        migrations.AddField(
            model_name='reportpipeline',
            name='document_root_id',
            field=models.UUIDField(help_text='this is id of root document of the changed documents', null=True),
        ),
        migrations.AddField(
            model_name='reportpipeline',
            name='is_change',
            field=models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents'),
        ),
        migrations.AddField(
            model_name='reportproduct',
            name='document_change_order',
            field=models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True),
        ),
        migrations.AddField(
            model_name='reportproduct',
            name='document_root_id',
            field=models.UUIDField(help_text='this is id of root document of the changed documents', null=True),
        ),
        migrations.AddField(
            model_name='reportproduct',
            name='is_change',
            field=models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents'),
        ),
        migrations.AddField(
            model_name='reportrevenue',
            name='document_change_order',
            field=models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True),
        ),
        migrations.AddField(
            model_name='reportrevenue',
            name='document_root_id',
            field=models.UUIDField(help_text='this is id of root document of the changed documents', null=True),
        ),
        migrations.AddField(
            model_name='reportrevenue',
            name='is_change',
            field=models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents'),
        ),
    ]
