# Generated by Django 4.2.8 on 2024-04-13 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_reportcashflow_document_change_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportinventoryproductwarehouse',
            name='is_close',
        ),
    ]
