# Generated by Django 4.2.8 on 2024-05-08 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0013_saleorder_document_change_order_and_more'),
        ('report', '0016_remove_reportinventoryproductwarehouse_is_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcustomer',
            name='sale_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_customer_sale_order', to='saleorder.saleorder'),
        ),
        migrations.AddField(
            model_name='reportproduct',
            name='sale_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_product_sale_order', to='saleorder.saleorder'),
        ),
    ]
