# Generated by Django 4.2.8 on 2024-06-05 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0026_productwarehouselottransaction_goods_issue_and_more'),
        ('report', '0018_remove_reportinventoryproductwarehouse_wrong_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsub',
            name='lot_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_log_lot_mapped', to='saledata.productwarehouselot'),
        ),
        migrations.AddField(
            model_name='reportinventory',
            name='lot_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_inventory_lot_mapped', to='saledata.productwarehouselot'),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='lot_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_inventory_product_warehouse_lot_mapped', to='saledata.productwarehouselot'),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='sum_output_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reportinventorysub',
            name='lot_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_inventory_by_month_lot_mapped', to='saledata.productwarehouselot'),
        ),
        migrations.AlterField(
            model_name='reportinventoryproductwarehouse',
            name='sum_input_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reportinventoryproductwarehouse',
            name='sum_input_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reportinventoryproductwarehouse',
            name='sum_output_quantity',
            field=models.FloatField(default=0),
        ),
    ]
