# Generated by Django 4.2.8 on 2024-06-19 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0014_saleordercost_warehouse'),
        ('report', '0019_latestsub_lot_mapped_reportinventory_lot_mapped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestsub',
            name='sale_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest_log_sale_order', to='saleorder.saleorder'),
        ),
        migrations.AddField(
            model_name='reportinventory',
            name='sale_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_inventory_sale_order', to='saleorder.saleorder'),
        ),
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='sale_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_inventory_prd_wh_sale_order', to='saleorder.saleorder'),
        ),
        migrations.AddField(
            model_name='reportinventorysub',
            name='sale_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_inventory_log_sale_order', to='saleorder.saleorder'),
        ),
    ]
