# Generated by Django 4.2.8 on 2024-06-25 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0027_remove_productwarehouselot_raw_quantity_import'),
        ('report', '0020_latestsub_sale_order_reportinventory_sale_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestsub',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest_log_warehouse', to='saledata.warehouse'),
        ),
    ]
