# Generated by Django 4.2.8 on 2024-07-04 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0014_saleordercost_warehouse'),
        ('saledata', '0027_remove_productwarehouselot_raw_quantity_import'),
        ('report', '0021_alter_latestsub_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinventoryproductwarehouse',
            name='warehouse_for_filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_inventory_prd_wh_warehouse_for_filter', to='saledata.warehouse'),
        ),
        migrations.AddField(
            model_name='reportinventorysub',
            name='warehouse_for_filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_inventory_log_warehouse_for_filter', to='saledata.warehouse'),
        ),
        migrations.AlterField(
            model_name='reportinventoryproductwarehouse',
            name='lot_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_inventory_prd_wh_lot_mapped', to='saledata.productwarehouselot'),
        ),
        migrations.AlterField(
            model_name='reportinventoryproductwarehouse',
            name='period_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_inventory_prd_wh_period', to='saledata.periods'),
        ),
        migrations.AlterField(
            model_name='reportinventoryproductwarehouse',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_inventory_prd_wh_product', to='saledata.product'),
        ),
        migrations.AlterField(
            model_name='reportinventoryproductwarehouse',
            name='sale_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_inventory_prd_wh_sale_order', to='saleorder.saleorder'),
        ),
        migrations.AlterField(
            model_name='reportinventoryproductwarehouse',
            name='sub_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_inventory_prd_wh_sub_period', to='saledata.subperiods'),
        ),
        migrations.AlterField(
            model_name='reportinventoryproductwarehouse',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_inventory_prd_wh_warehouse', to='saledata.warehouse'),
        ),
        migrations.AlterField(
            model_name='reportinventorysub',
            name='lot_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_inventory_log_lot_mapped', to='saledata.productwarehouselot'),
        ),
        migrations.AlterField(
            model_name='reportinventorysub',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_inventory_log_product', to='saledata.product'),
        ),
        migrations.AlterField(
            model_name='reportinventorysub',
            name='report_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_inventory_log', to='report.reportinventory'),
        ),
        migrations.AlterField(
            model_name='reportinventorysub',
            name='sale_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_inventory_log_sale_order', to='saleorder.saleorder'),
        ),
        migrations.AlterField(
            model_name='reportinventorysub',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_inventory_log_warehouse', to='saledata.warehouse'),
        ),
    ]
