# Generated by Django 4.2.8 on 2024-07-06 11:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0027_remove_productwarehouselot_raw_quantity_import'),
        ('report', '0022_reportinventoryproductwarehouse_warehouse_for_filter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportinventoryproductwarehouse',
            name='warehouse_for_filter',
        ),
        migrations.RemoveField(
            model_name='reportinventorysub',
            name='warehouse_for_filter',
        ),
        migrations.AddField(
            model_name='reportinventorysub',
            name='physical_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_inventory_log_physical_warehouse', to='saledata.warehouse'),
        ),
        migrations.CreateModel(
            name='ReportInventoryProductWarehouseWH',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opening_quantity', models.FloatField(default=0)),
                ('ending_quantity', models.FloatField(default=0)),
                ('report_inventory_prd_wh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_inventory_prd_wh_wh', to='report.reportinventoryproductwarehouse')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_inventory_prd_wh_wh_warehouse', to='saledata.warehouse')),
            ],
            options={
                'verbose_name': 'Report Inventory Product Warehouse WH',
                'verbose_name_plural': 'Report Inventory Product Warehouse WH',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
