# Generated by Django 4.2.8 on 2024-10-14 16:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("saledata", "0040_alter_product_supplied_by_and_more"),
        ("saleorder", "0020_saleorderproduct_quantity_wo_remain"),
        ("report", "0026_reportcustomer_customer_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportStockLogByWarehouse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "Latest Log",
                "verbose_name_plural": "Latest Log",
                "ordering": (),
                "permissions": (),
                "default_permissions": (),
            },
        ),
        migrations.RenameModel(
            old_name="ReportInventoryCostWH",
            new_name="ReportInventoryCostByWarehouse",
        ),
        migrations.RenameField(
            model_name="reportstocklog",
            old_name="current_cost",
            new_name="perpetual_current_cost",
        ),
        migrations.RenameField(
            model_name="reportstocklog",
            old_name="current_quantity",
            new_name="perpetual_current_quantity",
        ),
        migrations.RenameField(
            model_name="reportstocklog",
            old_name="current_value",
            new_name="perpetual_current_value",
        ),
        migrations.AlterField(
            model_name="reportinventorycost",
            name="lot_mapped",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_inventory_cost_lot_mapped",
                to="saledata.productwarehouselot",
            ),
        ),
        migrations.AlterField(
            model_name="reportstock",
            name="lot_mapped",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_stock_lot_mapped",
                to="saledata.productwarehouselot",
            ),
        ),
        migrations.AlterField(
            model_name="reportstocklog",
            name="lot_mapped",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_stock_log_lot_mapped",
                to="saledata.productwarehouselot",
            ),
        ),
        migrations.DeleteModel(
            name="LatestLog",
        ),
        migrations.AddField(
            model_name="reportstocklogbywarehouse",
            name="latest_log",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report.reportstocklog",
            ),
        ),
        migrations.AddField(
            model_name="reportstocklogbywarehouse",
            name="lot_mapped",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="latest_log_lot_mapped",
                to="saledata.productwarehouselot",
            ),
        ),
        migrations.AddField(
            model_name="reportstocklogbywarehouse",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="latest_log_product",
                to="saledata.product",
            ),
        ),
        migrations.AddField(
            model_name="reportstocklogbywarehouse",
            name="sale_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="latest_log_sale_order",
                to="saleorder.saleorder",
            ),
        ),
        migrations.AddField(
            model_name="reportstocklogbywarehouse",
            name="warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="latest_log_warehouse",
                to="saledata.warehouse",
            ),
        ),
    ]
