# Generated by Django 4.2.8 on 2024-10-22 09:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0040_alter_product_supplied_by_and_more'),
        ('saleorder', '0020_saleorderproduct_quantity_wo_remain'),
        ('report', '0027_reportstocklogbywarehouse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportInventoryCostLatestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Latest Log',
                'verbose_name_plural': 'Latest Log',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='reportstocklog',
            name='fifo_cost_detail',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='reportstocklog',
            name='fifo_pushed_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ReportStockLogByWarehouse',
        ),
        migrations.AddField(
            model_name='reportinventorycostlatestlog',
            name='fifo_flag_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rp_inv_cost_fifo_flag_log', to='report.reportstocklog'),
        ),
        migrations.AddField(
            model_name='reportinventorycostlatestlog',
            name='latest_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rp_inv_cost_latest_log', to='report.reportstocklog'),
        ),
        migrations.AddField(
            model_name='reportinventorycostlatestlog',
            name='lot_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rp_inv_cost_lot_mapped', to='saledata.productwarehouselot'),
        ),
        migrations.AddField(
            model_name='reportinventorycostlatestlog',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rp_inv_cost_product', to='saledata.product'),
        ),
        migrations.AddField(
            model_name='reportinventorycostlatestlog',
            name='sale_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rp_inv_cost_sale_order', to='saleorder.saleorder'),
        ),
        migrations.AddField(
            model_name='reportinventorycostlatestlog',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rp_inv_cost_warehouse', to='saledata.warehouse'),
        ),
    ]
