# Generated by Django 4.2.8 on 2024-10-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0040_alter_product_supplied_by_and_more'),
        ('quotation', '0018_quotation_customer_data_quotation_next_association_and_more'),
        ('workflow', '0006_alter_association_date_modified_and_more'),
        ('opportunity', '0012_opportunity_next_association'),
        ('report', '0028_reportinventorycostlatestlog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportrevenue',
            options={'default_permissions': (), 'ordering': ('-date_approved',), 'permissions': (), 'verbose_name': 'Report Revenue', 'verbose_name_plural': 'Report Revenues'},
        ),
        migrations.AddField(
            model_name='reportcashflow',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
        migrations.AddField(
            model_name='reportcustomer',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
        migrations.AddField(
            model_name='reportinventorycost',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
        migrations.AddField(
            model_name='reportpipeline',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
        migrations.AddField(
            model_name='reportproduct',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
        migrations.AddField(
            model_name='reportrevenue',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_revenue_customer', to='saledata.account'),
        ),
        migrations.AddField(
            model_name='reportrevenue',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
        migrations.AddField(
            model_name='reportrevenue',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_revenue_opportunity', to='opportunity.opportunity'),
        ),
        migrations.AddField(
            model_name='reportrevenue',
            name='quotation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_revenue_quotation', to='quotation.quotation'),
        ),
        migrations.AddField(
            model_name='reportstock',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
        migrations.AddField(
            model_name='reportstocklog',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
    ]
