# Generated by Django 4.2.8 on 2024-11-27 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_process_global_app_processconfiguration_global_app_and_more'),
        ('report', '0030_balanceinitialization_balanceinitializationserial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceinitialization',
            name='process_stage_app',
            field=models.ForeignKey(help_text='The process stage app claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.processstageapplication'),
        ),
        migrations.AddField(
            model_name='balanceinitializationlot',
            name='process_stage_app',
            field=models.ForeignKey(help_text='The process stage app claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.processstageapplication'),
        ),
        migrations.AddField(
            model_name='balanceinitializationserial',
            name='process_stage_app',
            field=models.ForeignKey(help_text='The process stage app claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.processstageapplication'),
        ),
        migrations.AddField(
            model_name='reportcashflow',
            name='process_stage_app',
            field=models.ForeignKey(help_text='The process stage app claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.processstageapplication'),
        ),
        migrations.AddField(
            model_name='reportcustomer',
            name='process_stage_app',
            field=models.ForeignKey(help_text='The process stage app claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.processstageapplication'),
        ),
        migrations.AddField(
            model_name='reportinventorycost',
            name='process_stage_app',
            field=models.ForeignKey(help_text='The process stage app claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.processstageapplication'),
        ),
        migrations.AddField(
            model_name='reportpipeline',
            name='process_stage_app',
            field=models.ForeignKey(help_text='The process stage app claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.processstageapplication'),
        ),
        migrations.AddField(
            model_name='reportproduct',
            name='process_stage_app',
            field=models.ForeignKey(help_text='The process stage app claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.processstageapplication'),
        ),
        migrations.AddField(
            model_name='reportrevenue',
            name='process_stage_app',
            field=models.ForeignKey(help_text='The process stage app claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.processstageapplication'),
        ),
        migrations.AddField(
            model_name='reportstock',
            name='process_stage_app',
            field=models.ForeignKey(help_text='The process stage app claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.processstageapplication'),
        ),
        migrations.AddField(
            model_name='reportstocklog',
            name='process_stage_app',
            field=models.ForeignKey(help_text='The process stage app claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.processstageapplication'),
        ),
    ]
