# Generated by Django 4.2.8 on 2024-12-31 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseorder', '0002_leaseorderpaymentstage_date_type_and_more'),
        ('report', '0031_balanceinitialization_process_stage_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinventorycost',
            name='lease_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_inventory_cost_lease_order', to='leaseorder.leaseorder'),
        ),
        migrations.AddField(
            model_name='reportinventorycostlatestlog',
            name='lease_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rp_inv_cost_lease_order', to='leaseorder.leaseorder'),
        ),
        migrations.AddField(
            model_name='reportstock',
            name='lease_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_stock_lease_order', to='leaseorder.leaseorder'),
        ),
        migrations.AddField(
            model_name='reportstocklog',
            name='lease_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_stock_log_lease_order', to='leaseorder.leaseorder'),
        ),
    ]
