# Generated by Django 4.2.8 on 2025-04-22 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseorder', '0010_alter_leaseorderproductasset_options_and_more'),
        ('report', '0032_reportinventorycost_lease_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcustomer',
            name='lease_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_customer_lease_order', to='leaseorder.leaseorder'),
        ),
        migrations.AddField(
            model_name='reportrevenue',
            name='lease_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_revenue_lease_order', to='leaseorder.leaseorder'),
        ),
    ]
