# Generated by Django 4.2.8 on 2025-10-07 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseorder', '0015_alter_leaseordercost_product_title_and_more'),
        ('saledata', '0080_alter_periods_default_inventory_value_method_and_more'),
        ('saleorder', '0036_saleorder_is_done_purchase_request'),
        ('report', '0035_rename_for_balance_reportinventorycost_for_balance_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinventorycost',
            name='serial_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_inventory_cost_serial_mapped', to='saledata.productwarehouseserial'),
        ),
        migrations.AddField(
            model_name='reportinventorycostlatestlog',
            name='serial_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rp_inv_cost_serial_mapped', to='saledata.productwarehouseserial'),
        ),
        migrations.AddField(
            model_name='reportstock',
            name='serial_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_stock_serial_mapped', to='saledata.productwarehouseserial'),
        ),
        migrations.AddField(
            model_name='reportstocklog',
            name='serial_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='reportstocklog',
            name='serial_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_stock_log_serial_mapped', to='saledata.productwarehouseserial'),
        ),
        migrations.AlterField(
            model_name='reportinventorycost',
            name='lease_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_inventory_cost_lease_order', to='leaseorder.leaseorder'),
        ),
        migrations.AlterField(
            model_name='reportinventorycost',
            name='lot_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_inventory_cost_lot_mapped', to='saledata.productwarehouselot'),
        ),
        migrations.AlterField(
            model_name='reportinventorycost',
            name='period_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_inventory_cost_period_mapped', to='saledata.periods'),
        ),
        migrations.AlterField(
            model_name='reportinventorycost',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_inventory_cost_product', to='saledata.product'),
        ),
        migrations.AlterField(
            model_name='reportinventorycost',
            name='sale_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_inventory_cost_sale_order', to='saleorder.saleorder'),
        ),
        migrations.AlterField(
            model_name='reportinventorycost',
            name='sub_latest_log',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.reportstocklog'),
        ),
        migrations.AlterField(
            model_name='reportinventorycost',
            name='sub_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_inventory_cost_sub_period', to='saledata.subperiods'),
        ),
        migrations.AlterField(
            model_name='reportinventorycost',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_inventory_cost_warehouse', to='saledata.warehouse'),
        ),
        migrations.AlterField(
            model_name='reportinventorycostbywarehouse',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_inventory_cost_wh_warehouse', to='saledata.warehouse'),
        ),
        migrations.AlterField(
            model_name='reportinventorycostlatestlog',
            name='lease_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rp_inv_cost_lease_order', to='leaseorder.leaseorder'),
        ),
        migrations.AlterField(
            model_name='reportinventorycostlatestlog',
            name='lot_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rp_inv_cost_lot_mapped', to='saledata.productwarehouselot'),
        ),
        migrations.AlterField(
            model_name='reportinventorycostlatestlog',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rp_inv_cost_product', to='saledata.product'),
        ),
        migrations.AlterField(
            model_name='reportinventorycostlatestlog',
            name='sale_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rp_inv_cost_sale_order', to='saleorder.saleorder'),
        ),
        migrations.AlterField(
            model_name='reportinventorycostlatestlog',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rp_inv_cost_warehouse', to='saledata.warehouse'),
        ),
        migrations.AlterField(
            model_name='reportstock',
            name='lease_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_stock_lease_order', to='leaseorder.leaseorder'),
        ),
        migrations.AlterField(
            model_name='reportstock',
            name='lot_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_stock_lot_mapped', to='saledata.productwarehouselot'),
        ),
        migrations.AlterField(
            model_name='reportstock',
            name='period_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_stock_period_mapped', to='saledata.periods'),
        ),
        migrations.AlterField(
            model_name='reportstock',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_stock_product', to='saledata.product'),
        ),
        migrations.AlterField(
            model_name='reportstock',
            name='sale_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_stock_sale_order', to='saleorder.saleorder'),
        ),
        migrations.AlterField(
            model_name='reportstock',
            name='sub_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_stock_sub_period', to='saledata.subperiods'),
        ),
        migrations.AlterField(
            model_name='reportstocklog',
            name='lease_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_stock_log_lease_order', to='leaseorder.leaseorder'),
        ),
        migrations.AlterField(
            model_name='reportstocklog',
            name='lot_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_stock_log_lot_mapped', to='saledata.productwarehouselot'),
        ),
        migrations.AlterField(
            model_name='reportstocklog',
            name='physical_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_stock_log_physical_warehouse', to='saledata.warehouse'),
        ),
        migrations.AlterField(
            model_name='reportstocklog',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_stock_log_product', to='saledata.product'),
        ),
        migrations.AlterField(
            model_name='reportstocklog',
            name='sale_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_stock_log_sale_order', to='saleorder.saleorder'),
        ),
        migrations.AlterField(
            model_name='reportstocklog',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_stock_log_warehouse', to='saledata.warehouse'),
        ),
    ]
