# Generated by Django 4.2.8 on 2025-10-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0036_reportinventorycost_serial_mapped_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportinventorycost',
            name='serial_mapped',
        ),
        migrations.RemoveField(
            model_name='reportinventorycostlatestlog',
            name='serial_mapped',
        ),
        migrations.RemoveField(
            model_name='reportstock',
            name='serial_mapped',
        ),
        migrations.RemoveField(
            model_name='reportstocklog',
            name='serial_mapped',
        ),
        migrations.AddField(
            model_name='reportinventorycost',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportinventorycostlatestlog',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportstock',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportstocklog',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
