# Generated by Django 4.2.8 on 2025-10-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0037_remove_reportinventorycost_serial_mapped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceinitializationserial',
            name='specific_value',
            field=models.FloatField(default=0),
        ),
    ]
