# Generated by Django 4.2.8 on 2025-11-06 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceorder', '0010_alter_serviceorderpaymentdetail_options_and_more'),
        ('report', '0038_balanceinitializationserial_specific_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportinventorycost',
            name='service_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_inventory_cost_service_order', to='serviceorder.serviceorder'),
        ),
        migrations.AddField(
            model_name='reportinventorycostlatestlog',
            name='service_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rp_inv_cost_service_order', to='serviceorder.serviceorder'),
        ),
        migrations.AddField(
            model_name='reportstock',
            name='service_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_stock_service_order', to='serviceorder.serviceorder'),
        ),
        migrations.AddField(
            model_name='reportstocklog',
            name='service_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_stock_log_service_order', to='serviceorder.serviceorder'),
        ),
    ]
