# Generated by Django 4.2.8 on 2024-01-24 16:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0008_company_email_app_password_status_and_more'),
        ('purchasing', '0003_purchaseorder_purchase_order_payment_stage_and_more'),
        ('saledata', '0012_warehouse_is_dropship_alter_warehouse_full_address'),
        ('attachments', '0005_publicfiles_relate_app_publicfiles_relate_app_code_and_more'),
        ('workflow', '0005_collabinworkflow_is_edit_all_zone_and_more'),
        ('inventory', '0004_goodsissue_next_node_collab_and_more'),
        ('process', '0001_initial'),
        ('hr', '0002_employee_avatar_img'),
        ('tenant', '0001_initial'),
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('supplier_name', models.CharField(blank=True, max_length=250, null=True)),
                ('posting_date', models.DateTimeField()),
                ('document_date', models.DateTimeField()),
                ('invoice_date', models.DateTimeField()),
                ('invoice_sign', models.CharField(max_length=250)),
                ('invoice_number', models.CharField(max_length=250)),
                ('invoice_example', models.SmallIntegerField(choices=[(0, '01GTKT0/001'), (1, '01GTKT3/001'), (2, '02GTTT0/001'), (3, '02GTTT3/001'), (4, '03XKNB3/001'), (5, '04HGDL3/001'), (6, '07KPTQ3/001')])),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('current_stage', models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('next_node_collab', models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee')),
                ('po_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchasing.purchaseorder')),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
                ('space', models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space')),
                ('supplier_mapped', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.account')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('workflow_runtime', models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc')),
            ],
            options={
                'verbose_name': 'AP Invoice',
                'verbose_name_plural': 'AP Invoices',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='APInvoiceItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_index', models.IntegerField(default=0)),
                ('product_quantity', models.FloatField(default=0)),
                ('product_unit_price', models.FloatField(default=0)),
                ('product_tax_value', models.FloatField(default=0)),
                ('product_subtotal', models.FloatField(default=0)),
                ('ap_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_invoice_items', to='apinvoice.apinvoice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.product')),
                ('product_uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.unitofmeasure')),
            ],
            options={
                'verbose_name': 'AP Invoice Item',
                'verbose_name_plural': 'AP Invoice Items',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='APInvoiceGoodsReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ap_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_invoice_goods_receipts', to='apinvoice.apinvoice')),
                ('goods_receipt_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.goodsreceipt')),
            ],
            options={
                'verbose_name': 'AP Invoice Goods Receipt',
                'verbose_name_plural': 'AP Invoice Goods Receipt',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='APInvoiceAttachmentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('ap_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_invoice_attachments', to='apinvoice.apinvoice')),
                ('attachment', models.OneToOneField(help_text='Many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_files', to='attachments.files', verbose_name='Attachment files')),
            ],
            options={
                'verbose_name': 'AP Invoice attachment',
                'verbose_name_plural': 'AP Invoice attachments',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
