# Generated by Django 4.2.8 on 2024-03-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apinvoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apinvoice',
            name='invoice_example',
            field=models.SmallIntegerField(choices=[(0, '01GTKT0'), (1, '01GTKT3'), (2, '02GTTT0'), (3, '02GTTT3'), (4, '03XKNB3'), (5, '04HGDL3'), (6, '07KPTQ3')]),
        ),
    ]
