# Generated by Django 4.2.8 on 2024-08-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apinvoice', '0003_apinvoice_document_change_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apinvoice',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
    ]
