# Generated by Django 4.2.8 on 2024-10-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_alter_association_date_modified_and_more'),
        ('apinvoice', '0004_alter_apinvoice_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='apinvoice',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
    ]
