# Generated by Django 4.2.8 on 2025-02-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apinvoice', '0006_apinvoice_process_stage_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='apinvoiceitems',
            name='increased_FA_value',
            field=models.FloatField(default=0),
        ),
    ]
