# Generated by Django 4.2.8 on 2025-04-03 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0064_remove_account_parent_account_and_more'),
        ('apinvoice', '0007_apinvoiceitems_increased_fa_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apinvoice',
            old_name='po_mapped',
            new_name='purchase_order_mapped',
        ),
        migrations.RemoveField(
            model_name='apinvoice',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='cash_outflow_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='purchase_order_mapped_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='sum_after_tax_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='sum_pretax_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='sum_tax_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='apinvoice',
            name='supplier_mapped_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='apinvoicegoodsreceipt',
            name='goods_receipt_mapped_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='apinvoiceitems',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='apinvoiceitems',
            name='product_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='apinvoiceitems',
            name='product_subtotal_final',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='apinvoiceitems',
            name='product_tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.tax'),
        ),
        migrations.AddField(
            model_name='apinvoiceitems',
            name='product_tax_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='apinvoiceitems',
            name='product_uom_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='apinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='apinvoice',
            name='invoice_sign',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='apinvoiceitems',
            name='increased_FA_value',
            field=models.FloatField(default=0, help_text='increased fixed asset value for this item (product_subtotal)'),
        ),
    ]
