# Generated by Django 4.2.8 on 2025-12-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apinvoice', '0010_alter_apinvoiceitems_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apinvoiceitems',
            name='increased_FA_value',
        ),
        migrations.AddField(
            model_name='apinvoiceitems',
            name='increased_asset_quantity',
            field=models.IntegerField(default=0, help_text='increased fixed asset quantity for this item'),
        ),
    ]
