# Generated by Django 4.1.3 on 2023-05-30 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0022_alter_account_annual_revenue_and_more'),
        ('promotion', '0006_promotion_customers_map_promotion'),
        ('saleorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderproduct',
            name='is_promotion',
            field=models.BooleanField(default=False, help_text='flag to know this product is for promotion (discount, gift,...)'),
        ),
        migrations.AddField(
            model_name='saleorderproduct',
            name='is_shipping',
            field=models.BooleanField(default=False, help_text='flag to know this product is for shipping fee'),
        ),
        migrations.AddField(
            model_name='saleorderproduct',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_product_promotion', to='promotion.promotion', verbose_name='promotion'),
        ),
        migrations.AddField(
            model_name='saleorderproduct',
            name='shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_product_shipping', to='saledata.shipping', verbose_name='shipping'),
        ),
    ]
