# Generated by Django 4.1.3 on 2023-11-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderexpense',
            name='payment_plan_real_value',
            field=models.FloatField(default=0),
        ),
    ]
