# Generated by Django 4.1.3 on 2023-11-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0002_saleorderexpense_payment_plan_real_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderexpense',
            name='is_labor',
            field=models.BooleanField(default=False, help_text='flag to check if record is MasterData Internal Labor Item (model Expense)'),
        ),
    ]
