# Generated by Django 4.1.3 on 2023-05-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0002_saleorderproduct_is_promotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='delivery_call',
            field=models.BooleanField(default=False, help_text='State call delivery of this', verbose_name='Called delivery'),
        ),
        migrations.AlterField(
            model_name='saleordercost',
            name='product_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='saleorderexpense',
            name='expense_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='saleorderproduct',
            name='product_quantity',
            field=models.FloatField(default=0),
        ),
    ]
