# Generated by Django 4.1.3 on 2023-11-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0003_saleorderexpense_is_labor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorderexpense',
            name='payment_plan_real_value',
        ),
    ]
