# Generated by Django 4.1.3 on 2023-06-16 00:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companyconfig'),
        ('saleorder', '0005_saleordercost_is_shipping_saleordercost_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrderAppConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_sale_config', models.JSONField(default=dict, help_text='all config use for Sale Order without Opportunity, data record in ConfigShortSale')),
                ('long_sale_config', models.JSONField(default=dict, help_text='all config use for Sale Order with Opportunity, data record in ConfigLongSale')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_config_detail', to='company.company')),
            ],
            options={
                'verbose_name': 'Sale Order Config',
                'verbose_name_plural': 'Sale Order Configs',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ConfigOrderShortSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_choose_price_list', models.BooleanField(default=False, help_text='flag to check if user can choose price in price list')),
                ('is_input_price', models.BooleanField(default=False, help_text='flag to check if user can input price for any product')),
                ('is_discount_on_product', models.BooleanField(default=False, help_text='flag to check if user can input discount for any product')),
                ('is_discount_on_total', models.BooleanField(default=False, help_text='flag to check if user can input discount for total of all products')),
                ('sale_order_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_config_short_sale', to='saleorder.saleorderappconfig', verbose_name='config short sale')),
            ],
            options={
                'verbose_name': 'Sale Order Short Sale Config',
                'verbose_name_plural': 'Sale Order Short Sale Configs',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ConfigOrderLongSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_not_input_price', models.BooleanField(default=False, help_text='flag to check if user can input price for any product')),
                ('is_not_discount_on_product', models.BooleanField(default=False, help_text='flag to check if user can input discount for any product')),
                ('is_not_discount_on_total', models.BooleanField(default=False, help_text='flag to check if user can input discount for total of all products')),
                ('sale_order_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_config_long_sale', to='saleorder.saleorderappconfig', verbose_name='config long sale')),
            ],
            options={
                'verbose_name': 'Sale Order Long Sale Config',
                'verbose_name_plural': 'Sale Order Long Sale Configs',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
