# Generated by Django 4.1.3 on 2023-06-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0006_saleorderappconfig_configordershortsale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleordercost',
            name='product_subtotal_price_after_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='saleorderexpense',
            name='expense_subtotal_price_after_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='saleorderexpense',
            name='expense_type_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saleorderproduct',
            name='product_subtotal_price_after_tax',
            field=models.FloatField(default=0),
        ),
    ]
