# Generated by Django 4.1.3 on 2023-12-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0006_saleorder_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='delivery_status',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Delivering'), (2, 'Partially delivered'), (3, 'Delivered')], default=0),
        ),
    ]
