# Generated by Django 4.1.3 on 2023-12-15 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0005_product_available_notify_and_more'),
        ('saleorder', '0007_alter_saleorder_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='customer_billing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_order_customer_billing', to='saledata.accountbillingaddress', verbose_name='sale order billing'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='customer_shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_order_customer_shipping', to='saledata.accountshippingaddress', verbose_name='sale order shipping'),
        ),
    ]
