# Generated by Django 4.1.3 on 2023-07-05 11:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companyconfig'),
        ('saleorder', '0007_saleordercost_product_subtotal_price_after_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='sale_order_indicators_data',
            field=models.JSONField(default=list, help_text='read data indicators, use for get list or detail sale order, records in model SaleOrderIndicator'),
        ),
        migrations.CreateModel(
            name='SaleOrderIndicatorConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('example', models.CharField(blank=True, max_length=300)),
                ('application_code', models.CharField(blank=True, max_length=100)),
                ('formula_data', models.JSONField(default=list)),
                ('formula_data_show', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_order_indicator_config_company', to='company.company')),
            ],
            options={
                'verbose_name': 'Sale Order Indicator Config',
                'verbose_name_plural': 'Sale Order Indicator Configs',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SaleOrderIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indicator_value', models.FloatField(default=0, help_text='value of specific indicator for sale order')),
                ('indicator_rate', models.FloatField(default=0, help_text='rate value of specific indicator for sale order')),
                ('quotation_indicator_value', models.FloatField(default=0, help_text='value of specific indicator for quotation mapped with sale order')),
                ('quotation_indicator_rate', models.FloatField(default=0, help_text='rate value of specific indicator for quotation mapped with sale order')),
                ('difference_indicator_value', models.FloatField(default=0, help_text='difference value between quotation and sale order')),
                ('order', models.IntegerField(default=1)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_indicator_indicator', to='saleorder.saleorderindicatorconfig', verbose_name='indicator')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_indicator_sale_order', to='saleorder.saleorder', verbose_name='sale order')),
            ],
            options={
                'verbose_name': 'Sale Order Indicator',
                'verbose_name_plural': 'Sale Order Indicators',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
