# Generated by Django 4.2.8 on 2024-01-18 14:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_company_email_app_password_status_and_more'),
        ('hr', '0002_employee_avatar_img'),
        ('tenant', '0001_initial'),
        ('saleorder', '0009_saleorder_next_node_collab'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='sale_order_payment_stage',
            field=models.JSONField(default=list, help_text='read data payment stage, use for get list or detail sale order'),
        ),
        migrations.CreateModel(
            name='SaleOrderPaymentStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('stage', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Sale order'), (1, 'Contract'), (2, 'Delivery'), (3, 'Final acceptance'))")),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='remark')),
                ('date', models.DateTimeField(null=True)),
                ('date_type', models.SmallIntegerField(default=0)),
                ('number_of_day', models.IntegerField(default=0, help_text='number of days before due date')),
                ('payment_ratio', models.FloatField(default=0)),
                ('value_before_tax', models.FloatField(default=0)),
                ('due_date', models.DateTimeField(null=True)),
                ('is_ar_invoice', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_stage_sale_order', to='saleorder.saleorder', verbose_name='sale order')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Sale Order Payment Stage',
                'verbose_name_plural': 'Sale Order Payment Stages',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
