# Generated by Django 4.1.3 on 2023-08-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0011_saleorderexpense_is_product_saleorderexpense_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderproduct',
            name='remain_for_purchase_request',
            field=models.FloatField(default=0),
        ),
    ]
