# Generated by Django 4.1.3 on 2023-08-09 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0039_alter_product_options'),
        ('saleorder', '0013_saleorderproduct_remain_for_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='customer_billing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_customer_billing', to='saledata.accountbillingaddress', verbose_name='sale order billing'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='customer_shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_customer_shipping', to='saledata.accountshippingaddress', verbose_name='sale order shipping'),
        ),
    ]
