# Generated by Django 4.2.8 on 2024-05-14 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0022_productwarehouselot_raw_quantity_import'),
        ('saleorder', '0013_saleorder_document_change_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleordercost',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_cost_warehouse', to='saledata.warehouse', verbose_name='warehouse'),
        ),
    ]
