# Generated by Django 4.2.8 on 2024-07-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0014_saleordercost_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='has_regis',
            field=models.BooleanField(default=False, help_text='is True if linked with registration else False'),
        ),
    ]
