# Generated by Django 4.1.3 on 2023-09-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0049_remove_product_general_product_type_and_more'),
        ('saleorder', '0016_alter_saleorder_system_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderexpense',
            name='expense_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_expense_expense_item', to='saledata.expenseitem', verbose_name='expense item'),
        ),
    ]
