# Generated by Django 4.2.8 on 2024-08-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0016_alter_saleorderappconfig_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleordercost',
            name='product_data',
            field=models.JSONField(default=dict, help_text='data json of product'),
        ),
        migrations.AddField(
            model_name='saleordercost',
            name='shipping_data',
            field=models.JSONField(default=dict, help_text='data json of shipping'),
        ),
        migrations.AddField(
            model_name='saleordercost',
            name='tax_data',
            field=models.JSONField(default=dict, help_text='data json of tax'),
        ),
        migrations.AddField(
            model_name='saleordercost',
            name='uom_data',
            field=models.JSONField(default=dict, help_text='data json of uom'),
        ),
        migrations.AddField(
            model_name='saleordercost',
            name='warehouse_data',
            field=models.JSONField(default=dict, help_text='data json of warehouse'),
        ),
        migrations.AddField(
            model_name='saleorderexpense',
            name='expense_data',
            field=models.JSONField(default=dict, help_text='data json of expense'),
        ),
        migrations.AddField(
            model_name='saleorderexpense',
            name='expense_item_data',
            field=models.JSONField(default=dict, help_text='data json of expense_item'),
        ),
        migrations.AddField(
            model_name='saleorderexpense',
            name='tax_data',
            field=models.JSONField(default=dict, help_text='data json of tax'),
        ),
        migrations.AddField(
            model_name='saleorderexpense',
            name='uom_data',
            field=models.JSONField(default=dict, help_text='data json of uom'),
        ),
        migrations.AddField(
            model_name='saleorderproduct',
            name='product_data',
            field=models.JSONField(default=dict, help_text='data json of product'),
        ),
        migrations.AddField(
            model_name='saleorderproduct',
            name='promotion_data',
            field=models.JSONField(default=dict, help_text='data json of promotion'),
        ),
        migrations.AddField(
            model_name='saleorderproduct',
            name='shipping_data',
            field=models.JSONField(default=dict, help_text='data json of shipping'),
        ),
        migrations.AddField(
            model_name='saleorderproduct',
            name='tax_data',
            field=models.JSONField(default=dict, help_text='data json of tax'),
        ),
        migrations.AddField(
            model_name='saleorderproduct',
            name='uom_data',
            field=models.JSONField(default=dict, help_text='data json of uom'),
        ),
    ]
