# Generated by Django 4.2.8 on 2024-08-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0018_alter_saleorder_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleordercost',
            name='supplied_by',
            field=models.SmallIntegerField(default=0),
        ),
    ]
