# Generated by Django 4.2.8 on 2024-09-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0019_saleordercost_supplied_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderproduct',
            name='quantity_wo_remain',
            field=models.FloatField(default=0, help_text='this is quantity of product which is not work ordered yet, update when WO finish'),
        ),
    ]
