# Generated by Django 4.2.8 on 2024-10-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_alter_association_date_modified_and_more'),
        ('saleorder', '0020_saleorderproduct_quantity_wo_remain'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='customer_data',
            field=models.JSONField(default=dict, help_text='data json of customer'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
        migrations.AddField(
            model_name='saleorderindicator',
            name='quotation_indicator_data',
            field=models.JSONField(default=dict, help_text='data json of quotation indicator'),
        ),
    ]
