# Generated by Django 4.2.8 on 2024-11-18 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_project_date_close'),
        ('saleorder', '0022_saleorder_contact_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='flag to know this record is recurring template'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='project',
            field=models.ForeignKey(help_text='Relate to Project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_prj', to='project.project'),
        ),
    ]
