# Generated by Django 4.2.8 on 2024-11-25 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recurrence', '0001_initial'),
        ('saleorder', '0023_saleorder_is_recurring_saleorder_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='is_recurrence_template',
            field=models.BooleanField(default=False, help_text='flag to know this record is set as recurrence template'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='recurrence_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_recurrence_task', to='recurrence.recurrencetask'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='flag to know this record is recurring'),
        ),
    ]
