# Generated by Django 4.2.8 on 2024-12-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0025_saleorder_process_stage_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='quotation_data',
            field=models.JSONField(default=dict, help_text='data json of quotation'),
        ),
    ]
