# Generated by Django 4.2.8 on 2024-12-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0027_saleordercost_code_saleordercost_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderpaymentstage',
            name='date_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='saleorderpaymentstage',
            name='issue_invoice',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='saleorderpaymentstage',
            name='value_after_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='saleorderpaymentstage',
            name='value_total',
            field=models.FloatField(default=0),
        ),
    ]
