# Generated by Django 4.2.8 on 2025-06-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0030_rename_issue_invoice_saleorderpaymentstage_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderproduct',
            name='product_discount_amount_total',
            field=models.FloatField(default=0),
        ),
    ]
