# Generated by Django 4.2.8 on 2025-08-20 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0032_saleorderattachment_saleorder_attachment_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The record created at value'),
        ),
    ]
