# Generated by Django 4.2.8 on 2025-09-23 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0079_warehouse_address_data_warehouse_detail_address'),
        ('saleorder', '0034_alter_saleordercost_product_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderproduct',
            name='product_quantity_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='saleorderproduct',
            name='uom_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_product_uom_time', to='saledata.unitofmeasure', verbose_name='unit'),
        ),
        migrations.AddField(
            model_name='saleorderproduct',
            name='uom_time_data',
            field=models.JSONField(default=dict, help_text='data json of uom'),
        ),
    ]
