# Generated by Django 4.2.8 on 2025-09-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0035_saleorderproduct_product_quantity_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='is_done_purchase_request',
            field=models.BooleanField(default=False),
        ),
    ]
