# Generated by Django 4.2.8 on 2025-10-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0037_saleorderproduct_product_specific'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleordercost',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
