# Generated by Django 4.2.8 on 2025-10-20 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0083_remove_product_avatar_and_more'),
        ('saleorder', '0038_saleordercost_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='currency_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_currency_company', to='saledata.currency'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='currency_company_data',
            field=models.JSONField(default=dict, help_text='data json of currency_company'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='currency_exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_currency_exchange', to='saledata.currency'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='currency_exchange_data',
            field=models.JSONField(default=dict, help_text='data json of currency_exchange'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='currency_exchange_rate',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='is_currency_exchange',
            field=models.BooleanField(default=False, help_text='flag to know allow currency exchange'),
        ),
    ]
