# Generated by Django 4.2.8 on 2024-12-19 16:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('company', '0014_alter_companyconfig_options'),
        ('leaseorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseorderpaymentstage',
            name='date_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='leaseorderpaymentstage',
            name='issue_invoice',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='leaseorderpaymentstage',
            name='value_after_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseorderpaymentstage',
            name='value_total',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='LeaseOrderLogistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('lease_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaseorder.leaseorder')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Lease Order Logistic',
                'verbose_name_plural': 'Lease Order Logistics',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
