# Generated by Django 4.2.8 on 2024-12-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseorder', '0002_leaseorderpaymentstage_date_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseorderproduct',
            name='asset_type',
            field=models.SmallIntegerField(help_text="choices= ((1, 'Product'), (2, 'Tool'), (3, 'Fixed asset'))", null=True),
        ),
    ]
