# Generated by Django 4.2.8 on 2025-01-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseorder', '0003_alter_leaseorderproduct_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseordercost',
            name='product_depreciation_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseordercost',
            name='product_quantity_depreciation',
            field=models.FloatField(default=0),
        ),
    ]
