# Generated by Django 4.2.8 on 2025-02-26 12:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_email_app_password_and_more'),
        ('saledata', '0056_rename_lease_depreciation_price_product_depreciation_price_and_more'),
        ('tenant', '0001_initial'),
        ('company', '0016_companyconfig_accounting_policies_and_more'),
        ('leaseorder', '0005_leaseordercost_product_depreciation_adjustment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaseordercost',
            old_name='product_quantity_depreciation',
            new_name='product_depreciation_time',
        ),
        migrations.AddField(
            model_name='leaseorder',
            name='lease_costs_leased_data',
            field=models.JSONField(default=list, help_text='read data cost leased, use for get list or detail lease order'),
        ),
        migrations.AddField(
            model_name='leaseordercost',
            name='product_lease_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='leaseordercost',
            name='product_lease_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='leaseorderproduct',
            name='product_quantity_leased_data',
            field=models.JSONField(default=list, help_text='read data products leased'),
        ),
        migrations.AlterField(
            model_name='leaseorder',
            name='lease_costs_data',
            field=models.JSONField(default=list, help_text='read data cost, use for get list or detail lease order'),
        ),
        migrations.AlterField(
            model_name='leaseorder',
            name='lease_expenses_data',
            field=models.JSONField(default=list, help_text='read data expense, use for get list or detail lease order'),
        ),
        migrations.AlterField(
            model_name='leaseorder',
            name='lease_payment_stage',
            field=models.JSONField(default=list, help_text='read data payment stage, use for get list or detail lease order'),
        ),
        migrations.CreateModel(
            name='LeaseOrderProductLeased',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('product_data', models.JSONField(default=dict, help_text='data json of product')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('lease_order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_product_leased_lo_product', to='leaseorder.leaseorderproduct', verbose_name='lease order product')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_product_leased_product', to='saledata.product', verbose_name='product leased')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Lease Order Product Leased',
                'verbose_name_plural': 'Lease Order Products Leased',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LeaseOrderCostLeased',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('product_data', models.JSONField(default=dict, help_text='data json of product')),
                ('uom_time_data', models.JSONField(default=dict, help_text='data json of uom time')),
                ('product_quantity_time', models.FloatField(default=0)),
                ('net_value', models.FloatField(default=0)),
                ('product_subtotal_price', models.FloatField(default=0)),
                ('order', models.IntegerField(default=1)),
                ('product_depreciation_subtotal', models.FloatField(default=0)),
                ('product_depreciation_price', models.FloatField(default=0)),
                ('product_depreciation_time', models.FloatField(default=0)),
                ('product_lease_start_date', models.DateField(null=True)),
                ('product_lease_end_date', models.DateField(null=True)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('lease_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_cost_leased_lease_order', to='leaseorder.leaseorder', verbose_name='lease order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_cost_leased_product', to='saledata.product', verbose_name='product')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('uom_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_cost_leased_uom_time', to='saledata.unitofmeasure', verbose_name='uom time')),
            ],
            options={
                'verbose_name': 'Lease Order Cost Leased',
                'verbose_name_plural': 'Lease Order Costs Leased',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
