# Generated by Django 4.2.8 on 2025-03-13 10:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0059_remove_product_date_first_delivery_and_more'),
        ('tenant', '0001_initial'),
        ('company', '0016_companyconfig_accounting_policies_and_more'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('asset', '0006_alter_fixedasset_status'),
        ('leaseorder', '0006_rename_product_quantity_depreciation_leaseordercost_product_depreciation_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseOrderProductAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('product_data', models.JSONField(default=dict, help_text='data json of product')),
                ('asset_data', models.JSONField(default=dict, help_text='data json of asset')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_product_asset_asset', to='asset.fixedasset', verbose_name='asset')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('lease_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_product_asset_lease_order', to='leaseorder.leaseorder', verbose_name='lease order')),
            ],
            options={
                'verbose_name': 'Lease Order Product Asset',
                'verbose_name_plural': 'Lease Order Products Asset',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='leaseorderproductleased',
            name='company',
        ),
        migrations.RemoveField(
            model_name='leaseorderproductleased',
            name='employee_created',
        ),
        migrations.RemoveField(
            model_name='leaseorderproductleased',
            name='employee_modified',
        ),
        migrations.RemoveField(
            model_name='leaseorderproductleased',
            name='lease_order_product',
        ),
        migrations.RemoveField(
            model_name='leaseorderproductleased',
            name='product',
        ),
        migrations.RemoveField(
            model_name='leaseorderproductleased',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='leaseorderproduct',
            name='product_quantity_leased',
        ),
        migrations.RemoveField(
            model_name='leaseorderproduct',
            name='product_quantity_leased_data',
        ),
        migrations.RemoveField(
            model_name='leaseorderproduct',
            name='product_quantity_new',
        ),
        migrations.AddField(
            model_name='leaseordercost',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_cost_asset', to='asset.fixedasset', verbose_name='asset'),
        ),
        migrations.AddField(
            model_name='leaseordercost',
            name='asset_data',
            field=models.JSONField(default=dict, help_text='data json of asset'),
        ),
        migrations.AddField(
            model_name='leaseordercost',
            name='asset_type',
            field=models.SmallIntegerField(help_text="choices= ((1, 'Product'), (2, 'Tool'), (3, 'Fixed asset'))", null=True),
        ),
        migrations.AddField(
            model_name='leaseordercost',
            name='depreciation_data',
            field=models.JSONField(default=list, help_text='data json of depreciation'),
        ),
        migrations.AddField(
            model_name='leaseordercost',
            name='depreciation_lease_data',
            field=models.JSONField(default=list, help_text='data json of depreciation lease'),
        ),
        migrations.AddField(
            model_name='leaseordercost',
            name='offset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_cost_offset', to='saledata.product', verbose_name='offset'),
        ),
        migrations.AddField(
            model_name='leaseordercost',
            name='offset_data',
            field=models.JSONField(default=dict, help_text='data json of offset'),
        ),
        migrations.AddField(
            model_name='leaseorderproduct',
            name='asset_data',
            field=models.JSONField(default=list, help_text='data json of asset'),
        ),
        migrations.AlterField(
            model_name='leaseorderproduct',
            name='offset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_product_offset', to='saledata.product', verbose_name='offset'),
        ),
        migrations.DeleteModel(
            name='LeaseOrderCostLeased',
        ),
        migrations.DeleteModel(
            name='LeaseOrderProductLeased',
        ),
        migrations.AddField(
            model_name='leaseorderproductasset',
            name='lease_order_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_product_asset_lo_product', to='leaseorder.leaseorderproduct', verbose_name='lease order product'),
        ),
        migrations.AddField(
            model_name='leaseorderproductasset',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_product_asset_product', to='saledata.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='leaseorderproductasset',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
    ]
