# Generated by Django 4.2.8 on 2025-03-20 22:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('company', '0018_delete_companybankaccount'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('saledata', '0062_alter_bank_options_alter_bankaccount_options_and_more'),
        ('leaseorder', '0007_leaseorderproductasset_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaseorderpaymentstage',
            old_name='issue_invoice',
            new_name='invoice',
        ),
        migrations.RemoveField(
            model_name='leaseorderpaymentstage',
            name='payment_ratio',
        ),
        migrations.RemoveField(
            model_name='leaseorderpaymentstage',
            name='value_after_tax',
        ),
        migrations.AddField(
            model_name='leaseorder',
            name='lease_invoice',
            field=models.JSONField(default=list, help_text='read data invoice, use for get list or detail lease order'),
        ),
        migrations.AddField(
            model_name='leaseorderpaymentstage',
            name='invoice_data',
            field=models.JSONField(default=dict, help_text='data json of invoice'),
        ),
        migrations.AddField(
            model_name='leaseorderpaymentstage',
            name='ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='leaseorderpaymentstage',
            name='reconcile_data',
            field=models.JSONField(default=list, help_text='data json of reconcile'),
        ),
        migrations.AddField(
            model_name='leaseorderpaymentstage',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_payment_stage_tax', to='saledata.tax', verbose_name='tax'),
        ),
        migrations.AddField(
            model_name='leaseorderpaymentstage',
            name='tax_data',
            field=models.JSONField(default=dict, help_text='data json of tax'),
        ),
        migrations.AddField(
            model_name='leaseorderpaymentstage',
            name='value_reconcile',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='leaseorderpaymentstage',
            name='value_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='leaseorderpaymentstage',
            name='lease_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_payment_stage_lease_order', to='leaseorder.leaseorder', verbose_name='lease order'),
        ),
        migrations.AlterField(
            model_name='leaseorderpaymentstage',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_order_payment_stage_term', to='saledata.term', verbose_name='payment term'),
        ),
        migrations.CreateModel(
            name='LeaseOrderInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='remark')),
                ('date', models.DateTimeField(null=True)),
                ('term_data', models.JSONField(default=list, help_text='data json of terms')),
                ('ratio', models.FloatField(null=True)),
                ('tax_data', models.JSONField(default=dict, help_text='data json of tax')),
                ('total', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('order', models.IntegerField(default=1)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('lease_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_invoice_lease_order', to='leaseorder.leaseorder', verbose_name='lease order')),
                ('tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_invoice_tax', to='saledata.tax', verbose_name='tax')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Lease Order Invoice',
                'verbose_name_plural': 'Lease Order Invoices',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
