# Generated by Django 4.2.8 on 2025-03-28 16:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_delete_companybankaccount'),
        ('asset', '0007_alter_instrumenttool_status'),
        ('tenant', '0001_initial'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('saledata', '0064_remove_account_parent_account_and_more'),
        ('leaseorder', '0009_leaseorderappconfig_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaseorderproductasset',
            options={'default_permissions': (), 'ordering': ('-date_created',), 'permissions': (), 'verbose_name': 'Lease Order Product Asset', 'verbose_name_plural': 'Lease Order Products Assets'},
        ),
        migrations.AddField(
            model_name='leaseordercost',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_cost_tool', to='asset.instrumenttool', verbose_name='tool'),
        ),
        migrations.AddField(
            model_name='leaseordercost',
            name='tool_data',
            field=models.JSONField(default=dict, help_text='data json of tool'),
        ),
        migrations.AddField(
            model_name='leaseorderproduct',
            name='tool_data',
            field=models.JSONField(default=list, help_text='data json of tool'),
        ),
        migrations.AddField(
            model_name='leaseorderproductasset',
            name='product_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='LeaseOrderProductTool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('product_data', models.JSONField(default=dict, help_text='data json of product')),
                ('tool_data', models.JSONField(default=dict, help_text='data json of tool')),
                ('product_quantity', models.FloatField(default=0)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('lease_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_product_tool_lease_order', to='leaseorder.leaseorder', verbose_name='lease order')),
                ('lease_order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_product_tool_lo_product', to='leaseorder.leaseorderproduct', verbose_name='lease order product')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_product_tool_product', to='saledata.product', verbose_name='product')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_product_tool_tool', to='asset.instrumenttool', verbose_name='tool')),
            ],
            options={
                'verbose_name': 'Lease Order Product Tool',
                'verbose_name_plural': 'Lease Order Products Tools',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
