# Generated by Django 4.2.8 on 2025-06-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseorder', '0011_leaseordercost_asset_group_manage_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseorderproduct',
            name='product_discount_amount_total',
            field=models.FloatField(default=0),
        ),
    ]
