# Generated by Django 4.2.8 on 2025-09-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseorder', '0014_leaseorderproduct_offset_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseordercost',
            name='product_title',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaseorderexpense',
            name='product_title',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaseorderproduct',
            name='product_title',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
