# Generated by Django 4.2.8 on 2025-11-03 17:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0086_product_is_representative_product_and_more'),
        ('tenant', '0001_initial'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('company', '0023_companyconfig_shift_companyconfig_shift_data_and_more'),
        ('leaseorder', '0015_alter_leaseordercost_product_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaseorderproduct',
            name='offset',
        ),
        migrations.AlterField(
            model_name='leaseorderproduct',
            name='offset_data',
            field=models.JSONField(default=list, help_text='data json of offset'),
        ),
        migrations.CreateModel(
            name='LeaseOrderProductOffset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('product_data', models.JSONField(default=dict, help_text='data json of product')),
                ('offset_data', models.JSONField(default=dict, help_text='data json of offset')),
                ('product_quantity', models.FloatField(default=0)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('lease_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_product_offset_lease_order', to='leaseorder.leaseorder', verbose_name='lease order')),
                ('lease_order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_product_offset_lo_product', to='leaseorder.leaseorderproduct', verbose_name='lease order product')),
                ('offset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_product_offset_offset', to='saledata.product', verbose_name='offset')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_order_product_offset_product', to='saledata.product', verbose_name='product')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Lease Order Product Offset',
                'verbose_name_plural': 'Lease Order Products Offsets',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
