# Generated by Django 4.2.8 on 2024-01-03 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_avatar_img'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='next_node_collab',
            field=models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='product_tax_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='purchasequotation',
            name='next_node_collab',
            field=models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='purchasequotationrequest',
            name='next_node_collab',
            field=models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='next_node_collab',
            field=models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee'),
        ),
    ]
