# Generated by Django 4.1.3 on 2023-08-02 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0012_saleorderproduct_remain_for_purchase_request'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestproduct',
            name='sale_order_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_so_product', to='saleorder.saleorderproduct'),
        ),
    ]
