# Generated by Django 4.2.8 on 2024-01-22 16:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0011_productwarehouse_used_amount'),
        ('company', '0008_company_email_app_password_status_and_more'),
        ('tenant', '0001_initial'),
        ('hr', '0002_employee_avatar_img'),
        ('purchasing', '0002_purchaseorder_next_node_collab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_order_payment_stage',
            field=models.JSONField(default=list, help_text='read data payment stage, use for get list or detail purchase order'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderPaymentStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='remark')),
                ('payment_ratio', models.FloatField(default=0)),
                ('value_before_tax', models.FloatField(default=0)),
                ('value_after_tax', models.FloatField(default=0)),
                ('due_date', models.DateTimeField(null=True)),
                ('order', models.IntegerField(default=1)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_payment_stage_po', to='purchasing.purchaseorder', verbose_name='purchase order')),
                ('tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_payment_stage_tax', to='saledata.tax', verbose_name='tax')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Purchase Order Payment Stage',
                'verbose_name_plural': 'Purchase Order Payment Stages',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
