# Generated by Django 4.1.3 on 2023-08-07 10:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_is_admin_company'),
        ('tenant', '0001_initial'),
        ('space', '0001_initial'),
        ('process', '0001_initial'),
        ('workflow', '0007_alter_runtimeassignee_options_runtime_doc_pined_and_more'),
        ('saledata', '0038_alter_account_total_employees'),
        ('company', '0005_company_media_company_code_company_media_company_id'),
        ('saleorder', '0013_saleorderproduct_remain_for_purchase_order'),
        ('purchasing', '0003_purchasequotationrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel')], default=0)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('purchase_requests_data', models.JSONField(default=list, help_text='read data purchase requests, use for get list or detail')),
                ('delivered_date', models.DateTimeField(help_text='date that products will be delivered', null=True)),
                ('status_delivered', models.SmallIntegerField(default=0)),
                ('receipt_status', models.SmallIntegerField(choices=[(0, 'Wait'), (1, 'Received'), (2, 'Partially received'), (3, 'None')], default=0)),
                ('purchase_order_products_data', models.JSONField(default=list, help_text='read data products, use for get list or detail')),
                ('total_product_pretax_amount', models.FloatField(default=0, help_text='total pretax amount of tab product')),
                ('total_product_tax', models.FloatField(default=0, help_text='total tax of tab product')),
                ('total_product', models.FloatField(default=0, help_text='total amount of tab product')),
                ('total_product_revenue_before_tax', models.FloatField(default=0, help_text='total revenue before tax of tab product (after discount on total, apply promotion,...)')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_contact', to='saledata.contact', verbose_name='contact')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_request_order', to='purchasing.purchaseorder', verbose_name='purchase order')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_request_request', to='purchasing.purchaserequest', verbose_name='purchase request')),
            ],
            options={
                'verbose_name': 'Purchase Order Request',
                'verbose_name_plural': 'Purchase Order Requests',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderProductRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock', models.FloatField(default=0, help_text='quantity of product in stock')),
                ('product_title', models.CharField(blank=True, max_length=100, null=True)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_uom_request_title', models.CharField(blank=True, max_length=100, null=True)),
                ('product_uom_order_title', models.CharField(blank=True, max_length=100, null=True)),
                ('product_quantity_request', models.FloatField(default=0, help_text='quantity of product, UI get default by purchase request')),
                ('product_quantity_order', models.FloatField(default=0, help_text='quantity of product, UI get default by purchase request')),
                ('product_unit_price', models.FloatField(default=0, help_text='price of product, UI get default by supplier price')),
                ('product_tax_title', models.CharField(blank=True, max_length=100, null=True)),
                ('product_subtotal_price', models.FloatField(default=0)),
                ('product_subtotal_price_after_tax', models.FloatField(default=0)),
                ('order', models.IntegerField(default=1)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_product_product', to='saledata.product', verbose_name='product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_product_order', to='purchasing.purchaseorder', verbose_name='purchase order')),
                ('purchase_request_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_product_request', to='purchasing.purchaserequestproduct', verbose_name='purchase request product')),
                ('sale_order_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_so_product', to='saleorder.saleorderproduct')),
                ('tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_product_tax', to='saledata.tax', verbose_name='tax')),
                ('uom_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_product_uom_quotation', to='saledata.unitofmeasure', verbose_name='unit of product on purchase quotation')),
                ('uom_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_product_uom_request', to='saledata.unitofmeasure', verbose_name='unit of product on purchase request')),
            ],
            options={
                'verbose_name': 'Purchase Order Product',
                'verbose_name_plural': 'Purchase Order Products',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_requests',
            field=models.ManyToManyField(blank=True, related_name='purchase_order_map_request', through='purchasing.PurchaseOrderRequest', to='purchasing.purchaserequest'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(help_text='sale data Accounts have type supplier', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_supplier', to='saledata.account', verbose_name='supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
    ]
