# Generated by Django 4.2.8 on 2024-02-27 12:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_publicfiles_relate_app_publicfiles_relate_app_code_and_more'),
        ('purchasing', '0003_purchaseorder_purchase_order_payment_stage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderAttachmentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('attachment', models.OneToOneField(help_text='Many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_files', to='attachments.files', verbose_name='Attachment files')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_attachment_file_po', to='purchasing.purchaseorder', verbose_name='purchase order')),
            ],
            options={
                'verbose_name': 'Purchase order attachments',
                'verbose_name_plural': 'Purchase order attachments',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='attachment_m2m',
            field=models.ManyToManyField(blank=True, related_name='file_of_purchase_order', through='purchasing.PurchaseOrderAttachmentFile', to='attachments.files'),
        ),
    ]
