# Generated by Django 4.2.8 on 2024-04-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_purchaseorderattachmentfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='contact_data',
            field=models.JSONField(default=dict, help_text='read data contact, use for get list or detail'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='document_change_order',
            field=models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='document_root_id',
            field=models.UUIDField(help_text='this is id of root document of the changed documents', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_change',
            field=models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_data',
            field=models.JSONField(default=dict, help_text='read data supplier, use for get list or detail'),
        ),
        migrations.AddField(
            model_name='purchasequotation',
            name='document_change_order',
            field=models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True),
        ),
        migrations.AddField(
            model_name='purchasequotation',
            name='document_root_id',
            field=models.UUIDField(help_text='this is id of root document of the changed documents', null=True),
        ),
        migrations.AddField(
            model_name='purchasequotation',
            name='is_change',
            field=models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents'),
        ),
        migrations.AddField(
            model_name='purchasequotationrequest',
            name='document_change_order',
            field=models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True),
        ),
        migrations.AddField(
            model_name='purchasequotationrequest',
            name='document_root_id',
            field=models.UUIDField(help_text='this is id of root document of the changed documents', null=True),
        ),
        migrations.AddField(
            model_name='purchasequotationrequest',
            name='is_change',
            field=models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='document_change_order',
            field=models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='document_root_id',
            field=models.UUIDField(help_text='this is id of root document of the changed documents', null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='is_change',
            field=models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents'),
        ),
    ]
