# Generated by Django 4.1.3 on 2023-08-07 16:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
        ('process', '0001_initial'),
        ('hr', '0004_employee_is_admin_company'),
        ('company', '0005_company_media_company_code_company_media_company_id'),
        ('saledata', '0038_alter_account_total_employees'),
        ('tenant', '0001_initial'),
        ('workflow', '0007_alter_runtimeassignee_options_runtime_doc_pined_and_more'),
        ('purchasing', '0004_purchaseorder_purchaseorderrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseQuotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel')], default=0)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('expiration_date', models.DateTimeField(help_text='Deadline for delivery')),
                ('lead_time_from', models.FloatField()),
                ('lead_time_to', models.FloatField()),
                ('lead_time_type', models.SmallIntegerField(choices=[(1, 'Week'), (2, 'Day'), (3, 'Hour')])),
                ('note', models.CharField(max_length=1000)),
                ('pretax_price', models.FloatField(help_text='sum pretax price of products')),
                ('taxes_price', models.FloatField(help_text='sum taxes price of products')),
                ('total_price', models.FloatField(help_text='sum after tax price of products')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('contact_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.contact')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
            ],
            options={
                'verbose_name': 'Purchase Quotation',
                'verbose_name_plural': 'Purchase Quotations',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='purchasequotationrequest',
            name='purchase_quotation_request_products',
        ),
        migrations.RemoveField(
            model_name='purchasequotationrequest',
            name='purchase_quotation_request_prs',
        ),
        migrations.CreateModel(
            name='PurchaseQuotationProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('subtotal_price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_quotation_product', to='saledata.product')),
                ('purchase_quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_quotation', to='purchasing.purchasequotation')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_quotation_product_tax', to='saledata.tax')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_quotation_product_uom', to='saledata.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Purchase Quotation Product',
                'verbose_name_plural': 'Purchase Quotation Products',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='purchasequotation',
            name='purchase_quotation_request_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchasing.purchasequotationrequest'),
        ),
        migrations.AddField(
            model_name='purchasequotation',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='purchasequotation',
            name='supplier_mapped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.account'),
        ),
        migrations.AddField(
            model_name='purchasequotation',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='purchasequotation',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
    ]
