# Generated by Django 4.2.8 on 2024-07-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_purchaseorder_contact_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderpaymentstage',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
        migrations.AlterField(
            model_name='purchaserequestconfig',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
    ]
