# Generated by Django 4.1.3 on 2023-08-08 23:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0013_saleorderproduct_remain_for_purchase_order'),
        ('saledata', '0038_alter_account_total_employees'),
        ('purchasing', '0005_purchasequotation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock', models.FloatField(default=0, help_text='quantity of product in stock')),
                ('product_title', models.CharField(blank=True, max_length=100, null=True)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_quantity_order_request', models.FloatField(default=0, help_text='quantity of product, UI get default by purchase request')),
                ('product_quantity_order_actual', models.FloatField(default=0, help_text='quantity of product, UI get default by purchase request')),
                ('product_unit_price', models.FloatField(default=0, help_text='price of product, UI get default by supplier price')),
                ('product_tax_title', models.CharField(blank=True, max_length=100, null=True)),
                ('product_subtotal_price', models.FloatField(default=0)),
                ('product_subtotal_price_after_tax', models.FloatField(default=0)),
                ('order', models.IntegerField(default=1)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_product_product', to='saledata.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Purchase Order Product',
                'verbose_name_plural': 'Purchase Order Products',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderQuotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_use', models.BooleanField(default=False, help_text='purchase quotation that used to order')),
            ],
            options={
                'verbose_name': 'Purchase Order Quotation',
                'verbose_name_plural': 'Purchase Order Quotations',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderRequestProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_order', models.FloatField(default=0, help_text='quantity order')),
                ('quantity_remain', models.FloatField(default=0, help_text='quantity remain to order')),
                ('purchase_order_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_request_order_product', to='purchasing.purchaseorderproduct', verbose_name='purchase order product')),
            ],
            options={
                'verbose_name': 'Purchase Order Request Product',
                'verbose_name_plural': 'Purchase Order Request Products',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_quotations_data',
            field=models.JSONField(default=list, help_text='read data purchase quotations, use for get list or detail'),
        ),
        migrations.AddField(
            model_name='purchaserequestproduct',
            name='remain_for_purchase_order',
            field=models.FloatField(default=0, help_text='this is quantity of product which is not purchased order yet, update when PO finish'),
        ),
        migrations.DeleteModel(
            name='PurchaseOrderProductRequest',
        ),
        migrations.AddField(
            model_name='purchaseorderrequestproduct',
            name='purchase_request_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_request_request_product', to='purchasing.purchaserequestproduct', verbose_name='purchase request product'),
        ),
        migrations.AddField(
            model_name='purchaseorderrequestproduct',
            name='sale_order_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_request_so_product', to='saleorder.saleorderproduct'),
        ),
        migrations.AddField(
            model_name='purchaseorderquotation',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_quotation_order', to='purchasing.purchaseorder', verbose_name='purchase order'),
        ),
        migrations.AddField(
            model_name='purchaseorderquotation',
            name='purchase_quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_quotation_quotation', to='purchasing.purchasequotation', verbose_name='purchase quotation'),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_product_order', to='purchasing.purchaseorder', verbose_name='purchase order'),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.tax', verbose_name='tax'),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='uom_order_actual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_product_uom_order', to='saledata.unitofmeasure', verbose_name='unit of product order actual'),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='uom_order_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_product_uom_request', to='saledata.unitofmeasure', verbose_name='unit of product order on request'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_quotations',
            field=models.ManyToManyField(blank=True, related_name='purchase_order_map_quotation', through='purchasing.PurchaseOrderQuotation', to='purchasing.purchasequotation'),
        ),
    ]
