# Generated by Django 4.1.3 on 2023-08-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0006_purchaseorderproduct_purchaseorderquotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasequotation',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='purchasequotationproduct',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='purchasequotationrequest',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='purchasequotationrequestproduct',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
