# Generated by Django 4.2.8 on 2024-08-17 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "distributionplan",
            "0002_distributionplan_is_create_purchase_request_and_more",
        ),
        ("purchasing", "0006_alter_purchaseorderpaymentstage_date_modified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="distribution_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pr_distribution_plan",
                to="distributionplan.distributionplan",
            ),
        ),
    ]
