# Generated by Django 4.2.8 on 2024-08-19 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0031_alter_accountactivity_date_modified_and_more'),
        ('distributionplan', '0002_distributionplan_is_create_purchase_request_and_more'),
        ('purchasing', '0006_alter_purchaseorderpaymentstage_date_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequestproduct',
            name='description',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='distribution_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_distribution_plan', to='distributionplan.distributionplan'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='request_for',
            field=models.SmallIntegerField(choices=[(0, 'For Sale Order'), (1, 'For Stock Free'), (2, 'For Other'), (3, 'For Stock Plan')], default=0),
        ),
        migrations.AlterField(
            model_name='purchaserequestproduct',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_tax', to='saledata.tax'),
        ),
    ]
