# Generated by Django 4.1.3 on 2023-08-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0007_alter_purchasequotation_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequestproduct',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
