# Generated by Django 4.2.8 on 2024-08-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0007_purchaserequest_distribution_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaserequest",
            name="request_for",
            field=models.SmallIntegerField(
                choices=[
                    (0, "For Sale Order"),
                    (1, "For Stock"),
                    (2, "For Other"),
                    (3, "For Stock Plan"),
                ],
                default=0,
            ),
        ),
    ]
