# Generated by Django 4.2.8 on 2024-09-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0008_alter_purchaseorder_date_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='is_all_receipted',
        ),
        migrations.RemoveField(
            model_name='purchaseorderproduct',
            name='gr_completed_quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseorderrequestproduct',
            name='gr_completed_quantity',
        ),
    ]
