# Generated by Django 4.2.8 on 2024-08-17 02:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0008_alter_purchaserequest_request_for"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaserequestproduct",
            name="description",
        ),
    ]
