# Generated by Django 4.2.8 on 2024-08-17 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("saledata", "0031_alter_accountactivity_date_modified_and_more"),
        ("purchasing", "0009_remove_purchaserequestproduct_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaserequestproduct",
            name="tax",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_request_tax",
                to="saledata.tax",
            ),
        ),
    ]
