# Generated by Django 4.2.8 on 2024-09-26 20:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0009_alter_files_file_type_alter_publicfiles_file_type'),
        ('purchasing', '0009_remove_purchaseorder_is_all_receipted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequestAttachmentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('attachment', models.OneToOneField(help_text='Many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_files', to='attachments.files', verbose_name='Attachment files')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request_attachments', to='purchasing.purchaserequest')),
            ],
            options={
                'verbose_name': 'Purchase Request attachment',
                'verbose_name_plural': 'Purchase Request attachments',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PurchaseQuotationRequestAttachmentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('attachment', models.OneToOneField(help_text='Many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_files', to='attachments.files', verbose_name='Attachment files')),
                ('purchase_quotation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_quotation_request_attachments', to='purchasing.purchasequotationrequest')),
            ],
            options={
                'verbose_name': 'Purchase Quotation Request attachment',
                'verbose_name_plural': 'Purchase Quotation Request attachments',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
