# Generated by Django 4.1.3 on 2023-08-31 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0009_alter_purchaseorder_system_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_request_products_data',
            field=models.JSONField(default=list, help_text='read data purchase request products not map any PO, use for get list or detail'),
        ),
        migrations.AddField(
            model_name='purchaseorderrequestproduct',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_request_product_order', to='purchasing.purchaseorder', verbose_name='purchase order'),
        ),
    ]
