# Generated by Django 4.2.8 on 2024-11-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0011_purchaseorder_next_association_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='is_shipping',
            field=models.BooleanField(default=False, help_text='flag to know this record is shipping not product'),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='shipping_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='product_code',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='product_description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='product_tax_title',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='product_title',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
