# Generated by Django 4.2.8 on 2024-12-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0013_purchaseorder_process_stage_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='request_for',
            field=models.SmallIntegerField(choices=[(0, 'For Sale Order'), (1, 'For Stock Free'), (2, 'For Fixed Asset'), (3, 'For Stock Plan')], default=0),
        ),
    ]
