# Generated by Django 4.2.4 on 2023-10-04 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0054_alter_product_description'),
        ('purchasing', '0013_purchaserequestproduct_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasequotationrequestproduct',
            name='description',
        ),
        migrations.AlterField(
            model_name='purchasequotationrequestproduct',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_quotation_request_product_tax', to='saledata.tax'),
        ),
    ]
