# Generated by Django 4.1.3 on 2023-10-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0015_remove_purchaseorder_purchase_request_products_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='is_all_ordered',
            field=models.BooleanField(default=False, help_text='True if all products are ordered by Purchase Order'),
        ),
    ]
