# Generated by Django 4.1.3 on 2023-10-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0016_purchaserequest_is_all_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_all_receipted',
            field=models.BooleanField(default=False, help_text='True if all products are receipted by Goods Receipt'),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='gr_completed_quantity',
            field=models.FloatField(default=0, help_text='this is quantity of product which is goods receipted, update when GR finish'),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='gr_remain_quantity',
            field=models.FloatField(default=0, help_text='this is quantity of product which is not goods receipted yet, update when GR finish'),
        ),
        migrations.AddField(
            model_name='purchaseorderrequestproduct',
            name='gr_completed_quantity',
            field=models.FloatField(default=0, help_text='this is quantity of product which is goods receipted, update when GR finish'),
        ),
        migrations.AddField(
            model_name='purchaseorderrequestproduct',
            name='gr_remain_quantity',
            field=models.FloatField(default=0, help_text='this is quantity of product which is not goods receipted yet, update when GR finish'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='receipt_status',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Wait'), (2, 'Partially received'), (3, 'Received')], default=0),
        ),
    ]
