# Generated by Django 4.2.8 on 2025-04-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0016_remove_purchaseorderpaymentstage_payment_ratio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderpaymentstage',
            old_name='cash_inflow_done',
            new_name='cash_outflow_done',
        ),
        migrations.RenameField(
            model_name='purchaseorderpaymentstage',
            old_name='is_ar_invoice',
            new_name='is_ap_invoice',
        ),
    ]
