# Generated by Django 4.2.8 on 2025-09-25 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0035_saleorderproduct_product_quantity_time_and_more'),
        ('saledata', '0079_warehouse_address_data_warehouse_detail_address'),
        ('purchasing', '0017_rename_cash_inflow_done_purchaseorderpaymentstage_cash_outflow_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='contact_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='distribution_plan_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='sale_order_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='supplier_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='purchaserequestproduct',
            name='product_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='purchaserequestproduct',
            name='tax_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='purchaserequestproduct',
            name='uom_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequestproduct',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
        migrations.AlterField(
            model_name='purchaserequestproduct',
            name='sale_order_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_so_product', to='saleorder.saleorderproduct'),
        ),
        migrations.AlterField(
            model_name='purchaserequestproduct',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_tax', to='saledata.tax'),
        ),
        migrations.AlterField(
            model_name='purchaserequestproduct',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_uom', to='saledata.unitofmeasure'),
        ),
    ]
