# Generated by Django 4.2.8 on 2025-09-29 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0036_saleorder_is_done_purchase_request'),
        ('serviceorder', '0003_serviceorder_is_done_purchase_request_and_more'),
        ('purchasing', '0018_purchaserequest_contact_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='service_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_service_order', to='serviceorder.serviceorder'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='service_order_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='purchaserequestproduct',
            name='service_order_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_svo_product', to='serviceorder.serviceorderservicedetail'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='request_for',
            field=models.SmallIntegerField(choices=[(0, 'For Sale Order'), (1, 'For Stock Free'), (2, 'For Fixed Asset'), (3, 'For Stock Plan'), (4, 'For Service Order')], default=0),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='sale_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_sale_order', to='saleorder.saleorder'),
        ),
    ]
