# Generated by Django 4.2.8 on 2025-10-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0019_purchaserequest_service_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='product_title',
            field=models.TextField(blank=True),
        ),
    ]
