# Generated by Django 4.2.8 on 2025-11-24 09:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0023_companyconfig_shift_companyconfig_shift_data_and_more'),
        ('tenant', '0001_initial'),
        ('base', '0019_nprovince_nward'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('accountingsettings', '0007_alter_dimensionvalue_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('app_code', models.CharField(help_text='{app_label}.{model}', max_length=100, verbose_name='Code of application')),
                ('doc_id', models.UUIDField(verbose_name='Main document ID')),
                ('total', models.FloatField(default=0)),
                ('budget_line_data', models.JSONField(default=list, help_text='json data of budget lines')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='Push when WF of document is finished', null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_application', to='base.application')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('group_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_group_inherit', to='hr.group')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ('-date_approved',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True)),
                ('unit_price', models.FloatField(default=0, help_text='Base price pushed from document')),
                ('quantity_planned', models.FloatField(default=0, help_text='Base quantity pushed from document')),
                ('quantity_consumed', models.FloatField(default=0, help_text='Consumed quantity on value_planned')),
                ('tax_data', models.JSONField(default=dict, help_text='data json of tax')),
                ('value_planned', models.FloatField(default=0, help_text='Base total value pushed from document')),
                ('value_consumed', models.FloatField(default=0, help_text='Consumed total value on value_planned')),
                ('dimension_value_data', models.JSONField(default=list, help_text='json data of dimension_values')),
                ('order', models.IntegerField(default=1)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_line_budget', to='budget.budget')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
            ],
            options={
                'verbose_name': 'Budget line',
                'verbose_name_plural': 'Budget lines',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BudgetLineTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('budget_line_data', models.JSONField(default=dict, help_text='json data of budget line')),
                ('app_code', models.CharField(help_text='{app_label}.{model}', max_length=100, verbose_name='Code of application')),
                ('doc_id', models.UUIDField(verbose_name='Transaction document ID')),
                ('dimension_first_data', models.JSONField(default=dict, help_text='json data of dimension_first')),
                ('dimension_value_first_data', models.JSONField(default=dict, help_text='json data of dimension_value_first')),
                ('dimension_second_data', models.JSONField(default=dict, help_text='json data of dimension_second')),
                ('dimension_value_second_data', models.JSONField(default=dict, help_text='json data of dimension_value_second')),
                ('value_consume', models.FloatField(default=0, help_text='Transaction value on budget line')),
                ('order', models.IntegerField(default=1)),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_line_transaction_budget_line', to='budget.budgetline')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Budget line transaction',
                'verbose_name_plural': 'Budget line transactions',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BudgetLineDimensionValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('md_app_code', models.CharField(blank=True, help_text='{app_label}.{model}', max_length=100, verbose_name='Code of application')),
                ('md_id', models.UUIDField(null=True, verbose_name='Master data ID')),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_line_dimension_budget_line', to='budget.budgetline')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('dimension_value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_line_dimension_dimension_value', to='accountingsettings.dimensionvalue')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Budget line Dimension',
                'verbose_name_plural': 'Budget line Dimensions',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='budgetline',
            name='dimension_values',
            field=models.ManyToManyField(blank=True, related_name='budget_line_m2m_dimension_value', through='budget.BudgetLineDimensionValue', to='accountingsettings.dimensionvalue'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
    ]
