# Generated by Django 4.1.3 on 2023-11-16 17:45

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_collabinworkflow_in_wf_option_and_more'),
        ('process', '0001_initial'),
        ('hr', '0001_initial'),
        ('space', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunitytask',
            name='assign_to',
        ),
        migrations.RemoveField(
            model_name='opportunitytaskconfig',
            name='in_assign_opt',
        ),
        migrations.RemoveField(
            model_name='opportunitytaskconfig',
            name='is_in_assign',
        ),
        migrations.RemoveField(
            model_name='opportunitytaskconfig',
            name='is_out_assign',
        ),
        migrations.RemoveField(
            model_name='opportunitytaskconfig',
            name='out_assign_opt',
        ),
        migrations.AddField(
            model_name='opportunitytask',
            name='current_stage',
            field=models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc'),
        ),
        migrations.AddField(
            model_name='opportunitytask',
            name='current_stage_title',
            field=models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100),
        ),
        migrations.AddField(
            model_name='opportunitytask',
            name='date_approved',
            field=models.DateTimeField(help_text='The record created when WF of document is finished', null=True),
        ),
        migrations.AddField(
            model_name='opportunitytask',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='opportunitytask',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='opportunitytask',
            name='system_remarks',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='opportunitytask',
            name='system_status',
            field=models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))"),
        ),
        migrations.AddField(
            model_name='opportunitytask',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
        migrations.AlterField(
            model_name='opportunitytask',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
    ]
