# Generated by Django 4.1.3 on 2023-07-20 09:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


def gen_uuid(apps, schema_editor):
    task_att_md = apps.get_model('task', 'TaskAttachmentFile')
    for row in task_att_md.objects.all():
        row.media_file = uuid.uuid4()
        row.save(update_fields=['media_file'])


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachmentfile',
            name='media_file',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='opportunitytask',
            name='attach',
            field=models.JSONField(default=list, help_text='["uuid4", "uuid4"]', null=True, verbose_name='attachment file'),
        ),
        migrations.AlterField(
            model_name='opportunitytaskconfig',
            name='out_assign_opt',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'only member in dept'), (2, 'only staff in dept'), (3, 'both 1 & 2')], default=0, verbose_name='option assign out opp/pro'),
        ),
        migrations.AlterField(
            model_name='taskattachmentfile',
            name='attachment',
            field=models.OneToOneField(help_text='Task had one/many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='task_attachment_file', to='attachments.files', verbose_name='Task attachment files'),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
