# Generated by Django 4.2.8 on 2023-12-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_opportunitytask_assign_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskattachmentfile',
            name='media_file',
        ),
    ]
