# Generated by Django 4.1.3 on 2023-08-14 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_employee_code_alter_employee_unique_together'),
        ('tenant', '0001_initial'),
        ('company', '0006_alter_company_code'),
        ('task', '0002_taskattachmentfile_media_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitylogwork',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='opportunitylogwork',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='opportunitylogwork',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date modified this record in last'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunitylogwork',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='opportunitylogwork',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='opportunitylogwork',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunitylogwork',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='opportunitylogwork',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='opportunitytaskconfig',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='opportunitytaskconfig',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value'),
        ),
        migrations.AddField(
            model_name='opportunitytaskconfig',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date modified this record in last'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunitytaskconfig',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='opportunitytaskconfig',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='opportunitytaskconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='opportunitytaskconfig',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunitytaskconfig',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='opportunitytaskconfig',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='opportunitytaskstatus',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='opportunitytaskstatus',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='opportunitytaskstatus',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value'),
        ),
        migrations.AddField(
            model_name='opportunitytaskstatus',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date modified this record in last'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunitytaskstatus',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='opportunitytaskstatus',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='opportunitytaskstatus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='opportunitytaskstatus',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opportunitytaskstatus',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='taskattachmentfile',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='taskattachmentfile',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='taskattachmentfile',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value'),
        ),
        migrations.AddField(
            model_name='taskattachmentfile',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date modified this record in last'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskattachmentfile',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='taskattachmentfile',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='taskattachmentfile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='taskattachmentfile',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskattachmentfile',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='taskattachmentfile',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
