# Generated by Django 4.1.3 on 2023-08-28 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_employee_code_alter_employee_unique_together'),
        ('task', '0003_opportunitylogwork_code_opportunitylogwork_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitytask',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_opportunitytasks_employee_inherit', to='hr.employee'),
        ),
    ]
