# Generated by Django 4.2.8 on 2024-03-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_opportunitytask_next_node_collab'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitytask',
            name='percent_completed',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='percent completed'),
        ),
        migrations.AddField(
            model_name='opportunitytaskstatus',
            name='is_finish',
            field=models.BooleanField(default=False, verbose_name='This is task finish'),
        ),
    ]
