# Generated by Django 4.2.8 on 2024-05-30 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_groupmapwork_planmemberproject_projectgroups_and_more'),
        ('task', '0006_opportunitytask_document_change_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitytask',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='opportunitytask',
            name='project_data',
            field=models.JSONField(default=dict, null=True, verbose_name='project backup'),
        ),
    ]
