# Generated by Django 4.2.8 on 2024-07-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_opportunitytask_project_opportunitytask_project_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitylogwork',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
        migrations.AlterField(
            model_name='opportunitytaskconfig',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
        migrations.AlterField(
            model_name='opportunitytaskstatus',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
        migrations.AlterField(
            model_name='taskattachmentfile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
    ]
