# Generated by Django 4.2.8 on 2024-08-27 10:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_email_app_password_and_more'),
        ('task', '0008_alter_opportunitylogwork_date_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitytask',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
        migrations.CreateModel(
            name='OpportunityTaskSummaryDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'wait'), (1, 'Ready')], default=0)),
                ('actives', models.PositiveSmallIntegerField(default=0)),
                ('overdue', models.PositiveSmallIntegerField(default=0)),
                ('upcoming_today', models.PositiveSmallIntegerField(default=0)),
                ('upcoming_soon', models.PositiveSmallIntegerField(default=0)),
                ('today_created', models.PositiveSmallIntegerField(default=0)),
                ('start_today', models.PositiveSmallIntegerField(default=0)),
                ('by_status', models.JSONField(default=list)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
            options={
                'verbose_name': 'Opportunity Task Summary Daily',
                'verbose_name_plural': 'Opportunity Task Summary Daily',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
