# Generated by Django 4.2.8 on 2024-08-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0008_alter_files_date_modified_alter_folder_date_modified_and_more'),
        ('task', '0009_alter_opportunitytask_date_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskattachmentfile',
            name='code',
        ),
        migrations.RemoveField(
            model_name='taskattachmentfile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='taskattachmentfile',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='taskattachmentfile',
            name='employee_created',
        ),
        migrations.RemoveField(
            model_name='taskattachmentfile',
            name='employee_modified',
        ),
        migrations.RemoveField(
            model_name='taskattachmentfile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='taskattachmentfile',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='taskattachmentfile',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='taskattachmentfile',
            name='title',
        ),
        migrations.AddField(
            model_name='opportunitytask',
            name='attach_assignee',
            field=models.JSONField(default=list, help_text='["uuid4", "uuid4"]', null=True, verbose_name='attachment file of assignee'),
        ),
        migrations.AddField(
            model_name='opportunitytask',
            name='attachment_m2m',
            field=models.ManyToManyField(blank=True, related_name='file_of_task_request', through='task.TaskAttachmentFile', to='attachments.files'),
        ),
        migrations.AddField(
            model_name='taskattachmentfile',
            name='is_assignee_file',
            field=models.BooleanField(default=False, help_text='is true if this file of assignee post', verbose_name='is assignee file'),
        ),
        migrations.AlterField(
            model_name='opportunitytask',
            name='attach',
            field=models.JSONField(default=list, help_text='["uuid4", "uuid4"]', null=True, verbose_name='attachment file of assigner'),
        ),
        migrations.AlterField(
            model_name='taskattachmentfile',
            name='attachment',
            field=models.OneToOneField(help_text='Many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_files', to='attachments.files', verbose_name='Attachment files'),
        ),
    ]
