# Generated by Django 4.2.8 on 2025-09-17 09:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_email_app_password_and_more'),
        ('tenant', '0001_initial'),
        ('company', '0023_companyconfig_shift_companyconfig_shift_data_and_more'),
        ('task', '0014_logtaskofemployee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunitytask',
            options={'default_permissions': (), 'ordering': ('end_date',), 'permissions': (), 'verbose_name': 'Opportunity Task Log Work', 'verbose_name_plural': 'Opportunity Task Log Work'},
        ),
        migrations.AddField(
            model_name='opportunitytaskconfig',
            name='user_allow_group_handle',
            field=models.JSONField(default=dict, help_text=b'{"uuid": {"id": "uuid4", "full_name": "Nguyen van A", "group": {"id": "uuid4", "title": "group received task group"}}, "uuid2": {"id": "uuid4", "full_name": "Nguyen van B", "group": {"id": "uuid4", "title": "group received task group"}}}', verbose_name='List of employee data backup'),
        ),
        migrations.CreateModel(
            name='TaskAssigneeGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('employee_list_access', models.JSONField(default=list, help_text=b'[{"id": "uuid4", "full_name": "Nguyen van A", "group": {"id": "uuid4", "title": "group received task group"}}, {"id": "uuid4", "full_name": "Nguyen van B", "group": {"id": "uuid4", "title": "group received task group"}}]', verbose_name='List of employee data backup')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Assignee Task group',
                'verbose_name_plural': 'Assignee Task groups',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='opportunitytask',
            name='group_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_assignee_task', to='task.taskassigneegroup', verbose_name='group assignee employee'),
        ),
    ]
