# Generated by Django 4.2.8 on 2025-10-01 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_alter_opportunitytask_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachmentfile',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_attachment_file_task', to='task.opportunitytask', verbose_name='Attachment file of task'),
        ),
    ]
