# Generated by Django 4.1.3 on 2023-04-26 15:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saledata', '0006_expense_expensegeneral_expenseprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel')], default=0)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('quotation_products_data', models.JSONField(default=list, help_text='read data products, use for get list or detail quotation')),
                ('quotation_term_data', models.JSONField(default=dict, help_text='read data terms, use for get list or detail quotation')),
                ('quotation_logistic_data', models.JSONField(default=dict, help_text='read data logistics, use for get list or detail quotation')),
                ('quotation_costs_data', models.JSONField(default=list, help_text='read data cost, use for get list or detail quotation')),
                ('quotation_expenses_data', models.JSONField(default=list, help_text='read data expense, use for get list or detail quotation')),
                ('total_product_pretax_amount', models.FloatField(default=0, help_text='total pretax amount of tab product')),
                ('total_product_discount', models.FloatField(default=0, help_text='total discount of tab product')),
                ('total_product_tax', models.FloatField(default=0, help_text='total tax of tab product')),
                ('total_product', models.FloatField(default=0, help_text='total amount of tab product')),
                ('total_cost_pretax_amount', models.FloatField(default=0, help_text='total pretax amount of tab cost')),
                ('total_cost_tax', models.FloatField(default=0, help_text='total tax of tab cost')),
                ('total_cost', models.FloatField(default=0, help_text='total amount of tab cost')),
                ('total_expense_pretax_amount', models.FloatField(default=0, help_text='total pretax amount of tab expense')),
                ('total_expense_tax', models.FloatField(default=0, help_text='total tax of tab expense')),
                ('total_expense', models.FloatField(default=0, help_text='total amount of tab expense')),
                ('is_customer_confirm', models.BooleanField(default=False, help_text='flag to check customer confirm quotation')),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QuotationCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_title', models.CharField(blank=True, max_length=100, null=True)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('product_uom_title', models.CharField(blank=True, max_length=100, null=True)),
                ('product_uom_code', models.CharField(blank=True, max_length=100, null=True)),
                ('product_quantity', models.IntegerField(default=0)),
                ('product_cost_price', models.FloatField(default=0)),
                ('product_tax_title', models.CharField(blank=True, max_length=100, null=True)),
                ('product_tax_value', models.FloatField(default=0)),
                ('product_tax_amount', models.FloatField(default=0)),
                ('product_subtotal_price', models.FloatField(default=0)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Quotation Cost',
                'verbose_name_plural': 'Quotation Costs',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QuotationExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_title', models.CharField(blank=True, max_length=100, null=True)),
                ('expense_code', models.CharField(blank=True, max_length=100, null=True)),
                ('expense_uom_title', models.CharField(blank=True, max_length=100, null=True)),
                ('expense_uom_code', models.CharField(blank=True, max_length=100, null=True)),
                ('expense_quantity', models.IntegerField(default=0)),
                ('expense_price', models.FloatField(default=0)),
                ('expense_tax_title', models.CharField(blank=True, max_length=100, null=True)),
                ('expense_tax_value', models.FloatField(default=0)),
                ('expense_tax_amount', models.FloatField(default=0)),
                ('expense_subtotal_price', models.FloatField(default=0)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Quotation Expense',
                'verbose_name_plural': 'Quotation Expenses',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QuotationLogistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Quotation Logistic',
                'verbose_name_plural': 'Quotation Logistics',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QuotationProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_title', models.CharField(blank=True, max_length=100, null=True)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_uom_title', models.CharField(blank=True, max_length=100, null=True)),
                ('product_uom_code', models.CharField(blank=True, max_length=100, null=True)),
                ('product_quantity', models.IntegerField(default=0)),
                ('product_unit_price', models.FloatField(default=0)),
                ('product_discount_value', models.FloatField(default=0)),
                ('product_discount_amount', models.FloatField(default=0)),
                ('product_tax_title', models.CharField(blank=True, max_length=100, null=True)),
                ('product_tax_value', models.FloatField(default=0)),
                ('product_tax_amount', models.FloatField(default=0)),
                ('product_subtotal_price', models.FloatField(default=0)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Quotation Product',
                'verbose_name_plural': 'Quotation Products',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QuotationTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Quotation Term',
                'verbose_name_plural': 'Quotation Terms',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QuotationTermDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Quotation Term Discount',
                'verbose_name_plural': 'Quotation Term Discounts',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QuotationTermPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.price')),
                ('quotation_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.quotationterm')),
            ],
            options={
                'verbose_name': 'Quotation Term Price',
                'verbose_name_plural': 'Quotation Term Prices',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
