# Generated by Django 4.1.3 on 2023-04-26 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
        ('saledata', '0007_discount'),
        ('space', '0001_initial'),
        ('company', '0003_alter_companyuseremployee_employee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0001_initial'),
        ('quotation', '0001_initial'),
        ('process', '0001_initial'),
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationtermdiscount',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.discount'),
        ),
        migrations.AddField(
            model_name='quotationtermdiscount',
            name='quotation_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.quotationterm'),
        ),
        migrations.AddField(
            model_name='quotationterm',
            name='discount_list',
            field=models.ManyToManyField(related_name='quotation_term_map_discounts', through='quotation.QuotationTermDiscount', to='saledata.discount'),
        ),
        migrations.AddField(
            model_name='quotationterm',
            name='payment_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_term_payment_term', to='saledata.paymentterm', verbose_name='payment terms'),
        ),
        migrations.AddField(
            model_name='quotationterm',
            name='price_list',
            field=models.ManyToManyField(related_name='quotation_term_map_prices', through='quotation.QuotationTermPrice', to='saledata.price'),
        ),
        migrations.AddField(
            model_name='quotationterm',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.quotation'),
        ),
        migrations.AddField(
            model_name='quotationproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_product_product', to='saledata.product', verbose_name='quotation'),
        ),
        migrations.AddField(
            model_name='quotationproduct',
            name='quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_product_quotation', to='quotation.quotation', verbose_name='quotation'),
        ),
        migrations.AddField(
            model_name='quotationproduct',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_product_tax', to='saledata.tax', verbose_name='unit'),
        ),
        migrations.AddField(
            model_name='quotationproduct',
            name='unit_of_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_product_uom', to='saledata.unitofmeasure', verbose_name='unit'),
        ),
        migrations.AddField(
            model_name='quotationlogistic',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotation.quotation'),
        ),
        migrations.AddField(
            model_name='quotationexpense',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_expense_expense', to='saledata.expense', verbose_name='quotation'),
        ),
        migrations.AddField(
            model_name='quotationexpense',
            name='quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_expense_quotation', to='quotation.quotation', verbose_name='quotation'),
        ),
        migrations.AddField(
            model_name='quotationexpense',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_expense_tax', to='saledata.tax', verbose_name='unit'),
        ),
        migrations.AddField(
            model_name='quotationexpense',
            name='unit_of_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_expense_uom', to='saledata.unitofmeasure', verbose_name='unit'),
        ),
        migrations.AddField(
            model_name='quotationcost',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_cost_product', to='saledata.product', verbose_name='quotation'),
        ),
        migrations.AddField(
            model_name='quotationcost',
            name='quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_cost_quotation', to='quotation.quotation', verbose_name='quotation'),
        ),
        migrations.AddField(
            model_name='quotationcost',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_cost_tax', to='saledata.tax', verbose_name='unit'),
        ),
        migrations.AddField(
            model_name='quotationcost',
            name='unit_of_measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_cost_uom', to='saledata.unitofmeasure', verbose_name='unit'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_contact', to='saledata.contact', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(help_text='sale data Accounts have type customer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_customer', to='saledata.account', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='employee_modified',
            field=models.ForeignKey(help_text='User modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_opportunity', to='opportunity.opportunity', verbose_name='opportunity'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sale_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_sale_person', to='hr.employee', verbose_name='sale person'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
    ]
