# Generated by Django 4.1.3 on 2023-05-04 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0009_expenseprice_uom'),
        ('quotation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='payment_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_payment_term', to='saledata.paymentterm', verbose_name='payment term'),
        ),
    ]
