# Generated by Django 4.1.3 on 2023-11-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_quotationexpense_is_labor'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationindicatorconfig',
            name='acceptance_affect_by',
            field=models.SmallIntegerField(default=1, help_text="choices= ((1, 'None'), (2, 'Plan value'), (3, 'Delivery'), (4, 'Payment'))"),
        ),
        migrations.AddField(
            model_name='quotationindicatorconfig',
            name='is_acceptance_editable',
            field=models.BooleanField(default=False),
        ),
    ]
