# Generated by Django 4.1.3 on 2023-11-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_quotationindicatorconfig_acceptance_affect_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationexpense',
            name='payment_plan_real_value',
        ),
    ]
