# Generated by Django 4.1.3 on 2023-05-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_quotation_total_product_discount_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationproduct',
            name='is_promotion',
            field=models.BooleanField(default=False, help_text='flag to know this product is for promotion (discount, gift,...)'),
        ),
    ]
