# Generated by Django 4.1.3 on 2023-05-24 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0019_goodreceipt_goodreceiptproduct'),
        ('promotion', '0006_promotion_customers_map_promotion'),
        ('quotation', '0005_quotationproduct_is_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationproduct',
            name='is_shipping',
            field=models.BooleanField(default=False, help_text='flag to know this product is for shipping fee'),
        ),
        migrations.AddField(
            model_name='quotationproduct',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_product_promotion', to='promotion.promotion', verbose_name='promotion'),
        ),
        migrations.AddField(
            model_name='quotationproduct',
            name='shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_product_shipping', to='saledata.shipping', verbose_name='shipping'),
        ),
    ]
