# Generated by Django 4.1.3 on 2023-05-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0007_quotationappconfig_configshortsale_configlongsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationcost',
            name='product_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quotationexpense',
            name='expense_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='quotationproduct',
            name='product_quantity',
            field=models.FloatField(default=0),
        ),
    ]
