# Generated by Django 4.1.3 on 2023-06-07 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0024_warehousestock'),
        ('quotation', '0009_quotation_workflow_runtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationcost',
            name='is_shipping',
            field=models.BooleanField(default=False, help_text='flag to know this cost is for shipping fee'),
        ),
        migrations.AddField(
            model_name='quotationcost',
            name='shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_cost_shipping', to='saledata.shipping', verbose_name='shipping'),
        ),
    ]
