# Generated by Django 4.2.8 on 2024-02-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0009_quotation_indicator_gross_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='payment_term_data',
            field=models.JSONField(default=dict, help_text='read data payment term, use for get list or detail quotation'),
        ),
        migrations.AddField(
            model_name='quotationproduct',
            name='group_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotationproduct',
            name='group_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotationproduct',
            name='is_group',
            field=models.BooleanField(default=False, help_text='flag to know product group not product'),
        ),
    ]
