# Generated by Django 4.1.3 on 2023-06-16 00:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companyconfig'),
        ('quotation', '0010_quotationcost_is_shipping_quotationcost_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('application_code', models.CharField(blank=True, max_length=100)),
                ('is_indicator_param', models.BooleanField(default=False)),
                ('is_sale_param', models.BooleanField(default=False)),
                ('is_math_operator', models.BooleanField(default=False)),
                ('formula_indicator_params', models.JSONField(default=list, help_text="setup by indicator params, examples: ['indicatorID1', '-', 'indicatorID2', '+', 'indicatorID3',]")),
                ('formula_sale_params', models.JSONField(default=list, help_text="setup by sale params, examples: ['saleID1', '-', 'saleID2', '+', 'saleID3',...]")),
                ('order', models.IntegerField(default=1)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_company', to='company.company')),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='QuotationIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indicator_result', models.FloatField(default=0, help_text='result of specific indicator for quotation')),
                ('indicator_rate_result', models.FloatField(default=0, help_text='rate result of specific indicator for quotation')),
                ('order', models.IntegerField(default=1)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_indicator_indicator', to='quotation.indicator', verbose_name='indicator')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_indicator_quotation', to='quotation.quotation', verbose_name='quotation')),
            ],
            options={
                'verbose_name': 'Quotation Indicator',
                'verbose_name_plural': 'Quotation Indicators',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
