# Generated by Django 4.1.3 on 2023-06-20 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companyconfig'),
        ('quotation', '0011_indicator_quotationindicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='formula_indicator_params',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='formula_sale_params',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='is_indicator_param',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='is_math_operator',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='is_sale_param',
        ),
        migrations.RemoveField(
            model_name='quotationindicator',
            name='indicator_rate_result',
        ),
        migrations.RemoveField(
            model_name='quotationindicator',
            name='indicator_result',
        ),
        migrations.AddField(
            model_name='indicator',
            name='formula_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='indicator',
            name='formula_data_show',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotationindicator',
            name='indicator_rate',
            field=models.FloatField(default=0, help_text='rate value of specific indicator for quotation'),
        ),
        migrations.AddField(
            model_name='quotationindicator',
            name='indicator_value',
            field=models.FloatField(default=0, help_text='value of specific indicator for quotation'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_company', to='company.company'),
        ),
    ]
