# Generated by Django 4.1.3 on 2023-06-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0012_remove_indicator_formula_indicator_params_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='description',
            new_name='remark',
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_indicators_data',
            field=models.JSONField(default=list, help_text='read data indicators, use for get list or detail quotation, records in model QuotationIndicator'),
        ),
    ]
