# Generated by Django 4.2.8 on 2024-05-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0012_quotationcost_warehouse_configshortsalerole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationindicatorconfig',
            name='acceptance_affect_by',
            field=models.SmallIntegerField(default=1, help_text="choices= ((1, 'None'), (2, 'Plan value'), (3, 'Delivery'), (4, 'Payment'), (5, 'Invoice'), (6, 'Project'))"),
        ),
    ]
