# Generated by Django 4.2.8 on 2024-08-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0014_alter_quotationappconfig_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationcost',
            name='product_data',
            field=models.JSONField(default=dict, help_text='data json of product'),
        ),
        migrations.AddField(
            model_name='quotationcost',
            name='shipping_data',
            field=models.JSONField(default=dict, help_text='data json of shipping'),
        ),
        migrations.AddField(
            model_name='quotationcost',
            name='tax_data',
            field=models.JSONField(default=dict, help_text='data json of tax'),
        ),
        migrations.AddField(
            model_name='quotationcost',
            name='uom_data',
            field=models.JSONField(default=dict, help_text='data json of uom'),
        ),
        migrations.AddField(
            model_name='quotationcost',
            name='warehouse_data',
            field=models.JSONField(default=dict, help_text='data json of warehouse'),
        ),
        migrations.AddField(
            model_name='quotationexpense',
            name='expense_data',
            field=models.JSONField(default=dict, help_text='data json of expense'),
        ),
        migrations.AddField(
            model_name='quotationexpense',
            name='expense_item_data',
            field=models.JSONField(default=dict, help_text='data json of expense_item'),
        ),
        migrations.AddField(
            model_name='quotationexpense',
            name='tax_data',
            field=models.JSONField(default=dict, help_text='data json of tax'),
        ),
        migrations.AddField(
            model_name='quotationexpense',
            name='uom_data',
            field=models.JSONField(default=dict, help_text='data json of uom'),
        ),
        migrations.AddField(
            model_name='quotationproduct',
            name='product_data',
            field=models.JSONField(default=dict, help_text='data json of product'),
        ),
        migrations.AddField(
            model_name='quotationproduct',
            name='promotion_data',
            field=models.JSONField(default=dict, help_text='data json of promotion'),
        ),
        migrations.AddField(
            model_name='quotationproduct',
            name='shipping_data',
            field=models.JSONField(default=dict, help_text='data json of shipping'),
        ),
        migrations.AddField(
            model_name='quotationproduct',
            name='tax_data',
            field=models.JSONField(default=dict, help_text='data json of tax'),
        ),
        migrations.AddField(
            model_name='quotationproduct',
            name='uom_data',
            field=models.JSONField(default=dict, help_text='data json of uom'),
        ),
    ]
