# Generated by Django 4.1.3 on 2023-07-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0015_quotationindicatorconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='total_product_revenue_before_tax',
            field=models.FloatField(default=0, help_text='total revenue before tax of tab product (after discount on total, apply promotion,...)'),
        ),
    ]
