# Generated by Django 4.1.3 on 2023-07-26 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0037_alter_unitofmeasure_rounding_delete_warehousestock'),
        ('quotation', '0016_quotation_total_product_revenue_before_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationexpense',
            name='is_product',
            field=models.BooleanField(default=False, help_text='flag to check if record is MasterData Expense or Product, if True is Product'),
        ),
        migrations.AddField(
            model_name='quotationexpense',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_expense_product', to='saledata.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='quotationexpense',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotationexpense',
            name='product_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quotationexpense',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_expense_expense', to='saledata.expense', verbose_name='expense'),
        ),
    ]
