# Generated by Django 4.1.3 on 2023-08-09 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0039_alter_product_options'),
        ('quotation', '0017_quotationexpense_is_product_quotationexpense_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='customer_billing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_customer_billing', to='saledata.accountbillingaddress', verbose_name='customer billing'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_customer_shipping', to='saledata.accountshippingaddress', verbose_name='customer shipping'),
        ),
    ]
