# Generated by Django 4.2.8 on 2024-11-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0018_quotation_customer_data_quotation_next_association_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='contact_data',
            field=models.JSONField(default=dict, help_text='data json of contact'),
        ),
    ]
