# Generated by Django 4.1.3 on 2023-10-09 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('quotation', '0021_quotationexpense_expense_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='project',
            field=models.ForeignKey(help_text='Relate to Project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_prj', to='project.project'),
        ),
    ]
