# Generated by Django 4.2.8 on 2025-05-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0022_quotationcost_code_quotationcost_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationindicatorconfig',
            name='is_negative_set_zero',
            field=models.BooleanField(default=False, help_text='flag allow return 0 if value indicator is negative'),
        ),
    ]
