# Generated by Django 4.2.8 on 2025-08-20 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0025_quotation_currency_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The record created at value'),
        ),
    ]
