# Generated by Django 4.2.8 on 2025-10-13 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0082_productspecificidentificationserialnumber_product_warehouse_serial'),
        ('quotation', '0029_quotation_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationproduct',
            name='product_specific',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_product_product_specific', to='saledata.productspecificidentificationserialnumber', verbose_name='product specific'),
        ),
    ]
