# Generated by Django 4.1.3 on 2023-03-09 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0007_employee_permission_by_configured_and_more'),
        ('base', '0004_applicationproperty'),
        ('company', '0004_company_is_active_company_is_delete'),
        ('tenant', '0002_tenant_is_active_tenant_is_delete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('user_created', models.UUIDField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_modified', models.UUIDField(null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('mode', models.IntegerField(choices=[(0, 'Global'), (1, 'Private'), (2, 'Team')], default=0)),
                ('mode_id', models.UUIDField(null=True)),
                ('code_application', models.TextField(help_text='code of application in base', null=True, verbose_name='code application')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('is_multi_company', models.BooleanField(default=False, verbose_name='Multi company')),
                ('is_define_zone', models.BooleanField(default=False, verbose_name='Define zone')),
                ('actions_rename', jsonfield.fields.JSONField(default=[], help_text='use for show rename of actions in specific workflow')),
                ('is_in_use', models.BooleanField(help_text='to know what workflow is currently config for application', null=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_application', to='base.application', verbose_name='application')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
            managers=[
                ('object_global', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('user_created', models.UUIDField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_modified', models.UUIDField(null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('mode', models.IntegerField(choices=[(0, 'Global'), (1, 'Private'), (2, 'Team')], default=0)),
                ('mode_id', models.UUIDField(null=True)),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('property_list', jsonfield.fields.JSONField(default=[], verbose_name='property list')),
                ('order', models.IntegerField(null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.tenant')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_workflow', to='workflow.workflow')),
            ],
            options={
                'verbose_name': 'Zone in workflow',
                'verbose_name_plural': 'Zone in workflow',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
            managers=[
                ('object_global', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('user_created', models.UUIDField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_modified', models.UUIDField(null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('mode', models.IntegerField(choices=[(0, 'Global'), (1, 'Private'), (2, 'Team')], default=0)),
                ('mode_id', models.UUIDField(null=True)),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('actions', jsonfield.fields.JSONField(default=[], help_text='actions of node', verbose_name='actions')),
                ('is_system', models.BooleanField(default=False, help_text='check if is nodes system', verbose_name='is system')),
                ('code_node_system', models.CharField(blank=True, help_text='code nodes system: Initial, Approve, Complete,...', max_length=100, null=True)),
                ('option_collaborator', models.SmallIntegerField(choices=[(0, 'In form'), (1, 'Out form'), (2, 'In workflow')], default=0, help_text='option choose collaborator: In form, Out form, In workflow', verbose_name='collaborator options')),
                ('field_select_collaborator', models.CharField(blank=True, help_text='field has data employees in document, option 1', max_length=550, null=True)),
                ('collaborator_list', jsonfield.fields.JSONField(default=[], help_text='list employees, option 2', verbose_name='employees')),
                ('zone', jsonfield.fields.JSONField(default=[], help_text='list zones of collaborator', verbose_name='zone')),
                ('order', models.IntegerField(null=True)),
                ('condition', jsonfield.fields.JSONField(blank=True, default=[], null=True, verbose_name='Condition')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.tenant')),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='node_workflow', to='workflow.workflow', verbose_name='workflow')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
            managers=[
                ('object_global', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('user_created', models.UUIDField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_modified', models.UUIDField(null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('mode', models.IntegerField(choices=[(0, 'Global'), (1, 'Private'), (2, 'Team')], default=0)),
                ('mode_id', models.UUIDField(null=True)),
                ('zone', jsonfield.fields.JSONField(default=[], help_text='list zones of collaborator', verbose_name='zone')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_employee', to='hr.employee', verbose_name='employee')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_node', to='workflow.node', verbose_name='node')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Collaborator',
                'verbose_name_plural': 'Collaborators',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
            managers=[
                ('object_global', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('user_created', models.UUIDField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_modified', models.UUIDField(null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('mode', models.IntegerField(choices=[(0, 'Global'), (1, 'Private'), (2, 'Team')], default=0)),
                ('mode_id', models.UUIDField(null=True)),
                ('condition', jsonfield.fields.JSONField(blank=True, default=[], null=True, verbose_name='Condition')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('node_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_node_input', to='workflow.node', verbose_name='node input')),
                ('node_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_node_output', to='workflow.node', verbose_name='node output')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.tenant')),
                ('workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='association_workflow', to='workflow.workflow', verbose_name='workflow')),
            ],
            options={
                'verbose_name': 'Association',
                'verbose_name_plural': 'Associations',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
            managers=[
                ('object_global', django.db.models.manager.Manager()),
            ],
        ),
    ]
