# Generated by Django 4.1.3 on 2023-04-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='coordinates',
            field=models.JSONField(default=dict, verbose_name='coordinates'),
        ),
        migrations.AlterField(
            model_name='association',
            name='condition',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='zone',
            field=models.JSONField(default=list, help_text='list zones of collaborator', verbose_name='zone'),
        ),
        migrations.AlterField(
            model_name='node',
            name='actions',
            field=models.JSONField(default=list, help_text='actions of node', verbose_name='actions'),
        ),
        migrations.AlterField(
            model_name='node',
            name='collab_in_form',
            field=models.JSONField(default=dict, help_text='use for option in form'),
        ),
        migrations.AlterField(
            model_name='node',
            name='collab_in_workflow',
            field=models.JSONField(default=list, help_text='use for option in workflow'),
        ),
        migrations.AlterField(
            model_name='node',
            name='collab_out_form',
            field=models.JSONField(default=dict, help_text='use for option out form'),
        ),
        migrations.AlterField(
            model_name='node',
            name='condition',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='node',
            name='zone_initial_node',
            field=models.JSONField(default=list, help_text='list zones of initial node', verbose_name='zone'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='actions_rename',
            field=models.JSONField(default=list, help_text='use for show rename of actions in specific workflow'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='property_list',
            field=models.JSONField(default=list, verbose_name='property list'),
        ),
    ]
