# Generated by Django 4.1.3 on 2023-04-06 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
        ('hr', '0001_initial'),
        ('company', '0002_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollabInWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='User modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collab in workflow',
                'verbose_name_plural': 'Collab in workflow',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CollabInWorkflowZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.collabinworkflow')),
            ],
            options={
                'verbose_name': 'Collab in workflow zone',
                'verbose_name_plural': 'Collab in workflow zones',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CollaborationInForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('app_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.applicationproperty')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='User modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collab in form',
                'verbose_name_plural': 'Collab in form',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CollaborationInFormZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.collaborationinform')),
            ],
            options={
                'verbose_name': 'Collab in form zone',
                'verbose_name_plural': 'Collab in form zones',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CollaborationOutForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='User modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collab out form',
                'verbose_name_plural': 'Collab out form',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CollaborationOutFormEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.collaborationoutform')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
            options={
                'verbose_name': 'Collab out form employee',
                'verbose_name_plural': 'Collab out form employees',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CollaborationOutFormZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.collaborationoutform')),
            ],
            options={
                'verbose_name': 'Collab out form zone',
                'verbose_name_plural': 'Collab out form zones',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InitialNodeZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Initial Node Zone',
                'verbose_name_plural': 'Initial Node Zones',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ZoneProperties',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.applicationproperty')),
            ],
            options={
                'verbose_name': 'Zone Property',
                'verbose_name_plural': 'Zones Properties',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='association',
            name='node_in_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='association',
            name='node_out_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='node',
            name='coordinates',
            field=models.JSONField(default=dict, verbose_name='coordinates'),
        ),
        migrations.AlterField(
            model_name='association',
            name='condition',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='node',
            name='actions',
            field=models.JSONField(default=list, help_text='actions of node', verbose_name='actions'),
        ),
        migrations.AlterField(
            model_name='node',
            name='collab_in_form',
            field=models.JSONField(default=dict, help_text='use for option in form'),
        ),
        migrations.AlterField(
            model_name='node',
            name='collab_in_workflow',
            field=models.JSONField(default=list, help_text='use for option in workflow'),
        ),
        migrations.AlterField(
            model_name='node',
            name='collab_out_form',
            field=models.JSONField(default=dict, help_text='use for option out form'),
        ),
        migrations.AlterField(
            model_name='node',
            name='condition',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='node',
            name='zone_initial_node',
            field=models.JSONField(default=list, help_text='list zones of initial node', verbose_name='zone'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='actions_rename',
            field=models.JSONField(default=list, help_text='use for show rename of actions in specific workflow'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='property_list',
            field=models.JSONField(default=list, verbose_name='property list'),
        ),
        migrations.DeleteModel(
            name='Collaborator',
        ),
        migrations.AddField(
            model_name='zoneproperties',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.zone'),
        ),
        migrations.AddField(
            model_name='initialnodezone',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.node'),
        ),
        migrations.AddField(
            model_name='initialnodezone',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.zone'),
        ),
        migrations.AddField(
            model_name='collaborationoutformzone',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.zone'),
        ),
        migrations.AddField(
            model_name='collaborationoutform',
            name='employees',
            field=models.ManyToManyField(related_name='collab_out_forms_map_employees', through='workflow.CollaborationOutFormEmployee', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='collaborationoutform',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.node'),
        ),
        migrations.AddField(
            model_name='collaborationoutform',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='collaborationoutform',
            name='zone',
            field=models.ManyToManyField(related_name='collab_out_forms_map_zones', through='workflow.CollaborationOutFormZone', to='workflow.zone'),
        ),
        migrations.AddField(
            model_name='collaborationinformzone',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.zone'),
        ),
        migrations.AddField(
            model_name='collaborationinform',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.node'),
        ),
        migrations.AddField(
            model_name='collaborationinform',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='collaborationinform',
            name='zone',
            field=models.ManyToManyField(related_name='collab_in_forms_map_zones', through='workflow.CollaborationInFormZone', to='workflow.zone'),
        ),
        migrations.AddField(
            model_name='collabinworkflowzone',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.zone'),
        ),
        migrations.AddField(
            model_name='collabinworkflow',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.node'),
        ),
        migrations.AddField(
            model_name='collabinworkflow',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='collabinworkflow',
            name='zone',
            field=models.ManyToManyField(related_name='collab_in_workflows_map_zones', through='workflow.CollabInWorkflowZone', to='workflow.zone'),
        ),
        migrations.AddField(
            model_name='node',
            name='zones_initial_node',
            field=models.ManyToManyField(related_name='initial_node_map_zones', through='workflow.InitialNodeZone', to='workflow.zone'),
        ),
        migrations.AddField(
            model_name='zone',
            name='properties',
            field=models.ManyToManyField(related_name='zones_map_properties', through='workflow.ZoneProperties', to='base.applicationproperty'),
        ),
    ]
