# Generated by Django 4.1.3 on 2023-04-03 10:53

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_alter_association_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'default_permissions': (), 'ordering': ('order',), 'permissions': (), 'verbose_name': 'Node', 'verbose_name_plural': 'Nodes'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'default_permissions': (), 'ordering': ('order',), 'permissions': (), 'verbose_name': 'Zone in workflow', 'verbose_name_plural': 'Zone in workflow'},
        ),
        migrations.RemoveField(
            model_name='node',
            name='collaborator_list',
        ),
        migrations.RemoveField(
            model_name='node',
            name='field_select_collaborator',
        ),
        migrations.RemoveField(
            model_name='node',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='is_in_use',
        ),
        migrations.AddField(
            model_name='node',
            name='collab_in_form',
            field=jsonfield.fields.JSONField(default={}, help_text='use for option in form'),
        ),
        migrations.AddField(
            model_name='node',
            name='collab_in_workflow',
            field=jsonfield.fields.JSONField(default=[], help_text='use for option in workflow'),
        ),
        migrations.AddField(
            model_name='node',
            name='collab_out_form',
            field=jsonfield.fields.JSONField(default={}, help_text='use for option out form'),
        ),
        migrations.AddField(
            model_name='node',
            name='zone_initial_node',
            field=jsonfield.fields.JSONField(default=[], help_text='list zones of initial node', verbose_name='zone'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='date_applied',
            field=models.DateField(help_text='date applied this workflow for application', null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='is_applied',
            field=models.BooleanField(default=False, help_text='to know what workflow is currently applied for application'),
        ),
    ]
