# Generated by Django 4.1.3 on 2023-03-14 09:19

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_alter_association_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='collaborator_list',
        ),
        migrations.RemoveField(
            model_name='node',
            name='field_select_collaborator',
        ),
        migrations.RemoveField(
            model_name='node',
            name='zone',
        ),
        migrations.AddField(
            model_name='node',
            name='collab_in_form',
            field=jsonfield.fields.JSONField(default={}, help_text='use for option in form'),
        ),
        migrations.AddField(
            model_name='node',
            name='collab_in_workflow',
            field=jsonfield.fields.JSONField(default=[], help_text='use for option in workflow'),
        ),
        migrations.AddField(
            model_name='node',
            name='collab_out_form',
            field=jsonfield.fields.JSONField(default={}, help_text='use for option out form'),
        ),
        migrations.AddField(
            model_name='node',
            name='zone_initial_node',
            field=jsonfield.fields.JSONField(default=[], help_text='list zones of initial node', verbose_name='zone'),
        ),
    ]
