# Generated by Django 4.1.3 on 2023-05-29 10:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_baseitemunit'),
        ('hr', '0001_initial'),
        ('workflow', '0003_collabinworkflow_collabinworkflowzone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runtime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_id', models.UUIDField(verbose_name='Document was runtime')),
                ('doc_title', models.TextField(blank=True, help_text='Title get from Doc Obj when create runtime obj', verbose_name='Title of Doc')),
                ('doc_params', models.JSONField(default=dict, verbose_name='Params parsed of doc runtime')),
                ('state', models.IntegerField(choices=[(0, 'Created'), (1, 'In Progress'), (2, 'Finish'), (3, 'Finish with flow non-apply')], default=0, verbose_name='State of stage runtime')),
                ('status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Success'), (2, 'Fail'), (3, 'Pending')], default=0, verbose_name='Status of document runtime')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at time')),
                ('date_finished', models.DateTimeField(help_text='The records finish at time', null=True)),
                ('task_bg_id', models.UUIDField(help_text='ID of task run background', null=True, verbose_name='ID Task')),
                ('task_bg_state', models.CharField(choices=[('PENDING', 'The task is waiting to be executed | task đang chờ để được thực thi'), ('STARTED', 'The task has started execution | task đã được bắt đầu thực thi'), ('SUCCESS', 'The task has successfully executed | task đã thực thi thành công'), ('FAILURE', 'The task has failed during execution | task đã thất bại trong quá trình thực thi'), ('RETRY', 'The task is being retried after a failure | task đang được thực hiện lại sau khi đã thất bại'), ('REVOKED', 'The task has been cancelled before completion or execution | task đã bị hủy bỏ trước khi hoàn thành hoặc bị thực thi'), ('IGNORED', 'The task was ignored and not executed | task bị bỏ qua và không được thực thi')], default='PENDING', help_text='Sate run of task background', max_length=10, verbose_name='State Task BG')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.application', verbose_name='App of DocID')),
                ('doc_employee_created', models.ForeignKey(help_text='Data from Runtime first time', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee', verbose_name='Employee created of Document')),
                ('flow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflow', verbose_name='Workflow applied')),
            ],
            options={
                'verbose_name': 'Runtime',
                'verbose_name_plural': 'Runtime',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RuntimeAssignee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone_and_properties', models.JSONField(default=dict, help_text='[{"id": "", "title": "", "remark": "", "properties": ["application_property_id"]}]', verbose_name='Zone detail and Properties ID of Zone | collect from Zone() and ApplicationProperties()')),
                ('action_perform', models.JSONField(default=list, help_text='[0,1,2,3]', verbose_name='Is action code array that was performed by assignee')),
                ('is_done', models.BooleanField(default=False, help_text='True if assignee finish your task, False if assignee need action finish with approve, next,...', verbose_name='Flag status Task of assignee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_runtime_assignee_of_employee', to='hr.employee', verbose_name='Employee selected')),
            ],
            options={
                'verbose_name': 'Stage map Employee plus Zone',
                'verbose_name_plural': 'Stage map Employee plus Zone',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='collaborationinform',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workflow.node'),
        ),
        migrations.AlterField(
            model_name='collaborationoutform',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workflow.node'),
        ),
        migrations.CreateModel(
            name='RuntimeStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Title copy from node')),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='Code copy from node')),
                ('node_data', models.JSONField(default=dict, help_text='{"id": "", "title": "", "code": "", "date_created": ""}', verbose_name='Detail of Config Node at this created')),
                ('actions', models.JSONField(default=dict, help_text='Collect from Node.actions', verbose_name='Action code array')),
                ('exit_node_conditions', models.JSONField(default=dict, help_text='Collect data from Node.condition)', verbose_name='Condition for exit node')),
                ('association_passed_data', models.JSONField(default=dict, help_text='{"id": "", "node_in": {"id": "", "title": "", "code": ""}, "node_out": {"id": "", "title": "", "code": ""}, "condition": []}', verbose_name='Storage data of association passed')),
                ('assignee_count', models.SmallIntegerField(default=0, help_text='Counter of assignee_and_zone, count employee', verbose_name='Employee Count')),
                ('order', models.IntegerField(default=0, verbose_name='Order Number step in Runtime, Stage arrange in order by ASC (ascending)')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Node was created at time')),
                ('date_exit', models.DateTimeField(help_text='Node was exited at time', null=True)),
                ('log_count', models.SmallIntegerField(default=0, help_text='Support display UX of FE', verbose_name='Total log of Stage')),
                ('assignee_and_zone', models.ManyToManyField(help_text='Assignee have task with properties zone', related_name='assignee_and_zone_of_runtime_stage', through='workflow.RuntimeAssignee', to='hr.employee', verbose_name='Employee + Zone need action in this stage')),
                ('association_passed', models.ForeignKey(help_text='Association selected when create stage from node', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.association', verbose_name='Association was passed')),
                ('from_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_stage_before', to='workflow.runtimestage', verbose_name='Stage Before (from node)')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.node', verbose_name='Relate to Config Node. node_data get data from this')),
                ('runtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.runtime', verbose_name='All Node by Runtime')),
                ('to_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_stage_after', to='workflow.runtimestage', verbose_name='Stage After (to node)')),
            ],
            options={
                'verbose_name': 'Runtime Node',
                'verbose_name_plural': 'Runtime Node',
                'ordering': ('-order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RuntimeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_data', models.JSONField(default=dict, help_text='{"id": "", "first_name": "", "last_name": "", "email": "", "avatar": "",}', verbose_name="Employee's data changed docs")),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Log Activity was created at time')),
                ('kind', models.SmallIntegerField(choices=[(0, 'Login'), (1, 'In Doc'), (2, 'In Flow')], help_text='0: log from login, 1: log from doc, 2: log from workflow', verbose_name='Flag filter doc for some main case: login history, doc history only, flow history only.')),
                ('action', models.SmallIntegerField(verbose_name='Action choice that was used by actor')),
                ('msg', models.TextField(blank=True, verbose_name='Message log action of actor')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee')),
                ('runtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.runtime', verbose_name='All log of Runtime Doc')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_of_stage_runtime', to='workflow.runtimestage', verbose_name='Log in Stage Runtime | =null when Runtime create + Dont apply WF')),
            ],
            options={
                'verbose_name': 'Log Activity',
                'verbose_name_plural': 'Log Activity',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='runtimeassignee',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_of_runtime_stage', to='workflow.runtimestage', verbose_name='Assignee in Stage'),
        ),
        migrations.AddField(
            model_name='runtime',
            name='stage_currents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_currently_of_runtime', to='workflow.runtimestage', verbose_name='Stage Currently'),
        ),
        migrations.AlterUniqueTogether(
            name='runtime',
            unique_together={('doc_id', 'app')},
        ),
    ]
