# Generated by Django 4.1.3 on 2023-03-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_remove_node_collaborator_list_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'default_permissions': (), 'ordering': ('order',), 'permissions': (), 'verbose_name': 'Node', 'verbose_name_plural': 'Nodes'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'default_permissions': (), 'ordering': ('order',), 'permissions': (), 'verbose_name': 'Zone in workflow', 'verbose_name_plural': 'Zone in workflow'},
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='is_in_use',
        ),
        migrations.AddField(
            model_name='workflow',
            name='date_applied',
            field=models.DateField(help_text='date applied this workflow for application', null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='is_applied',
            field=models.BooleanField(default=False, help_text='to know what workflow is currently applied for application'),
        ),
    ]
