# Generated by Django 4.1.3 on 2023-12-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_alter_collabinworkflow_position_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runtime',
            name='state',
            field=models.IntegerField(choices=[(0, 'Created'), (1, 'In Progress'), (2, 'Finish'), (3, 'Finish with flow non-apply'), (4, 'Fail')], default=0, verbose_name='State of stage runtime'),
        ),
    ]
