# Generated by Django 4.2.8 on 2024-01-03 10:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_runtime_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='collabinworkflow',
            name='is_edit_all_zone',
            field=models.BooleanField(default=False, help_text='flag to know collaborator can edit whole document (not check zone)'),
        ),
        migrations.AddField(
            model_name='collaborationinform',
            name='is_edit_all_zone',
            field=models.BooleanField(default=False, help_text='flag to know collaborator can edit whole document (not check zone)'),
        ),
        migrations.AddField(
            model_name='collaborationoutform',
            name='is_edit_all_zone',
            field=models.BooleanField(default=False, help_text='flag to know collaborator can edit whole document (not check zone)'),
        ),
        migrations.AddField(
            model_name='node',
            name='is_edit_all_zone',
            field=models.BooleanField(default=False, help_text='flag to know collaborator can edit whole document (not check zone)'),
        ),
        migrations.AddField(
            model_name='node',
            name='zone_hidden_initial_node',
            field=models.JSONField(default=list, help_text='list zones hidden of initial node', verbose_name='init zone hidden'),
        ),
        migrations.AddField(
            model_name='runtimeassignee',
            name='is_edit_all_zone',
            field=models.BooleanField(default=False, help_text='flag to know collaborator can edit whole document (not check zone)'),
        ),
        migrations.AddField(
            model_name='runtimeassignee',
            name='remark',
            field=models.CharField(blank=True, help_text='use for action return', max_length=255),
        ),
        migrations.AddField(
            model_name='runtimeassignee',
            name='zone_hidden_and_properties',
            field=models.JSONField(default=dict, help_text='[{"id": "", "title": "", "remark": "", "properties": ["application_property_id"]}]', verbose_name='Zone detail and Properties ID of Zone | collect from Zone() and ApplicationProperties()'),
        ),
        migrations.AddField(
            model_name='runtimestage',
            name='assignee_and_zone_hidden_data',
            field=models.JSONField(default=dict, help_text='{"employee_id": [{"id": "", "title": "", "remark": "", "properties": ["application_property_id"]}]}', verbose_name='Summary assignee and zone hidden data'),
        ),
        migrations.AlterField(
            model_name='collabinworkflowzone',
            name='collab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_wf_zone_collab', to='workflow.collabinworkflow'),
        ),
        migrations.AlterField(
            model_name='collabinworkflowzone',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_wf_zone_zone', to='workflow.zone'),
        ),
        migrations.AlterField(
            model_name='collaborationinformzone',
            name='collab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_form_zone_collab', to='workflow.collaborationinform'),
        ),
        migrations.AlterField(
            model_name='collaborationinformzone',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_form_zone_zone', to='workflow.zone'),
        ),
        migrations.AlterField(
            model_name='collaborationoutformzone',
            name='collab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_form_zone_collab', to='workflow.collaborationoutform'),
        ),
        migrations.AlterField(
            model_name='collaborationoutformzone',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_form_zone_zone', to='workflow.zone'),
        ),
        migrations.AlterField(
            model_name='initialnodezone',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='init_node_zone_node', to='workflow.node'),
        ),
        migrations.AlterField(
            model_name='initialnodezone',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='init_node_zone_zone', to='workflow.zone'),
        ),
        migrations.AlterField(
            model_name='node',
            name='code_node_system',
            field=models.CharField(blank=True, help_text='code nodes system: initial, approved, completed,...', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='InitialNodeZoneHidden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='init_node_zone_hidden_node', to='workflow.node')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='init_node_zone_hidden_zone', to='workflow.zone')),
            ],
            options={
                'verbose_name': 'Initial Node Zone Hidden',
                'verbose_name_plural': 'Initial Node Zones Hidden',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CollaborationOutFormZoneHidden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_form_zone_hidden_collab', to='workflow.collaborationoutform')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_form_zone_hidden_zone', to='workflow.zone')),
            ],
            options={
                'verbose_name': 'Collab out form zone hidden',
                'verbose_name_plural': 'Collab out form zones hidden',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CollaborationInFormZoneHidden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_form_zone_hidden_collab', to='workflow.collaborationinform')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_form_zone_hidden_zone', to='workflow.zone')),
            ],
            options={
                'verbose_name': 'Collab in form zone hidden',
                'verbose_name_plural': 'Collab in form zones hidden',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CollabInWorkflowZoneHidden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_wf_zone_hidden_collab', to='workflow.collabinworkflow')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_wf_zone_hidden_zone', to='workflow.zone')),
            ],
            options={
                'verbose_name': 'Collab in workflow zone hidden',
                'verbose_name_plural': 'Collab in workflow zones hidden',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='collabinworkflow',
            name='zone_hidden',
            field=models.ManyToManyField(related_name='collab_in_workflows_map_zones_hidden', through='workflow.CollabInWorkflowZoneHidden', to='workflow.zone'),
        ),
        migrations.AddField(
            model_name='collaborationinform',
            name='zone_hidden',
            field=models.ManyToManyField(related_name='collab_in_forms_map_zones_hidden', through='workflow.CollaborationInFormZoneHidden', to='workflow.zone'),
        ),
        migrations.AddField(
            model_name='collaborationoutform',
            name='zone_hidden',
            field=models.ManyToManyField(related_name='collab_out_forms_map_zones_hidden', through='workflow.CollaborationOutFormZoneHidden', to='workflow.zone'),
        ),
        migrations.AddField(
            model_name='node',
            name='zones_hidden_initial_node',
            field=models.ManyToManyField(related_name='initial_node_map_zones_hidden', through='workflow.InitialNodeZoneHidden', to='workflow.zone'),
        ),
    ]
