# Generated by Django 4.1.3 on 2023-05-31 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companyconfig'),
        ('base', '0004_baseitemunit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0001_initial'),
        ('tenant', '0001_initial'),
        ('workflow', '0004_runtime_runtimeassignee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowConfigOfApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('mode', models.SmallIntegerField(choices=[(0, 'UnApply'), (1, 'Apply'), (2, 'Pending')], default=0, verbose_name='Mode feature in workflow')),
                ('error_total', models.SmallIntegerField(default=0, verbose_name='Error total in feature')),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_config_of_application', to='base.application', verbose_name='application')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='User modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('workflow_currently', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflow', verbose_name='Workflow applied of feature')),
            ],
            options={
                'verbose_name': 'Workflow of Apps',
                'verbose_name_plural': 'Workflow of Apps',
                'ordering': ('title',),
                'permissions': (),
                'default_permissions': (),
                'unique_together': {('company', 'application')},
            },
        ),
    ]
