# Generated by Django 4.1.3 on 2023-06-05 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('company', '0004_companyconfig'),
        ('tenant', '0001_initial'),
        ('workflow', '0005_workflowconfigofapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runtimelog',
            options={'default_permissions': (), 'ordering': ('-date_created',), 'permissions': (), 'verbose_name': 'Log Activity', 'verbose_name_plural': 'Log Activity'},
        ),
        migrations.RemoveField(
            model_name='runtime',
            name='task_bg_id',
        ),
        migrations.AddField(
            model_name='runtime',
            name='app_code',
            field=models.CharField(default='', help_text='{app_label}.{model}', max_length=100, verbose_name='Code of application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runtime',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='runtime',
            name='start_mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'UnApply'), (1, 'Apply'), (2, 'Pending')], default=None, null=True),
        ),
        migrations.AddField(
            model_name='runtime',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='runtimelog',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Is system Log'),
        ),
        migrations.AddField(
            model_name='runtimestage',
            name='assignee_and_zone_data',
            field=models.JSONField(default=dict, help_text='{"employee_id": [{"id": "", "title": "", "remark": "", "properties": ["application_property_id"]}]}', verbose_name='Summary assignee and zone data'),
        ),
        migrations.AlterField(
            model_name='association',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='collabinworkflow',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='collaborationinform',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='collaborationoutform',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='node',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='workflowconfigofapp',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
    ]
