# Generated by Django 4.2.8 on 2024-12-25 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_alter_association_date_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runtimestage',
            name='node',
            field=models.ForeignKey(help_text='Workflow node for this runtime stage, this field set null if record node deleted', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.node', verbose_name='Relate to Config Node. node_data get data from this'),
        ),
    ]
