# Generated by Django 4.1.3 on 2023-06-22 16:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('log', '0003_docpined_bookmark'),
        ('company', '0004_companyconfig'),
        ('workflow', '0006_alter_runtimelog_options_remove_runtime_task_bg_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runtimeassignee',
            options={'default_permissions': (), 'ordering': ('-date_created',), 'permissions': (), 'verbose_name': 'Stage map Employee plus Zone', 'verbose_name_plural': 'Stage map Employee plus Zone'},
        ),
        migrations.AddField(
            model_name='runtime',
            name='doc_pined',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runtime_of_doc_pined', to='log.docpined', verbose_name='Doc Pined relate'),
        ),
        migrations.AddField(
            model_name='runtimeassignee',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='runtimeassignee',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at time'),
        ),
        migrations.AddField(
            model_name='runtimeassignee',
            name='employee_data',
            field=models.JSONField(default=dict, help_text='{"id": "", "first_name": "", "last_name": "", "full_name": "", "avatar": ""}', verbose_name='Employee backup data'),
        ),
        migrations.AddField(
            model_name='runtimeassignee',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='runtimelog',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='runtimelog',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='runtimestage',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='runtimestage',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
    ]
