# Generated by Django 4.2.8 on 2025-01-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_alter_runtimestage_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collabinworkflow',
            name='position_choice',
            field=models.SmallIntegerField(choices=[(1, 'Beneficiary'), (2, '1st manager'), (3, '2nd manager'), (4, 'Upper manager'), (5, 'Manager of x group level')], help_text='position choice (1st manager, 2nd manager,...) help to get exact employee of Node when Runtime', null=True, verbose_name='position choice (in_wf_option==1)'),
        ),
    ]
