# Generated by Django 4.1.3 on 2023-08-18 12:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_employee_code_alter_employee_unique_together'),
        ('workflow', '0007_alter_runtimeassignee_options_runtime_doc_pined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtime',
            name='doc_employee_inherit',
            field=models.ForeignKey(help_text='Data from Runtime first time', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_inherit_of_runtime', to='hr.employee', verbose_name='Employee inherit of Document'),
        ),
        migrations.AlterField(
            model_name='runtime',
            name='doc_employee_created',
            field=models.ForeignKey(help_text='Data from Runtime first time', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_created_of_runtime', to='hr.employee', verbose_name='Employee created of Document'),
        ),
        migrations.CreateModel(
            name='RuntimeViewer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='Employee of Viewer')),
                ('runtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.runtime', verbose_name='Runtime of Viewer')),
            ],
            options={
                'verbose_name': 'Viewer Append of Runtime',
                'verbose_name_plural': 'Viewer Append of Runtime',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
                'unique_together': {('runtime', 'employee')},
            },
        ),
        migrations.AddField(
            model_name='runtime',
            name='viewer_append',
            field=models.ManyToManyField(help_text='All employee ID was append view permit', related_name='employee_viewer_append', through='workflow.RuntimeViewer', to='hr.employee', verbose_name='All employee ID Viewer'),
        ),
    ]
