# Generated by Django 4.2.8 on 2024-07-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagramdocument',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
        migrations.AlterField(
            model_name='diagramprefix',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
        migrations.AlterField(
            model_name='diagramsuffix',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
    ]
