# Generated by Django 4.2.8 on 2025-10-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_alter_taskattachmentfile_task'),
        ('serviceorder', '0004_serviceorderservicedetail_attributes_total_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderworkorder',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='service_order_work_order_m2m_task', through='serviceorder.ServiceOrderWorkOrderTask', to='task.opportunitytask'),
        ),
    ]
