# Generated by Django 4.2.8 on 2025-10-07 16:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_companyconfig_shift_companyconfig_shift_data_and_more'),
        ('tenant', '0001_initial'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('quotation', '0029_quotation_valid_until'),
        ('serviceorder', '0005_serviceorderworkorder_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='indicator_gross_profit',
            field=models.FloatField(default=0, help_text='value of indicator gross profit (IN0003)'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='indicator_net_income',
            field=models.FloatField(default=0, help_text='value of indicator net income (IN0006)'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='indicator_revenue',
            field=models.FloatField(default=0, help_text='value of indicator revenue (IN0001)'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='service_order_indicators_data',
            field=models.JSONField(default=list, help_text='read data indicators, records in model ServiceOrderIndicator'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='total_product',
            field=models.FloatField(default=0, help_text='total of tab product'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='total_product_pretax_amount',
            field=models.FloatField(default=0, help_text='total pretax of tab product'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='total_product_revenue_before_tax',
            field=models.FloatField(default=0, help_text='total before tax of tab product'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='total_product_tax',
            field=models.FloatField(default=0, help_text='total tax of tab product'),
        ),
        migrations.CreateModel(
            name='ServiceOrderIndicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('indicator_value', models.FloatField(default=0, help_text='value of specific indicator for sale order')),
                ('indicator_rate', models.FloatField(default=0, help_text='rate value of specific indicator for sale order')),
                ('quotation_indicator_data', models.JSONField(default=dict, help_text='data json of quotation indicator')),
                ('quotation_indicator_value', models.FloatField(default=0, help_text='value of specific indicator for quotation mapped with service order')),
                ('quotation_indicator_rate', models.FloatField(default=0, help_text='rate value of specific indicator for quotation mapped with service order')),
                ('difference_indicator_value', models.FloatField(default=0, help_text='difference value between quotation and sale order')),
                ('order', models.IntegerField(default=1)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('quotation_indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_order_indicator_quotation_indicator', to='quotation.quotationindicatorconfig', verbose_name='quotation indicator')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_order_indicator_service_order', to='serviceorder.serviceorder', verbose_name='service order')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Service Order Indicator',
                'verbose_name_plural': 'Service Order Indicators',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
