# Generated by Django 4.2.8 on 2025-10-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceorder', '0007_serviceorderservicedetail_service_percent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorderexpense',
            old_name='subtotal_price',
            new_name='expense_subtotal_price',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='expense_pretax_value',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='expense_tax_value',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='expense_total_value',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='total_expense',
            field=models.FloatField(default=0, help_text='total amount of tab expense'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='total_expense_pretax_amount',
            field=models.FloatField(default=0, help_text='total pretax amount of tab expense'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='total_expense_tax',
            field=models.FloatField(default=0, help_text='total tax of tab expense'),
        ),
    ]
