# Generated by Django 4.2.8 on 2025-10-27 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0086_product_is_representative_product_and_more'),
        ('serviceorder', '0008_rename_subtotal_price_serviceorderexpense_expense_subtotal_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_order_contact', to='saledata.contact', verbose_name='contact'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='contact_data',
            field=models.JSONField(default=dict, help_text='data json of contact'),
        ),
        migrations.AddField(
            model_name='serviceorderworkordercontribution',
            name='delivery_call',
            field=models.BooleanField(default=False, help_text='State call delivery of this', verbose_name='Called delivery'),
        ),
    ]
