# Generated by Django 4.2.8 on 2025-11-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceorder', '0010_alter_serviceorderpaymentdetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='total_cost',
            field=models.FloatField(default=0, help_text='total amount of tab cost'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='total_cost_pretax_amount',
            field=models.FloatField(default=0, help_text='total pretax amount of tab cost'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='total_cost_tax',
            field=models.FloatField(default=0, help_text='total tax of tab cost'),
        ),
    ]
