# Generated by Django 4.2.8 on 2024-01-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingzoomconfig',
            name='account_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meetingzoomconfig',
            name='client_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meetingzoomconfig',
            name='client_secret',
            field=models.TextField(blank=True),
        ),
    ]
