# Generated by Django 4.2.8 on 2024-01-15 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0009_periods_planned'),
        ('hr', '0002_employee_avatar_img'),
        ('meeting', '0004_meetingschedule_account_external_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingscheduleparticipant',
            name='participant',
        ),
        migrations.AddField(
            model_name='meetingscheduleparticipant',
            name='external',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.contact'),
        ),
        migrations.AddField(
            model_name='meetingscheduleparticipant',
            name='internal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.employee'),
        ),
    ]
