# Generated by Django 4.2.8 on 2024-09-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_alter_meetingschedule_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingschedule',
            name='meeting_end_datetime',
            field=models.DateTimeField(blank=None, null=True),
        ),
        migrations.AddField(
            model_name='meetingschedule',
            name='meeting_start_datetime',
            field=models.DateField(blank=None, null=True),
        ),
    ]
