# Generated by Django 4.2.8 on 2025-02-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0011_meetingschedule_process_stage_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingscheduleparticipant',
            name='send_email_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingscheduleparticipant',
            name='send_notify_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meetingschedule',
            name='meeting_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingschedule',
            name='meeting_start_datetime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
