from django.urls import path, include

urlpatterns = [
    path('quotation/', include('apps.sales.quotation.urls')),
    path('opportunity/', include('apps.sales.opportunity.urls')),
    path('saleorder/', include('apps.sales.saleorder.urls')),
    path('cashoutflow/', include('apps.sales.cashoutflow.urls')),
    path('delivery/', include('apps.sales.delivery.urls')),
    path('task/', include('apps.sales.task.urls')),
    path('purchasing/', include('apps.sales.purchasing.urls')),
    path('inventory/', include('apps.sales.inventory.urls')),
    path('report/', include('apps.sales.report.urls')),
    path('acceptance/', include('apps.sales.acceptance.urls')),
    path('revenue-plans/', include('apps.sales.revenue_plan.urls')),
    path('ar-invoice/', include('apps.sales.arinvoice.urls')),
    path('ap-invoice/', include('apps.sales.apinvoice.urls')),
    path('lead/', include('apps.sales.lead.urls')),
    path('project/', include('apps.sales.project.urls')),
    path('budget-plans/', include('apps.sales.budgetplan.urls')),
    path('distribution-plans/', include('apps.sales.distributionplan.urls')),
    path('contract/', include('apps.sales.contract.urls')),
    path('production/', include('apps.sales.production.urls')),
    path('bidding/', include('apps.sales.bidding.urls')),
    path('leaseorder/', include('apps.sales.leaseorder.urls')),
    path('consulting/', include('apps.sales.consulting.urls')),
    path('financial-cashflow/', include('apps.sales.financialcashflow.urls')),
    path('financial-reconciliation/', include('apps.sales.reconciliation.urls')),
    path('partner-center/', include('apps.sales.partnercenter.urls')),
    path('asset/', include('apps.sales.asset.urls')),
    path('group-order/', include('apps.sales.grouporder.urls')),
    path('paymentplan/', include('apps.sales.paymentplan.urls')),
    path('product-modification/', include('apps.sales.productmodification.urls')),
    path('product-modification-bom/', include('apps.sales.productmodificationbom.urls')),
    path('equipment-loan/', include('apps.sales.equipmentloan.urls')),
    path('equipment-return/', include('apps.sales.equipmentreturn.urls')),
    path('serviceorder/', include('apps.sales.serviceorder.urls')),
]
