# Generated by Django 4.2.8 on 2025-07-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentloan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentloanitem',
            name='sum_returned_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='equipmentloanitemdetail',
            name='is_returned_serial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipmentloanitemdetail',
            name='lot_returned_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='equipmentloanitemdetail',
            name='returned_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='equipmentloanitem',
            name='loan_quantity',
            field=models.FloatField(default=0),
        ),
    ]
