# Generated by Django 4.2.8 on 2025-07-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentloan', '0002_equipmentloanitem_sum_returned_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentloan',
            name='product_loan_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='equipmentloan',
            name='return_status',
            field=models.SmallIntegerField(choices=[(0, 'Wait'), (1, 'Partially'), (2, 'Done')], default=0),
        ),
    ]
