# Generated by Django 4.2.8 on 2025-06-09 22:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0022_company_function_number_data'),
        ('workflow', '0008_alter_collabinworkflow_position_choice'),
        ('saledata', '0066_accountcontacts_account_contacts_mapped'),
        ('tenant', '0001_initial'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('space', '0001_initial'),
        ('process', '0009_processmembers_is_system_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=1)),
                ('component_text_data', models.JSONField(default=dict)),
                ('component_product_data', models.JSONField(default=dict)),
                ('component_quantity', models.IntegerField()),
                ('is_added_component', models.BooleanField(default=False)),
                ('component_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.product')),
            ],
            options={
                'verbose_name': 'Current Component',
                'verbose_name_plural': 'Current Components',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProductModification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('is_change', models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents')),
                ('document_root_id', models.UUIDField(help_text='this is id of root document of the changed documents', null=True)),
                ('document_change_order', models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('prd_wh_data', models.JSONField(default=dict)),
                ('prd_wh_lot_data', models.JSONField(default=dict)),
                ('prd_wh_serial_data', models.JSONField(default=dict)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('current_stage', models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('next_association', models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association')),
                ('next_node_collab', models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee')),
                ('prd_wh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.productwarehouse')),
                ('prd_wh_lot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.productwarehouselot')),
                ('prd_wh_serial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.productwarehouseserial')),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
                ('process_stage_app', models.ForeignKey(help_text='The process stage app claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.processstageapplication')),
                ('product_modified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_modified', to='saledata.product')),
                ('space', models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('workflow_runtime', models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc')),
            ],
            options={
                'verbose_name': 'Product Modification',
                'verbose_name_plural': 'Product Modification',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RemovedComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=1)),
                ('component_text_data', models.JSONField(default=dict)),
                ('component_product_data', models.JSONField(default=dict)),
                ('component_quantity', models.IntegerField()),
                ('component_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.product')),
                ('product_modified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removed_components', to='productmodification.productmodification')),
            ],
            options={
                'verbose_name': 'Removed Component',
                'verbose_name_plural': 'Removed Components',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RemovedComponentDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_prd_wh_quantity', models.FloatField(default=0)),
                ('component_prd_wh_lot_data', models.JSONField(default=dict)),
                ('component_prd_wh_lot_quantity', models.FloatField(default=0)),
                ('component_prd_wh_serial_data', models.JSONField(default=dict)),
                ('component_prd_wh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.productwarehouse')),
                ('component_prd_wh_lot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.productwarehouselot')),
                ('component_prd_wh_serial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.productwarehouseserial')),
                ('removed_component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='removed_components_detail', to='productmodification.removedcomponent')),
            ],
            options={
                'verbose_name': 'Removed Component Detail',
                'verbose_name_plural': 'Removed Components Detail',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CurrentComponentDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_prd_wh_quantity', models.FloatField(default=0)),
                ('component_prd_wh_lot_data', models.JSONField(default=dict)),
                ('component_prd_wh_lot_quantity', models.FloatField(default=0)),
                ('component_prd_wh_serial_data', models.JSONField(default=dict)),
                ('component_prd_wh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.productwarehouse')),
                ('component_prd_wh_lot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.productwarehouselot')),
                ('component_prd_wh_serial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.productwarehouseserial')),
                ('current_component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_components_detail', to='productmodification.currentcomponent')),
            ],
            options={
                'verbose_name': 'Current Component Detail',
                'verbose_name_plural': 'Current Components Detail',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='currentcomponent',
            name='product_modified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_components', to='productmodification.productmodification'),
        ),
    ]
