# Generated by Django 4.2.8 on 2025-06-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmodification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodification',
            name='created_goods_issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodification',
            name='created_goods_receipt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='removedcomponent',
            name='fair_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='removedcomponent',
            name='gr_remain_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='removedcomponent',
            name='is_mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='removedcomponent',
            name='product_mapped_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='currentcomponent',
            name='component_quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='removedcomponent',
            name='component_quantity',
            field=models.FloatField(default=0),
        ),
    ]
