# Generated by Django 4.2.8 on 2025-10-27 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0086_product_is_representative_product_and_more'),
        ('productmodification', '0003_productmodification_new_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodification',
            name='created_goods_issue',
        ),
        migrations.AddField(
            model_name='productmodification',
            name='created_goods_issue_for_root',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodification',
            name='representative_product_modified',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='representative_product_modified', to='saledata.product'),
        ),
    ]
