# Generated by Django 4.2.8 on 2025-02-26 10:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0004_employee_email_app_password_and_more'),
        ('saledata', '0055_remove_producttype_is_asset_tool_and_more'),
        ('company', '0016_companyconfig_accounting_policies_and_more'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('acc_code', models.CharField(max_length=100)),
                ('acc_name', models.CharField(max_length=100)),
                ('foreign_acc_name', models.CharField(max_length=100)),
                ('acc_status', models.BooleanField(default=True)),
                ('acc_type', models.SmallIntegerField(choices=[(0, 'Off-table accounts'), (1, 'Assets'), (2, 'Liabilities'), (3, "Owner's equity"), (4, 'Revenue'), (5, 'Costs of production, business'), (6, 'Other incomes'), (7, 'Other expenses'), (8, 'Income summary')])),
                ('has_child', models.BooleanField(default=False)),
                ('level', models.IntegerField(default=1)),
                ('is_account', models.BooleanField(default=False)),
                ('control_account', models.BooleanField(default=False)),
                ('is_all_currency', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('currency_mapped', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.currency')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('parent_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountingsettings.chartofaccounts')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Chart Of Accounts',
                'verbose_name_plural': 'Chart Of Accounts',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WarehouseAccountDetermination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('account_determination_type', models.SmallIntegerField(choices=[(0, 'Sale'), (1, 'Purchasing'), (2, 'Inventory')], default=0)),
                ('is_change', models.BooleanField(default=False, help_text='True if user has change default account determination')),
                ('account_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wh_account_deter_account_mapped', to='accountingsettings.chartofaccounts')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('warehouse_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wh_account_deter_warehouse_mapped', to='saledata.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Account Determination',
                'verbose_name_plural': 'Warehouse Account Determination',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProductTypeAccountDetermination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('account_determination_type', models.SmallIntegerField(choices=[(0, 'Sale'), (1, 'Purchasing'), (2, 'Inventory')], default=0)),
                ('is_change', models.BooleanField(default=False, help_text='True if user has change default account determination')),
                ('account_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prd_type_account_deter_account_mapped', to='accountingsettings.chartofaccounts')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('product_type_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prd_type_account_deter_product_type_mapped', to='saledata.producttype')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Product Type Account Determination',
                'verbose_name_plural': 'Product Type Account Determination',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProductAccountDetermination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('account_determination_type', models.SmallIntegerField(choices=[(0, 'Sale'), (1, 'Purchasing'), (2, 'Inventory')], default=0)),
                ('is_change', models.BooleanField(default=False, help_text='True if user has change default account determination')),
                ('account_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prd_account_deter_account_mapped', to='accountingsettings.chartofaccounts')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('product_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prd_account_deter_product_mapped', to='saledata.product')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Product Account Determination',
                'verbose_name_plural': 'Product Account Determination',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DefaultAccountDetermination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('default_account_determination_type', models.SmallIntegerField(choices=[(0, 'Sale'), (1, 'Purchasing'), (2, 'Inventory')], default=0)),
                ('account_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_account_deter_account', to='accountingsettings.chartofaccounts')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Default Account Determination',
                'verbose_name_plural': 'Default Account Determination',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
