# Generated by Django 4.2.8 on 2025-03-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingsettings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productaccountdetermination',
            old_name='is_change',
            new_name='is_changed',
        ),
        migrations.RenameField(
            model_name='producttypeaccountdetermination',
            old_name='is_change',
            new_name='is_changed',
        ),
        migrations.RenameField(
            model_name='warehouseaccountdetermination',
            old_name='is_change',
            new_name='is_changed',
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productaccountdetermination',
            name='account_mapped_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='productaccountdetermination',
            name='can_change_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producttypeaccountdetermination',
            name='account_mapped_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='producttypeaccountdetermination',
            name='can_change_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouseaccountdetermination',
            name='account_mapped_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='warehouseaccountdetermination',
            name='can_change_account',
            field=models.BooleanField(default=False),
        ),
    ]
