# Generated by Django 4.2.8 on 2025-03-14 14:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accountingsettings', '0002_rename_is_change_productaccountdetermination_is_changed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultaccountdetermination',
            options={'default_permissions': (), 'ordering': ('order',), 'permissions': (), 'verbose_name': 'Default Account Determination', 'verbose_name_plural': 'Default Account Determination'},
        ),
        migrations.RemoveField(
            model_name='defaultaccountdetermination',
            name='account_mapped',
        ),
        migrations.RemoveField(
            model_name='productaccountdetermination',
            name='account_mapped',
        ),
        migrations.RemoveField(
            model_name='productaccountdetermination',
            name='account_mapped_data',
        ),
        migrations.RemoveField(
            model_name='producttypeaccountdetermination',
            name='account_mapped',
        ),
        migrations.RemoveField(
            model_name='producttypeaccountdetermination',
            name='account_mapped_data',
        ),
        migrations.RemoveField(
            model_name='warehouseaccountdetermination',
            name='account_mapped',
        ),
        migrations.RemoveField(
            model_name='warehouseaccountdetermination',
            name='account_mapped_data',
        ),
        migrations.AddField(
            model_name='defaultaccountdetermination',
            name='can_change_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defaultaccountdetermination',
            name='foreign_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='defaultaccountdetermination',
            name='is_changed',
            field=models.BooleanField(default=False, help_text='True if user has change default account determination'),
        ),
        migrations.AddField(
            model_name='defaultaccountdetermination',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productaccountdetermination',
            name='foreign_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='producttypeaccountdetermination',
            name='foreign_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='warehouseaccountdetermination',
            name='foreign_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='defaultaccountdetermination',
            name='default_account_determination_type',
            field=models.SmallIntegerField(choices=[(0, 'Sale'), (1, 'Purchasing'), (2, 'Inventory'), (3, 'Fixed, Assets')], default=0),
        ),
        migrations.AlterField(
            model_name='productaccountdetermination',
            name='account_determination_type',
            field=models.SmallIntegerField(choices=[(0, 'Sale'), (1, 'Purchasing'), (2, 'Inventory'), (3, 'Fixed, Assets')], default=0),
        ),
        migrations.AlterField(
            model_name='producttypeaccountdetermination',
            name='account_determination_type',
            field=models.SmallIntegerField(choices=[(0, 'Sale'), (1, 'Purchasing'), (2, 'Inventory'), (3, 'Fixed, Assets')], default=0),
        ),
        migrations.AlterField(
            model_name='warehouseaccountdetermination',
            name='account_determination_type',
            field=models.SmallIntegerField(choices=[(0, 'Sale'), (1, 'Purchasing'), (2, 'Inventory'), (3, 'Fixed, Assets')], default=0),
        ),
        migrations.CreateModel(
            name='WarehouseAccountDeterminationSub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_mapped_data', models.JSONField(default=dict)),
                ('account_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wh_account_deter_account_mapped', to='accountingsettings.chartofaccounts')),
                ('wh_account_deter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wh_account_deter_sub', to='accountingsettings.warehouseaccountdetermination')),
            ],
            options={
                'verbose_name': 'Warehouse Account Determination Sub',
                'verbose_name_plural': 'Warehouse Account Determination Sub',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProductTypeAccountDeterminationSub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_mapped_data', models.JSONField(default=dict)),
                ('account_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prd_type_account_deter_account_mapped', to='accountingsettings.chartofaccounts')),
                ('prd_type_account_deter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prd_type_account_deter_sub', to='accountingsettings.producttypeaccountdetermination')),
            ],
            options={
                'verbose_name': 'Product Type Account Determination Sub',
                'verbose_name_plural': 'Product Type Account Determination Sub',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProductAccountDeterminationSub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_mapped_data', models.JSONField(default=dict)),
                ('account_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prd_account_deter_account_mapped', to='accountingsettings.chartofaccounts')),
                ('prd_account_deter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prd_account_deter_sub', to='accountingsettings.productaccountdetermination')),
            ],
            options={
                'verbose_name': 'Product Account Determination Sub',
                'verbose_name_plural': 'Product Account Determination Sub',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DefaultAccountDeterminationSub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_mapped_data', models.JSONField(default=dict)),
                ('account_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_acc_deter_account_mapped', to='accountingsettings.chartofaccounts')),
                ('default_acc_deter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_acc_deter_sub', to='accountingsettings.defaultaccountdetermination')),
            ],
            options={
                'verbose_name': 'Default Account Determination Sub',
                'verbose_name_plural': 'Default Account Determination Sub',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
