# Generated by Django 4.2.8 on 2025-11-07 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_companyconfig_shift_companyconfig_shift_data_and_more'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('tenant', '0001_initial'),
        ('accountingsettings', '0003_alter_defaultaccountdetermination_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetermination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('foreign_title', models.CharField(blank=True, max_length=100)),
                ('account_determination_type', models.SmallIntegerField(choices=[(0, 'Sale'), (1, 'Purchasing'), (2, 'Inventory'), (3, 'Fixed, Assets')], default=0)),
                ('can_change_account', models.BooleanField(default=False)),
                ('is_changed', models.BooleanField(default=False, help_text='True if user has change default account determination')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Account Determination',
                'verbose_name_plural': 'Account Determination',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AccountDeterminationSub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_mapped_data', models.JSONField(default=dict)),
                ('account_determination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_determination_sub', to='accountingsettings.accountdetermination')),
                ('account_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_determination_account_mapped', to='accountingsettings.chartofaccounts')),
            ],
            options={
                'verbose_name': 'Account Determination Sub',
                'verbose_name_plural': 'Account Determination Sub',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='defaultaccountdeterminationsub',
            name='account_mapped',
        ),
        migrations.RemoveField(
            model_name='defaultaccountdeterminationsub',
            name='default_acc_deter',
        ),
        migrations.DeleteModel(
            name='DefaultAccountDetermination',
        ),
        migrations.DeleteModel(
            name='DefaultAccountDeterminationSub',
        ),
    ]
