# Generated by Django 4.2.8 on 2025-11-14 11:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_companyconfig_shift_companyconfig_shift_data_and_more'),
        ('base', '0019_nprovince_nward'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('saledata', '0086_product_is_representative_product_and_more'),
        ('tenant', '0001_initial'),
        ('accountingsettings', '0004_accountdetermination_accountdeterminationsub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('related_app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.application')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Dimension Definition',
                'verbose_name_plural': 'Dimension Definitions',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DimensionValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('allow_posting', models.BooleanField()),
                ('related_doc_id', models.UUIDField(help_text='uuid of the related model record', null=True)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_values', to='accountingsettings.dimension')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_values', to='accountingsettings.dimensionvalue', verbose_name='')),
                ('period_mapped', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_dimension_values', to='saledata.periods')),
                ('related_app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.application')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Dimension Value',
                'verbose_name_plural': 'Dimension Value',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DimensionSyncConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('sync_on_save', models.BooleanField(default=False)),
                ('sync_on_delete', models.BooleanField(default=False)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_config', to='accountingsettings.dimension')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('related_app', models.ForeignKey(help_text='For example: set auto sync dimension for Account masterdata', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.application')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Dimension Sync Config',
                'verbose_name_plural': 'Dimension Sync Configs',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AccountDimensionMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Required'), (1, 'Optional')], default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_dimensions', to='accountingsettings.chartofaccounts')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_finance_accounts', to='accountingsettings.dimension')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Account Dimension Map',
                'verbose_name_plural': 'Account Dimension Maps',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
