# Generated by Django 4.2.8 on 2025-11-23 16:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_email_app_password_and_more'),
        ('tenant', '0001_initial'),
        ('company', '0023_companyconfig_shift_companyconfig_shift_data_and_more'),
        ('accountingsettings', '0005_dimension_dimensionvalue_dimensionsyncconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('remark', models.TextField()),
                ('category_type', models.IntegerField(choices=[(0, 'Tangible Asset'), (1, 'Intangible Asset'), (2, 'Instrument and Tool'), (3, 'Prepaid Expense')], default=0)),
                ('depreciation_method', models.PositiveSmallIntegerField(choices=[(0, 'Straight line depreciation'), (1, 'Adjusted reducing balance')], default=0)),
                ('depreciation_time', models.PositiveIntegerField(default=0)),
                ('accumulated_depreciation_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accumulated_depreciation_asset_categories', to='accountingsettings.chartofaccounts')),
                ('asset_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_account_categories', to='accountingsettings.chartofaccounts')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('depreciation_expense_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_expense_asset_categories', to='accountingsettings.chartofaccounts')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_categories', to='accountingsettings.assetcategory')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
