# Generated by Django 4.2.8 on 2025-11-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingsettings', '0006_assetcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensionvalue',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
