# Generated by Django 4.1.3 on 2025-12-01 15:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0009_processmembers_is_system_and_more'),
        ('space', '0001_initial'),
        ('tenant', '0001_initial'),
        ('workflow', '0008_alter_collabinworkflow_position_choice'),
        ('company', '0023_companyconfig_shift_companyconfig_shift_data_and_more'),
        ('saledata', '0087_product_asset_category'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('accountingsettings', '0007_alter_dimensionvalue_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionSplitTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_split_templates', to='accountingsettings.dimension')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Dimension Split Template',
                'verbose_name_plural': 'Dimension Split Templates',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DimensionSplitTemplateLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('percent', models.FloatField(default=0)),
                ('dimension_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_value_split_template_lines', to='accountingsettings.dimensionvalue')),
            ],
            options={
                'verbose_name': 'Dimension Split Template',
                'verbose_name_plural': 'Dimension Split Templates',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InitialBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('is_change', models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents')),
                ('document_root_id', models.UUIDField(help_text='this is id of root document of the changed documents', null=True)),
                ('document_change_order', models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('period_mapped_data', models.JSONField(default=dict)),
                ('tab_account_balance_data', models.JSONField(default=list)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('current_stage', models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('next_association', models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association')),
                ('next_node_collab', models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee')),
                ('period_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ib_period_mapped', to='saledata.periods')),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
                ('process_stage_app', models.ForeignKey(help_text='The process stage app claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.processstageapplication')),
                ('space', models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('workflow_runtime', models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc')),
            ],
            options={
                'verbose_name': 'Initial Balance',
                'verbose_name_plural': 'Initial Balances',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InitialBalanceGoodsLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Initial Balance Goods Lot',
                'verbose_name_plural': 'Initial Balance Goods Lots',
                'ordering': ('lot_mapped__lot_number',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InitialBalanceGoodsSerial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specific_value', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Initial Balance Goods Serial',
                'verbose_name_plural': 'Initial Balance Goods Serials',
                'ordering': ('serial_mapped__serial_number',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InitialBalanceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('is_change', models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents')),
                ('document_root_id', models.UUIDField(help_text='this is id of root document of the changed documents', null=True)),
                ('document_change_order', models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('initial_balance_type', models.SmallIntegerField(choices=[(0, 'Money'), (1, 'Goods'), (2, 'Customer receivable'), (3, 'Supplier payable'), (4, 'Employee payable'), (5, 'Tools'), (6, 'Fixed assets'), (7, 'Accounts')])),
                ('tab_amount', models.FloatField(default=0)),
                ('debit_value', models.FloatField(default=0)),
                ('credit_value', models.FloatField(default=0)),
                ('account_data', models.JSONField(default=dict)),
                ('is_fc', models.BooleanField(default=False)),
                ('currency_mapped_data', models.JSONField(default=dict)),
                ('money_type', models.SmallIntegerField(choices=[(0, 'Cash'), (1, 'Bank deposit')], default=0)),
                ('money_value', models.FloatField(default=0)),
                ('money_value_exchange', models.FloatField(default=0)),
                ('money_detail_data', models.JSONField(default=dict)),
                ('goods_value', models.FloatField(default=0)),
                ('goods_quantity', models.FloatField(default=0)),
                ('goods_data_lot', models.JSONField(default=list)),
                ('goods_data_sn', models.JSONField(default=list)),
                ('customer_receivable_value', models.FloatField(default=0)),
                ('customer_receivable_customer_data', models.JSONField(default=dict)),
                ('customer_receivable_detail_data', models.JSONField(default=dict)),
                ('supplier_payable_value', models.FloatField(default=0)),
                ('supplier_payable_supplier_data', models.JSONField(default=dict)),
                ('supplier_payable_detail_data', models.JSONField(default=dict)),
                ('employee_payable_value', models.FloatField(default=0)),
                ('employee_payable_type', models.SmallIntegerField(choices=[(0, 'Advance payment'), (1, 'Payment'), (2, 'Advance salary')], default=0)),
                ('employee_payable_employee_data', models.JSONField(default=dict)),
                ('employee_payable_detail_data', models.JSONField(default=dict)),
                ('tools_value', models.FloatField(default=0)),
                ('tools_detail_data', models.JSONField(default=dict)),
                ('account_value', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Initial Balance Line',
                'verbose_name_plural': 'Initial Balance Lines',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='productaccountdeterminationsub',
            name='account_mapped',
        ),
        migrations.RemoveField(
            model_name='productaccountdeterminationsub',
            name='prd_account_deter',
        ),
        migrations.RemoveField(
            model_name='producttypeaccountdetermination',
            name='company',
        ),
        migrations.RemoveField(
            model_name='producttypeaccountdetermination',
            name='employee_created',
        ),
        migrations.RemoveField(
            model_name='producttypeaccountdetermination',
            name='employee_modified',
        ),
        migrations.RemoveField(
            model_name='producttypeaccountdetermination',
            name='product_type_mapped',
        ),
        migrations.RemoveField(
            model_name='producttypeaccountdetermination',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='producttypeaccountdeterminationsub',
            name='account_mapped',
        ),
        migrations.RemoveField(
            model_name='producttypeaccountdeterminationsub',
            name='prd_type_account_deter',
        ),
        migrations.RemoveField(
            model_name='warehouseaccountdetermination',
            name='company',
        ),
        migrations.RemoveField(
            model_name='warehouseaccountdetermination',
            name='employee_created',
        ),
        migrations.RemoveField(
            model_name='warehouseaccountdetermination',
            name='employee_modified',
        ),
        migrations.RemoveField(
            model_name='warehouseaccountdetermination',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='warehouseaccountdetermination',
            name='warehouse_mapped',
        ),
        migrations.RemoveField(
            model_name='warehouseaccountdeterminationsub',
            name='account_mapped',
        ),
        migrations.RemoveField(
            model_name='warehouseaccountdeterminationsub',
            name='wh_account_deter',
        ),
        migrations.AlterModelOptions(
            name='accountdetermination',
            options={'ordering': ('account_determination_type', 'transaction_key'), 'verbose_name': 'Account Determination', 'verbose_name_plural': 'Account Determination'},
        ),
        migrations.AlterModelOptions(
            name='accountdeterminationsub',
            options={'ordering': ('order', '-priority'), 'verbose_name': 'Account Determination Sub', 'verbose_name_plural': 'Account Determination Subs'},
        ),
        migrations.AddField(
            model_name='accountdetermination',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountdetermination',
            name='transaction_key',
            field=models.CharField(db_index=True, default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountdeterminationsub',
            name='account_source_type',
            field=models.CharField(choices=[('FIXED', 'Cố định (Chọn cứng TK)'), ('LOOKUP', 'Động (Theo Role/Nhóm)'), ('CONDITIONAL', 'Theo điều kiện')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountdeterminationsub',
            name='amount_source',
            field=models.CharField(choices=[('TOTAL', 'Tổng thanh toán'), ('COST', 'Giá vốn (Cost)'), ('SALES', 'Doanh thu (Sales)'), ('TAX', 'Tiền thuế (Tax)'), ('DISCOUNT', 'Chiết khấu'), ('CASH', 'Số tiền mặt'), ('BANK', 'Số tiền ngân hàng')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountdeterminationsub',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountdeterminationsub',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountdeterminationsub',
            name='fixed_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='determination_fixed_account', to='accountingsettings.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='accountdeterminationsub',
            name='is_custom',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='accountdeterminationsub',
            name='match_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='accountdeterminationsub',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='accountdeterminationsub',
            name='priority',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='accountdeterminationsub',
            name='role_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountdeterminationsub',
            name='rule_level',
            field=models.CharField(choices=[('HEADER', 'Cả phiếu'), ('LINE', 'Từng dòng')], default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountdeterminationsub',
            name='search_rule',
            field=models.CharField(blank=True, db_index=True, default='default', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='accountdeterminationsub',
            name='side',
            field=models.CharField(choices=[('DEBIT', 'Bên nợ'), ('CREDIT', 'Bên có')], default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='currency_mapped_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='accountdetermination',
            name='account_determination_type',
            field=models.SmallIntegerField(choices=[(0, 'Sale'), (1, 'Purchasing'), (2, 'Inventory'), (3, 'Fixed Assets')], default=0),
        ),
        migrations.AlterField(
            model_name='accountdetermination',
            name='can_change_account',
            field=models.BooleanField(default=False, help_text='True if user can change'),
        ),
        migrations.AlterField(
            model_name='accountdeterminationsub',
            name='account_determination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='accountingsettings.accountdetermination'),
        ),
        migrations.AlterUniqueTogether(
            name='accountdetermination',
            unique_together={('company', 'transaction_key')},
        ),
        migrations.AlterUniqueTogether(
            name='accountdeterminationsub',
            unique_together={('account_determination', 'search_rule', 'order', 'side')},
        ),
        migrations.DeleteModel(
            name='ProductAccountDetermination',
        ),
        migrations.DeleteModel(
            name='ProductAccountDeterminationSub',
        ),
        migrations.DeleteModel(
            name='ProductTypeAccountDetermination',
        ),
        migrations.DeleteModel(
            name='ProductTypeAccountDeterminationSub',
        ),
        migrations.DeleteModel(
            name='WarehouseAccountDetermination',
        ),
        migrations.DeleteModel(
            name='WarehouseAccountDeterminationSub',
        ),
        migrations.AddField(
            model_name='initialbalanceline',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ib_line_account', to='accountingsettings.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='initialbalanceline',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='initialbalanceline',
            name='currency_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='saledata.currency'),
        ),
        migrations.AddField(
            model_name='initialbalanceline',
            name='current_stage',
            field=models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc'),
        ),
        migrations.AddField(
            model_name='initialbalanceline',
            name='customer_receivable_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ib_line_customer_receivable_customer', to='saledata.account'),
        ),
        migrations.AddField(
            model_name='initialbalanceline',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='initialbalanceline',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='initialbalanceline',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='initialbalanceline',
            name='employee_payable_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ib_line_employee_payable_employee', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='initialbalanceline',
            name='goods_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.product'),
        ),
        migrations.AddField(
            model_name='initialbalanceline',
            name='goods_uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='saledata.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='initialbalanceline',
            name='goods_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.warehouse'),
        ),
        migrations.AddField(
            model_name='initialbalanceline',
            name='initial_balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ib_line_initial_balance', to='accountingsettings.initialbalance'),
        ),
        migrations.AddField(
            model_name='initialbalanceline',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
        migrations.AddField(
            model_name='initialbalanceline',
            name='next_node_collab',
            field=models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='initialbalanceline',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='initialbalanceline',
            name='process_stage_app',
            field=models.ForeignKey(help_text='The process stage app claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.processstageapplication'),
        ),
        migrations.AddField(
            model_name='initialbalanceline',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='initialbalanceline',
            name='supplier_payable_supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ib_line_supplier_payable_supplier', to='saledata.account'),
        ),
        migrations.AddField(
            model_name='initialbalanceline',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='initialbalanceline',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
        migrations.AddField(
            model_name='initialbalancegoodsserial',
            name='initial_balance_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingsettings.initialbalanceline'),
        ),
        migrations.AddField(
            model_name='initialbalancegoodsserial',
            name='serial_mapped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.productwarehouseserial'),
        ),
        migrations.AddField(
            model_name='initialbalancegoodslot',
            name='initial_balance_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingsettings.initialbalanceline'),
        ),
        migrations.AddField(
            model_name='initialbalancegoodslot',
            name='lot_mapped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.productwarehouselot'),
        ),
        migrations.AddField(
            model_name='dimensionsplittemplateline',
            name='overwrite_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_split_template_lines', to='accountingsettings.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='dimensionsplittemplateline',
            name='split_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_template_lines', to='accountingsettings.dimensionsplittemplate'),
        ),
        migrations.RemoveField(
            model_name='accountdetermination',
            name='is_changed',
        ),
        migrations.RemoveField(
            model_name='accountdeterminationsub',
            name='account_mapped',
        ),
        migrations.RemoveField(
            model_name='accountdeterminationsub',
            name='account_mapped_data',
        ),
    ]
