# Generated by Django 4.2.8 on 2025-12-05 09:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('company', '0023_companyconfig_shift_companyconfig_shift_data_and_more'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('accountingsettings', '0008_dimensionsplittemplate_dimensionsplittemplateline_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jepostingrule',
            options={'ordering': ('je_document_type__code', 'rule_level', 'priority'), 'verbose_name': 'JE Posting Rule', 'verbose_name_plural': 'JE Posting Rules'},
        ),
        migrations.CreateModel(
            name='JEPostingGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('posting_group_type', models.CharField(choices=[('ITEM_GROUP', 'Item group'), ('PARTNER_GROUP', 'Partner group')], max_length=20)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'JE Posting Group',
                'verbose_name_plural': 'JE Posting Groups',
                'ordering': ('posting_group_type', 'code'),
                'unique_together': {('company', 'posting_group_type', 'code')},
            },
        ),
        migrations.CreateModel(
            name='JEGroupAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('tracking_app', models.CharField(choices=[('saledata.ProductType', 'Product Type'), ('saledata.Product', 'Product'), ('saledata.AccountType', 'Account Type'), ('saledata.Account', 'Account')], help_text='{app_label}.{model}', max_length=100, verbose_name='Code of application')),
                ('tracking_id', models.UUIDField()),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('posting_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_posting_group', to='accountingsettings.jepostinggroup')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'GL Group Assignment',
                'verbose_name_plural': 'GL Group Assignments',
                'ordering': ('posting_group__code', 'tracking_app'),
                'unique_together': {('company', 'tracking_app', 'tracking_id')},
            },
        ),
        migrations.CreateModel(
            name='JEGLAccountMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('role_key', models.CharField(choices=[('ASSET', 'Tài sản/Kho (156, 152...)'), ('COGS', 'Giá vốn hàng bán (632)'), ('REVENUE', 'Doanh thu (511)'), ('DONI', 'Doanh thu tạm tính/Chưa hóa đơn (1388)'), ('PAYABLE', 'Phải trả người bán (331)'), ('GRNI', 'Hàng về chưa hóa đơn (3388)'), ('RECEIVABLE', 'Phải thu khách hàng (131)'), ('TAX_IN', 'Thuế đầu vào (133)'), ('TAX_OUT', 'Thuế đầu ra (333)'), ('CASH', 'Tiền mặt (111)'), ('BANK', 'Tiền gửi ngân hàng (112)')], max_length=50)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_account_mapping_account', to='accountingsettings.chartofaccounts')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('posting_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_mappings', to='accountingsettings.jepostinggroup')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'JE GL Account Mapping',
                'verbose_name_plural': 'JE GL Accounts Mapping',
                'ordering': ('posting_group__code', 'role_key'),
                'unique_together': {('company', 'posting_group', 'role_key')},
            },
        ),
    ]
