# Generated by Django 4.2.8 on 2025-12-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountingsettings', '0010_alter_jegroupassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jedocdata',
            name='app_code',
            field=models.CharField(help_text='{app_label}.{model}', max_length=100, verbose_name='Code of application'),
        ),
        migrations.AlterField(
            model_name='jedocumenttype',
            name='module',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='jepostingrule',
            name='role_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
