# Generated by Django 4.2.8 on 2025-12-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountingsettings', '0012_jedocumenttype_current_stage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jeglaccountmapping',
            options={'ordering': ('posting_group__posting_group_type', 'posting_group__code', 'role_key'), 'verbose_name': 'JE GL Account Mapping', 'verbose_name_plural': 'JE GL Accounts Mapping'},
        ),
    ]
