# Generated by Django 4.2.8 on 2025-06-27 14:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
        ('process', '0009_processmembers_is_system_and_more'),
        ('attachments', '0011_files_is_approved_folder_is_admin_folder_is_owner_and_more'),
        ('workflow', '0008_alter_collabinworkflow_position_choice'),
        ('documentapproval', '0001_initial'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('company', '0022_company_function_number_data'),
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingAttachDocumentMapAttachFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('attachment', models.OneToOneField(help_text='Many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_files', to='attachments.files', verbose_name='Attachment files')),
            ],
            options={
                'verbose_name': 'KMS incoming document attachment',
                'verbose_name_plural': 'KMS incoming document attachment',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='KMSIncomingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('is_change', models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents')),
                ('document_root_id', models.UUIDField(help_text='this is id of root document of the changed documents', null=True)),
                ('document_change_order', models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True)),
                ('attachment_m2m', models.ManyToManyField(blank=True, related_name='kms_incoming_document_attachment_m2m', through='incomingdocument.IncomingAttachDocumentMapAttachFile', to='attachments.files')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('current_stage', models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('next_association', models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association')),
                ('next_node_collab', models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee')),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
                ('process_stage_app', models.ForeignKey(help_text='The process stage app claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.processstageapplication')),
                ('space', models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('workflow_runtime', models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc')),
            ],
            options={
                'verbose_name': 'Incoming document of KMS',
                'verbose_name_plural': 'Incoming documents of KMS',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='KMSInternalRecipientIncomingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('kind', models.SmallIntegerField(choices=[(1, 'employee'), (2, 'group')], default=1)),
                ('employee_access', models.JSONField(default=list, help_text='["uuid4", "uuid4"]', null=True, verbose_name='employee list has access this file')),
                ('group_access', models.JSONField(default=list, help_text='["uuid4", "uuid4"]', null=True, verbose_name='Permission of Group')),
                ('document_permission_list', models.JSONField(default=dict, help_text='{"permission_kind": [1, 2, 3, 4, 5, 6, 7]}', null=True, verbose_name='Permission of Employee')),
                ('expiration_date', models.DateField(null=True, verbose_name='expiration date')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('incoming_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kms_kmsinternalrecipient_incoming_doc', to='incomingdocument.kmsincomingdocument', verbose_name='Internal Recipient of KMS Incoming Document')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Internal recipient incoming document',
                'verbose_name_plural': 'Internal recipients incoming document',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='KMSAttachIncomingDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('sender', models.CharField(blank=True, max_length=250)),
                ('effective_date', models.DateTimeField(null=True)),
                ('expired_date', models.DateTimeField(null=True)),
                ('security_level', models.SmallIntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0)),
                ('attachment', models.JSONField(default=list, help_text='["uuid4", "uuid4"]', null=True, verbose_name='Attachment File')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('content_group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kms_incoming_document_content_groups', to='documentapproval.kmscontentgroup')),
                ('document_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kms_incoming_document_document_types', to='documentapproval.kmsdocumenttype')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('incoming_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kms_attach_incoming_documents', to='incomingdocument.kmsincomingdocument')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Attached Incoming Documents of KMS',
                'verbose_name_plural': 'list Attached Incoming Documents of KMS',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='incomingattachdocumentmapattachfile',
            name='incoming_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_document_attachment_incoming_document', to='incomingdocument.kmsincomingdocument', verbose_name='Attachment File of KMS attached Incoming Document'),
        ),
    ]
