# Generated by Django 4.2.8 on 2025-07-14 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_email_app_password_and_more'),
        ('incomingdocument', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kmsinternalrecipientincomingdocument',
            options={'default_permissions': (), 'ordering': (), 'permissions': (), 'verbose_name': 'Internal recipient incoming document', 'verbose_name_plural': 'Internal recipients incoming document'},
        ),
        migrations.RemoveField(
            model_name='kmsinternalrecipientincomingdocument',
            name='code',
        ),
        migrations.RemoveField(
            model_name='kmsinternalrecipientincomingdocument',
            name='company',
        ),
        migrations.RemoveField(
            model_name='kmsinternalrecipientincomingdocument',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='kmsinternalrecipientincomingdocument',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='kmsinternalrecipientincomingdocument',
            name='document_permission_list',
        ),
        migrations.RemoveField(
            model_name='kmsinternalrecipientincomingdocument',
            name='employee_created',
        ),
        migrations.RemoveField(
            model_name='kmsinternalrecipientincomingdocument',
            name='employee_modified',
        ),
        migrations.RemoveField(
            model_name='kmsinternalrecipientincomingdocument',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='kmsinternalrecipientincomingdocument',
            name='group_access',
        ),
        migrations.RemoveField(
            model_name='kmsinternalrecipientincomingdocument',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='kmsinternalrecipientincomingdocument',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='kmsinternalrecipientincomingdocument',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='kmsinternalrecipientincomingdocument',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='kmsinternalrecipientincomingdocument',
            name='title',
        ),
        migrations.AddField(
            model_name='kmsinternalrecipientincomingdocument',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kms_kmsinternalrecipient_employee', to='hr.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='kmsinternalrecipientincomingdocument',
            name='employee_access',
            field=models.JSONField(default=dict, help_text='store json data of employee', verbose_name='employee list has access this file'),
        ),
    ]
