# Generated by Django 4.2.8 on 2025-09-20 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0012_alter_filepermission_options_and_more'),
        ('incomingdocument', '0002_alter_kmsinternalrecipientincomingdocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmsattachincomingdocuments',
            name='folder',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kms_incoming_document_folders', to='attachments.folder'),
        ),
    ]
