# Generated by Django 4.2.8 on 2024-08-16 17:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0008_alter_files_date_modified_alter_folder_date_modified_and_more'),
        ('company', '0011_remove_company_email_app_password_and_more'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('workflow', '0006_alter_association_date_modified_and_more'),
        ('tenant', '0001_initial'),
        ('space', '0001_initial'),
        ('process', '0002_alter_salefunction_date_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('is_change', models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents')),
                ('document_root_id', models.UUIDField(help_text='this is id of root document of the changed documents', null=True)),
                ('document_change_order', models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('document_data', models.JSONField(default=list, help_text='data json of document')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('current_stage', models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('next_node_collab', models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee')),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
                ('space', models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('workflow_runtime', models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc')),
            ],
            options={
                'verbose_name': 'Contract Approval',
                'verbose_name_plural': 'Contracts Approval',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True, null=True, verbose_name='remark')),
                ('attachment_data', models.JSONField(default=list, help_text='data json of attachment')),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ContractDocumentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('attachment', models.OneToOneField(help_text='Many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_files', to='attachments.files', verbose_name='Attachment files')),
                ('contract_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_doc_attachment_doc', to='contract.contractdocument', verbose_name='contract document')),
            ],
            options={
                'verbose_name': 'Contract document attachment',
                'verbose_name_plural': 'Contract document attachments',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='attachment_m2m',
            field=models.ManyToManyField(blank=True, related_name='file_of_contract_document', through='contract.ContractDocumentAttachment', to='attachments.files'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_doc_contract', to='contract.contractapproval', verbose_name='contract'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
    ]
