# Generated by Django 4.2.8 on 2024-10-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_contractapproval_next_association'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractapproval',
            old_name='tinymce_content',
            new_name='abstract_content',
        ),
        migrations.AddField(
            model_name='contractapproval',
            name='legal_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractapproval',
            name='payment_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractapproval',
            name='trade_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
