# Generated by Django 4.2.8 on 2024-10-29 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0012_opportunity_next_association'),
        ('project', '0018_project_date_close'),
        ('contract', '0006_rename_tinymce_content_contractapproval_abstract_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractapproval',
            name='employee_inherit_data',
            field=models.JSONField(default=dict, help_text='data json of employee_inherit'),
        ),
        migrations.AddField(
            model_name='contractapproval',
            name='opportunity',
            field=models.ForeignKey(help_text='Relate to Opportunity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_opp', to='opportunity.opportunity'),
        ),
        migrations.AddField(
            model_name='contractapproval',
            name='opportunity_data',
            field=models.JSONField(default=dict, help_text='data json of opportunity'),
        ),
        migrations.AddField(
            model_name='contractapproval',
            name='project',
            field=models.ForeignKey(help_text='Relate to Project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_prj', to='project.project'),
        ),
    ]
