# Generated by Django 4.2.8 on 2024-08-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributionplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionplan',
            name='is_create_purchase_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributionplan',
            name='purchase_request_number',
            field=models.FloatField(default=0),
        ),
    ]
