# Generated by Django 4.2.8 on 2024-11-29 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('distributionplan', '0005_distributionplan_process_stage_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionplan',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='distributionplan',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
