# Generated by Django 4.2.8 on 2024-12-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributionplan', '0006_distributionplan_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionplan',
            name='is_create_purchase_request',
        ),
    ]
