"""
Django settings for misapi project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import json
import sys
import socket
import os

from colorama import Fore
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# override recursion limit
sys.setrecursionlimit(10000)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# load environment from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z+!6=0b0sdkx!#su_z1$+6(*_8&5lo5&%jy8n76c5l1b1um&%t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
DEBUG_SIGNAL_CHANGE = False

ALLOWED_HOSTS = []
ALLOWED_CIDR_NETS = []  # whitelist range IP
ALLOWED_IP_PROVISIONING = []  # provisioning server IP
PROVISIONING_PATH_PREFIX = '/api/provisioning/'  # prefix path navigation check provisioning
PROVISIONING_ACCESS_KEY = 'PROVISION'
PROVISIONING_ACCESS_VALUE = 'P7UqtC7fkE6TZ9wW448JREyamUmht79Bj6eGKjmcxn5xV4UgTZVw8vuKtcYRJnWY'

# Application definition

INSTALLED_APPS = \
    [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
    ] + [  # extend library
        'drf_yasg',  # API Document Page
        'rest_framework',  # rest API
        'compressor',  # Compress Assets File
        'rest_framework_simplejwt',  # Authenticate Token with JSON WEB TOKEN
        'django_celery_results',  # Listen celery task and record it to database.
        'debug_toolbar',  # debug toolbar support check API
    ] + [  # integrate some service management or tracing
        'apps.core.system',  # Save secret data in DB
        'apps.sharedapp',  # App support command
        'apps.core.provisioning',  # config receive request from PROVISIONING server
        'apps.core.log',  # all logged data, except Workflow Log
        'apps.core.attachments',  # all files data | link to file media
    ] + [  # application
        'apps.core.base',
        'apps.core.account',
        'apps.core.tenant',
        'apps.core.hr',
        'apps.core.company',
        'apps.core.space',

        'apps.core.workflow',
        'apps.core.process',
        'apps.masterdata.saledata',
        'apps.sales.opportunity',
        'apps.sales.quotation',
        'apps.masterdata.promotion',
        'apps.sales.saleorder',
        'apps.sales.cashoutflow',
        'apps.sales.delivery',
        'apps.sales.task',
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
#
# Allow Open Tracing all request.
MIDDLEWARE += ['apps.shared.extends.middleware.customize.JaegerTracingMiddleware']
#
# Author: Paul McLanahan <pmac@mozilla.com>
# Package: Allow range IP or switch path view from request key (customize)
# Home Page: https://github.com/mozmeao/django-allow-cidr
# Package Healthy Score: https://snyk.io/advisor/python/django-allow-cidr
MIDDLEWARE += ['apps.shared.extends.middleware.cidr_provisioning.AllowCIDRAndProvisioningMiddleware']
# Author: ©2018, Nine More Minutes, Inc.. | Powered by Sphinx 1.8.5 & Alabaster 0.7.12 | Page source
# Package: CRUM - Current Request User Middleware
# Home Page: https://django-crum.readthedocs.io/en/latest/
# Package Health Score: https://snyk.io/advisor/python/django-crum
MIDDLEWARE += ['crum.CurrentRequestUserMiddleware']
# debug toolbar middleware
MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware', ]
INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

ROOT_URLCONF = 'misapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': [
                'django.templatetags.static',  # <---- default
                # 'apps.shared.templatetags.static',
            ]
        },
    },
]

WSGI_APPLICATION = 'misapi.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASE_ROUTERS = ['routers.LogRouter']

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
# translate active language in Authenticated Classes

LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

LANGUAGE_CODE = 'en'

LANGUAGE_CHOICE = (
    ('en', 'English'),
    ('vi', 'Vietnamese'),
)

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = False

# Mail config
MAIL_CONFIG_OBJ_PK = os.environ.get('MAIL_CONFIG_OBJ_PK', '6db50f86-055d-4fc6-9235-208b0fbc0ef9')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'statics'),)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # other finders..
    'compressor.finders.CompressorFinder',
)

MEDIA_PREFIX_SITE = os.environ.get(
    'MEDIA_PREFIX_SITE',
    ''
)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
MEDIA_PROTOCOL = os.environ.get('MEDIA_PROTOCOL', 'http')
MEDIA_HOST = os.environ.get('MEDIA_HOST', '127.0.0.1')
MEDIA_PORT = os.environ.get('MEDIA_PORT', '8881')
MEDIA_SUFFIX = 'api'
MEDIA_DOMAIN = f'{MEDIA_PROTOCOL}://{MEDIA_HOST}:{MEDIA_PORT}/{(MEDIA_SUFFIX + "/") if MEDIA_SUFFIX else ""}'
MEDIA_ENABLED = False

# Media key and data private
MEDIA_KEY_FLAG = os.environ.get('MEDIA_KEY_FLAG', 'MEDIA-APIRequest')
MEDIA_KEY_SECRET_TOKEN_API = os.environ.get('MEDIA_KEY_SECRET_TOKEN_API', 'SECRET-KEY-APIRequest')
MEDIA_SECRET_TOKEN_API = os.environ.get('MEDIA_SECRET_TOKEN_API', 'bhVpajC75NCEPwGs')

# Key return resp after call API
API_KEY_AUTH = 'Authorization'
API_PREFIX_TOKEN = 'Bearer'
API_KEY_RESPONSE_DATA = 'result'
API_KEY_RESPONSE_ERRORS = 'errors'
API_KEY_RESPONSE_STATUS = 'status'
API_KEY_RESPONSE_PAGE_SIZE = 'page_size'
API_KEY_RESPONSE_PAGE_COUNT = 'count'
API_KEY_RESPONSE_PAGE_NEXT = 'next'
API_KEY_RESPONSE_PAGE_PREVIOUS = 'previous'

UI_RESP_KEY_STATE = 'state'
UI_RESP_KEY_STATUS = 'status'
UI_RESP_KEY_RESULT = 'result'
UI_RESP_KEY_ERRORS = 'errors'
UI_RESP_KEY_PAGE_SIZE = 'page_size'
UI_RESP_KEY_PAGE_COUNT = 'page_count'
UI_RESP_KEY_PAGE_NEXT = 'page_next'
UI_RESP_KEY_PAGE_PREVIOUS = 'page_previous'

# DEBUG CODE enable: allow raise errors if it is enabled else return default value (value is correct type)
RAISE_EXCEPTION_DEBUG = True

# FILE - AVATAR
AVATAR_FILE_MAX_SIZE = 5 * 1024 * 1024  # 5MiB

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# test runner override | runner for command: python manage.py test
TEST_RUNNER = 'misapi.testrunner.CustomTestRunner'
# -- test runner override | runner for command: python manage.py test

# REST API & JWT
REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'apps.shared.extends.exceptions.custom_exception_handler',
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.AllowAny',),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        'apps.core.auths.authenticate.MyCustomJWTAuthenticate',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': ('rest_framework.parsers.JSONParser',),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'apps.shared.extends.pagination.CustomResultsSetPagination',
    'PAGE_SIZE': 100,
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
}
CUSTOM_PAGE_MAXIMUM_SIZE = 1500

AUTH_USER_MODEL = 'account.User'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': 'HEk5@d&z7Kvq)GFp32SKdumR4h2E@H@D',  # SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(hours=12),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
}
# -- REST API & JWT

# page API documentations
SHOW_API_DOCS = False
HEADER_MINIMAL_CODE = 'SuaD2m'
HEADER_SKIP_AUTH_CODE = 'Wl46tj'
SWAGGER_SETTINGS = {
    'LOGIN_URL': '/',
    'LOGOUT_URL': '/logout',
    'DEFAULT_MODEL_DEPTH': -1,
    'USE_SESSION_AUTH': False,
    'SHOW_COMMON_EXTENSIONS': False,
    'SECURITY_DEFINITIONS': {
        'Bearer': {'type': 'apiKey', 'name': 'Authorization', 'in': 'header'},
        f'Provisioning: {PROVISIONING_ACCESS_VALUE}': {
            'type': 'apiKey',
            'name': 'PROVISION',
            'in': 'header',
        },
        f'Minimal: {HEADER_MINIMAL_CODE}': {
            'type': 'apiKey',
            'name': 'DATAISMINIMAL',
            'in': 'header',
        },
        f'SKIP AUTH: {HEADER_SKIP_AUTH_CODE}': {
            'type': 'apiKey',
            'name': 'DATAISSKIPAUTH',
            'in': 'header',
        },
        f'Dropdown List: "true"': {
            'type': 'apiKey',
            'name': 'DATAISDD',
            'in': 'header',
        },
    },
    'SUPPORTED_SUBMIT_METHODS': ['get', 'post', 'put', 'delete', 'patch'],
    'APIS_SORTER': 'alpha',
    'OPERATIONS_SORTER': 'alpha',
    'DOC_EXPANSION': 'none',
    'CSS_OVERRIDE': '/statics/swagger-dark.css',  # Thêm đường dẫn đến file CSS tùy chỉnh
}
SWAGGER_URL = 'http://127.0.0.1:8000/api'
FORCE_SCRIPT_NAME = None  # SWAGGER_URL.replace('/api', '')
# -- page API documentations

# Cache
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}
CACHE_KEY_PREFIX = 'MiS'
# -- Cache

# option account user create
ENABLE_TURN_ON_IS_EMAIL = False
# -- option account user create

# CELERY + RABBITMQ CONFIG
CELERY_BROKER_URL = None  # 'amqp://guest:guest@127.0.0.1:5672//'
CELERY_TASK_ALWAYS_EAGER = True  # allow executable task real-time (True) or push task to queue (False)
# -- CELERY + RABBITMQ CONFIG

# import local_settings
try:
    from .local_settings import *
except ImportError:
    pass

# -- import local_settings

# Logging
if os.environ.get('ENABLE_LOGGING', False) in [1, '1']:
    LOG_DIR = os.path.join(BASE_DIR, "logs")
    if not os.path.exists(LOG_DIR):
        os.makedirs(LOG_DIR)
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
                "datefmt": "%d/%b/%Y-%H:%M:%S",
            },
            "celery_formatter": {
                "format": "%(asctime)s %(levelname)s module=%(module)s, process_id=%(process)d, %(message)s",
            }
        },
        "handlers": {
            "file": {
                "level": "INFO",
                "class": "logging.handlers.TimedRotatingFileHandler",
                "filename": os.path.join(LOG_DIR, "api.log"),
                "when": "D",
                "interval": 1,
                "backupCount": 5,
                "formatter": "verbose",
            },
            "celery_handler": {
                "level": "INFO",
                "class": "logging.handlers.TimedRotatingFileHandler",
                "filename": os.path.join(LOG_DIR, "celery.log"),
                "when": "D",
                "interval": 1,
                "backupCount": 5,
                "formatter": "celery_formatter",
            },
        },
        "loggers": {
            "": {
                "handlers": ["file"],
                "level": "INFO",
            },
            "celery": {
                "handlers": ["celery_handler"],
                "level": "INFO",
                "propagate": True
            },
        },
    }
# -- Logging

# PROD configurations
ENABLE_PROD = True if os.environ.get('ENABLE_PROD', '0') in [1, '1'] else False
if ENABLE_PROD is True:
    # allow host
    OS_ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '[]')
    ALLOWED_HOSTS = json.loads(OS_ALLOWED_HOSTS)

    # set up celery prod
    CELERY_RESULT_SERIALIZER = 'json'
    CELERY_ACCEPT_CONTENT = ['json']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_BACKEND = 'django-db'
    CELERY_TASK_ALWAYS_EAGER = True if os.environ.get('CELERY_TASK_ALWAYS_EAGER', 0) in [1, '1'] else False
    CELERY_BROKER_VHOST = os.environ.get('MSG_QUEUE_BROKER_VHOST', '/')
    MSG_QUEUE_HOST = os.environ.get("MSG_QUEUE_HOST")  # '127.0.0.1' or host_name
    MSG_QUEUE_PORT = os.environ.get("MSG_QUEUE_PORT")  # default '5672'
    MSG_QUEUE_USER = os.environ.get("MSG_QUEUE_USER")  # default 'rabbitmq_user'
    MSG_QUEUE_PASSWORD = os.environ.get("MSG_QUEUE_PASSWORD")  # default 'rabbitmq_password'
    if MSG_QUEUE_HOST and MSG_QUEUE_PORT:
        CELERY_BROKER_URL = f'amqp://{MSG_QUEUE_USER}:{MSG_QUEUE_PASSWORD}@{MSG_QUEUE_HOST}:{MSG_QUEUE_PORT}'
    else:
        raise ValueError('CELERY CONFIG must be required HOST & PORT.')

    # setup database default prod
    DATABASES.update(
        {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': os.environ.get('DB_NAME'),
                'USER': os.environ.get('DB_USER'),
                'PASSWORD': os.environ.get('DB_PASSWORD'),
                'HOST': os.environ.get('DB_HOST'),
                'PORT': os.environ.get('DB_PORT'),
            }
        }
    )

    # API Documentations
    SHOW_API_DOCS = os.environ.get('SHOW_API_DOCS', False)

    # media domain
    MEDIA_DOMAIN = os.environ.get('MEDIA_DOMAIN', MEDIA_DOMAIN)
    MEDIA_ENABLED = True if os.environ.get('MEDIA_ENABLED', '0') in [1, '1'] else False
# -- PROD configurations

# Tracing
JAEGER_TRACING_ENABLE = os.environ.get('ENABLE_TRACING', False)
if JAEGER_TRACING_ENABLE in [1, '1']:
    JAEGER_TRACING_ENABLE = True
    JAEGER_TRACING_HOST = os.environ.get('JAEGER_TRACING_HOST', 'jaeger_global')
    JAEGER_TRACING_PORT = os.environ.get('JAEGER_TRACING_PORT', 6831)
    JAEGER_TRACING_PROJECT_NAME = os.environ.get('JAEGER_TRACING_PROJECT_NAME', 'MiS API')
    JAEGER_TRACING_EXCLUDE_LOG_PATH = '/__'
# -- Tracing

# Display config about DB, Cache, CELERY,...
OS_DEBUG = os.environ.get('DEBUG', DEBUG)
if OS_DEBUG is True or OS_DEBUG in [1, '1']:
    # debug toolbar IP Internal
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS = [ip[: ip.rfind(".")] + ".1" for ip in ips] + ["127.0.0.1", "10.0.2.2"]

    print(Fore.CYAN, '### SETTINGS CONFIG VERBOSE ----------------------------------------------------#', '\033[0m')
    print(Fore.BLUE, f'#  1. DATABASES: {DATABASES} \033[0m')
    print(Fore.YELLOW, f'#  2. CELERY_BROKER_URL: {str(CELERY_BROKER_URL)} \033[0m')
    print(Fore.GREEN, f'#  3. CELERY_TASK_ALWAYS_EAGER: {str(CELERY_TASK_ALWAYS_EAGER)} \033[0m')
    print(Fore.RED, f'#  4. ALLOWED_HOSTS: {str(ALLOWED_HOSTS)} \033[0m')
    print(Fore.LIGHTBLUE_EX, f'#  5. TRACING [JAEGER]: {JAEGER_TRACING_ENABLE} \033[0m')
    print(Fore.CYAN, '----------------------------------------------------------------------------------', '\033[0m')
# -- Display config about DB, Cache, CELERY,...

CELERY_TASK_ALWAYS_EAGER = True
