"""
Django settings for misapi project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import json
import sys
import socket
import os
import textwrap

from colorama import Fore
from datetime import timedelta
from pathlib import Path

import firebase_admin
from firebase_admin import credentials

from .load_env import load_env

# override recursion limit
sys.setrecursionlimit(10000)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# load environment from .env file
load_env(BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z+!6=0b0sdkx!#su_z1$+6(*_8&5lo5&%jy8n76c5l1b1um&%t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
DEBUG_PERMIT = False
DEBUG_BG_TASK = False
DEBUG_SIGNAL_CHANGE = False
SHOW_TESTCASE_NAME = False
SHOW_SYSTEM_DATA = False

ALLOWED_HOSTS = []
ALLOWED_CIDR_NETS = []  # whitelist range IP
ALLOWED_IP_PROVISIONING = []  # provisioning server IP
PROVISIONING_PATH_PREFIX = '/api/provisioning/'  # prefix path navigation check provisioning
PROVISIONING_ACCESS_KEY = 'PROVISION'
PROVISIONING_ACCESS_VALUE = 'P7UqtC7fkE6TZ9wW448JREyamUmht79Bj6eGKjmcxn5xV4UgTZVw8vuKtcYRJnWY'

# Application definition

INSTALLED_APPS = \
    [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
    ] + [  # extend library
        'drf_yasg',  # API Document Page
        'rest_framework',  # rest API
        'rest_framework_simplejwt.token_blacklist',
        'compressor',  # Compress Assets File
        'rest_framework_simplejwt',  # Authenticate Token with JSON WEB TOKEN
        'django_celery_results',  # Listen celery task and record it to database.
        'debug_toolbar',  # debug toolbar support check API
        'django_extensions',  # some tool for command | https://github.com/django-extensions/django-extensions
        'django_celery_beat',  # celery crontab
        'storages',  # storages[s3]
    ] + [  # integrate some service management or tracing
        'apps.core.system',  # Save secret data in DB
        'apps.sharedapp',  # App support command
        'apps.core.provisioning',  # config receive request from PROVISIONING server
        'apps.core.log',  # all logged data, except Workflow Log
        'apps.core.attachments',  # all files data | link to file media
        'apps.core.printer',  # print templates & rules
        'apps.core.mailer',  # mail templates & rules
        'apps.core.diagram',  # diagram for apps
        'apps.core.forms',  # form
        'apps.core.chatbot',  # chatbot AI
        'apps.core.recurrence',  # recurrence for apps
        'apps.core.chat3rd',
        'apps.core.firebase',
        'apps.core.contract_templates',  # contract template config
    ] + [  # application
        'apps.core.base',
        'apps.core.account',
        'apps.core.tenant',
        'apps.core.hr',
        'apps.core.company',
        'apps.core.space',
        'apps.core.comment',
        'apps.core.workflow',
        'apps.core.process',
        'apps.masterdata.saledata',
        'apps.sales.opportunity',
        'apps.sales.quotation',
        'apps.masterdata.promotion',
        'apps.sales.saleorder',
        'apps.sales.cashoutflow',
        'apps.sales.delivery',
        'apps.sales.task',
        'apps.sales.purchasing',
        'apps.sales.inventory',
        'apps.sales.project',
        'apps.sales.report',
        'apps.sales.acceptance',

        'apps.eoffice.leave',
        'apps.eoffice.businesstrip',
        'apps.eoffice.assettools',
        'apps.eoffice.meeting',
        'apps.sales.revenue_plan',
        'apps.sales.arinvoice',
        'apps.sales.apinvoice',
        'apps.sales.lead',
        'apps.sales.budgetplan',
        'apps.sales.distributionplan',
        'apps.sales.contract',
        'apps.sales.production',
        'apps.sales.bidding',
        'apps.sales.leaseorder',
        'apps.sales.consulting',
        'apps.sales.partnercenter',
        'apps.sales.grouporder',
        'apps.sales.productmodification',
        'apps.sales.productmodificationbom',
        'apps.sales.equipmentloan',
        'apps.sales.equipmentreturn',
        'apps.sales.serviceorder',
    ] + [  # Tools improvement from dev team
        'apps.core.web_builder',
    ] + [
        # authenticate
        'django_otp',
    ] + [  # HRM
        'apps.hrm.employeeinfo',
        'apps.hrm.attendance',
        'apps.hrm.absenceexplanation',
    ] + [
        'apps.sales.financialcashflow',
        'apps.sales.reconciliation',
        'apps.sales.asset',
        'apps.sales.paymentplan',
    ] + [
        'apps.accounting.accountingsettings',
        'apps.accounting.journalentry'
    ] + [  # KMS
        'apps.kms.documentapproval',
        'apps.kms.incomingdocument',
    ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.shared.extends.middleware.ActiveTranslateAndAllowedMethodMiddleware',
]
#
# Author: Paul McLanahan <pmac@mozilla.com>
# Package: Allow range IP or switch path view from request key (customize)
# Home Page: https://github.com/mozmeao/django-allow-cidr
# Package Healthy Score: https://snyk.io/advisor/python/django-allow-cidr
MIDDLEWARE += ['apps.shared.extends.middleware.cidr_provisioning.AllowCIDRAndProvisioningMiddleware']
# Author: ©2018, Nine More Minutes, Inc.. | Powered by Sphinx 1.8.5 & Alabaster 0.7.12 | Page source
# Package: CRUM - Current Request User Middleware
# Home Page: https://django-crum.readthedocs.io/en/latest/
# Package Health Score: https://snyk.io/advisor/python/django-crum
MIDDLEWARE += ['crum.CurrentRequestUserMiddleware']
# debug toolbar middleware
MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware', ]
INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

CSRF_TRUSTED_ORIGINS = json.loads(os.environ.get('CSRF_TRUSTED_ORIGINS', '[]'))

ROOT_URLCONF = 'misapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': [
                'django.templatetags.static',  # <---- default
                # 'apps.shared.templatetags.static',
            ]
        },
    },
]

WSGI_APPLICATION = 'misapi.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'mockup_db_ci': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / '.gitlab-ci-db.sqlite3',
    }
}

DATABASE_ROUTERS = ['routers.LogRouter']

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
# translate active language in Authenticated Classes

LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

LANGUAGE_CODE = 'en'

LANGUAGE_CHOICE = (
    ('en', 'English'),
    ('vi', 'Vietnamese'),
)

LANGUAGE_CHOICE_CODE = [item[0] for item in LANGUAGE_CHOICE]

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = False

# Trusted Link Domain
TRUSTED_DOMAIN_LINK = json.loads(os.environ.get('TRUSTED_DOMAIN_LINK', '[]'))
FORM_MAX_SIZE_HTML_BYTES = int(os.environ.get('FORM_MAX_SIZE_HTML_BYTES', 300 * 1024))  # 500 kB = 512 000 bytes

# UI of API
UI_DOMAIN = os.environ.get('UI_DOMAIN', None)
UI_DOMAIN_SUFFIX = os.environ.get('UI_DOMAIN_SUFFIX', None)
UI_DOMAIN_PROTOCOL = os.environ.get('UI_DOMAIN_PROTOCOL', 'https')
UI_DOMAIN_PATH_REVERSE = os.environ.get('UI_DOMAIN_PATH_REVERSE', '/form/r/g/rs-get')
UI_DOMAIN_PATH_REVERSE_PAGE = os.environ.get('UI_DOMAIN_PATH_REVERSE', '/form/r/g/rs')
UI_FULL_DOMAIN = os.environ.get('UI_FULL_DOMAIN', None)
UI_FIXED_DOMAIN = os.environ.get('UI_FIXED_DOMAIN', None)

# Mail config
MAIL_CONFIG_OBJ_PK = os.environ.get('MAIL_CONFIG_OBJ_PK', '6db50f86-055d-4fc6-9235-208b0fbc0ef9')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

EMAIL_CONFIG_PASSWORD = 'email-cfg-pwd+M2fwL5JV~}Y+a4Bp_nv@(c/N$Qs*r;Wj)C3kFD]!=x.`&z:>hq'

EMAIL_CONFIG_ENCRYPTOR_PASSWORD = 'email-config-Gd5$(RJ3*M3Ubm3m9g$RPeYwtPF95yNV*V%dT8LFucVbtNPuUJ&a#'

EMAIL_CONFIG_SSL_KEY_MAX_SIZE = int(
    os.getenv('EMAIL_CONFIG_SSL_KEY_MAX_SIZE', 20 * 1024)  # 20KB
)
EMAIL_CONFIG_SSL_CERT_MAX_SIZE = int(
    os.getenv('EMAIL_CONFIG_SSL_KEY_MAX_SIZE', 10 * 1024)  # 10KB
)

EMAIL_SERVER_DEFAULT_HOST = os.environ.get('EMAIL_SERVER_DEFAULT_HOST', None)
EMAIL_SERVER_DEFAULT_PORT = os.environ.get('EMAIL_SERVER_DEFAULT_PORT', None)
EMAIL_SERVER_DEFAULT_USERNAME = os.environ.get('EMAIL_SERVER_DEFAULT_USERNAME', None)
EMAIL_SERVER_DEFAULT_PASSWORD = os.environ.get('EMAIL_SERVER_DEFAULT_PASSWORD', None)
EMAIL_SERVER_DEFAULT_USE_TLS = os.environ.get('EMAIL_SERVER_DEFAULT_USE_TLS', '1') == '1'
EMAIL_SERVER_DEFAULT_USE_SSL = os.environ.get('EMAIL_SERVER_DEFAULT_USE_SSL', '0') == '1'
EMAIL_SERVER_DEFAULT_SSL_KEY = os.environ.get('EMAIL_SERVER_DEFAULT_SSL_KEY', None)
EMAIL_SERVER_DEFAULT_SSL_CERT = os.environ.get('EMAIL_SERVER_DEFAULT_SSL_CERT', None)
EMAIL_SERVER_DEFAULT_REPLY = os.environ.get('EMAIL_SERVER_DEFAULT_REPLY', None)
EMAIL_SERVER_DEFAULT_CC = json.loads(os.environ.get('EMAIL_SERVER_DEFAULT_CC', '[]'))
EMAIL_SERVER_DEFAULT_BCC = json.loads(os.environ.get('EMAIL_SERVER_DEFAULT_BCC', '[]'))

# option account user create
ENABLE_TURN_ON_IS_EMAIL = False
# -- option account user create

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'statics'),)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # other finders..
    'compressor.finders.CompressorFinder',
)

MEDIA_PREFIX_SITE = os.environ.get(
    'MEDIA_PREFIX_SITE',
    ''
)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
MEDIA_PROTOCOL = os.environ.get('MEDIA_PROTOCOL', 'http')
MEDIA_HOST = os.environ.get('MEDIA_HOST', '127.0.0.1')
MEDIA_PORT = os.environ.get('MEDIA_PORT', '8881')
MEDIA_SUFFIX = 'api'
MEDIA_DOMAIN = f'{MEDIA_PROTOCOL}://{MEDIA_HOST}:{MEDIA_PORT}/{(MEDIA_SUFFIX + "/") if MEDIA_SUFFIX else ""}'
MEDIA_ENABLED = False

# Media key and data private
MEDIA_KEY_FLAG = os.environ.get('MEDIA_KEY_FLAG', 'MEDIA-APIRequest')
MEDIA_KEY_SECRET_TOKEN_API = os.environ.get('MEDIA_KEY_SECRET_TOKEN_API', 'SECRET-KEY-APIRequest')
MEDIA_SECRET_TOKEN_API = os.environ.get('MEDIA_SECRET_TOKEN_API', 'bhVpajC75NCEPwGs')

# AWS S3
# https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html
# https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingBucket.html
#       AWS_S3_CUSTOM_DOMAIN = https://DOC-EXAMPLE-BUCKET.s3.us-west-2.amazonaws.com/photos/puppy.jpg
#       AWS_DEFAULT_ACL = https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#canned-acl
FILE_SIZE_COMPANY_LOGO = int(
    os.getenv('FILE_SIZE_COMPANY_LOGO', 1024 * 1024 * 3)  # 3MB
)
FILE_SIZE_COMPANY_ICON = int(
    os.getenv('FILE_SIZE_COMPANY_ICON', 1024 * 100)  # 100KB
)
FILE_SIZE_WEB_BUILDER = int(
    os.getenv('FILE_SIZE_UPLOAD_LIMIT', 5 * 1024 * 1024)  # 5MB
)
FILE_AVATAR_MAX_SIZE = 3 * 1024 * 1024  # 3MiB
FILE_SIZE_UPLOAD_LIMIT = int(
    os.getenv('FILE_SIZE_UPLOAD_LIMIT', 20 * 1024 * 1024)  # 20MB
)
FILE_SIZE_OF_EMPLOYEE_TOTAL = int(
    os.getenv('FILE_SIZE_OF_EMPLOYEE_TOTAL', 5 * 1024 * 1024 * 1024)  # defaults: 5 Gigabytes
)
FILE_STORAGE_EXPIRED = 60 * 5  # unit: seconds
FILE_ENABLE_MAGIC_CHECK = os.environ.get('FILE_ENABLE_MAGIC_CHECK', '0') in [1, '1']
USE_S3 = os.getenv('USE_S3', '0') == '1'
if USE_S3:
    # aws settings
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME')
    AWS_DEFAULT_ACL = None
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 60 * 5
    AWS_LOCATION = ''

    # update Storage expired
    FILE_STORAGE_EXPIRED = AWS_QUERYSTRING_EXPIRE

    # s3 static settings
    STATIC_LOCATION = 'static'
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{STATIC_LOCATION}/'
    STATICFILES_STORAGE = 'apps.core.attachments.storages.aws.storages_backend.StaticStorage'

    # s3 public media settings | apps.core.attachments.storages.aws.storages_backend.PublicMediaStorage
    PUBLIC_MEDIA_LOCATION = 'media/public'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{PUBLIC_MEDIA_LOCATION}/'
    DEFAULT_FILE_STORAGE = 'apps.core.attachments.storages.aws.storages_backend.PublicMediaStorage'

    # s3 private media settings | apps.core.attachments.storages.aws.storages_backend.PrivateMediaStorage
    PRIVATE_MEDIA_LOCATION = 'media/private'

else:
    STATIC_BASE_URL = STATIC_URL
    STATIC_LOCATION = STATIC_ROOT
    PUBLIC_MEDIA_BASE_URL = MEDIA_URL + 'public/'
    PUBLIC_MEDIA_LOCATION = os.path.join(MEDIA_ROOT, 'public')
    PRIVATE_MEDIA_BASE_URL = MEDIA_URL + 'private/'
    PRIVATE_MEDIA_LOCATION = os.path.join(MEDIA_ROOT, 'private')

FILE_WEB_BUILDER_RELATE_APP = 'SYS:WEB_BUILDER'
FILE_WEB_BUILDER_LIMIT_SIZE = int(
    os.getenv('FILE_WEB_BUILDER_LIMIT_SIZE', 2 * 1024 * 1024 * 1024)  # 5GB
)
# -- AWS S3

# Key return resp after call API
API_KEY_AUTH = 'Authorization'
API_PREFIX_TOKEN = 'Bearer'
API_KEY_RESPONSE_DATA = 'result'
API_KEY_RESPONSE_ERRORS = 'errors'
API_KEY_RESPONSE_STATUS = 'status'
API_KEY_RESPONSE_PAGE_SIZE = 'page_size'
API_KEY_RESPONSE_PAGE_COUNT = 'count'
API_KEY_RESPONSE_PAGE_NEXT = 'next'
API_KEY_RESPONSE_PAGE_PREVIOUS = 'previous'

UI_RESP_KEY_STATE = 'state'
UI_RESP_KEY_STATUS = 'status'
UI_RESP_KEY_RESULT = 'result'
UI_RESP_KEY_ERRORS = 'errors'
UI_RESP_KEY_PAGE_SIZE = 'page_size'
UI_RESP_KEY_PAGE_COUNT = 'page_count'
UI_RESP_KEY_PAGE_NEXT = 'page_next'
UI_RESP_KEY_PAGE_PREVIOUS = 'page_previous'

# DEBUG CODE enable: allow raise errors if it is enabled else return default value (value is correct type)
RAISE_EXCEPTION_DEBUG = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# test runner override | runner for command: python manage.py test
TEST_RUNNER = 'misapi.testrunner.CustomTestRunner'
TEST_ARGS = ['--keepdb']
DJANGO_TEST_ARGS = ['--keepdb']
# -- test runner override | runner for command: python manage.py test

# REST API & JWT
REST_FRAMEWORK = {
    'DEFAULT_METADATA_CLASS': None,
    'EXCEPTION_HANDLER': 'apps.shared.extends.exceptions.custom_exception_handler',
    'DEFAULT_PERMISSION_CLASSES': (
        # 'rest_framework.permissions.AllowAny',
        'apps.shared.extends.drf.AllowAnyDisableOptionsPermission',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        'apps.core.auths.authenticate.MyCustomJWTAuthenticate',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': ('rest_framework.parsers.JSONParser',),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'apps.shared.extends.pagination.CustomResultsSetPagination',
    'PAGE_SIZE': 50,
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',

    # rate limit && throttle
    'DEFAULT_THROTTLE_CLASSES': [
        'misapi.throttling.AuthThrottle',
        'misapi.throttling.AnonThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'auth': f"{os.environ.get('THROTTLE_AUTH', '200')}/minute",
        'anon': f"{os.environ.get('THROTTLE_ANON', '50')}/minute",
    }
}
if DEBUG is True:
    REST_FRAMEWORK['DEFAULT_METADATA_CLASS'] = 'rest_framework.metadata.SimpleMetadata'
CUSTOM_PAGE_MAXIMUM_SIZE = 1000

AUTH_USER_MODEL = 'account.User'

# Authenticate 2FA and JWT
PASSWORD_TOTP_2FA = os.environ.get('PASSWORD_TOTP_2FA', 'totp-2fa-L47*s2uFT+bw7!fpSJ@9J2aaaf^hFQrd')
LOGO_TOTP_2FA = os.environ.get(
    'LOGO_TOTP_2FA',
    'https://www.bflow.vn/images/brand/bflow-by-mts/png/bflow-by-mts-original.png'
)
ISSUER_TOTP_2FA = os.environ.get('ISSUER_TOTP_2FA', 'Bflow.vn')
LOCKED_OUT_FAILED_AMOUNT = int(os.environ.get('LOCKED_OUT_FAILED_AMOUNT', 5))
SYNC_2FA_ENABLED = os.environ.get('SYNC_2FA_ENABLED', '1') in [1, '1']
JWT_KEY_2FA_ENABLED = 'is_2fa_enabled'
JWT_KEY_2FA_VERIFIED = 'is_2fa_verified'
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': os.environ.get('JWT_SIGNING_KEY', 'HEk5@d&z7Kvq)GFp32SKdumR4h2E@H@D'),
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'AUTH_HEADER_NAME_REFRESH_TOKEN': 'HTTP_AUTHORIZATION_REFRESH',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(hours=12),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
}
# -- REST API & JWT

# page API documentations
SHOW_API_DOCS = False
HEADER_MINIMAL_CODE = 'SuaD2m'
HEADER_SKIP_AUTH_CODE = 'Wl46tj'
SWAGGER_SETTINGS = {
    'LOGIN_URL': '/',
    'LOGOUT_URL': '/logout',
    'DEFAULT_MODEL_DEPTH': -1,
    'USE_SESSION_AUTH': False,
    'SHOW_COMMON_EXTENSIONS': False,
    'SECURITY_DEFINITIONS': {
        'Bearer': {'type': 'apiKey', 'name': 'Authorization', 'in': 'header'},
        f'Provisioning: {PROVISIONING_ACCESS_VALUE}': {
            'type': 'apiKey',
            'name': 'PROVISION',
            'in': 'header',
        },
        f'Minimal: {HEADER_MINIMAL_CODE}': {
            'type': 'apiKey',
            'name': 'DATAISMINIMAL',
            'in': 'header',
        },
        f'SKIP AUTH: {HEADER_SKIP_AUTH_CODE}': {
            'type': 'apiKey',
            'name': 'DATAISSKIPAUTH',
            'in': 'header',
        },
        f'Dropdown List: "true"': {
            'type': 'apiKey',
            'name': 'DATAISDD',
            'in': 'header',
        },
    },
    'SUPPORTED_SUBMIT_METHODS': ['get', 'post', 'put', 'delete', 'patch'],
    'APIS_SORTER': 'alpha',
    'OPERATIONS_SORTER': 'alpha',
    'DOC_EXPANSION': 'none',
    'CSS_OVERRIDE': '/statics/swagger-dark.css',  # Thêm đường dẫn đến file CSS tùy chỉnh
}
SWAGGER_URL = 'http://127.0.0.1:8000/api'
FORCE_SCRIPT_NAME = None  # SWAGGER_URL.replace('/api', '')
# -- page API documentations

# Cache
CACHE_ENABLED = False
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}
CACHE_KEY_PREFIX = 'MiS'
CACHE_EXPIRES_DEFAULT = 15 * 60  # 15 minutes
# -- Cache

# CELERY + RABBITMQ CONFIG
CELERY_BROKER_URL = None  # 'amqp://guest:guest@127.0.0.1:5672//'
CELERY_TASK_ALWAYS_EAGER = True  # allow executable task real-time (True) or push task to queue (False)
CELERY_RESULT_EXTENDED = True

# CELERY BEAT
CELERY_ENABLE_UTC = False
CELERY_TIMEZONE = 'Asia/Ho_Chi_Minh'
DJANGO_CELERY_BEAT_TZ_AWARE = False

# -- CELERY + RABBITMQ CONFIG

# import local_settings
try:
    from .local_settings import *
except ImportError:
    pass

# -- import local_settings

# Logging
if os.environ.get('ENABLE_LOGGING', False) in [1, '1']:
    LOG_DIR = os.path.join(BASE_DIR, "logs")
    if not os.path.exists(LOG_DIR):
        os.makedirs(LOG_DIR)
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
                "datefmt": "%d/%b/%Y-%H:%M:%S",
            },
            "celery_formatter": {
                "format": "%(asctime)s %(levelname)s module=%(module)s, process_id=%(process)d, %(message)s",
            }
        },
        "handlers": {
            "file": {
                "level": "INFO",
                "class": "logging.handlers.TimedRotatingFileHandler",
                "filename": os.path.join(LOG_DIR, "api.log"),
                "when": "D",
                "interval": 1,
                "backupCount": 5,
                "formatter": "verbose",
            },
            "celery_handler": {
                "level": "INFO",
                "class": "logging.handlers.TimedRotatingFileHandler",
                "filename": os.path.join(LOG_DIR, "celery.log"),
                "when": "D",
                "interval": 1,
                "backupCount": 5,
                "formatter": "celery_formatter",
            },
        },
        "loggers": {
            "": {
                "handlers": ["file"],
                "level": "INFO",
            },
            "celery": {
                "handlers": ["celery_handler"],
                "level": "INFO",
                "propagate": True
            },
        },
    }
# -- Logging

# PROD configurations
ENABLE_PROD = True if os.environ.get('ENABLE_PROD', '0') in [1, '1'] else False
if ENABLE_PROD is True:
    # allow host
    OS_ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '[]')
    ALLOWED_HOSTS = json.loads(OS_ALLOWED_HOSTS)

    # set up celery prod
    CELERY_RESULT_SERIALIZER = 'json'
    CELERY_ACCEPT_CONTENT = ['json']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_BACKEND = 'django-db'
    CELERY_TASK_ALWAYS_EAGER = True if os.environ.get('CELERY_TASK_ALWAYS_EAGER', 0) in [1, '1'] else False
    CELERY_BROKER_VHOST = os.environ.get('MSG_QUEUE_BROKER_VHOST', '/')
    MSG_QUEUE_HOST = os.environ.get("MSG_QUEUE_HOST")  # '127.0.0.1' or host_name
    MSG_QUEUE_PORT = os.environ.get("MSG_QUEUE_PORT")  # default '5672'
    MSG_QUEUE_USER = os.environ.get("MSG_QUEUE_USER")  # default 'rabbitmq_user'
    MSG_QUEUE_PASSWORD = os.environ.get("MSG_QUEUE_PASSWORD")  # default 'rabbitmq_password'
    if MSG_QUEUE_HOST and MSG_QUEUE_PORT:
        CELERY_BROKER_URL = f'amqp://{MSG_QUEUE_USER}:{MSG_QUEUE_PASSWORD}@{MSG_QUEUE_HOST}:{MSG_QUEUE_PORT}'
    else:
        raise ValueError('CELERY CONFIG must be required HOST & PORT.')

    # setup database default prod
    DATABASES.update(
        {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': os.environ.get('DB_NAME'),
                'USER': os.environ.get('DB_USER'),
                'PASSWORD': os.environ.get('DB_PASSWORD'),
                'HOST': os.environ.get('DB_HOST'),
                'PORT': os.environ.get('DB_PORT'),
                'OPTIONS': {
                    'charset': 'utf8mb4',
                },
                'CONN_MAX_AGE': 600,  # 60 * 10
            }
        }
    )

    # API Documentations
    SHOW_API_DOCS = os.environ.get('SHOW_API_DOCS', False)

    # media domain
    MEDIA_DOMAIN = os.environ.get('MEDIA_DOMAIN', MEDIA_DOMAIN)
    MEDIA_ENABLED = True if os.environ.get('MEDIA_ENABLED', '0') in [1, '1'] else False

    # caching
    CACHE_ENABLED = True if os.environ.get("CACHE_ENABLED", '0') in [1, '1'] else False
    if CACHE_ENABLED is True:
        CACHE_KEY_PREFIX = os.environ.get('CACHE_KEY_PREFIX', CACHE_KEY_PREFIX)
        CACHE_HOST = os.environ.get('CACHE_HOST', '127.0.0.1')
        CACHE_PORT = os.environ.get('CACHE_PORT', '11211')
        CACHE_OPTION = json.loads(os.environ.get('CACHE_OPTION', '{}'))
        CACHE_EXPIRES_DEFAULT = int(os.environ.get('CACHE_EXPIRES_DEFAULT', CACHE_EXPIRES_DEFAULT))
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache',
                'LOCATION': f'{CACHE_HOST}:{CACHE_PORT}',
                'OPTIONS': {
                    # 'TIMEOUT': 60 * 15,  # default 5 minutes, current 15 minutes
                    # 'MAX_ENTRIES': 300,  # default 300, current 300
                    # 'KEY_PREFIX': CACHE_KEY_PREFIX,
                    # 'KEY_FUNCTION': 'apps.shared.extends.caching.make_key_global',
                    # **CACHE_OPTION,  # relate to: https://docs.djangoproject.com/en/4.2/topics/cache/#cache-arguments
                }
            }
        }

# -- PROD configurations

# Tracing
JAEGER_TRACING_ENABLE = os.environ.get('ENABLE_TRACING', False) in [1, '1']
if JAEGER_TRACING_ENABLE is True:
    JAEGER_TRACING_HOST = os.environ.get('JAEGER_TRACING_HOST', 'jaeger_global')
    JAEGER_TRACING_PORT = os.environ.get('JAEGER_TRACING_PORT', 6831)
    JAEGER_TRACING_PROJECT_NAME = os.environ.get('JAEGER_TRACING_PROJECT_NAME', 'MiS API')
    JAEGER_TRACING_EXCLUDE_LOG_PATH = '/__'
# -- Tracing

# debug permit working
SHOW_SYSTEM_DATA = True if os.environ.get('SHOW_SYSTEM_DATA', '0') in [1, '1'] else False
SHOW_TESTCASE_NAME = True if os.environ.get('SHOW_TESTCASE_NAME', '0') in [1, '1'] else False
DEBUG_PERMIT = True if os.environ.get('DEBUG_PERMIT', '0') in [1, '1'] else False
DEBUG_BG_TASK = True if os.environ.get('DEBUG_BG_TASK', '0') in [1, '1'] else False

# mongodb
MONGO_HOST = os.environ.get('MONGO_HOST', '127.0.0.1')
MONGO_PORT = int(os.environ.get('MONGO_PORT', 27017))
MONGO_DB_NAME = os.environ.get('MONGO_DB_NAME', 'bflow')
MONGO_USERNAME = os.environ.get('MONGO_USERNAME', '')
MONGO_PASSWORD = os.environ.get('MONGO_PASSWORD', '')

# CI Database
DB_SQLITE_MOCKUP = os.path.isfile(os.path.join(BASE_DIR, '.gitlab-ci-db.sqlite3'))
CICD_ENABLED__USE_DB_MOCKUP = os.environ.get('CICD_ENABLED__USE_DB_MOCKUP', '0') in ["1", 1]
if CICD_ENABLED__USE_DB_MOCKUP is True and DB_SQLITE_MOCKUP is True:
    # change file db of sqlite3 from default to file sqlite3
    # DATABASES['default'] = DATABASES['mockup_db_ci']
    DATABASES.update(
        {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': os.environ.get('DB_NAME'),
                'USER': os.environ.get('DB_USER'),
                'PASSWORD': os.environ.get('DB_PASSWORD'),
                'HOST': os.environ.get('DB_HOST'),
                'PORT': os.environ.get('DB_PORT'),
                'OPTIONS': {
                    'charset': 'utf8mb4',
                },
                "TEST": {
                    "NAME": os.environ.get('DB_NAME'),
                },
            }
        }
    )


# Display config about DB, Cache, CELERY,...
def display_wraptext(text, length=80):
    return "\n |  ".join(textwrap.wrap(text, length))


# Firebase
FIREBASE_FILE_CONFIG = os.path.join(BASE_DIR, 'serviceAccountKey.json')
FIREBASE_ENABLE = os.path.isfile(FIREBASE_FILE_CONFIG)
if FIREBASE_ENABLE is True:
    cred = credentials.Certificate(FIREBASE_FILE_CONFIG)
    firebase_admin.initialize_app(cred)


DEBUG = os.environ.get('DEBUG', '1') in [1, '1']
if DEBUG is True:
    # debug toolbar IP Internal
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS = [ip[: ip.rfind(".")] + ".1" for ip in ips] + ["127.0.0.1", "10.0.2.2"]

    # print(Fore.CYAN, '### SETTINGS CONFIG VERBOSE ----------------------------------------------------#', '\033[0m')
    # print(Fore.BLUE, display_wraptext(f'#  1. DATABASES: {DATABASES}'), '\033[0m')
    # print(Fore.YELLOW, display_wraptext(f'#  2. CELERY_BROKER_URL: {str(CELERY_BROKER_URL)}'), '\033[0m')
    # print(Fore.GREEN, display_wraptext(f'#  3. CELERY_TASK_ALWAYS_EAGER: {str(CELERY_TASK_ALWAYS_EAGER)}'), '\033[0m')
    # print(Fore.RED, display_wraptext(f'#  4. ALLOWED_HOSTS: {str(ALLOWED_HOSTS)}'), '\033[0m')
    # print(Fore.LIGHTBLUE_EX, display_wraptext(f'#  5. TRACING [JAEGER]: {JAEGER_TRACING_ENABLE}'), '\033[0m')
    # print(Fore.LIGHTMAGENTA_EX, display_wraptext(f'#  6. CACHE [MEMCACHED]: {CACHE_ENABLED}'), '\033[0m')
    # print(Fore.CYAN, '--------------------------------------------------------------------------------#', '\033[0m')
# -- Display config about DB, Cache, CELERY,...

print(Fore.BLUE, f'#  DATABASES: {DATABASES["default"]["NAME"]}', '\033[0m')
