# Generated by Django 4.1.3 on 2023-04-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='space',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='space',
            name='user_modified',
        ),
    ]
