# Generated by Django 4.1.3 on 2023-03-10 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_space_is_active_space_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='space',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='space',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='space',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='space',
            name='user_modified',
        ),
    ]
