# Generated by Django 4.1.3 on 2023-11-23 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_initial'),
        ('acceptance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalacceptanceindicator',
            name='delivery_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fa_indicator_delivery_sub', to='delivery.orderdeliverysub', verbose_name='delivery sub'),
        ),
    ]
