# Generated by Django 4.1.3 on 2023-11-27 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_quotationindicatorconfig_acceptance_affect_by_and_more'),
        ('acceptance', '0002_finalacceptanceindicator_delivery_sub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalacceptanceindicator',
            old_name='is_sale_order',
            new_name='is_plan',
        ),
        migrations.AddField(
            model_name='finalacceptanceindicator',
            name='indicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fa_indicator_indicator', to='quotation.quotationindicatorconfig', verbose_name='indicator'),
        ),
    ]
