# Generated by Django 4.1.3 on 2023-11-28 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0003_product_is_public_website_product_price_list_and_more'),
        ('acceptance', '0003_rename_is_sale_order_finalacceptanceindicator_is_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalacceptanceindicator',
            name='labor_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fa_indicator_labor_item', to='saledata.expense', verbose_name='labor item'),
        ),
    ]
