# Generated by Django 4.1.3 on 2023-12-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0004_finalacceptanceindicator_labor_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalacceptanceindicator',
            name='actual_value_after_tax',
            field=models.FloatField(default=0),
        ),
    ]
