# Generated by Django 4.2.8 on 2024-01-03 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_avatar_img'),
        ('acceptance', '0005_finalacceptanceindicator_actual_value_after_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalacceptance',
            name='next_node_collab',
            field=models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee'),
        ),
    ]
