# Generated by Django 4.2.8 on 2024-05-17 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arinvoice', '0006_arinvoice_document_change_order_and_more'),
        ('acceptance', '0008_finalacceptance_document_change_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalacceptanceindicator',
            name='is_delivery',
        ),
        migrations.RemoveField(
            model_name='finalacceptanceindicator',
            name='is_indicator',
        ),
        migrations.RemoveField(
            model_name='finalacceptanceindicator',
            name='is_payment',
        ),
        migrations.RemoveField(
            model_name='finalacceptanceindicator',
            name='is_plan',
        ),
        migrations.AddField(
            model_name='finalacceptanceindicator',
            name='acceptance_affect_by',
            field=models.SmallIntegerField(default=1, help_text="choices= ((1, 'None'), (2, 'Plan value'), (3, 'Delivery'), (4, 'Payment'), (5, 'Invoice'), (6, 'Project'))"),
        ),
        migrations.AddField(
            model_name='finalacceptanceindicator',
            name='ar_invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fa_indicator_ar_invoice', to='arinvoice.arinvoice', verbose_name='ar invoice'),
        ),
    ]
