# Generated by Django 4.2.8 on 2024-12-25 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0028_saleorderpaymentstage_date_type_and_more'),
        ('leaseorder', '0002_leaseorderpaymentstage_date_type_and_more'),
        ('acceptance', '0013_finalacceptance_process_stage_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalacceptance',
            name='lease_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_acceptance_lease_order', to='leaseorder.leaseorder', verbose_name='lease order'),
        ),
        migrations.AddField(
            model_name='finalacceptanceindicator',
            name='lease_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fa_indicator_lease_order', to='leaseorder.leaseorder', verbose_name='lease order'),
        ),
        migrations.AddField(
            model_name='finalacceptanceindicator',
            name='lease_order_indicator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='leaseorder.leaseorderindicator'),
        ),
        migrations.AlterField(
            model_name='finalacceptance',
            name='sale_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_acceptance_sale_order', to='saleorder.saleorder', verbose_name='sale order'),
        ),
    ]
