# Generated by Django 4.2.8 on 2023-12-21 15:51

import apps.core.attachments.models
import apps.core.attachments.storages.aws.storages_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='media_file_id',
        ),
        migrations.AddField(
            model_name='files',
            name='belong_to',
            field=models.SmallIntegerField(choices=[(0, 'Self'), (1, 'Company')], default=0),
        ),
        migrations.AddField(
            model_name='files',
            name='file',
            field=models.FileField(default=None, storage=apps.core.attachments.storages.aws.storages_backend.PrivateMediaStorage, upload_to=apps.core.attachments.models.generate_path_file),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='files',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='relate_app_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='relate_doc_id',
            field=models.UUIDField(null=True),
        ),
    ]
