# Generated by Django 4.2.8 on 2023-12-27 14:23

import apps.core.attachments.models
import django.core.files.storage.filesystem
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_avatar_img'),
        ('tenant', '0001_initial'),
        ('company', '0006_company_logo'),
        ('attachments', '0003_remove_files_media_file_id_files_belong_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='belong_to',
        ),
        migrations.CreateModel(
            name='PublicFiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('file_name', models.TextField()),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('file', models.FileField(storage=django.core.files.storage.filesystem.FileSystemStorage, upload_to=apps.core.attachments.models.generate_path_file)),
                ('remarks', models.TextField(blank=True)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Public Files',
                'verbose_name_plural': 'Public Files',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
