# Generated by Django 4.2.8 on 2025-06-09 21:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_email_app_password_and_more'),
        ('base', '0018_applicationproperty_is_filter_condition'),
        ('attachments', '0009_alter_files_file_type_alter_publicfiles_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.application'),
        ),
        migrations.CreateModel(
            name='FolderPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_or_group', models.BooleanField(default=False, verbose_name='type of recipient')),
                ('exp_date', models.DateTimeField(null=True)),
                ('capability_list', models.JSONField(default=list, help_text='[[1, "Preview"], [2, "Viewer"], [3, "Editor"], [4, "Custom"]]')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('employee_list', models.JSONField(default=dict, help_text='{"uuid": {"id": "uuid", "full_name": "Nguyen Van A", "group": {}}}')),
                ('group_list', models.JSONField(default=dict, help_text='{"uuid": {"id": "uuid", "title": "Group A", "parent_n": "uuid"}}')),
                ('folder_perm_list', models.JSONField(default=list, help_text='[[1, "See"], [2, "Upload"], [3, "Download"], [4, "Create subfolders"], [5, "Delete"], [6, "Share"]]', null=True)),
                ('file_in_perm_list', models.JSONField(default=list, help_text='[[1, "Review"], [2, "Download"], [3, "Edit file attributes"], [4, "Share"], [5, "Upload version"], [6, "Duplicate"], [6, "Edit file"]]', null=True)),
                ('is_apply_sub', models.BooleanField(default=False)),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_permission_folder', to='attachments.folder', verbose_name='folder permission')),
            ],
            options={
                'verbose_name': 'Folder Permission',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FilePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_or_group', models.BooleanField(default=False, verbose_name='type of recipient')),
                ('exp_date', models.DateTimeField(null=True)),
                ('capability_list', models.JSONField(default=list, help_text='[[1, "Preview"], [2, "Viewer"], [3, "Editor"], [4, "Custom"]]')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('employee_list', models.JSONField(default=dict, help_text='{"uuid": {"id":"uuid", "full_name": "Nguyen Van A", "group": {}}}')),
                ('group_list', models.JSONField(default=dict, help_text='{"uuid": {"id":"uuid", "title": "Group A", "parent_n": "uuid"}}')),
                ('file_perm_list', models.JSONField(default=list, help_text='[[1, "Review"], [2, "Download"], [3, "Edit file attributes"], [4, "Share"], [5, "Upload version"], [6, "Duplicate"], [6, "Edit file"]]', null=True)),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_permission_file', to='attachments.files', verbose_name='file permission')),
            ],
            options={
                'verbose_name': 'File Permission',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
