# Generated by Django 4.2.8 on 2025-09-25 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentapproval', '0001_initial'),
        ('attachments', '0012_alter_filepermission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='content_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_content_group', to='documentapproval.kmscontentgroup'),
        ),
        migrations.AddField(
            model_name='files',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_document_type', to='documentapproval.kmsdocumenttype'),
        ),
        migrations.AddField(
            model_name='publicfiles',
            name='content_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_content_group', to='documentapproval.kmscontentgroup'),
        ),
        migrations.AddField(
            model_name='publicfiles',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_document_type', to='documentapproval.kmsdocumenttype'),
        ),
    ]
