# Generated by Django 4.2.8 on 2025-09-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0013_files_content_group_files_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='doc_code',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
