# Generated by Django 4.2.8 on 2025-09-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0014_folder_doc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='doc_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
