# Generated by Django 4.2.8 on 2025-10-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0016_folder_doc_id_alter_files_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='module_id',
            field=models.UUIDField(null=True, verbose_name='module_id in MODULE_MAPPING, unique in tenant-company'),
        ),
    ]
