# Generated by Django 4.2.8 on 2025-10-08 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0080_alter_periods_default_inventory_value_method_and_more'),
        ('servicequotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicequotationservicedetail',
            name='service_percent',
            field=models.FloatField(default=0, help_text='Weighting factor for service detail'),
        ),
        migrations.AddField(
            model_name='servicequotationworkordercost',
            name='expense_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_quotation_work_order_costs', to='saledata.expenseitem'),
        ),
    ]
