# Generated by Django 4.2.8 on 2025-10-17 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0083_remove_product_avatar_and_more'),
        ('servicequotation', '0002_servicequotationservicedetail_service_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicequotationservicedetail',
            name='attributes_total_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='servicequotationservicedetail',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_quotation_service_details', to='saledata.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='servicequotationservicedetail',
            name='duration_unit_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='servicequotationservicedetail',
            name='duration_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicequotationservicedetail',
            name='product_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='servicequotationservicedetail',
            name='selected_attributes',
            field=models.JSONField(default=dict),
        ),
    ]
