# Generated by Django 4.2.8 on 2024-07-18 09:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_collabinworkflow_is_edit_all_zone_and_more'),
        ('hr', '0003_alter_group_unique_together_and_more'),
        ('company', '0010_rename_cost_per_lot_batch_companyconfig_cost_per_lot_and_more'),
        ('process', '0001_initial'),
        ('tenant', '0001_initial'),
        ('saledata', '0029_warehouseshelf'),
        ('space', '0001_initial'),
        ('project', '0004_projectworks_expense_data_workmapexpense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workmapexpense',
            options={'default_permissions': (), 'ordering': ('-date_created',), 'permissions': (), 'verbose_name': 'Work map expense', 'verbose_name_plural': 'Work map expense'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_owner_data',
        ),
        migrations.AddField(
            model_name='project',
            name='prj_sub_tax_price',
            field=models.FloatField(default=0, help_text='Total price tax of project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='prj_sub_total',
            field=models.FloatField(default=0, help_text='Total price of project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='prj_sub_total_after_tax',
            field=models.FloatField(default=0, help_text='Total price after tax', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_pm',
            field=models.ForeignKey(help_text='Representative of project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_project_pm', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_pm_data',
            field=models.JSONField(default=dict, help_text='[{"id": "", "full_name": "", "code": ""}]', verbose_name='Employee PM info backup'),
        ),
        migrations.AlterField(
            model_name='workmapexpense',
            name='tax',
            field=models.ForeignKey(help_text='Tax per record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tax', to='saledata.tax', verbose_name='Tax'),
        ),
        migrations.CreateModel(
            name='ProjectBaseline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('is_change', models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents')),
                ('document_root_id', models.UUIDField(help_text='this is id of root document of the changed documents', null=True)),
                ('document_change_order', models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('project_data', models.JSONField(default=list, help_text='{"id": "ce0c0422-ffb8-4891-aaf7-c54bc7f17d9a", "title": "Kietht edit and update", "code": "PJ008", "start_date": "2024-07-23 00:00:00", "finish_date": "2024-07-27 00:00:00", "completion_rate": 0, "project_pm": {"id": "ddbaf4ba-1f1a-487f-a37d-b6847c1bf901", "code": "EMP14", "full_name": "Hu\\u1ef3nh Tu\\u1ea5n Ki\\u1ec7t"}, "employee_inherit": {"id": "8b930c65-2794-4904-89db-e7b992f49554", "code": "EMP0004", "full_name": "H\\u1ed3 V\\u00e2n Qu\\u1ef3nh"}, "system_status": 1, "works": [{"id": "587fc1fb-df7f-4694-883b-4f330ebecb09", "title": "C\\u00f4ng vi\\u1ec7c 01", "work_status": 0, "date_from": "2024-07-02T00:00:00", "date_end": "2024-07-07T00:00:00", "order": 1, "group": "", "relationships_type": null, "dependencies_parent": "", "progress": 0, "weight": 10, "expense_data": {"tax": 100, "price": 1000, "total_after_tax": 1100}}], "groups": [], "members": [{"id": "ddbaf4ba-1f1a-487f-a37d-b6847c1bf901", "first_name": "Ki\\u1ec7t", "last_name": "Hu\\u1ef3nh Tu\\u1ea5n", "full_name": "Hu\\u1ef3nh Tu\\u1ea5n Ki\\u1ec7t", "email": "ldhoa2002@gmail.com", "avatar": null, "is_active": true}], "workflow_runtime_id": null, "is_change": false, "document_root_id": null, "document_change_order": null, "status": 200}', verbose_name='Project data')),
                ('member_data', models.JSONField(default=list, help_text='[{"id": "ef3ab1bb-e699-4250-ac6d-aefacb77385e", "date_modified": "2024-07-01 09:54:39", "permit_view_this_project": true, "permit_add_member": true, "permit_add_gaw": true, "permission_by_configured": [{"id": "0031870a-db7d-4deb-bba6-a9ea8b713a0c", "edit": true, "view": true, "range": "1", "space": "0", "app_id": "e66cfb5a-b3ce-4694-a4da-47618f53de4c", "create": true, "delete": true}], "status": 200}]', verbose_name='Member data list')),
                ('member_perm_data', models.JSONField(default=list, help_text='{"ef3ab1bb-e699-4250-ac6d-aefacb77385e": [{"id": "ef3ab1bb-e699-4250-ac6d-aefacb77385e", "date_modified": "2024-07-01 09:54:39", "permit_view_this_project": true, "permit_add_member": true, "permit_add_gaw": true, "permission_by_configured": [{"id": "0031870a-db7d-4deb-bba6-a9ea8b713a0c", "edit": true, "view": true, "range": "1", "space": "0", "app_id": "e66cfb5a-b3ce-4694-a4da-47618f53de4c", "create": true, "delete": true}]}]}', verbose_name='Employee perm data list')),
                ('work_task_data', models.JSONField(default=list, help_text='[{"id": "", "task": {"id": "", "title": "lorem ipsum", "code": "XX0X"}, "work": {"id": "", "title": "lorem ipsum", "code": "XX0X"}, "percent": 0, "assignee": {"id": "", "full_name": "Nguyen van A"}, "work_before": {"id": "", "title": "lorem ipsum", "code": "XX0X"}}]', verbose_name='Work task list')),
                ('work_expense_data', models.JSONField(default=list, help_text='[{"id": "29801e4c-225b-44a7-b739-a69f84ecc49e", "title": "lorem ipsum dolor sit amet", "expense_name": {}, "expense_item": {"id": "90357742-baa9-4a17-a20a-ace15483e111", "title": "Chi ph\\u00ed nh\\u00e2n c\\u00f4ng ph\\u00e1t tri\\u1ec3n PM"}, "uom": {"id": "a16e3b9e-2f4a-442e-bc54-b6ec18569d3c", "title": "Second"}, "quantity": 1, "expense_price": 1000, "tax": {"id": "12628b53-7248-4f3b-9ec1-19590a41ecff", "title": "VAT10%", "rate": 10}, "sub_total": 1000, "sub_total_after_tax": 1100, "is_labor": false}]')),
                ('baseline_version', models.IntegerField(default=1)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('current_stage', models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('next_node_collab', models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee')),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
                ('project_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_project_related', to='project.project')),
                ('space', models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('workflow_runtime', models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc')),
            ],
            options={
                'verbose_name': 'Project baseline',
                'verbose_name_plural': 'Project baseline',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
