# Generated by Django 4.2.8 on 2024-07-22 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_workmapexpense_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmapgroup',
            options={'default_permissions': (), 'ordering': ('-date_created',), 'permissions': (), 'verbose_name': 'Project map group', 'verbose_name_plural': 'Project map groups'},
        ),
    ]
