# Generated by Django 4.2.8 on 2024-07-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_projectmapgroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbaseline',
            name='member_perm_data',
            field=models.JSONField(default=dict, help_text='{"ef3ab1bb-e699-4250-ac6d-aefacb77385e": [{"id": "ef3ab1bb-e699-4250-ac6d-aefacb77385e", "date_modified": "2024-07-01 09:54:39", "permit_view_this_project": true, "permit_add_member": true, "permit_add_gaw": true, "permission_by_configured": [{"id": "0031870a-db7d-4deb-bba6-a9ea8b713a0c", "edit": true, "view": true, "range": "1", "space": "0", "app_id": "e66cfb5a-b3ce-4694-a4da-47618f53de4c", "create": true, "delete": true}]}]}', verbose_name='Employee perm data list'),
        ),
        migrations.AlterField(
            model_name='projectbaseline',
            name='project_data',
            field=models.JSONField(default=dict, help_text='{"id": "ce0c0422-ffb8-4891-aaf7-c54bc7f17d9a", "title": "Kietht edit and update", "code": "PJ008", "start_date": "2024-07-23 00:00:00", "finish_date": "2024-07-27 00:00:00", "completion_rate": 0, "project_pm": {"id": "ddbaf4ba-1f1a-487f-a37d-b6847c1bf901", "code": "EMP14", "full_name": "Hu\\u1ef3nh Tu\\u1ea5n Ki\\u1ec7t"}, "employee_inherit": {"id": "8b930c65-2794-4904-89db-e7b992f49554", "code": "EMP0004", "full_name": "H\\u1ed3 V\\u00e2n Qu\\u1ef3nh"}, "system_status": 1, "works": [{"id": "587fc1fb-df7f-4694-883b-4f330ebecb09", "title": "C\\u00f4ng vi\\u1ec7c 01", "work_status": 0, "date_from": "2024-07-02T00:00:00", "date_end": "2024-07-07T00:00:00", "order": 1, "group": "", "relationships_type": null, "dependencies_parent": "", "progress": 0, "weight": 10, "expense_data": {"tax": 100, "price": 1000, "total_after_tax": 1100}}], "groups": [], "members": [{"id": "ddbaf4ba-1f1a-487f-a37d-b6847c1bf901", "first_name": "Ki\\u1ec7t", "last_name": "Hu\\u1ef3nh Tu\\u1ea5n", "full_name": "Hu\\u1ef3nh Tu\\u1ea5n Ki\\u1ec7t", "email": "ldhoa2002@gmail.com", "avatar": null, "is_active": true}], "workflow_runtime_id": null, "is_change": false, "document_root_id": null, "document_change_order": null, "status": 200}', verbose_name='Project data'),
        ),
    ]
