# Generated by Django 4.2.8 on 2024-08-02 17:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('company', '0011_remove_company_email_app_password_and_more'),
        ('project', '0008_alter_projectmaptasks_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completion_rate',
            field=models.FloatField(default=0, null=True, verbose_name='Complete rate'),
        ),
        migrations.AlterField(
            model_name='projectworks',
            name='work_dependencies_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_parent', to='project.projectworks', verbose_name='parent work'),
        ),
        migrations.AlterField(
            model_name='projectworks',
            name='work_dependencies_type',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Start to start'), (1, 'Finish to start')], null=True),
        ),
        migrations.CreateModel(
            name='ProjectConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('person_can_end', models.JSONField(default=dict, null=True, verbose_name='list of employee can complete project')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_company', to='company.company')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Project config',
                'verbose_name_plural': 'Project config of company',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
