# Generated by Django 4.2.8 on 2024-08-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_completion_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.SmallIntegerField(default=1, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))"),
        ),
    ]
