# Generated by Django 4.2.8 on 2024-08-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_groupmapwork_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='prev_status',
            field=models.SmallIntegerField(default=1, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))"),
        ),
    ]
