# Generated by Django 4.2.8 on 2024-09-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_projectworks_bom_data_workmapbom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmapexpense',
            name='is_service',
            field=models.BooleanField(default=False, help_text='flag to know this record reference to bom service'),
        ),
    ]
