# Generated by Django 4.2.8 on 2024-10-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_alter_association_date_modified_and_more'),
        ('project', '0016_alter_projectnewscomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmapwork',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
        migrations.AddField(
            model_name='project',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
        migrations.AddField(
            model_name='projectbaseline',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
        migrations.AddField(
            model_name='projectgroups',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
        migrations.AddField(
            model_name='projectmapgroup',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
        migrations.AddField(
            model_name='projectmapwork',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
        migrations.AddField(
            model_name='projectworks',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
        migrations.AddField(
            model_name='workmapexpense',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
        migrations.AddField(
            model_name='workmaptask',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
    ]
