# Generated by Django 4.2.8 on 2024-10-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_groupmapwork_next_association_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_close',
            field=models.DateField(blank=True, null=True, verbose_name='Close date'),
        ),
    ]
