# Generated by Django 4.2.8 on 2024-06-18 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0009_company_software_start_using_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant', '0001_initial'),
        ('hr', '0003_alter_group_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True, verbose_name='Remark of form, showing after form name')),
                ('label_placement', models.CharField(choices=[('top', 'TOP'), ('left', 'LEFT'), ('right', 'RIGHT')], max_length=10)),
                ('instruction_placement', models.CharField(choices=[('top', 'TOP'), ('bottom', 'BOTTOM')], max_length=10)),
                ('authentication_required', models.BooleanField(default=False)),
                ('submit_only_one', models.BooleanField(default=False)),
                ('edit_submitted', models.BooleanField(default=False)),
                ('entries_default_show', models.JSONField(default=dict, help_text='The default display of Referrer Name in entries')),
                ('configs_order', models.JSONField(default=list, help_text='[idx1, idx2]', verbose_name='Order of idx config')),
                ('configs', models.JSONField(default=dict, help_text='[{"type": "form-title", ...}, {...},]', verbose_name='Config row with type (dict in list)')),
                ('theme_selected', models.CharField(blank=True, help_text='Code theme apply for form', max_length=50, null=True)),
                ('theme_assets', models.JSONField(default=dict, help_text='{"js": [], "css": []}', verbose_name='Asset include of theme')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Form',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FormPublished',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_delete', models.BooleanField(default=False)),
                ('date_publish_start', models.DateField(default=django.utils.timezone.now, help_text='Set activation date and time')),
                ('date_publish_finish', models.DateField(help_text='Set deactivation date and time', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='With active, start and finish will be apply. With deactivate, the access was deny.')),
                ('html_text', models.TextField(blank=True, help_text='This is HTML text that config was generated')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_iframe', models.BooleanField(default=False)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_published', to='forms.form')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Published Forms',
                'verbose_name_plural': 'Published Forms',
                'ordering': ('-is_active', '-date_publish_finish'),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FormPublishedEntries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('body_data', models.JSONField(default=dict, help_text='Data of client was submit', verbose_name='Data submit')),
                ('ref_name', models.TextField(blank=True, help_text='Track referrals in parameter', null=True, verbose_name='Reference Name')),
                ('meta_data', models.JSONField(default=dict, help_text='Collect same data of request: PATH, PATH_INFO, METHOD, ENCODING, CONTENT_TYPE, CONTENT_PARAMS', verbose_name='Request Headers')),
                ('unique_data', models.JSONField(default=dict, help_text='Key-value of unique field', verbose_name='Unique Data')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('published', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formpublished', verbose_name='Record belong to Published')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('user_created', models.ForeignKey(help_text='User created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_user_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Published Entries',
                'verbose_name_plural': 'Form Published Entries',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
