# Generated by Django 4.2.8 on 2024-08-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_formpublishauthenticateemail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpublishauthenticateemail',
            name='cookies',
        ),
        migrations.RemoveField(
            model_name='formpublishauthenticateemail',
            name='cookies_expires',
        ),
        migrations.RemoveField(
            model_name='formpublishauthenticateemail',
            name='opt_expires',
        ),
        migrations.AddField(
            model_name='form',
            name='authentication_type',
            field=models.CharField(choices=[('system', "Company's member"), ('email', 'Email')], default='system', max_length=10),
        ),
        migrations.AddField(
            model_name='formpublishauthenticateemail',
            name='expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='formpublishauthenticateemail',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formpublishauthenticateemail',
            name='otp_expires',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='formpublishauthenticateemail',
            name='otp_expires_seconds',
            field=models.SmallIntegerField(default=0),
        ),
    ]
