# Generated by Django 4.2.8 on 2024-09-18 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_company_icon'),
        ('tenant', '0001_initial'),
        ('forms', '0004_remove_formpublishauthenticateemail_cookies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpublishauthenticateemail',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='formpublishauthenticateemail',
            name='form',
            field=models.ForeignKey(help_text='The form claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_belong_to_form', to='forms.formpublished'),
        ),
        migrations.AddField(
            model_name='formpublishauthenticateemail',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
    ]
