# Generated by Django 4.2.8 on 2024-09-18 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_formpublishauthenticateemail_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpublishauthenticateemail',
            name='form_publish',
            field=models.ForeignKey(help_text='The form published claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_belong_to_form', to='forms.formpublished'),
        ),
        migrations.AlterField(
            model_name='formpublishauthenticateemail',
            name='form',
            field=models.ForeignKey(help_text='The form claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_belong_to_form', to='forms.form'),
        ),
    ]
