# Generated by Django 4.2.8 on 2024-07-22 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0005_collabinworkflow_is_edit_all_zone_and_more'),
        ('process', '0001_initial'),
        ('company', '0010_rename_cost_per_lot_batch_companyconfig_cost_per_lot_and_more'),
        ('hr', '0003_alter_group_unique_together_and_more'),
        ('tenant', '0001_initial'),
        ('space', '0001_initial'),
        ('saledata', '0030_remove_periods_planned_periods_has_budget_planned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('is_change', models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents')),
                ('document_root_id', models.UUIDField(help_text='this is id of root document of the changed documents', null=True)),
                ('document_change_order', models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('monthly', models.BooleanField(default=False)),
                ('quarterly', models.BooleanField(default=False)),
                ('auto_sum_target', models.BooleanField(default=False)),
                ('is_lock', models.BooleanField(default=False)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('current_stage', models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('next_node_collab', models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee')),
                ('period_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plan_period_mapped', to='saledata.periods')),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
                ('space', models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('workflow_runtime', models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc')),
            ],
            options={
                'verbose_name': 'Budget Plan',
                'verbose_name_plural': 'Budget Plans',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BudgetPlanGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plan_group_budget_plan', to='budgetplan.budgetplan')),
                ('group_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plan_group_group_mapped', to='hr.group')),
            ],
            options={
                'verbose_name': 'Budget Plan Group',
                'verbose_name_plural': 'Budget Plan Groups',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BudgetPlanGroupConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_config_company', to='company.company')),
                ('employee_allowed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_config_employee_allowed', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Budget Plan Group Config',
                'verbose_name_plural': 'Budget Plan Group Configs',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BudgetPlanGroupExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('group_month_list', models.JSONField(default=list)),
                ('group_quarter_list', models.JSONField(default=list)),
                ('group_year', models.FloatField(default=0)),
                ('budget_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plan_group_expense_budget_plan', to='budgetplan.budgetplan')),
                ('budget_plan_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plan_group_expense_budget_plan_group', to='budgetplan.budgetplangroup')),
                ('expense_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plan_group_expense_expense_item', to='saledata.expenseitem')),
            ],
            options={
                'verbose_name': 'Budget Plan Group Expense',
                'verbose_name_plural': 'Budget Plans Groups Expenses',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BudgetPlanGroupConfigEmployeeGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('can_view', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('budget_plan_group_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_config_detail', to='budgetplan.budgetplangroupconfig')),
                ('group_allowed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_config_detail_group_allowed', to='hr.group')),
            ],
            options={
                'verbose_name': 'Budget Plan Group Config Employee Group',
                'verbose_name_plural': 'Budget Plan Group Config Employees Groups',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BudgetPlanCompanyExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('company_month_list', models.JSONField(default=list)),
                ('company_quarter_list', models.JSONField(default=list)),
                ('company_year', models.FloatField(default=0)),
                ('budget_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plan_company_expense_budget_plan', to='budgetplan.budgetplan')),
                ('expense_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_plan_company_expense_expense_item', to='saledata.expenseitem')),
            ],
            options={
                'verbose_name': 'Budget Plan Company',
                'verbose_name_plural': 'Budget Plan Companies',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
