# Generated by Django 4.2.8 on 2024-07-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetplan', '0002_budgetplangroup_is_locked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecanviewcompanybudgetplan',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employeecanviewcompanybudgetplan',
            name='employee_allowed',
        ),
        migrations.AddField(
            model_name='budgetplangroupconfig',
            name='can_lock_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budgetplangroupconfig',
            name='can_view_company',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='EmployeeCanLockBudgetPlan',
        ),
        migrations.DeleteModel(
            name='EmployeeCanViewCompanyBudgetPlan',
        ),
    ]
