# Generated by Django 4.1.3 on 2023-03-29 00:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('app_label', models.CharField(blank=True, help_text='application label ex. hr_employee', max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Application',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PlanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.application')),
            ],
            options={
                'verbose_name': 'Plan Application',
                'verbose_name_plural': 'Plan Applications',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('applications', models.ManyToManyField(blank=True, related_name='plan_map_application', through='base.PlanApplication', to='base.application')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'ordering': ('title',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='planapplication',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='PermissionApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=100, unique=True)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.application')),
            ],
            options={
                'verbose_name': 'Permission of Application',
                'verbose_name_plural': 'Permission of Application',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ApplicationProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Text'), (2, 'Date time'), (3, 'Choices'), (4, 'Checkbox'), (5, 'Master data'), (6, 'Number')], default=1)),
                ('content_type', models.TextField(blank=True, null=True)),
                ('properties', models.JSONField(default=dict)),
                ('compare_operator', models.JSONField(default=dict)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.application')),
            ],
            options={
                'verbose_name': 'Application property',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='application',
            name='plans',
            field=models.ManyToManyField(blank=True, related_name='application_map_plan', through='base.PlanApplication', to='base.subscriptionplan'),
        ),
    ]
