# Generated by Django 4.1.3 on 2023-01-06 10:49

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('user_created', models.UUIDField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_modified', models.UUIDField(null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Application',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('user_created', models.UUIDField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_modified', models.UUIDField(null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('extras', jsonfield.fields.JSONField(default={})),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'ordering': ('title',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
