# Generated by Django 4.1.3 on 2023-11-11 23:09

import apps.core.base.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('app_label', models.CharField(blank=True, help_text='application label ex. hr_employee', max_length=150, null=True)),
                ('model_code', models.CharField(blank=True, help_text='Model code', max_length=150, null=True)),
                ('is_workflow', models.BooleanField(default=True, verbose_name='Application apply Workflow')),
                ('option_permission', models.PositiveSmallIntegerField(choices=[(0, 'All option range'), (1, 'Only company range')], default=0, help_text='0: Allow full control range, 1: Allow only company', verbose_name='Allow Type Permission')),
                ('option_allowed', models.JSONField(default=list, verbose_name='Option code was allowed')),
                ('app_depend_on', models.JSONField(default=list, help_text='["{app_id}", "{app_id}", "{app_id}"]', verbose_name='App ID depend')),
                ('permit_mapping', models.JSONField(default=dict, verbose_name='Permit map Range and Depends On')),
                ('depend_follow_main', models.BooleanField(default=True, help_text='Default it append to with Main ID Group, False: append to global (same general)', verbose_name='Depends Follow Main ID')),
                ('filtering_inheritor', models.BooleanField(default=True, help_text='Apply rule filter employee_inherit_id in mask_view', verbose_name='Allow Filter Inheritor')),
                ('spacing_allow', models.JSONField(default=apps.core.base.models.default_space_allow, help_text='0: General, 1: All space (not filter opp, prj,... isnull)', verbose_name='Code Allow Space')),
            ],
            options={
                'verbose_name': 'Application',
                'ordering': ('title',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BaseItemUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('measure', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'BaseItemUnit',
                'verbose_name_plural': 'BaseItemUnits',
                'ordering': ('title',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='City of Country')),
                ('id_crawler', models.SmallIntegerField(verbose_name='ID of record in API Data')),
                ('zip_code', models.CharField(blank=True, max_length=15, verbose_name='Zip Code/Postal Code')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'City',
                'ordering': ('title',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('symbol', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currency',
                'ordering': ('code',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='District of City')),
                ('id_crawler', models.SmallIntegerField(verbose_name='ID of record in API Data')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts_of_city', to='base.city')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'District',
                'ordering': ('title',),
                'permissions': (),
                'default_permissions': (),
                'unique_together': {('city', 'id_crawler')},
            },
        ),
        migrations.CreateModel(
            name='IndicatorParam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('syntax', models.CharField(blank=True, help_text='syntax show in editor when user select this function', max_length=200)),
                ('syntax_show', models.CharField(blank=True, help_text='syntax show in description', max_length=200)),
                ('example', models.CharField(blank=True, max_length=300)),
                ('param_type', models.SmallIntegerField(choices=[(0, 'Indicator'), (1, 'Property'), (2, 'Function'), (3, 'Operator')], default=0)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Indicator Param',
                'verbose_name_plural': 'Indicator Params',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PlanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.application')),
            ],
            options={
                'verbose_name': 'Plan Application',
                'verbose_name_plural': 'Plan Applications',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('applications', models.ManyToManyField(blank=True, related_name='plan_map_application', through='base.PlanApplication', to='base.application')),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'ordering': ('title',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='planapplication',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='PermissionApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=100, unique=True)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.application')),
            ],
            options={
                'verbose_name': 'Permission of Application',
                'verbose_name_plural': 'Permission of Application',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Name of Country')),
                ('code_2', models.CharField(max_length=2, verbose_name='ISO Country Code: 2 letters')),
                ('code_3', models.CharField(max_length=3, verbose_name='ISO Country Code: 3 letters')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='Official Language of Country')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Country',
                'ordering': ('title',),
                'permissions': (),
                'default_permissions': (),
                'unique_together': {('code_2', 'code_3')},
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities_of_country', to='base.country'),
        ),
        migrations.CreateModel(
            name='ApplicationProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Text'), (2, 'Date time'), (3, 'Choices'), (4, 'Checkbox'), (5, 'Master data'), (6, 'Number')], default=1)),
                ('content_type', models.TextField(blank=True, null=True)),
                ('properties', models.JSONField(default=dict)),
                ('compare_operator', models.JSONField(default=dict)),
                ('opp_stage_operator', models.JSONField(default=list, help_text='comparison operator (≠ and =)')),
                ('stage_compare_data', models.JSONField(default=dict, help_text='compare data format {"=": [...], "≠": [...]}')),
                ('is_sale_indicator', models.BooleanField(default=False, help_text='property which is only used for config sale indicators')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.application')),
            ],
            options={
                'verbose_name': 'Application property',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='application',
            name='plans',
            field=models.ManyToManyField(blank=True, related_name='application_map_plan', through='base.PlanApplication', to='base.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Ward of District')),
                ('id_crawler', models.SmallIntegerField(verbose_name='ID of record in API Data')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards_of_district', to='base.district')),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Ward',
                'ordering': ('title',),
                'permissions': (),
                'default_permissions': (),
                'unique_together': {('district', 'id_crawler')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('country', 'id_crawler')},
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('app_label', 'model_code')},
        ),
    ]
