# Generated by Django 4.1.3 on 2023-04-17 15:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='City of Country')),
                ('id_crawler', models.SmallIntegerField(verbose_name='ID of record in API Data')),
                ('zip_code', models.CharField(blank=True, max_length=15, verbose_name='Zip Code/Postal Code')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'City',
                'ordering': ('title',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='District of City')),
                ('id_crawler', models.SmallIntegerField(verbose_name='ID of record in API Data')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts_of_city', to='base.city')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'District',
                'ordering': ('title',),
                'permissions': (),
                'default_permissions': (),
                'unique_together': {('city', 'id_crawler')},
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Name of Country')),
                ('code_2', models.CharField(max_length=2, verbose_name='ISO Country Code: 2 letters')),
                ('code_3', models.CharField(max_length=3, verbose_name='ISO Country Code: 3 letters')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='Official Language of Country')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Country',
                'ordering': ('title',),
                'permissions': (),
                'default_permissions': (),
                'unique_together': {('code_2', 'code_3')},
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities_of_country', to='base.country'),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Ward of District')),
                ('id_crawler', models.SmallIntegerField(verbose_name='ID of record in API Data')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards_of_district', to='base.district')),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Ward',
                'ordering': ('title',),
                'permissions': (),
                'default_permissions': (),
                'unique_together': {('district', 'id_crawler')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('country', 'id_crawler')},
        ),
    ]
