# Generated by Django 4.2.8 on 2023-12-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='short_search',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
