# Generated by Django 4.1.3 on 2023-01-09 19:11

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.application')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Plan Application',
                'verbose_name_plural': 'Plan Applications',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
            managers=[
                ('object_normal', django.db.models.manager.Manager()),
            ],
        ),
    ]
