# Generated by Django 4.1.3 on 2023-02-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_planapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='application',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='delete'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='delete'),
        ),
    ]
