# Generated by Django 4.1.3 on 2023-03-09 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_application_is_active_application_is_delete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('user_created', models.UUIDField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_modified', models.UUIDField(null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('remark', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Text'), (2, 'Date time'), (3, 'Choices'), (4, 'Checkbox'), (5, 'Master data'), (6, 'Number')], default=1)),
                ('content_type', models.TextField(blank=True, null=True)),
                ('properties', models.JSONField(default=dict)),
                ('compare_operator', models.JSONField(default=dict)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.application')),
            ],
            options={
                'verbose_name': 'Application property',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
