# Generated by Django 4.2.8 on 2024-01-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_applicationproperty_parent_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationproperty',
            name='code_related',
            field=models.JSONField(default=list, verbose_name='code of other properties that relate to this property by business rule'),
        ),
    ]
