# Generated by Django 4.1.3 on 2023-05-16 17:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItemUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('measure', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'BaseItemUnit',
                'verbose_name_plural': 'BaseItemUnits',
                'ordering': ('title',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
