# Generated by Django 4.1.3 on 2023-06-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_baseitemunit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'default_permissions': (), 'ordering': ('title',), 'permissions': (), 'verbose_name': 'Application'},
        ),
        migrations.AddField(
            model_name='application',
            name='is_workflow',
            field=models.BooleanField(default=True, verbose_name='Application apply Workflow'),
        ),
    ]
