# Generated by Django 4.1.3 on 2023-03-10 09:52

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_applicationproperty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planapplication',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'Plan Application', 'verbose_name_plural': 'Plan Applications'},
        ),
        migrations.AlterModelManagers(
            name='planapplication',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user_modified',
        ),
        migrations.RemoveField(
            model_name='applicationproperty',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='applicationproperty',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='applicationproperty',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='applicationproperty',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='applicationproperty',
            name='user_modified',
        ),
        migrations.RemoveField(
            model_name='planapplication',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='planapplication',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='user_modified',
        ),
        migrations.CreateModel(
            name='PermissionApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=100, unique=True)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.application')),
            ],
            options={
                'verbose_name': 'Permission of Application',
                'verbose_name_plural': 'Permission of Application',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
