# Generated by Django 4.1.3 on 2023-03-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_planapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='plans',
            field=models.ManyToManyField(blank=True, related_name='application_map_plan', through='base.PlanApplication', to='base.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='plan_map_application', through='base.PlanApplication', to='base.application'),
        ),
    ]
