# Generated by Django 4.2.8 on 2024-02-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_applicationproperty_is_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationproperty',
            name='title_slug',
            field=models.SlugField(blank=True),
        ),
    ]
