# Generated by Django 4.1.3 on 2023-06-27 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_application_options_application_is_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorParam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('syntax', models.CharField(blank=True, help_text='syntax show in editor when user select this function', max_length=200)),
                ('syntax_show', models.CharField(blank=True, help_text='syntax show in description', max_length=200)),
                ('example', models.CharField(blank=True, max_length=300)),
                ('param_type', models.SmallIntegerField(choices=[(0, 'Indicator'), (1, 'Property'), (2, 'Function'), (3, 'Operator')], default=0)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Indicator Param',
                'verbose_name_plural': 'Indicator Params',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
