# Generated by Django 4.2.8 on 2024-03-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_applicationproperty_title_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='allow_import',
            field=models.BooleanField(default=False, verbose_name='Allow import data'),
        ),
        migrations.AddField(
            model_name='application',
            name='allow_print',
            field=models.BooleanField(default=False, verbose_name='Allow print template'),
        ),
    ]
