# Generated by Django 4.1.3 on 2023-06-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_indicatorparam'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationproperty',
            name='opp_stage_operator',
            field=models.JSONField(default=list, help_text='comparison operator (≠ and =)'),
        ),
        migrations.AddField(
            model_name='applicationproperty',
            name='stage_compare_data',
            field=models.JSONField(default=dict, help_text='compare data format {"=": [...], "≠": [...]}'),
        ),
    ]
