# Generated by Django 4.1.3 on 2023-03-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_application_plans_subscriptionplan_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_label',
            field=models.CharField(blank=True, help_text='application label ex. hr_employee', max_length=150, null=True),
        ),
    ]
