# Generated by Django 4.1.3 on 2023-07-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_applicationproperty_is_sale_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='option_permission',
            field=models.PositiveSmallIntegerField(choices=[(0, 'All option range'), (1, 'Only company range')], default=0, help_text='0: Allow full control range, 1: Allow only company', verbose_name='Allow Type Permission'),
        ),
    ]
