# Generated by Django 4.2.8 on 2024-03-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_application_allow_mail_applicationproperty_is_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationproperty',
            name='system_code',
            field=models.CharField(max_length=5, null=True, verbose_name='Split Data System'),
        ),
    ]
