# Generated by Django 4.1.3 on 2023-08-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_application_option_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='model_code',
            field=models.CharField(blank=True, help_text='Model code', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='option_allowed',
            field=models.JSONField(default=list, verbose_name='Option code was allowed'),
        ),
    ]
