# Generated by Django 4.2.8 on 2024-07-12 14:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_group_unique_together_and_more'),
        ('company', '0010_rename_cost_per_lot_batch_companyconfig_cost_per_lot_and_more'),
        ('tenant', '0001_initial'),
        ('base', '0011_applicationproperty_app_code_md_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppEmpConfigZonesEditing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Employee Zone Editing',
                'verbose_name_plural': 'Employees Zones Editing',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AppEmpConfigZonesHidden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Employee Zone Hidden',
                'verbose_name_plural': 'Employees Zones Hidden',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True, null=True, verbose_name='remark')),
                ('properties_data', models.JSONField(default=list, help_text='list data parsed from ApplicationProperty [{},{}]', verbose_name='property list')),
                ('order', models.IntegerField(default=1)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones_application', to='base.application', verbose_name='application')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ZonesProperties',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones_props_property', to='base.applicationproperty')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones_props_zone', to='base.zones')),
            ],
            options={
                'verbose_name': 'Zone Property',
                'verbose_name_plural': 'Zones Properties',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='zones',
            name='properties',
            field=models.ManyToManyField(blank=True, related_name='zones_relate_properties', through='base.ZonesProperties', to='base.applicationproperty'),
        ),
        migrations.AddField(
            model_name='zones',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.CreateModel(
            name='ApplicationEmpConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('app_code', models.CharField(help_text='{app_label}.{model}', max_length=100, verbose_name='Code of application')),
                ('employee_data', models.JSONField(default=dict, help_text='data parsed from Employee {}', verbose_name='employee data')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='remark')),
                ('zones_editing_data', models.JSONField(default=list, help_text='list data parsed from Zones [{},{}]', verbose_name='zone list')),
                ('zones_hidden_data', models.JSONField(default=list, help_text='list data parsed from Zones [{},{}]', verbose_name='zone list')),
                ('order', models.IntegerField(default=1)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_emp_config_application', to='base.application', verbose_name='application')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('zones_editing', models.ManyToManyField(blank=True, related_name='app_emp_config_relate_zones_editing', through='base.AppEmpConfigZonesEditing', to='base.zones')),
                ('zones_hidden', models.ManyToManyField(blank=True, related_name='app_emp_config_relate_zones_hidden', through='base.AppEmpConfigZonesHidden', to='base.zones')),
            ],
            options={
                'verbose_name': 'Application Employee Config',
                'verbose_name_plural': 'Application Employee Configs',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='appempconfigzoneshidden',
            name='app_emp_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_emp_config_zones_hidden_config', to='base.applicationempconfig'),
        ),
        migrations.AddField(
            model_name='appempconfigzoneshidden',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_emp_config_zones_hidden_zone', to='base.zones'),
        ),
        migrations.AddField(
            model_name='appempconfigzonesediting',
            name='app_emp_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_emp_config_zones_editing_config', to='base.applicationempconfig'),
        ),
        migrations.AddField(
            model_name='appempconfigzonesediting',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_emp_config_zones_editing_zone', to='base.zones'),
        ),
    ]
