# Generated by Django 4.1.3 on 2023-10-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_application_app_depend_on_application_permit_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='depend_follow_main',
            field=models.BooleanField(default=True, help_text='Default it append to with Main ID Group, False: append to global (same general)', verbose_name='Depends Follow Main ID'),
        ),
    ]
