# Generated by Django 4.2.8 on 2024-10-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_applicationempconfig_date_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationproperty',
            name='app_code_md',
        ),
        migrations.AddField(
            model_name='applicationproperty',
            name='is_wf_condition',
            field=models.BooleanField(default=False, help_text='property which is only used for config WF condition'),
        ),
        migrations.AddField(
            model_name='applicationproperty',
            name='is_wf_zone',
            field=models.BooleanField(default=False, help_text='property which is only used for config WF zone'),
        ),
        migrations.AlterField(
            model_name='applicationproperty',
            name='code_related',
            field=models.JSONField(default=list, verbose_name='list field code of other properties that relate to this property by business rule'),
        ),
        migrations.AlterField(
            model_name='applicationproperty',
            name='content_type',
            field=models.TextField(blank=True, help_text='{app_label}.{model}, use for property type master data', max_length=100, null=True, verbose_name='Code of application'),
        ),
    ]
