# Generated by Django 4.1.3 on 2023-10-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_application_filtering_inheritor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('app_label', 'model_code')},
        ),
    ]
