# Generated by Django 4.1.3 on 2023-10-27 11:20

import apps.core.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_application_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='spacing_allow',
            field=models.JSONField(default=apps.core.base.models.default_space_allow, help_text='0: General, 1: All space (not filter opp, prj,... isnull)', verbose_name='Code Allow Space'),
        ),
    ]
