# Generated by Django 4.2.8 on 2024-11-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_applicationproperty_app_code_md_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='allow_process',
            field=models.BooleanField(default=False, verbose_name='Allow use at process'),
        ),
    ]
