# Generated by Django 4.2.8 on 2024-11-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_application_allow_opportunity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='allow_recurrence',
            field=models.BooleanField(default=False, verbose_name='Allow config recurrence'),
        ),
    ]
