# Generated by Django 4.2.8 on 2025-01-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_application_allow_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationproperty',
            name='is_filter_condition',
            field=models.BooleanField(default=False, help_text='property which is only used for config filter condition'),
        ),
    ]
