# Generated by Django 4.2.8 on 2025-03-14 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financialcashflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashinflow',
            name='accounting_bank_account',
        ),
        migrations.RemoveField(
            model_name='cashinflow',
            name='accounting_cash_account',
        ),
    ]
