# Generated by Django 4.2.8 on 2025-03-14 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financialcashflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashinflow',
            name='accounting_bank_account',
        ),
        migrations.RemoveField(
            model_name='cashinflow',
            name='accounting_cash_account',
        ),
        migrations.AddField(
            model_name='cashinflowitem',
            name='sale_order_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_inflow_item_so_stage', to='saleorder.saleorderpaymentstage'),
        ),
        migrations.AddField(
            model_name='cashinflowitem',
            name='sale_order_stage_data',
            field=models.JSONField(default=dict),
        ),
    ]
