# Generated by Django 4.2.8 on 2025-03-19 21:04
from django.core.exceptions import FieldDoesNotExist
from django.db import migrations, models
import django.db.models.deletion


def remove_field_if_exists(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    # Get historical model versions
    CashInflowItem = apps.get_model('financialcashflow', 'CashInflowItem')
    CashInflowItemDetail = apps.get_model('financialcashflow', 'CashInflowItemDetail')

    # List of fields to remove from CashInflowItem
    cashinflowitem_fields = [
        'code', 'company', 'current_stage', 'current_stage_title', 'date_approved',
        'date_created', 'date_modified', 'document_change_order', 'document_root_id',
        'employee_created', 'employee_inherit', 'employee_modified', 'is_active',
        'is_change', 'is_delete', 'next_association', 'next_node_collab', 'process',
        'process_stage_app', 'space', 'system_remarks', 'system_status', 'tenant',
        'title', 'workflow_runtime'
    ]

    # List of fields to remove from CashInflowItemDetail
    cashinflowitemdetail_fields = [
        'code', 'company', 'current_stage', 'current_stage_title', 'date_approved',
        'date_created', 'date_modified', 'document_change_order', 'document_root_id',
        'employee_created', 'employee_inherit', 'employee_modified', 'is_active',
        'is_change', 'is_delete', 'next_association', 'next_node_collab', 'process',
        'process_stage_app', 'space', 'system_remarks', 'system_status', 'tenant',
        'title', 'workflow_runtime'
    ]

    # Get table descriptions
    with schema_editor.connection.cursor() as cursor:
        cashinflowitem_columns = [
            field.name for field in schema_editor.connection.introspection.get_table_description(
                cursor, CashInflowItem._meta.db_table
            )
        ]
        cashinflowitemdetail_columns = [
            field.name for field in schema_editor.connection.introspection.get_table_description(
                cursor, CashInflowItemDetail._meta.db_table
            )
        ]

    # Check and remove fields from CashInflowItem
    for field_name in cashinflowitem_fields:
        if field_name in cashinflowitem_columns:
            try:
                field = CashInflowItem._meta.get_field(field_name)
                schema_editor.remove_field(CashInflowItem, field)
            except FieldDoesNotExist:
                # Field doesn’t exist in the model state, skip it
                pass

    # Check and remove fields from CashInflowItemDetail
    for field_name in cashinflowitemdetail_fields:
        if field_name in cashinflowitemdetail_columns:
            try:
                field = CashInflowItemDetail._meta.get_field(field_name)
                schema_editor.remove_field(CashInflowItemDetail, field)
            except FieldDoesNotExist:
                # Field doesn’t exist in the model state, skip it
                pass


def add_field_if_not_exists(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    CashInflowItem = apps.get_model('financialcashflow', 'CashInflowItem')

    # Define the fields to add
    sale_order_stage_field = models.ForeignKey(
        null=True,
        on_delete=django.db.models.deletion.CASCADE,
        related_name='cash_inflow_item_so_stage',
        to='saleorder.saleorderpaymentstage'
    )
    sale_order_stage_data_field = models.JSONField(default=dict)

    # Get table description
    with schema_editor.connection.cursor() as cursor:
        cashinflowitem_columns = [
            field.name for field in schema_editor.connection.introspection.get_table_description(
                cursor, CashInflowItem._meta.db_table
            )
        ]

    # Check and add sale_order_stage field
    if 'sale_order_stage_id' not in cashinflowitem_columns:
        schema_editor.add_field(CashInflowItem, sale_order_stage_field)

    # Check and add sale_order_stage_data field
    if 'sale_order_stage_data' not in cashinflowitem_columns:
        schema_editor.add_field(CashInflowItem, sale_order_stage_data_field)


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0062_alter_bank_options_alter_bankaccount_options_and_more'),
        ('saleorder', '0029_saleorderpaymentstage_cash_inflow_done'),
        ('financialcashflow', '0002_remove_cashinflow_accounting_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashinflowitem',
            options={'default_permissions': (), 'ordering': (), 'permissions': (), 'verbose_name': 'Cash Inflow Item', 'verbose_name_plural': 'Cash Inflow Items'},
        ),
        migrations.AlterModelOptions(
            name='cashinflowitemdetail',
            options={'default_permissions': (), 'ordering': (), 'permissions': (), 'verbose_name': 'Cash Inflow Item Details', 'verbose_name_plural': 'Cash Inflow Items Detail'},
        ),
        # Handle field removals
        migrations.RunPython(remove_field_if_exists),
        # Handle field additions
        migrations.RunPython(add_field_if_not_exists),
        # Alter existing field
        migrations.AlterField(
            model_name='cashinflow',
            name='company_bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_inflow_company_bank_account', to='saledata.bankaccount'),
        ),
    ]