# Generated by Django 4.2.8 on 2025-08-22 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0075_attribute_attributelist_attributewarranty_and_more'),
        ('purchasing', '0017_rename_cash_inflow_done_purchaseorderpaymentstage_cash_outflow_done_and_more'),
        ('financialcashflow', '0006_cashoutflow_payment_to_customer_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashoutflow',
            old_name='company_bank_account_data',
            new_name='account_bank_account_data',
        ),
        migrations.RemoveField(
            model_name='cashoutflow',
            name='company_bank_account',
        ),
        migrations.AddField(
            model_name='cashoutflow',
            name='account_bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_outflow_account_bank_account', to='saledata.accountbanks'),
        ),
        migrations.AddField(
            model_name='cashoutflow',
            name='banking_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashoutflowitem',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_outflow_item_purchase_order', to='purchasing.purchaseorder'),
        ),
    ]
