# Generated by Django 4.1.3 on 2023-11-11 23:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
        ('hr', '0001_initial'),
        ('company', '0002_initial'),
        ('saledata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerByList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_by_list_customer', to='saledata.account')),
            ],
            options={
                'verbose_name': 'Customer by list',
                'verbose_name_plural': 'Customer by lists',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DiscountMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('before_after_tax', models.BooleanField(help_text='Option check before or after tax', verbose_name='Before After tax check')),
                ('percent_fix_amount', models.BooleanField(help_text='Option percent or fixed amount', verbose_name='Percent or Fixed amount')),
                ('percent_value', models.FloatField(blank=True, help_text='This field is required when user check "Percent" icon', null=True, verbose_name='percent number')),
                ('max_percent_value', models.FloatField(blank=True, help_text='For percent option when user check "Percent" icon', null=True, verbose_name='max percent amount')),
                ('fix_value', models.FloatField(blank=True, help_text='This field is required when user check "Fixed amount" field', null=True, verbose_name='Fixed amount')),
                ('use_count', models.IntegerField(default=1, help_text='Count time per customer per times', verbose_name='Use count')),
                ('times_condition', models.IntegerField(choices=[(1, 'Valid time'), (2, 'Week'), (3, 'Month')], default=1, help_text='Choose times apply for per use per customer', verbose_name='Times choose')),
                ('max_usages', models.IntegerField(default=0, help_text='Maximum of usages is apply for discount campaign code', verbose_name='Max usages')),
                ('is_on_order', models.BooleanField(default=False, help_text='checkbox Discount on order', verbose_name='Discount on order')),
                ('is_minimum', models.BooleanField(default=False, help_text='Checkbox near Discount on order', verbose_name='Minimum purchase')),
                ('minimum_value', models.FloatField(blank=True, help_text='input minimum purchase value', null=True, verbose_name='Minimum purchase value')),
                ('is_on_product', models.BooleanField(default=False, verbose_name='Discount on product')),
                ('is_min_quantity', models.BooleanField(default=False, verbose_name='Minimum quantity')),
                ('num_minimum', models.IntegerField(default=0, verbose_name='Number of minimum quantity')),
                ('free_shipping', models.BooleanField(default=0, verbose_name='Free shipping')),
                ('product_selected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_method_product', to='saledata.product')),
            ],
            options={
                'verbose_name': 'Discount method',
                'verbose_name_plural': 'Discount methods',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CouponsMethod',
            fields=[
                ('discountmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='promotion.discountmethod')),
                ('coupons_no', models.IntegerField(default=0, verbose_name='Coupons No')),
            ],
            options={
                'verbose_name': 'Coupons method',
                'verbose_name_plural': 'Coupons methods',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
            bases=('promotion.discountmethod',),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('valid_date_start', models.DateField(help_text="promotion valid time from, with format '%Y-%m-%d'", verbose_name='Valid date start')),
                ('valid_date_end', models.DateField(help_text="promotion valid time to, with format '%Y-%m-%d'", verbose_name='Valid date end')),
                ('remark', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descriptions')),
                ('customer_type', models.IntegerField(default=0, help_text='filter customer by option choose (0: all, 1: choose customer, 2: filter by condition)', verbose_name='Customer type')),
                ('customer_by_list', models.JSONField(default=list, help_text='list of customer follow by customer type (option = 1) example: [uuid1, uuid2]', verbose_name='Customer by list')),
                ('customer_by_condition', models.JSONField(default=list, help_text='condition for filter customer list follow by customer type (option = 2) example: [{property: 1, operator: =, result: uuid, property_type: text, logic: and, order: 1}]', verbose_name='Customer by condition')),
                ('customer_remark', models.CharField(blank=True, help_text='Explanation about customer type', max_length=250, null=True, verbose_name='Customer Descriptions')),
                ('is_discount', models.BooleanField(help_text='Promotion for discount', null=True, verbose_name='Discount check')),
                ('is_coupons', models.BooleanField(help_text='Promotion for Coupons', null=True, verbose_name='Coupons check')),
                ('is_gift', models.BooleanField(help_text='Promotion for gift', null=True, verbose_name='Gift check')),
                ('discount_method', models.JSONField(default=list, help_text='Discount method JSON string data', verbose_name='JSON discount method')),
                ('coupons_method', models.JSONField(default=list, help_text='Coupons method JSON string data', verbose_name='Coupons method')),
                ('gift_method', models.JSONField(default=list, help_text='Gift method JSON string data', verbose_name='Gift method')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_currency', to='saledata.currency')),
                ('customers_map_promotion', models.ManyToManyField(blank=True, related_name='customers_map_promotion', through='promotion.CustomerByList', to='saledata.account')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GiftMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('use_count', models.IntegerField(default=1, help_text='Count time per customer per times REQUIRED', verbose_name='Use count')),
                ('times_condition', models.IntegerField(choices=[(1, 'Valid time'), (2, 'Week'), (3, 'Month')], default=1, help_text='Choose times apply for per use per customer REQUIRED', verbose_name='Times choose')),
                ('max_usages', models.IntegerField(default=0, help_text='Maximum of usages is apply for discount campaign code REQUIRED', verbose_name='Max usages')),
                ('is_free_product', models.BooleanField(default=True, verbose_name='Free product')),
                ('num_product_received', models.IntegerField(default=1, verbose_name='Free product')),
                ('is_min_purchase', models.BooleanField(default=False, verbose_name='Minimum purchase')),
                ('before_after_tax', models.BooleanField(default=True, help_text='Option select before or after tax', verbose_name='Before After tax select')),
                ('min_purchase_cost', models.FloatField(default=0, verbose_name='Cost of total value')),
                ('is_purchase', models.BooleanField(default=False, verbose_name='Cost of total value')),
                ('purchase_num', models.IntegerField(default=0, verbose_name='Number of product when purchase')),
                ('product_received', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_method_product_received', to='saledata.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_method_promotion', to='promotion.promotion')),
                ('purchase_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_method_purchase_product', to='saledata.product')),
            ],
            options={
                'verbose_name': 'Gift method',
                'verbose_name_plural': 'Gifts method',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='discountmethod',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_method_promotion', to='promotion.promotion'),
        ),
        migrations.AddField(
            model_name='customerbylist',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_by_list_promotion', to='promotion.promotion'),
        ),
        migrations.CreateModel(
            name='CustomerByCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property', models.CharField(help_text='Customer field in model Customer', max_length=50, verbose_name='Customer property')),
                ('operator', models.CharField(help_text='Operator for filter customer with property and result value had provided', max_length=50, verbose_name='Operator')),
                ('result', models.CharField(help_text='Customer value field follow by value of property', max_length=50, verbose_name='Customer result')),
                ('logic', models.CharField(blank=True, help_text='Logic between condition for connect 2 or many condition purpose', max_length=50, null=True, verbose_name='Logic')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Order')),
                ('result_detail', models.JSONField(default=list, help_text='result JSON string data', verbose_name='result detail field')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_by_condition_promotion', to='promotion.promotion')),
            ],
            options={
                'verbose_name': 'Customer by condition',
                'verbose_name_plural': 'Customer by conditions',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
