# Generated by Django 4.1.3 on 2023-05-10 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0011_currency_currency'),
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountmethod',
            name='max_percent_value',
            field=models.FloatField(blank=True, help_text='For percent option when user check "Percent" icon', null=True, verbose_name='max percent amount'),
        ),
        migrations.AddField(
            model_name='discountmethod',
            name='percent_value',
            field=models.FloatField(blank=True, help_text='This field is required when user check "Percent" icon', null=True, verbose_name='percent number'),
        ),
        migrations.AlterField(
            model_name='customerbylist',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_by_list_customer', to='saledata.account'),
        ),
        migrations.AlterField(
            model_name='discountmethod',
            name='before_after_tax',
            field=models.BooleanField(help_text='Option check before or after tax', verbose_name='Before After tax check'),
        ),
        migrations.AlterField(
            model_name='discountmethod',
            name='fix_value',
            field=models.FloatField(blank=True, help_text='This field is required when user check "Fixed amount" field', null=True, verbose_name='Fixed amount'),
        ),
        migrations.AlterField(
            model_name='discountmethod',
            name='is_minimum',
            field=models.BooleanField(default=False, help_text='Checkbox near Discount on order', verbose_name='Minimum purchase'),
        ),
        migrations.AlterField(
            model_name='discountmethod',
            name='is_on_order',
            field=models.BooleanField(default=False, help_text='checkbox Discount on order', verbose_name='Discount on order'),
        ),
        migrations.AlterField(
            model_name='discountmethod',
            name='minimum_value',
            field=models.FloatField(blank=True, help_text='input minimum purchase value', null=True, verbose_name='Minimum purchase value'),
        ),
        migrations.AlterField(
            model_name='discountmethod',
            name='percent_fix_amount',
            field=models.BooleanField(help_text='Option percent or fixed amount', verbose_name='Percent or Fixed amount'),
        ),
        migrations.AlterField(
            model_name='giftmethod',
            name='max_usages',
            field=models.IntegerField(default=0, help_text='Maximum of usages is apply for discount campaign code REQUIRED', verbose_name='Max usages'),
        ),
        migrations.AlterField(
            model_name='giftmethod',
            name='times_condition',
            field=models.IntegerField(choices=[(1, 'Valid time'), (2, 'Week'), (3, 'Month')], default=1, help_text='Choose times apply for per use per customer REQUIRED', verbose_name='Times choose'),
        ),
        migrations.AlterField(
            model_name='giftmethod',
            name='use_count',
            field=models.IntegerField(default=1, help_text='Count time per customer per times REQUIRED', verbose_name='Use count'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='customer_type',
            field=models.IntegerField(default=0, help_text='filter customer by option choose (0: all, 1: choose customer, 2: filter by condition)', verbose_name='Customer type'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_coupons',
            field=models.BooleanField(help_text='Promotion for Coupons', null=True, verbose_name='Coupons check'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_discount',
            field=models.BooleanField(help_text='Promotion for discount', null=True, verbose_name='Discount check'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_gift',
            field=models.BooleanField(help_text='Promotion for gift', null=True, verbose_name='Gift check'),
        ),
    ]
