# Generated by Django 4.1.3 on 2023-05-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0013_alter_accountaccounttypes_options_and_more'),
        ('promotion', '0002_discountmethod_max_percent_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_currency', to='saledata.currency'),
        ),
    ]
