# Generated by Django 4.1.3 on 2023-05-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_customerbycondition_result_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbycondition',
            name='property_type',
        ),
    ]
