# Generated by Django 4.1.3 on 2023-05-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0016_remove_formulacondition_uom_and_more'),
        ('promotion', '0005_remove_customerbycondition_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='customers_map_promotion',
            field=models.ManyToManyField(blank=True, related_name='customers_map_promotion', through='promotion.CustomerByList', to='saledata.account'),
        ),
    ]
