# Generated by Django 4.1.3 on 2023-09-18 16:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0006_alter_company_code'),
        ('hr', '0006_alter_employee_code_alter_employee_unique_together'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_leave_config', to='company.company')),
            ],
            options={
                'verbose_name': 'Leave Config of Company',
                'verbose_name_plural': 'Leave Config of Company',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('paid_by', models.IntegerField(choices=[(1, 'Company salary'), (2, 'Social insurance'), (3, 'Unpaid')], default=3, help_text='Choose paid of leave type', verbose_name='paid by')),
                ('remark', models.CharField(blank=True, help_text='description of leave type', max_length=255, null=True, verbose_name='remark')),
                ('balance_control', models.BooleanField(default=False, help_text='If value is True this leave type can control surplus', verbose_name='Balance management')),
                ('is_lt_system', models.BooleanField(default=False, help_text='default type system', verbose_name='is system')),
                ('is_lt_edit', models.BooleanField(default=True, help_text='this type can edit', verbose_name='is edit')),
                ('is_check_expiration', models.BooleanField(default=False, help_text='allow check expiration', verbose_name='is check expired')),
                ('data_expired', models.DateTimeField(null=True, verbose_name='Date expired')),
                ('no_of_paid', models.IntegerField(default=0, help_text='number of leave type', verbose_name='number of type')),
                ('prev_year', models.IntegerField(default=0, help_text='number of previous year', verbose_name='Previous year')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('leave_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_type_config', to='leave.leaveconfig')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Leave Config of Company',
                'verbose_name_plural': 'Leave Config of Company',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
