# Generated by Django 4.1.3 on 2023-09-26 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_remove_company_language'),
        ('tenant', '0001_initial'),
        ('hr', '0006_alter_employee_code_alter_employee_unique_together'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingCalendarConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('working_days', models.JSONField(default=dict, help_text='{"mon": {"work": true, "mor": {"from": "08:00 AM", "to": "12:00 AM"}, "aft": {"from": "13:30 PM", "to": "17:30 PM"}}, "tue": {"work": true, "mor": {"from": "08:00 AM", "to": "12:00 AM"}, "aft": {"from": "13:30 PM", "to": "17:30 PM"}}, "wed": {"work": true, "mor": {"from": "08:00 AM", "to": "12:00 AM"}, "aft": {"from": "13:30 PM", "to": "17:30 PM"}}, "thu": {"work": true, "mor": {"from": "08:00 AM", "to": "12:00 AM"}, "aft": {"from": "13:30 PM", "to": "17:30 PM"}}, "fri": {"work": true, "mor": {"from": "08:00 AM", "to": "12:00 AM"}, "aft": {"from": "13:30 PM", "to": "17:30 PM"}}, "sat": {"work": false, "mor": {"from": "08:00 AM", "to": "12:00 AM"}, "aft": {"from": "13:30 PM", "to": "17:30 PM"}}, "sun": {"work": false, "mor": {"from": "08:00 AM", "to": "12:00 AM"}, "aft": {"from": "13:30 PM", "to": "17:30 PM"}}}', verbose_name='json working days')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Leave Holiday of Company',
                'verbose_name_plural': 'Leave Holiday of Company',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WorkingYearConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_year', models.IntegerField(default=1995, verbose_name='number year holiday')),
                ('working_calendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_year_working_calendar', to='leave.workingcalendarconfig', verbose_name='working calendar config')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WorkingHolidayConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holiday_date_from', models.DateField(null=True, verbose_name='holiday from')),
                ('holiday_date_to', models.DateField(null=True, verbose_name='holiday to')),
                ('remark', models.CharField(max_length=500, verbose_name='description')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_year_working_calendar', to='leave.workingyearconfig', verbose_name='working calendar config')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
