# Generated by Django 4.1.3 on 2023-10-06 18:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('company', '0008_remove_company_language'),
        ('space', '0001_initial'),
        ('workflow', '0008_runtime_doc_employee_inherit_and_more'),
        ('hr', '0007_employee_permission_by_opp_and_more'),
        ('process', '0002_salefunction_process_code_process_company_and_more'),
        ('leave', '0002_workingcalendarconfig_workingyearconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('request_date', models.DateField(null=True, verbose_name='request date')),
                ('detail_data', models.JSONField(default=list, help_text='[{"order": 0, "leave_type": "bce75617-b78e4-1258-689d-caf5ebaa7c6", "date_from": "2023-08-12", "morning_shift_f": true, "date_to": "2023-08-12", "morning_shift_t": false, "subtotal": 1, "remark": "lorem ipsum"}]', null=True)),
                ('start_day', models.DateField(null=True, verbose_name='Date start of list request')),
                ('total', models.FloatField(help_text='total day of request', null=True, verbose_name='total')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
                ('space', models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('workflow_runtime', models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc')),
            ],
            options={
                'verbose_name': 'Leave request',
                'verbose_name_plural': 'Leave request',
                'ordering': ('-start_day',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LeaveRequestDateListRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(help_text='index row in date list', null=True, verbose_name='index row in date list')),
                ('date_from', models.DateField(help_text='date register from', null=True, verbose_name='Date from leave')),
                ('morning_shift_f', models.BooleanField(help_text='morning or afternoon shift of date from', verbose_name='morning or afternoon shift of date from')),
                ('date_to', models.DateField(help_text='date to register to', null=True, verbose_name='Date to leave')),
                ('morning_shift_t', models.BooleanField(help_text='morning or afternoon shift of date to', verbose_name='morning or afternoon shift of date to')),
                ('subtotal', models.FloatField(help_text='total day of record', null=True, verbose_name='total day per line detail')),
                ('remark', models.CharField(max_length=500, null=True, verbose_name='descriptions')),
                ('leave', models.ForeignKey(help_text='Leave request ID', on_delete=django.db.models.deletion.CASCADE, related_name='leave_request_date_leave', to='leave.leaverequest')),
                ('leave_type', models.ForeignKey(help_text='foreign key to leave type model', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_request_date_list_frk_leave_type', to='leave.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Config of Company',
                'verbose_name_plural': 'Leave Config of Company',
                'ordering': ('-order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
