# Generated by Django 4.2.8 on 2024-01-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leaveavailable_next_node_collab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveavailablehistory',
            name='open_year',
            field=models.IntegerField(default=0, help_text='year of annual created', null=True, verbose_name='Opening year'),
        ),
    ]
