# Generated by Django 4.1.3 on 2023-10-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leaveavailable_leaverequestdatelistregister_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='no_of_paid',
            field=models.IntegerField(default=0, help_text='number of leave type', null=True, verbose_name='number of type'),
        ),
    ]
