# Generated by Django 4.2.8 on 2024-04-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leaveavailablehistory_open_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveavailable',
            name='document_change_order',
            field=models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True),
        ),
        migrations.AddField(
            model_name='leaveavailable',
            name='document_root_id',
            field=models.UUIDField(help_text='this is id of root document of the changed documents', null=True),
        ),
        migrations.AddField(
            model_name='leaveavailable',
            name='is_change',
            field=models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents'),
        ),
        migrations.AddField(
            model_name='leaveavailablehistory',
            name='document_change_order',
            field=models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True),
        ),
        migrations.AddField(
            model_name='leaveavailablehistory',
            name='document_root_id',
            field=models.UUIDField(help_text='this is id of root document of the changed documents', null=True),
        ),
        migrations.AddField(
            model_name='leaveavailablehistory',
            name='is_change',
            field=models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='document_change_order',
            field=models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='document_root_id',
            field=models.UUIDField(help_text='this is id of root document of the changed documents', null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_change',
            field=models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents'),
        ),
        migrations.AddField(
            model_name='leaverequestdatelistregister',
            name='document_change_order',
            field=models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True),
        ),
        migrations.AddField(
            model_name='leaverequestdatelistregister',
            name='document_root_id',
            field=models.UUIDField(help_text='this is id of root document of the changed documents', null=True),
        ),
        migrations.AddField(
            model_name='leaverequestdatelistregister',
            name='is_change',
            field=models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents'),
        ),
    ]
