# Generated by Django 4.1.3 on 2023-10-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_alter_leavetype_no_of_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveavailable',
            name='check_balance',
            field=models.BooleanField(default=False, verbose_name='balance control of type related leave type'),
        ),
        migrations.AlterField(
            model_name='leaveavailable',
            name='expiration_date',
            field=models.DateField(null=True, verbose_name='date expiration'),
        ),
        migrations.AlterField(
            model_name='workingcalendarconfig',
            name='working_days',
            field=models.JSONField(default=dict, help_text='{"0": {"work": false, "mor": {"from": "08:00 AM", "to": "12:00 AM"}, "aft": {"from": "13:30 PM", "to": "17:30 PM"}}, "1": {"work": true, "mor": {"from": "08:00 AM", "to": "12:00 AM"}, "aft": {"from": "13:30 PM", "to": "17:30 PM"}}, "2": {"work": true, "mor": {"from": "08:00 AM", "to": "12:00 AM"}, "aft": {"from": "13:30 PM", "to": "17:30 PM"}}, "3": {"work": true, "mor": {"from": "08:00 AM", "to": "12:00 AM"}, "aft": {"from": "13:30 PM", "to": "17:30 PM"}}, "4": {"work": true, "mor": {"from": "08:00 AM", "to": "12:00 AM"}, "aft": {"from": "13:30 PM", "to": "17:30 PM"}}, "5": {"work": true, "mor": {"from": "08:00 AM", "to": "12:00 AM"}, "aft": {"from": "13:30 PM", "to": "17:30 PM"}}, "6": {"work": false, "mor": {"from": "08:00 AM", "to": "12:00 AM"}, "aft": {"from": "13:30 PM", "to": "17:30 PM"}}}', verbose_name='json working days'),
        ),
    ]
