# Generated by Django 4.1.3 on 2023-11-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_leaveavailable_check_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveavailablehistory',
            name='type_arises',
            field=models.IntegerField(choices=[(1, 'By admin'), (2, 'By system'), (3, 'By employee')], default=1, help_text='Choose paid of leave type', verbose_name='paid by'),
            preserve_default=False,
        ),
    ]
