# Generated by Django 4.2.8 on 2025-10-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_alter_leaverequest_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequestdatelistregister',
            name='morning_shift_f',
        ),
        migrations.RemoveField(
            model_name='leaverequestdatelistregister',
            name='morning_shift_t',
        ),
        migrations.RemoveField(
            model_name='workingyearconfig',
            name='working_calendar',
        ),
        migrations.AddField(
            model_name='leaverequestdatelistregister',
            name='first_half',
            field=models.BooleanField(default=False, help_text='morning shift of shift assignment', verbose_name='first half shift'),
        ),
        migrations.AddField(
            model_name='leaverequestdatelistregister',
            name='second_half',
            field=models.BooleanField(default=False, help_text='afternoon shift of shift assignment', verbose_name='second half shift'),
        ),
    ]
