# Generated by Django 4.2.8 on 2025-02-26 10:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0004_employee_email_app_password_and_more'),
        ('tenant', '0001_initial'),
        ('saledata', '0055_remove_producttype_is_asset_tool_and_more'),
        ('space', '0001_initial'),
        ('company', '0016_companyconfig_accounting_policies_and_more'),
        ('workflow', '0008_alter_collabinworkflow_position_choice'),
        ('process', '0009_processmembers_is_system_and_more'),
        ('accountingsettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('is_change', models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents')),
                ('document_root_id', models.UUIDField(help_text='this is id of root document of the changed documents', null=True)),
                ('document_change_order', models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('system_auto_create', models.BooleanField(default=False, help_text='flag to know this record is created by system')),
                ('je_transaction_app_code', models.CharField(help_text='{app_label}.{model}', max_length=100, null=True, verbose_name='Code of application')),
                ('je_transaction_id', models.UUIDField(null=True, verbose_name='Document that has foreign key to JE')),
                ('je_transaction_data', models.JSONField(default=dict)),
                ('je_posting_date', models.DateTimeField(null=True)),
                ('je_document_date', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('current_stage', models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('next_association', models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association')),
                ('next_node_collab', models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee')),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
                ('process_stage_app', models.ForeignKey(help_text='The process stage app claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.processstageapplication')),
                ('space', models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('workflow_runtime', models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ('date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='JournalEntryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('account_data', models.JSONField(default=dict)),
                ('business_partner_data', models.JSONField(default=dict)),
                ('debit', models.FloatField(default=0)),
                ('credit', models.FloatField(default=0)),
                ('is_fc', models.BooleanField(default=False)),
                ('je_item_type', models.SmallIntegerField(choices=[(0, 'Debit'), (1, 'Credit')], default=0)),
                ('taxable_value', models.FloatField(default=0)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='je_item_account', to='accountingsettings.chartofaccounts')),
                ('business_partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='je_item_business_partner', to='saledata.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='je_items', to='journalentry.journalentry')),
            ],
            options={
                'verbose_name': 'Journal Entry Item',
                'verbose_name_plural': 'Journal Entry Items',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
