# Generated by Django 4.2.8 on 2025-11-05 14:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_email_app_password_and_more'),
        ('saledata', '0086_product_is_representative_product_and_more'),
        ('accountingsettings', '0003_alter_defaultaccountdetermination_options_and_more'),
        ('tenant', '0001_initial'),
        ('company', '0023_companyconfig_shift_companyconfig_shift_data_and_more'),
        ('journalentry', '0003_alter_journalentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('account_data', models.JSONField(default=dict)),
                ('je_line_type', models.SmallIntegerField(choices=[(0, 'Debit'), (1, 'Credit')], default=0)),
                ('product_mapped_data', models.JSONField(default=dict)),
                ('business_partner_data', models.JSONField(default=dict)),
                ('business_employee_data', models.JSONField(default=dict)),
                ('debit', models.FloatField(default=0)),
                ('credit', models.FloatField(default=0)),
                ('is_fc', models.BooleanField(default=False)),
                ('currency_mapped_data', models.JSONField(default=dict)),
                ('taxable_value', models.FloatField(default=0)),
                ('use_for_recon', models.BooleanField(default=False)),
                ('use_for_recon_type', models.CharField(blank=True, max_length=100)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='je_line_account', to='accountingsettings.chartofaccounts')),
                ('business_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='je_line_business_employee', to='hr.employee')),
                ('business_partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='je_line_business_partner', to='saledata.account')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('currency_mapped', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='saledata.currency')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Journal Entry Line',
                'verbose_name_plural': 'Journal Entry Lines',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='je_state',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Posted'), (2, 'Reversed')], default=0),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='period_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='je_period_mapped', to='saledata.periods'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='je_reversed_by', to='journalentry.journalentry'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sub_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='je_sub_period', to='saledata.subperiods'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sub_period_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='total_credit',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='total_debit',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='JournalEntryItem',
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='je_lines', to='journalentry.journalentry'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='product_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='je_line_product_mapped', to='saledata.product'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
    ]
