# Generated by Django 4.2.8 on 2024-01-11 18:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0005_collabinworkflow_is_edit_all_zone_and_more'),
        ('hr', '0002_employee_avatar_img'),
        ('company', '0008_company_email_app_password_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenuePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('group_mapped_list', models.JSONField(default=list)),
                ('monthly', models.BooleanField(default=False)),
                ('quarterly', models.BooleanField(default=False)),
                ('auto_sum_target', models.BooleanField(default=False)),
                ('company_month_target', models.JSONField(default=list)),
                ('company_quarter_target', models.JSONField(default=list)),
                ('company_year_target', models.FloatField()),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('current_stage', models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('next_node_collab', models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Revenue Plan',
                'verbose_name_plural': 'Revenue Plans',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RevenuePlanGroupEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emp_month_target', models.JSONField(default=list)),
                ('emp_quarter_target', models.JSONField(default=list)),
                ('emp_year_target', models.FloatField()),
                ('employee_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('revenue_plan_group_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_plan_group_mapped', to='hr.group')),
                ('revenue_plan_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_plan_mapped_group_employee', to='revenue_plan.revenueplan')),
            ],
            options={
                'verbose_name': 'Revenue Plan Group Employee',
                'verbose_name_plural': 'Revenue Plans Groups Employees',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RevenuePlanGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_month_target', models.JSONField(default=list)),
                ('group_quarter_target', models.JSONField(default=list)),
                ('group_year_target', models.FloatField()),
                ('employee_mapped_list', models.JSONField(default=list)),
                ('group_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.group')),
                ('revenue_plan_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_plan_mapped_group', to='revenue_plan.revenueplan')),
            ],
            options={
                'verbose_name': 'Revenue Plan Group',
                'verbose_name_plural': 'Revenue Plans Groups',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
