# Generated by Django 4.2.8 on 2024-01-11 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0005_collabinworkflow_is_edit_all_zone_and_more'),
        ('tenant', '0001_initial'),
        ('space', '0001_initial'),
        ('saledata', '0008_revenueplanconfig_revenueplanconfigroles_periods'),
        ('process', '0001_initial'),
        ('revenue_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueplan',
            name='period_mapped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.periods'),
        ),
        migrations.AddField(
            model_name='revenueplan',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='revenueplan',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='revenueplan',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='revenueplan',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
    ]
