# Generated by Django 4.2.8 on 2024-01-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue_plan', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenueplan',
            name='company_month_profit_target',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='revenueplan',
            name='company_quarter_profit_target',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='revenueplan',
            name='company_year_profit_target',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='revenueplan',
            name='profit_target_type',
            field=models.SmallIntegerField(choices=[(0, 'Gross profit'), (1, 'Net income')], default=0),
        ),
        migrations.AddField(
            model_name='revenueplangroup',
            name='group_month_profit_target',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='revenueplangroup',
            name='group_quarter_profit_target',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='revenueplangroup',
            name='group_year_profit_target',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='emp_month_profit_target',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='emp_quarter_profit_target',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='emp_year_profit_target',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='revenueplan',
            name='company_year_target',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='revenueplangroup',
            name='group_year_target',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='revenueplangroupemployee',
            name='emp_year_target',
            field=models.FloatField(default=0),
        ),
    ]
