# Generated by Django 4.2.8 on 2024-03-06 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_avatar_img'),
        ('revenue_plan', '0003_revenueplan_company_month_profit_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenueplangroupemployee',
            name='employee_mapped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rp_group_employee_employee', to='hr.employee'),
        ),
    ]
