# Generated by Django 4.2.8 on 2025-01-26 00:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0009_processmembers_is_system_and_more'),
        ('company', '0015_companybankaccount'),
        ('workflow', '0008_alter_collabinworkflow_position_choice'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('tenant', '0001_initial'),
        ('space', '0001_initial'),
        ('revenue_plan', '0008_revenueplan_process_stage_app'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenueplangroupemployee',
            options={'default_permissions': (), 'ordering': ('employee_mapped__code',), 'permissions': (), 'verbose_name': 'Revenue Plan Group Employee', 'verbose_name_plural': 'Revenue Plans Groups Employees'},
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='current_stage',
            field=models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc'),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='current_stage_title',
            field=models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='date_approved',
            field=models.DateTimeField(help_text='The record created when WF of document is finished', null=True),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value'),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='document_change_order',
            field=models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='document_root_id',
            field=models.UUIDField(help_text='this is id of root document of the changed documents', null=True),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='is_change',
            field=models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents'),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='next_node_collab',
            field=models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='process_stage_app',
            field=models.ForeignKey(help_text='The process stage app claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.processstageapplication'),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='system_remarks',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='system_status',
            field=models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))"),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='revenueplangroupemployee',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
    ]
