# Generated by Django 4.1.3 on 2022-12-27 16:38

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0003_alter_tenant_sub_domain'),
        ('hr', '0003_employee_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('user_created', models.UUIDField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_modified', models.UUIDField(null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('mode', models.IntegerField(choices=[(0, 'Global'), (1, 'Private'), (2, 'Team')], default=0)),
                ('mode_id', models.UUIDField(null=True)),
                ('description', models.CharField(blank=True, max_length=600, null=True, verbose_name='group description')),
                ('group_employee', jsonfield.fields.JSONField(default=[], null=True, verbose_name='group employee')),
                ('first_manager_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='first manager title')),
                ('second_manager_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='second manager title')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.company')),
                ('first_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_first_manager', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
            managers=[
                ('object_global', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GroupLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('user_created', models.UUIDField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_modified', models.UUIDField(null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('mode', models.IntegerField(choices=[(0, 'Global'), (1, 'Private'), (2, 'Team')], default=0)),
                ('mode_id', models.UUIDField(null=True)),
                ('level', models.IntegerField(null=True, verbose_name='group level')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='group level description')),
                ('first_manager_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='first manager description')),
                ('second_manager_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='second manager description')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.company')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Group Level',
                'verbose_name_plural': 'Group Levels',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
            managers=[
                ('object_global', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GroupEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('role', jsonfield.fields.JSONField(default=[], null=True, verbose_name='role')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_employee_employee', to='hr.employee')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_employee_group', to='organization.group')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
            managers=[
                ('object_normal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='group_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.grouplevel'),
        ),
        migrations.AddField(
            model_name='group',
            name='parent_n',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_parent_n', to='organization.group', verbose_name='parent group'),
        ),
        migrations.AddField(
            model_name='group',
            name='second_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_second_manager', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='group',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.tenant'),
        ),
    ]
