# Generated by Django 4.1.3 on 2022-12-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouplevel',
            options={'default_permissions': (), 'ordering': ('level',), 'permissions': (), 'verbose_name': 'Group Level', 'verbose_name_plural': 'Group Levels'},
        ),
    ]
