# Generated by Django 4.1.3 on 2023-01-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_grouplevel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active status'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='delete'),
        ),
    ]
