# Generated by Django 4.2.8 on 2025-05-20 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arinvoice', '0015_remove_arinvoiceitems_product_discount_rate_and_more'),
        ('apinvoice', '0008_rename_po_mapped_apinvoice_purchase_order_mapped_and_more'),
        ('paymentplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='ap_invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan_ap_invoice', to='apinvoice.apinvoice', verbose_name='ap invoice'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='ap_invoice_data',
            field=models.JSONField(default=dict, help_text='data json of ap_invoice'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='ar_invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan_ar_invoice', to='arinvoice.arinvoice', verbose_name='ar invoice'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='ar_invoice_data',
            field=models.JSONField(default=dict, help_text='data json of ar_invoice'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='invoice_actual_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='invoice_planned_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='value_balance',
            field=models.FloatField(default=0),
        ),
    ]
