# Generated by Django 4.2.8 on 2025-06-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentplan', '0002_paymentplan_ap_invoice_paymentplan_ap_invoice_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentplan',
            options={'default_permissions': (), 'ordering': ('due_date',), 'permissions': (), 'verbose_name': 'Payment Plan', 'verbose_name_plural': 'Payment Plans'},
        ),
    ]
