# Generated by Django 4.2.8 on 2025-11-04 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseorder', '0016_remove_leaseorderproduct_offset_and_more'),
        ('paymentplan', '0003_alter_paymentplan_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='lease_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan_lease_order', to='leaseorder.leaseorder'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='lease_order_data',
            field=models.JSONField(default=dict, help_text='data json of lease_order'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='lo_payment_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_plan_lo_payment_stage', to='leaseorder.leaseorderpaymentstage', verbose_name='payment stage'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='lo_payment_stage_data',
            field=models.JSONField(default=dict, help_text='data json of lo_payment_stage'),
        ),
    ]
