# Generated by Django 4.2.8 on 2025-02-14 16:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apinvoice', '0007_apinvoiceitems_increased_fa_value'),
        ('hr', '0004_employee_email_app_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('is_change', models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents')),
                ('document_root_id', models.UUIDField(help_text='this is id of root document of the changed documents', null=True)),
                ('document_change_order', models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Using'), (1, 'Leased')], default=0)),
                ('source_type', models.PositiveSmallIntegerField(choices=[(0, 'New Purchase'), (1, 'Financial Lease'), (2, 'Taken from Goods, Finished Products'), (3, 'Capital Construction Investment'), (4, 'Capital Contribution, Sponsorship, Donation'), (5, 'Exchange')], default=0)),
                ('original_cost', models.FloatField(default=0)),
                ('accumulative_depreciation', models.FloatField(default=0)),
                ('net_book_value', models.FloatField(default=0)),
                ('depreciation_method', models.PositiveSmallIntegerField(choices=[(0, 'Straight line depreciation'), (1, 'Adjusted reducing balance')], default=0)),
                ('depreciation_time', models.PositiveIntegerField(default=0)),
                ('depreciation_time_unit', models.PositiveSmallIntegerField(choices=[(0, 'Month'), (1, 'Year')], default=0)),
                ('adjustment_factor', models.FloatField(null=True)),
                ('depreciation_start_date', models.DateTimeField()),
                ('depreciation_end_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Fixed Asset',
                'verbose_name_plural': 'Fixed Assets',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FixedAssetUseDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fixed_asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='use_departments', to='asset.fixedasset')),
                ('use_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='hr.group')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FixedAssetSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('document_no', models.CharField(max_length=150)),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(0, 'AP Invoice'), (1, 'Journal Entry')], default=0)),
                ('code', models.CharField(max_length=150)),
                ('value', models.FloatField()),
                ('fixed_asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_sources', to='asset.fixedasset')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FixedAssetAPInvoiceItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('increased_FA_value', models.FloatField(default=0)),
                ('ap_invoice_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets', to='apinvoice.apinvoiceitems')),
                ('fixed_asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_invoice_items', to='asset.fixedasset')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
