# Generated by Django 4.2.8 on 2025-02-18 21:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apinvoice', '0007_apinvoiceitems_increased_fa_value'),
        ('tenant', '0001_initial'),
        ('workflow', '0008_alter_collabinworkflow_position_choice'),
        ('space', '0001_initial'),
        ('saledata', '0054_toolclassification_fixedassetclassificationgroup_and_more'),
        ('process', '0009_processmembers_is_system_and_more'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('company', '0015_companybankaccount'),
        ('asset', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentTool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('is_change', models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents')),
                ('document_root_id', models.UUIDField(help_text='this is id of root document of the changed documents', null=True)),
                ('document_change_order', models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('asset_code', models.CharField(blank=True, max_length=100)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Using'), (1, 'Leased')], default=0)),
                ('source_type', models.PositiveSmallIntegerField(choices=[(0, 'New Purchase'), (1, 'Financial Lease'), (2, 'Taken from Goods, Finished Products'), (3, 'Capital Construction Investment'), (4, 'Capital Contribution, Sponsorship, Donation'), (5, 'Exchange')], default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('total_value', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('measure_unit', models.CharField(max_length=150)),
                ('depreciation_time', models.PositiveIntegerField(default=0)),
                ('depreciation_time_unit', models.PositiveSmallIntegerField(choices=[(0, 'Month'), (1, 'Year')], default=0)),
                ('depreciation_start_date', models.DateTimeField()),
                ('depreciation_end_date', models.DateTimeField()),
                ('classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_instrument_tools', to='saledata.toolclassification')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('current_stage', models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('manage_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_instrument_tools', to='hr.group')),
                ('next_association', models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association')),
                ('next_node_collab', models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee')),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
                ('process_stage_app', models.ForeignKey(help_text='The process stage app claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.processstageapplication')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_instrument_tools', to='saledata.product')),
                ('space', models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('use_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_instrument_tools', to='saledata.account')),
                ('workflow_runtime', models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc')),
            ],
            options={
                'verbose_name': 'Fixed Asset',
                'verbose_name_plural': 'Fixed Assets',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='asset_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='depreciation_value',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='InstrumentToolUseDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument_tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='use_departments', to='asset.instrumenttool')),
                ('use_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instrument_tools', to='hr.group')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InstrumentToolSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('document_no', models.CharField(max_length=150)),
                ('transaction_type', models.PositiveSmallIntegerField(choices=[(0, 'AP Invoice'), (1, 'Journal Entry')], default=0)),
                ('code', models.CharField(max_length=150)),
                ('value', models.FloatField()),
                ('instrument_tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_sources', to='asset.instrumenttool')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InstrumentToolAPInvoiceItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('increased_FA_value', models.FloatField(default=0)),
                ('ap_invoice_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrument_tools', to='apinvoice.apinvoiceitems')),
                ('instrument_tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_invoice_items', to='asset.instrumenttool')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
