# Generated by Django 4.2.8 on 2025-03-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_alter_fixedasset_depreciation_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedasset',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Using'), (1, 'Leased'), (2, 'Delivered'), (3, 'Under Maintenance'), (4, 'Fully Depreciated')], default=0),
        ),
    ]
