# Generated by Django 4.2.8 on 2025-02-27 09:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_alter_instrumenttool_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumenttool',
            name='write_off_quantity',
        ),
        migrations.CreateModel(
            name='InstrumentToolWriteOffQuantity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('write_off_quantity', models.IntegerField()),
                ('instrument_tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_off_quantities', to='asset.instrumenttool')),
                ('instrument_tool_write_off', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='asset.instrumenttoolwriteoff')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
