# Generated by Django 4.2.8 on 2025-03-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_alter_fixedasset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumenttool',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Using'), (1, 'Leased'), (2, 'Delivered'), (3, 'Under Maintenance'), (4, 'Fully Depreciated')], default=0),
        ),
    ]
