# Generated by Django 4.2.8 on 2025-03-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_alter_instrumenttool_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumenttool',
            name='allocated_quantity',
            field=models.PositiveIntegerField(default=0, help_text='quantity of allocated instruments and tools'),
        ),
    ]
