# Generated by Django 4.2.8 on 2025-06-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_instrumenttool_allocated_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumenttool',
            name='quantity_leased',
            field=models.FloatField(default=0, help_text='quantity that currently leased'),
        ),
    ]
