# Generated by Django 4.2.8 on 2025-12-19 17:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accountingsettings', '0012_jedocumenttype_current_stage_and_more'),
        ('tenant', '0001_initial'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('financialcashflow', '0007_rename_company_bank_account_data_cashoutflow_account_bank_account_data_and_more'),
        ('apinvoice', '0010_alter_apinvoiceitems_product_quantity'),
        ('saledata', '0087_product_asset_category'),
        ('company', '0023_companyconfig_shift_companyconfig_shift_data_and_more'),
        ('asset', '0010_fixedasset_asset_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAssetApInvoicePurchaseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('total_register_value', models.FloatField(default=0)),
                ('ap_invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_purchase_items', to='apinvoice.apinvoice')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FixedAssetApInvoicePurchaseItemDetailProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('ap_invoice_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_invoice_item_detail_products', to='apinvoice.apinvoiceitems')),
                ('ap_invoice_purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_products', to='asset.fixedassetapinvoicepurchaseitem')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FixedAssetCashOutPurchaseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('total_register_value', models.FloatField(default=0)),
                ('cash_out', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_purchase_items', to='financialcashflow.cashoutflow')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FixedAssetDepreciation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('period_months', models.FloatField()),
                ('accumulated_months', models.FloatField()),
                ('period_depreciation', models.FloatField()),
                ('accumulated_depreciation', models.FloatField()),
                ('is_posted', models.BooleanField()),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FixedAssetInventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('tracking_number', models.TextField()),
                ('tracking_method', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Batch/Lot number'), (2, 'Serial number')], default=0)),
                ('total_register_value', models.FloatField(default=0)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='fixedassetsource',
            name='fixed_asset',
        ),
        migrations.RemoveField(
            model_name='fixedasset',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='fixedasset',
            name='product',
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='accumulated_depreciation_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accumulated_depreciation_assets', to='accountingsettings.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='asset_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_account_assets', to='accountingsettings.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='depreciation_expense_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_expense_assets', to='accountingsettings.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='last_posted_date',
            field=models.DateField(help_text='latest date which asset run depreciation', null=True),
        ),
        migrations.AddField(
            model_name='fixedassetusedepartment',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fixedassetusedepartment',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='fixedassetusedepartment',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value'),
        ),
        migrations.AddField(
            model_name='fixedassetusedepartment',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
        migrations.AddField(
            model_name='fixedassetusedepartment',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='fixedassetusedepartment',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='fixedassetusedepartment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fixedassetusedepartment',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixedassetusedepartment',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='fixedassetusedepartment',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='source_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Transfer from Inventory'), (1, 'Purchase Fixed Assets'), (2, 'Self-Manufactured Fixed Assets'), (3, 'Capital Construction Investment'), (4, 'Donation / Sponsorship'), (5, 'Receive Capital Contribution')], default=0),
        ),
        migrations.DeleteModel(
            name='FixedAssetAPInvoiceItems',
        ),
        migrations.DeleteModel(
            name='FixedAssetSource',
        ),
        migrations.AddField(
            model_name='fixedassetinventoryitem',
            name='fixed_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='asset.fixedasset'),
        ),
        migrations.AddField(
            model_name='fixedassetinventoryitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_inventory_items', to='saledata.product'),
        ),
        migrations.AddField(
            model_name='fixedassetinventoryitem',
            name='product_warehouse_lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_warehouse_lot_inventory_items', to='saledata.productwarehouselot'),
        ),
        migrations.AddField(
            model_name='fixedassetinventoryitem',
            name='product_warehouse_serial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_warehouse_serial_inventory_items', to='saledata.productwarehouseserial'),
        ),
        migrations.AddField(
            model_name='fixedassetinventoryitem',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='fixedassetinventoryitem',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_inventory_items', to='saledata.warehouse'),
        ),
        migrations.AddField(
            model_name='fixedassetdepreciation',
            name='fixed_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciations', to='asset.fixedasset'),
        ),
        migrations.AddField(
            model_name='fixedassetdepreciation',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='fixedassetcashoutpurchaseitem',
            name='fixed_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_out_purchase_items', to='asset.fixedasset'),
        ),
        migrations.AddField(
            model_name='fixedassetcashoutpurchaseitem',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='fixedassetapinvoicepurchaseitem',
            name='fixed_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ap_purchase_items', to='asset.fixedasset'),
        ),
        migrations.AddField(
            model_name='fixedassetapinvoicepurchaseitem',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
    ]
