# Generated by Django 4.2.8 on 2024-05-29 21:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('opportunity', '0009_opportunityactivitylogs_doc_data'),
        ('hr', '0003_alter_group_unique_together_and_more'),
        ('saledata', '0024_remove_product_sale_cost'),
        ('company', '0009_company_software_start_using_time'),
        ('lead', '0002_alter_lead_options_alter_leadstage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='leadconfig',
            name='account_select',
        ),
        migrations.RemoveField(
            model_name='leadconfig',
            name='convert_account_create',
        ),
        migrations.RemoveField(
            model_name='leadconfig',
            name='convert_account_select',
        ),
        migrations.RemoveField(
            model_name='leadconfig',
            name='opp_select',
        ),
        migrations.AddField(
            model_name='lead',
            name='period_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='saledata.periods'),
        ),
        migrations.AddField(
            model_name='leadconfig',
            name='account_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_account_mapped', to='saledata.account'),
        ),
        migrations.AddField(
            model_name='leadconfig',
            name='opp_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_opp_mapped', to='opportunity.opportunity'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.SmallIntegerField(choices=[(1, 'Prospect'), (2, 'Open - not contacted'), (3, 'Working'), (4, 'Opportunity created'), (5, 'Disqualified'), (6, 'Not a target')], default=0),
        ),
        migrations.AlterField(
            model_name='leadconfig',
            name='assign_to_sale_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_assign_to_sale_config', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='leadconfig',
            name='contact_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_contact_mapped', to='saledata.contact'),
        ),
        migrations.CreateModel(
            name='LeadHint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_mobile', models.CharField(max_length=100, null=True)),
                ('customer_email', models.CharField(max_length=150, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_customer_hint', to='saledata.account')),
                ('opportunity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_opp_hint', to='opportunity.opportunity')),
            ],
            options={
                'verbose_name': 'Lead Hint',
                'verbose_name_plural': 'Lead Hints',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LeadChartInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_amount_information', models.JSONField(default=dict)),
                ('stage_amount_information', models.JSONField(default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('period_mapped', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.periods')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Lead Chart Information',
                'verbose_name_plural': 'Lead Charts Information',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
