# Generated by Django 4.2.8 on 2024-12-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_lead_process_stage_app_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadopportunity',
            options={'default_permissions': (), 'ordering': ('-date_created',), 'permissions': (), 'verbose_name': 'Leads Opportunity', 'verbose_name_plural': 'Lead Opportunity'},
        ),
    ]
