# Generated by Django 4.1.3 on 2023-11-11 23:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('sale_code_type', models.SmallIntegerField(choices=[(0, 'Sale'), (1, 'Purchase'), (2, 'None-sale')], help_text='0 is Sale, 1 is Purchase, 2 is None-sale')),
                ('advance_payment_type', models.SmallIntegerField(choices=[(0, 'For Employee'), (1, 'For Supplier')], default=False, help_text='0 is For Employee, 1 is For Supplier', verbose_name='AdvancePayment type')),
                ('method', models.SmallIntegerField(choices=[(0, 'Cash'), (1, 'Bank Transfer')], help_text='0 is Cash, 1 is Bank Transfer', verbose_name='AdvancePayment method')),
                ('return_date', models.DateTimeField()),
                ('money_gave', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'Advance Payment',
                'verbose_name_plural': 'Advances Payments',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AdvancePaymentCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_name', models.CharField(max_length=150, null=True)),
                ('expense_uom_name', models.CharField(max_length=150, null=True)),
                ('expense_quantity', models.IntegerField()),
                ('expense_unit_price', models.FloatField(default=0)),
                ('expense_tax_price', models.FloatField(default=0)),
                ('expense_subtotal_price', models.FloatField(default=0)),
                ('expense_after_tax_price', models.FloatField(default=0)),
                ('sum_return_value', models.FloatField(default=0)),
                ('sum_converted_value', models.FloatField(default=0)),
                ('sum_real_value', models.FloatField(default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
            ],
            options={
                'verbose_name': 'Advance Payment Cost',
                'verbose_name_plural': 'Advance Payment Costs',
                'ordering': ('date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('sale_code_type', models.SmallIntegerField(choices=[(0, 'Sale'), (1, 'Purchase'), (2, 'None-sale'), (3, 'Others')], help_text='0 is Sale, 1 is Purchase, 2 is None-sale')),
                ('method', models.SmallIntegerField(choices=[(0, 'Cash'), (1, 'Bank Transfer')], help_text='0 is Cash, 1 is Bank Transfer', verbose_name='Payment method')),
                ('status', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Payment Config',
                'verbose_name_plural': 'Payment Configs',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PaymentCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_description', models.CharField(max_length=150, null=True)),
                ('expense_uom_name', models.CharField(max_length=150, null=True)),
                ('expense_quantity', models.IntegerField()),
                ('expense_unit_price', models.FloatField(default=0)),
                ('expense_tax_price', models.FloatField(default=0)),
                ('expense_subtotal_price', models.FloatField(default=0)),
                ('expense_after_tax_price', models.FloatField(default=0)),
                ('document_number', models.CharField(max_length=150)),
                ('real_value', models.FloatField(default=0)),
                ('converted_value', models.FloatField(default=0)),
                ('sum_value', models.FloatField(default=0)),
                ('ap_cost_converted_list', models.JSONField(default=list)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
            ],
            options={
                'verbose_name': 'Payment Cost',
                'verbose_name_plural': 'Payment Costs',
                'ordering': ('date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReturnAdvance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('method', models.SmallIntegerField(choices=[(0, 'Cash'), (1, 'Bank Transfer')], default=0, help_text='0 is Cash, 1 is Bank Transfer', verbose_name='method return')),
                ('status', models.SmallIntegerField(choices=[(0, 'Approved')], default=0, verbose_name='status of Return Advance')),
                ('return_total', models.FloatField(default=0)),
                ('money_received', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Return Advance',
                'verbose_name_plural': 'Return Advances',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReturnAdvanceCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_name', models.CharField(max_length=150, null=True)),
                ('remain_value', models.FloatField(default=0)),
                ('return_value', models.FloatField(default=0)),
                ('advance_payment_cost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advance_payment_cost', to='cashoutflow.advancepaymentcost')),
            ],
            options={
                'verbose_name': 'Return Advance Cost',
                'verbose_name_plural': 'Return Advance Costs',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
