# Generated by Django 4.1.3 on 2023-05-18 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0004_companyconfig'),
        ('space', '0001_initial'),
        ('hr', '0001_initial'),
        ('tenant', '0001_initial'),
        ('opportunity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saledata', '0016_remove_formulacondition_uom_and_more'),
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel')], default=0)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('sale_code_type', models.SmallIntegerField(help_text='0 is Sale, 1 is Purchase')),
                ('type', models.BooleanField(default=False, help_text='0 is For Employee, 1 is For Supplier')),
                ('supplier', models.UUIDField(null=True, verbose_name='Supplier mapped')),
                ('method', models.SmallIntegerField(help_text='0 is Cash, 1 is Bank Transfer', verbose_name='AdvancePayment method')),
                ('return_date', models.DateTimeField()),
                ('money_gave', models.BooleanField(default=False)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_beneficiary', to='hr.employee')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('creator_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_creator_name', to='hr.employee')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='User modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
                ('sale_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opportunity.opportunity')),
                ('space', models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Advance Payment',
                'verbose_name_plural': 'Advances Payments',
                'ordering': ('date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AdvancePaymentCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_quantity', models.IntegerField()),
                ('expense_unit_price', models.FloatField(default=0)),
                ('tax_price', models.FloatField(default=0)),
                ('subtotal_price', models.FloatField(default=0)),
                ('after_tax_price', models.FloatField(default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('advance_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashoutflow.advancepayment')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.currency')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.expense')),
                ('expense_unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.unitofmeasure')),
                ('tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.tax')),
            ],
            options={
                'verbose_name': 'Advance Payment Cost',
                'verbose_name_plural': 'Advance Payment Costs',
                'ordering': ('date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
