# Generated by Django 4.1.3 on 2023-05-19 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0001_initial'),
        ('quotation', '0004_quotation_total_product_discount_rate'),
        ('cashoutflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancepayment',
            name='sale_code',
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='quotation_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quotation.quotation'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='sale_order_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saleorder.saleorder'),
        ),
    ]
