# Generated by Django 4.1.3 on 2023-05-17 11:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0015_alter_warehouse_options'),
        ('cashoutflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancepayment',
            options={'default_permissions': (), 'ordering': ('date_created',), 'permissions': (), 'verbose_name': 'Advance Payment', 'verbose_name_plural': 'Advances Payments'},
        ),
        migrations.CreateModel(
            name='AdvancePaymentCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField(default=0)),
                ('tax_price', models.FloatField(default=0)),
                ('subtotal_price', models.FloatField(default=0)),
                ('after_tax_price', models.FloatField(default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('advance_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashoutflow.advancepayment')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.currency')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.expense')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.tax')),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Advance Payment Cost',
                'verbose_name_plural': 'Advance Payment Costs',
                'ordering': ('date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
