# Generated by Django 4.1.3 on 2023-05-24 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepaymentcost',
            name='advance_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_payment', to='cashoutflow.advancepayment'),
        ),
    ]
