# Generated by Django 4.1.3 on 2023-11-11 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotation', '0001_initial'),
        ('process', '0001_initial'),
        ('company', '0002_initial'),
        ('tenant', '0001_initial'),
        ('space', '0001_initial'),
        ('workflow', '0001_initial'),
        ('hr', '0001_initial'),
        ('cashoutflow', '0002_initial'),
        ('saleorder', '0001_initial'),
        ('opportunity', '0001_initial'),
        ('saledata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='opportunity_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_opportunity_mapped', to='opportunity.opportunity'),
        ),
        migrations.AddField(
            model_name='payment',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='payment',
            name='quotation_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_quotation_mapped', to='quotation.quotation'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sale_order_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_sale_order_mapped', to='saleorder.saleorder'),
        ),
        migrations.AddField(
            model_name='payment',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='payment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.account', verbose_name='Supplier mapped'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='payment',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
        migrations.AddField(
            model_name='advancepaymentcost',
            name='advance_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_payment', to='cashoutflow.advancepayment'),
        ),
        migrations.AddField(
            model_name='advancepaymentcost',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.currency'),
        ),
        migrations.AddField(
            model_name='advancepaymentcost',
            name='expense_tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.tax'),
        ),
        migrations.AddField(
            model_name='advancepaymentcost',
            name='expense_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.expenseitem'),
        ),
        migrations.AddField(
            model_name='advancepaymentcost',
            name='opportunity_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_cost_opportunity_mapped', to='opportunity.opportunity'),
        ),
        migrations.AddField(
            model_name='advancepaymentcost',
            name='quotation_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_cost_quotation_mapped', to='quotation.quotation'),
        ),
        migrations.AddField(
            model_name='advancepaymentcost',
            name='sale_order_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_cost_sale_order_mapped', to='saleorder.saleorder'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='creator_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_creator_name', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='current_stage',
            field=models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='opportunity_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_opportunity_mapped', to='opportunity.opportunity'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='quotation_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_quotation_mapped', to='quotation.quotation'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='sale_order_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_sale_order_mapped', to='saleorder.saleorder'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.account', verbose_name='Supplier mapped'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
    ]
