# Generated by Django 4.1.3 on 2023-05-29 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('space', '0001_initial'),
        ('process', '0001_initial'),
        ('tenant', '0001_initial'),
        ('company', '0004_companyconfig'),
        ('hr', '0001_initial'),
        ('saledata', '0021_alter_conditionlocation_options_and_more'),
        ('cashoutflow', '0002_alter_advancepaymentcost_advance_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnAdvance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel')], default=0)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('method', models.SmallIntegerField(choices=[(0, 'Cash'), (1, 'Bank Transfer')], default=0, help_text='0 is Cash, 1 is Bank Transfer', verbose_name='method return')),
                ('status', models.SmallIntegerField(choices=[(0, 'Approved')], default=0, verbose_name='status of Return Advance')),
                ('return_total', models.FloatField(default=0)),
                ('money_received', models.BooleanField(default=False)),
                ('advance_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_advance_payment', to='cashoutflow.advancepayment')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary', to='hr.employee')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_name', to='hr.employee')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='User modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
                ('space', models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Return Advance',
                'verbose_name_plural': 'Return Advances',
                'ordering': ('date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReturnAdvanceCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remain_total', models.FloatField(default=0)),
                ('return_price', models.FloatField(default=0)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_advance_expense', to='saledata.expense')),
                ('return_advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_advance', to='cashoutflow.returnadvance')),
            ],
            options={
                'verbose_name': 'Return Advance Cost',
                'verbose_name_plural': 'Return Advance Costs',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
