# Generated by Django 4.1.3 on 2023-06-02 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
        ('hr', '0001_initial'),
        ('space', '0001_initial'),
        ('company', '0004_companyconfig'),
        ('saledata', '0022_alter_account_annual_revenue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant', '0001_initial'),
        ('cashoutflow', '0003_returnadvance_returnadvancecost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel')], default=0)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('sale_code_mapped', models.JSONField(default=list)),
                ('sale_code_type', models.SmallIntegerField(choices=[(0, 'Sale'), (1, 'Purchase'), (2, 'None-sale'), (3, 'Others')], help_text='0 is Sale, 1 is Purchase, 2 is None-sale, 3 is Others')),
                ('method', models.SmallIntegerField(choices=[(0, 'Cash'), (1, 'Bank Transfer')], help_text='0 is Cash, 1 is Bank Transfer', verbose_name='Payment method')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_beneficiary', to='hr.employee')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('creator_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_creator_name', to='hr.employee')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='User modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
                ('space', models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.account', verbose_name='Supplier mapped')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PaymentCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_quantity', models.IntegerField()),
                ('expense_unit_price', models.FloatField(default=0)),
                ('tax_price', models.FloatField(default=0)),
                ('subtotal_price', models.FloatField(default=0)),
                ('after_tax_price', models.FloatField(default=0)),
                ('document_number', models.CharField(max_length=150)),
                ('expense_ap_detail_list', models.JSONField(default=list)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.currency')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.expense')),
                ('expense_unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.unitofmeasure')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='cashoutflow.payment')),
                ('tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.tax')),
            ],
            options={
                'verbose_name': 'Payment Cost',
                'verbose_name_plural': 'Payment Costs',
                'ordering': ('date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PaymentCostItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_code_mapped', models.UUIDField(null=True)),
                ('real_value', models.FloatField(default=0, help_text='Value which is NOT CONVERTED from Advance Payment')),
                ('value_converted', models.FloatField(default=0, help_text='Value which is CONVERTED from Advance Payment')),
                ('sum_value', models.FloatField(default=0, help_text='Sum value (include real_value and value_converted')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('payment_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_cost', to='cashoutflow.paymentcost')),
            ],
            options={
                'verbose_name': 'Payment Cost Items',
                'verbose_name_plural': 'Payment Costs Items',
                'ordering': ('date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='advancepaymentcost',
            name='sum_converted_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='advancepaymentcost',
            name='sum_return_value',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='PaymentCostItemsDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_value_converted', models.FloatField(default=0, help_text='Value which is CONVERTED from Advance Payment Expense')),
                ('return_remain_value_after', models.FloatField(default=0, help_text='Remain value which is returned after converted')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('advance_payment_converted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_payment_converted', to='cashoutflow.advancepayment')),
                ('expense_converted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_converted', to='cashoutflow.advancepaymentcost')),
                ('payment_cost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_cost_item', to='cashoutflow.paymentcostitems')),
            ],
            options={
                'verbose_name': 'Payment Cost Item Detail',
                'verbose_name_plural': 'Payment Cost Item Details',
                'ordering': ('date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
