# Generated by Django 4.1.3 on 2023-06-05 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0004_advancepayment_workflow_runtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnadvancecost',
            old_name='remain_total',
            new_name='remain_value',
        ),
        migrations.RenameField(
            model_name='returnadvancecost',
            old_name='return_price',
            new_name='return_value',
        ),
        migrations.RemoveField(
            model_name='returnadvancecost',
            name='expense',
        ),
        migrations.AddField(
            model_name='returnadvancecost',
            name='advance_payment_cost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advance_payment_cost', to='cashoutflow.advancepaymentcost'),
        ),
    ]
