# Generated by Django 4.1.3 on 2023-11-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_remove_quotationexpense_payment_plan_real_value'),
        ('opportunity', '0002_initial'),
        ('saleorder', '0004_remove_saleorderexpense_payment_plan_real_value'),
        ('cashoutflow', '0004_remove_advancepaymentcost_sum_real_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcost',
            name='opportunity_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_cost_opportunity_mapped', to='opportunity.opportunity'),
        ),
        migrations.AddField(
            model_name='paymentcost',
            name='quotation_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_cost_quotation_mapped', to='quotation.quotation'),
        ),
        migrations.AddField(
            model_name='paymentcost',
            name='sale_order_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_cost_sale_order_mapped', to='saleorder.saleorder'),
        ),
    ]
