# Generated by Django 4.1.3 on 2023-06-02 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0004_payment_paymentcost_paymentcostitems_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentcostitems',
            old_name='value_converted',
            new_name='converted_value',
        ),
    ]
