# Generated by Django 4.1.3 on 2023-06-02 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0004_payment_paymentcost_paymentcostitems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcostitemsdetail',
            name='expense_converted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_converted', to='cashoutflow.advancepaymentcost'),
        ),
    ]
