# Generated by Django 4.1.3 on 2023-05-17 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0015_alter_warehouse_options'),
        ('cashoutflow', '0004_rename_tax_advancepaymentcost_tax_mapped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepaymentcost',
            name='tax_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.tax'),
        ),
    ]
