# Generated by Django 4.1.3 on 2023-11-29 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('saledata', '0003_product_is_public_website_product_price_list_and_more'),
        ('cashoutflow', '0005_paymentcost_opportunity_mapped_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='employee_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='Employee payment mapped'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_internal_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Cash'), (2, 'Bank Transfer')], help_text='0 is None, 1 is Cash, 2 is Bank Transfer', verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.account', verbose_name='Supplier mapped'),
        ),
    ]
