# Generated by Django 4.1.3 on 2023-12-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0006_payment_employee_payment_payment_is_internal_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancepayment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
