# Generated by Django 4.1.3 on 2023-06-14 10:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saleorder', '0005_saleordercost_is_shipping_saleordercost_shipping'),
        ('opportunity', '0002_opportunity_workflow_runtime_and_more'),
        ('quotation', '0010_quotationcost_is_shipping_quotationcost_shipping'),
        ('cashoutflow', '0006_payment_paymentcost_paymentcostitems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='opportunity_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_opportunity_mapped', to='opportunity.opportunity'),
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='quotation_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_quotation_mapped', to='quotation.quotation'),
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='sale_order_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_sale_order_mapped', to='saleorder.saleorder'),
        ),
        migrations.CreateModel(
            name='PaymentOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opportunity_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunity.opportunity')),
                ('payment_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashoutflow.payment')),
            ],
            options={
                'verbose_name': 'Payment Opportunity',
                'verbose_name_plural': 'Payments Opportunitys',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='opportunity_mapped',
            field=models.ManyToManyField(blank=True, related_name='opportunity_mapped', through='cashoutflow.PaymentOpportunity', to='opportunity.opportunity'),
        ),
    ]
