# Generated by Django 4.2.8 on 2023-12-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0007_remove_advancepayment_status_remove_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnadvance',
            name='status',
        ),
    ]
