# Generated by Django 4.1.3 on 2023-07-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0034_remove_expense_general_information_and_more'),
        ('cashoutflow', '0008_alter_returnadvance_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancepaymentcost',
            old_name='expense_quantity',
            new_name='product_quantity',
        ),
        migrations.RenameField(
            model_name='advancepaymentcost',
            old_name='expense_unit_of_measure',
            new_name='product_unit_of_measure',
        ),
        migrations.RenameField(
            model_name='advancepaymentcost',
            old_name='expense_unit_price',
            new_name='product_unit_price',
        ),
        migrations.RemoveField(
            model_name='advancepaymentcost',
            name='expense',
        ),
        migrations.AddField(
            model_name='advancepaymentcost',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.product'),
        ),
    ]
