# Generated by Django 4.1.3 on 2023-07-19 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0034_remove_expense_general_information_and_more'),
        ('cashoutflow', '0008_alter_returnadvance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentopportunity',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'Payment Opportunity', 'verbose_name_plural': 'Payments Opportunities'},
        ),
        migrations.RenameField(
            model_name='advancepaymentcost',
            old_name='expense_quantity',
            new_name='product_quantity',
        ),
        migrations.RenameField(
            model_name='advancepaymentcost',
            old_name='expense_unit_of_measure',
            new_name='product_unit_of_measure',
        ),
        migrations.RenameField(
            model_name='advancepaymentcost',
            old_name='expense_unit_price',
            new_name='product_unit_price',
        ),
        migrations.RenameField(
            model_name='paymentcost',
            old_name='expense_ap_detail_list',
            new_name='product_ap_detail_list',
        ),
        migrations.RenameField(
            model_name='paymentcost',
            old_name='expense_quantity',
            new_name='product_quantity',
        ),
        migrations.RenameField(
            model_name='paymentcost',
            old_name='expense_unit_of_measure',
            new_name='product_unit_of_measure',
        ),
        migrations.RenameField(
            model_name='paymentcost',
            old_name='expense_unit_price',
            new_name='product_unit_price',
        ),
        migrations.RenameField(
            model_name='paymentcostitems',
            old_name='expense_items_detail_list',
            new_name='product_items_detail_list',
        ),
        migrations.RemoveField(
            model_name='advancepaymentcost',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='paymentcost',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='paymentcostitemsdetail',
            name='expense_converted',
        ),
        migrations.RemoveField(
            model_name='paymentcostitemsdetail',
            name='expense_value_converted',
        ),
        migrations.AddField(
            model_name='advancepaymentcost',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.product'),
        ),
        migrations.AddField(
            model_name='paymentcost',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.product'),
        ),
        migrations.AddField(
            model_name='paymentcostitemsdetail',
            name='product_converted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_converted', to='cashoutflow.advancepaymentcost'),
        ),
        migrations.AddField(
            model_name='paymentcostitemsdetail',
            name='product_value_converted',
            field=models.FloatField(default=0, help_text='Value which is CONVERTED from Advance Payment product'),
        ),
    ]
