# Generated by Django 4.2.8 on 2024-01-08 16:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_publicfiles_relate_app_publicfiles_relate_app_code_and_more'),
        ('cashoutflow', '0009_advancepayment_next_node_collab_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttachmentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('attachment', models.OneToOneField(help_text='Many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_files', to='attachments.files', verbose_name='Attachment files')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attachments', to='cashoutflow.payment')),
            ],
            options={
                'verbose_name': 'Payment attachment',
                'verbose_name_plural': 'Payment attachments',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AdvancePaymentAttachmentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('advance_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_payment_attachments', to='cashoutflow.advancepayment')),
                ('attachment', models.OneToOneField(help_text='Many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_files', to='attachments.files', verbose_name='Attachment files')),
            ],
            options={
                'verbose_name': 'Advance payment attachment',
                'verbose_name_plural': 'Advance payment attachments',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
