# Generated by Django 4.2.4 on 2023-09-10 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0048_expenseitem'),
        ('cashoutflow', '0010_alter_advancepayment_system_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancepaymentcost',
            old_name='after_tax_price',
            new_name='expense_after_tax_price',
        ),
        migrations.RenameField(
            model_name='advancepaymentcost',
            old_name='product_quantity',
            new_name='expense_quantity',
        ),
        migrations.RenameField(
            model_name='advancepaymentcost',
            old_name='product_unit_price',
            new_name='expense_subtotal_price',
        ),
        migrations.RenameField(
            model_name='advancepaymentcost',
            old_name='tax',
            new_name='expense_tax',
        ),
        migrations.RenameField(
            model_name='advancepaymentcost',
            old_name='subtotal_price',
            new_name='expense_tax_price',
        ),
        migrations.RenameField(
            model_name='advancepaymentcost',
            old_name='tax_price',
            new_name='expense_unit_price',
        ),
        migrations.RemoveField(
            model_name='advancepaymentcost',
            name='product',
        ),
        migrations.RemoveField(
            model_name='advancepaymentcost',
            name='product_unit_of_measure',
        ),
        migrations.AddField(
            model_name='advancepaymentcost',
            name='expense_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='advancepaymentcost',
            name='expense_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.expenseitem'),
        ),
        migrations.AddField(
            model_name='advancepaymentcost',
            name='expense_uom_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
