# Generated by Django 4.1.3 on 2023-09-15 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0049_remove_product_general_product_type_and_more'),
        ('cashoutflow', '0011_rename_after_tax_price_advancepaymentcost_expense_after_tax_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnadvancecost',
            name='expense_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='returnadvancecost',
            name='expense_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_advance_expense', to='saledata.expenseitem'),
        ),
    ]
