# Generated by Django 4.2.4 on 2023-09-12 17:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_employee_code_alter_employee_unique_together'),
        ('company', '0006_alter_company_code'),
        ('cashoutflow', '0011_rename_after_tax_price_advancepaymentcost_expense_after_tax_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_payment_config_detail', to='company.company')),
                ('employee_allowed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
            options={
                'verbose_name': 'Payment Config',
                'verbose_name_plural': 'Payment Configs',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
