# Generated by Django 4.2.4 on 2023-09-11 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0048_expenseitem'),
        ('cashoutflow', '0011_rename_after_tax_price_advancepaymentcost_expense_after_tax_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentcost',
            old_name='after_tax_price',
            new_name='expense_after_tax_price',
        ),
        migrations.RenameField(
            model_name='paymentcost',
            old_name='product_ap_detail_list',
            new_name='expense_ap_detail_list',
        ),
        migrations.RenameField(
            model_name='paymentcost',
            old_name='product_quantity',
            new_name='expense_quantity',
        ),
        migrations.RenameField(
            model_name='paymentcost',
            old_name='product_unit_price',
            new_name='expense_subtotal_price',
        ),
        migrations.RenameField(
            model_name='paymentcost',
            old_name='tax',
            new_name='expense_tax',
        ),
        migrations.RenameField(
            model_name='paymentcost',
            old_name='subtotal_price',
            new_name='expense_tax_price',
        ),
        migrations.RenameField(
            model_name='paymentcost',
            old_name='tax_price',
            new_name='expense_unit_price',
        ),
        migrations.RenameField(
            model_name='paymentcostitems',
            old_name='product_items_detail_list',
            new_name='expense_items_detail_list',
        ),
        migrations.RenameField(
            model_name='paymentcostitemsdetail',
            old_name='product_converted',
            new_name='expense_converted',
        ),
        migrations.RenameField(
            model_name='paymentcostitemsdetail',
            old_name='product_value_converted',
            new_name='expense_value_converted',
        ),
        migrations.RemoveField(
            model_name='paymentcost',
            name='product',
        ),
        migrations.RemoveField(
            model_name='paymentcost',
            name='product_unit_of_measure',
        ),
        migrations.AddField(
            model_name='paymentcost',
            name='expense_description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='paymentcost',
            name='expense_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.expenseitem'),
        ),
        migrations.AddField(
            model_name='paymentcost',
            name='expense_uom_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
