# Generated by Django 4.2.8 on 2024-07-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0011_advancepayment_document_change_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='advance_value',
            field=models.FloatField(default=0),
        ),
    ]
