# Generated by Django 4.2.8 on 2024-07-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0012_advancepayment_advance_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='sale_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='sale_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
