# Generated by Django 4.2.4 on 2023-09-12 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_code'),
        ('cashoutflow', '0012_paymentconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentconfig',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
