# Generated by Django 4.2.8 on 2024-08-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0013_advancepayment_sale_code_payment_payment_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='advance_value_by_words',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
