# Generated by Django 4.1.3 on 2023-09-29 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0013_paymentcostitems_sale_code_mapped_code_paymentconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnadvance',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='returnadvance',
            name='creator',
        ),
    ]
