# Generated by Django 4.2.4 on 2023-09-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0013_alter_paymentconfig_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcostitems',
            name='sale_code_mapped_code',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
