# Generated by Django 4.2.8 on 2024-08-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0014_advancepayment_advance_value_by_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
        migrations.AlterField(
            model_name='returnadvance',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
    ]
