# Generated by Django 4.2.8 on 2024-08-29 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0015_alter_advancepayment_date_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancepayment',
            name='creator_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='creator_name',
        ),
    ]
