# Generated by Django 4.2.8 on 2024-09-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0016_remove_advancepayment_creator_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepaymentcost',
            name='expense_quantity',
            field=models.FloatField(),
        ),
    ]
