# Generated by Django 4.1.3 on 2023-11-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0016_alter_advancepayment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
