# Generated by Django 4.2.8 on 2024-09-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0017_alter_advancepaymentcost_expense_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepaymentcost',
            name='expense_tax_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='advancepaymentcost',
            name='expense_type_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='paymentcost',
            name='expense_tax_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='paymentcost',
            name='expense_type_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='returnadvancecost',
            name='expense_type_data',
            field=models.JSONField(default=dict),
        ),
    ]
