# Generated by Django 4.1.3 on 2023-11-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0017_alter_advancepayment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancepayment',
            name='beneficiary',
        ),
    ]
