# Generated by Django 4.1.3 on 2023-11-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0020_rename_expense_ap_detail_list_paymentcost_ap_cost_converted_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepaymentcost',
            name='sum_real_value',
            field=models.FloatField(default=0),
        ),
    ]
