# Generated by Django 4.2.8 on 2024-11-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0014_opportunitycalllog_process_opportunityemail_process_and_more'),
        ('project', '0018_project_date_close'),
        ('cashoutflow', '0020_advancepayment_next_association_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='opportunity',
            field=models.ForeignKey(help_text='Relate to Opportunity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_opp', to='opportunity.opportunity'),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='project',
            field=models.ForeignKey(help_text='Relate to Project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_prj', to='project.project'),
        ),
        migrations.AddField(
            model_name='advancepaymentcost',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ap_cost_opportunity', to='opportunity.opportunity'),
        ),
        migrations.AddField(
            model_name='payment',
            name='opportunity',
            field=models.ForeignKey(help_text='Relate to Opportunity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_opp', to='opportunity.opportunity'),
        ),
        migrations.AddField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(help_text='Relate to Project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_prj', to='project.project'),
        ),
        migrations.AddField(
            model_name='paymentcost',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_cost_opportunity', to='opportunity.opportunity'),
        ),
    ]
