# Generated by Django 4.2.8 on 2025-04-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0022_advancepayment_process_stage_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='free_input',
            field=models.BooleanField(default=False),
        ),
    ]
