# Generated by Django 4.2.8 on 2025-05-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0024_advancepayment_advance_value_before_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_value_before_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_value_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='advancepayment',
            name='return_date',
            field=models.DateField(),
        ),
    ]
