# Generated by Django 4.2.8 on 2025-05-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0025_payment_payment_value_before_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepaymentcost',
            name='expense_description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='paymentcost',
            name='expense_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='returnadvancecost',
            name='expense_description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcost',
            name='expense_description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
