# Generated by Django 4.2.8 on 2025-05-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashoutflow', '0028_advancepayment_advance_date_advancepayment_bank_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancepayment',
            name='opportunity_mapped',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='opportunity_mapped',
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_data',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
