# Generated by Django 4.2.8 on 2024-03-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printtemplates',
            old_name='is_using',
            new_name='is_default',
        ),
    ]
