# Generated by Django 4.1.3 on 2023-11-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0002_expense_expense_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_public_website',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='price_list',
            field=models.ManyToManyField(blank=True, related_name='product_map_price', through='saledata.ProductPriceList', to='saledata.price'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.FloatField(default=0, help_text='General price in General price list'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_cost',
            field=models.FloatField(help_text='Capital price for sale', null=True),
        ),
    ]
