# Generated by Django 4.1.3 on 2023-12-08 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0003_product_is_public_website_product_price_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='online_price_list',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_price_list', to='saledata.price'),
        ),
    ]
