# Generated by Django 4.1.3 on 2023-12-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0004_product_online_price_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='available_notify_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
