# Generated by Django 4.2.8 on 2024-01-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0008_revenueplanconfig_revenueplanconfigroles_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='periods',
            name='planned',
            field=models.BooleanField(default=False),
        ),
    ]
