# Generated by Django 4.1.3 on 2023-05-09 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_currency'),
        ('saledata', '0010_account_bank_accounts_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.currency'),
        ),
    ]
