# Generated by Django 4.1.3 on 2023-05-12 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_currency'),
        ('saledata', '0010_account_bank_accounts_information_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountaccounttypes',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'Account AccountTypes', 'verbose_name_plural': 'Accounts AccountTypes'},
        ),
        migrations.AlterModelOptions(
            name='accountbanks',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'Account Banks', 'verbose_name_plural': 'Accounts Banks'},
        ),
        migrations.AlterModelOptions(
            name='accountcreditcards',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'Account Credit Cards', 'verbose_name_plural': 'Accounts Credit Cards'},
        ),
        migrations.AlterModelOptions(
            name='accountemployee',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'Account Employee', 'verbose_name_plural': 'Accounts Employees'},
        ),
        migrations.AddField(
            model_name='account',
            name='account_types_mapped',
            field=models.ManyToManyField(blank=True, related_name='account_map_account_types', through='saledata.AccountAccountTypes', to='saledata.accounttype'),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.contact'),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.currency'),
        ),
    ]
