# Generated by Django 4.2.8 on 2024-01-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0010_periods_space_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwarehouse',
            name='used_amount',
            field=models.FloatField(default=0, help_text='Amount product delivered for employee use', verbose_name='Used Amount'),
        ),
    ]
