# Generated by Django 4.1.3 on 2023-05-04 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0010_accountgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.accountgroup'),
        ),
    ]
