# Generated by Django 4.1.3 on 2023-05-06 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0011_account_account_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit_limit',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='payment_term_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.paymentterm'),
        ),
        migrations.AddField(
            model_name='account',
            name='price_list_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.price'),
        ),
    ]
