# Generated by Django 4.1.3 on 2023-05-12 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0004_companyconfig'),
        ('base', '0003_currency'),
        ('hr', '0001_initial'),
        ('saledata', '0011_currency_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('margin', models.FloatField(default=0, help_text='Cost of shipping', null=True)),
                ('cost_method', models.IntegerField(default=1, help_text='0 - fixed, 1 - formula, 2 - service provider', null=True)),
                ('fixed_price', models.FloatField(default=0, help_text='Amount while user select Fixed Price for shipping', null=True)),
                ('formula_condition', models.JSONField(default=dict, help_text='Condition while user select Formula for shipping', null=True)),
                ('service_provider', models.JSONField(default=dict, help_text='Condition while user select Service Provider for shipping', null=True)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_currency', to='saledata.currency', verbose_name='currency of shipping')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='User modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Ship',
                'verbose_name_plural': 'Ships',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ShippingCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('formula', models.JSONField(default=dict, help_text='formula for each condition')),
                ('location_condition', models.ManyToManyField(blank=True, related_name='location_map_condition', through='saledata.ConditionLocation', to='base.city')),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_shipping_condition', to='saledata.shipping')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FormulaCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comparison_operators', models.IntegerField(default=1, help_text='1 - <; 2 - >; 3 - <=; 4 - >=', null=True)),
                ('threshold', models.IntegerField(default=0, help_text='threshold of unit of measure for comparison operator', null=True)),
                ('amount_condition', models.FloatField(default=0, help_text='fixed price for each condition', null=True)),
                ('extra_amount', models.FloatField(default=0, help_text='extra for amount condition', null=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_condition', to='saledata.shippingcondition', verbose_name='formula of condition')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uom_condition', to='saledata.unitofmeasure')),
                ('uom_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uom_group_condition', to='saledata.unitofmeasuregroup')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='conditionlocation',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='saledata.shippingcondition'),
        ),
        migrations.AddField(
            model_name='conditionlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='base.city', verbose_name='location for shipping Formula'),
        ),
    ]
