# Generated by Django 4.1.3 on 2023-05-06 10:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_currency'),
        ('saledata', '0012_account_credit_limit_account_payment_term_mapped_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCreditCards',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_card_type', models.CharField(blank=True, max_length=150, null=True, verbose_name='Credit card type')),
                ('credit_card_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Credit card number')),
                ('credit_card_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Credit card name')),
                ('expired_date', models.DateTimeField(null=True, verbose_name='EXP date')),
                ('is_default', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.account')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AccountBanks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name of bank')),
                ('bank_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code of bank')),
                ('bank_account_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Bank account name')),
                ('bank_account_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Bank account number')),
                ('bic_swift_code', models.CharField(blank=True, max_length=150, null=True, verbose_name='BIC/SWIFT code')),
                ('is_default', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.account')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.country')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
