# Generated by Django 4.1.3 on 2023-05-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0013_accountcreditcards_accountbanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank_accounts_information',
            field=models.JSONField(default=list),
        ),
    ]
