# Generated by Django 4.1.3 on 2023-05-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0013_account_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
