# Generated by Django 4.1.3 on 2023-05-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0014_accounttype_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='account_type_order',
            field=models.IntegerField(null=True),
        ),
    ]
