# Generated by Django 4.1.3 on 2023-05-16 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_baseitemunit'),
        ('saledata', '0015_alter_warehouse_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulacondition',
            name='uom',
        ),
        migrations.RemoveField(
            model_name='formulacondition',
            name='uom_group',
        ),
        migrations.AddField(
            model_name='formulacondition',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='unit_condition', to='base.baseitemunit'),
        ),
    ]
