# Generated by Django 4.2.8 on 2024-04-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0015_accountactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subperiods',
            name='state',
        ),
        migrations.AddField(
            model_name='subperiods',
            name='locked',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='subperiods',
            name='run_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subperiods',
            name='run_report_detail',
            field=models.BooleanField(default=False),
        ),
    ]
