# Generated by Django 4.1.3 on 2023-05-22 14:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_baseitemunit'),
        ('saledata', '0016_remove_formulacondition_uom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='height',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='productsale',
            name='length',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='productsale',
            name='width',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='productgeneral',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_general', to='saledata.product'),
        ),
        migrations.AlterField(
            model_name='productgeneral',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_general_product_category', to='saledata.productcategory'),
        ),
        migrations.AlterField(
            model_name='productgeneral',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_general_product_type', to='saledata.producttype'),
        ),
        migrations.AlterField(
            model_name='productgeneral',
            name='uom_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_general_uom_group', to='saledata.unitofmeasuregroup'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inventory', to='saledata.product'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_inventory_uom', to='saledata.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='productpricelist',
            name='currency_using',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_currency', to='saledata.currency'),
        ),
        migrations.AlterField(
            model_name='productpricelist',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_price', to='saledata.price'),
        ),
        migrations.AlterField(
            model_name='productpricelist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_product', to='saledata.product'),
        ),
        migrations.AlterField(
            model_name='productpricelist',
            name='uom_group_using',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_uom_group', to='saledata.unitofmeasuregroup'),
        ),
        migrations.AlterField(
            model_name='productpricelist',
            name='uom_using',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_uom', to='saledata.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='currency_using',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sale_currency', to='saledata.currency'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='default_uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sale_uom', to='saledata.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sale', to='saledata.product'),
        ),
        migrations.AlterField(
            model_name='productsale',
            name='tax_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sale_tax', to='saledata.tax'),
        ),
        migrations.CreateModel(
            name='ProductMeasurements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('measure', models.ForeignKey(limit_choices_to={'title__in': ['volume', 'weight']}, on_delete=django.db.models.deletion.CASCADE, related_name='product_volume', to='base.baseitemunit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_measure', to='saledata.product')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
