# Generated by Django 4.2.8 on 2024-04-11 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('company', '0009_company_software_start_using_time'),
        ('hr', '0003_alter_group_unique_together_and_more'),
        ('saledata', '0017_account_document_change_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseEmployeeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('warehouse_list', models.JSONField(default=list)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_employees_emp', to='hr.employee')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Warehouse Employee Config',
                'verbose_name_plural': 'Warehouse Employee Configs',
                'ordering': ('date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'default_permissions': (), 'ordering': (), 'permissions': (), 'verbose_name': 'WareHouse storage', 'verbose_name_plural': 'WareHouse storage'},
        ),
        migrations.CreateModel(
            name='WarehouseEmployeeConfigDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wh_emp_config_detail_cf', to='saledata.warehouseemployeeconfig')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wh_emp_config_detail_wh', to='saledata.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Employee Config Detail',
                'verbose_name_plural': 'Warehouse Employee Configs Detail',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
