# Generated by Django 4.1.3 on 2023-05-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0017_productsale_height_productsale_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='account_type_order',
            field=models.IntegerField(choices=[(0, 'Customer'), (1, 'Supplier'), (2, 'Partner'), (3, 'Competitor')], null=True),
        ),
    ]
