# Generated by Django 4.2.8 on 2024-04-08 10:36

from django.db import migrations, models

from apps.shared import StringHandler


def unique_code_salutation(apps, schema_editor):
    salutation_cls = apps.get_model('saledata', 'salutation')
    for obj in salutation_cls.objects.all():
        if not obj.code:
            obj.code = StringHandler.random_str(10, 2)
            obj.save(update_fields=['code'])


def unique_code_contact(apps, schema_editor):
    contact_cls = apps.get_model('saledata', 'contact')
    for obj in contact_cls.objects.all():
        if not obj.code:
            obj.code = StringHandler.random_str(10, 2)
            obj.save(update_fields=['code'])


def unique_code_currency(apps, schema_editor):
    currency_cls = apps.get_model('saledata', 'currency')
    for obj in currency_cls.objects.all():
        if not obj.abbreviation:
            obj.abbreviation = StringHandler.random_str(10, 2)
            obj.save(update_fields=['code'])


def unique_code_account_group(apps, schema_editor):
    account_group_cls = apps.get_model('saledata', 'accountgroup')
    for obj in account_group_cls.objects.all():
        if not obj.code:
            obj.code = StringHandler.random_str(10, 2)
            obj.save(update_fields=['code'])


def unique_code_industry(apps, schema_editor):
    industry_cls = apps.get_model('saledata', 'industry')
    for obj in industry_cls.objects.all():
        if not obj.code:
            obj.code = StringHandler.random_str(10, 2)
            obj.save(update_fields=['code'])


def unique_code_payment_term(apps, schema_editor):
    payment_term_cls = apps.get_model('saledata', 'paymentterm')
    for obj in payment_term_cls.objects.all():
        if not obj.code:
            obj.code = StringHandler.random_str(10, 2)
            obj.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_software_start_using_time'),
        ('saledata', '0018_warehouseemployeeconfig_alter_warehouse_options_and_more'),
    ]

    operations = [
        # salutation unique code before unique together code + company
        migrations.RunPython(unique_code_salutation),
        migrations.AlterField(
            model_name='salutation',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='salutation',
            unique_together={('company', 'code')},
        ),

        # contact unique code before unique together code + company
        migrations.RunPython(unique_code_contact),
        migrations.AlterField(
            model_name='contact',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('company', 'code')},
        ),

        # currency
        migrations.RunPython(unique_code_currency),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('company', 'abbreviation')},
        ),

        # account group
        migrations.RunPython(unique_code_account_group),
        migrations.AlterUniqueTogether(
            name='accountgroup',
            unique_together={('company', 'code')},
        ),

        # industry
        migrations.RunPython(unique_code_industry),
        migrations.AlterUniqueTogether(
            name='industry',
            unique_together={('company', 'code')},
        ),

        # payment term
        migrations.RunPython(unique_code_payment_term),
        migrations.AlterField(
            model_name='paymentterm',
            name='apply_for',
            field=models.IntegerField(
                choices=[(0, 'Sale'), (1, 'Purchase')], default=0, help_text='Applicable subjects'
            ),
        ),
        migrations.AlterField(
            model_name='paymentterm',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='term',
            name='after',
            field=models.IntegerField(
                choices=[(0, ''), (1, 'Contract date'), (2, 'Delivery date'), (3, 'Invoice date'),
                         (4, 'Acceptance date'), (5, 'End of invoice month'), (6, 'Order date')], default=0,
                help_text='This value using with no_of_days. Terms available with these conditions when it is '
                          'activated',
                verbose_name='After'
            ),
        ),
        migrations.AlterField(
            model_name='term',
            name='day_type',
            field=models.IntegerField(
                choices=[(1, 'Workday'), (2, 'Calendar day')], default=0,
                help_text='The day calculation rule ends with the value no_of_days', verbose_name='Day type'
            ),
        ),
        migrations.AlterField(
            model_name='term',
            name='no_of_days',
            field=models.CharField(
                help_text='Amount of days from after is activated', max_length=30, verbose_name='Number of days'
            ),
        ),
        migrations.AlterField(
            model_name='term',
            name='order',
            field=models.IntegerField(default=1, help_text='Order number of the term list in the payment term'),
        ),
        migrations.AlterField(
            model_name='term',
            name='unit_type',
            field=models.IntegerField(
                choices=[(0, 'Percent'), (1, 'Amount'), (2, 'Balance')], default=0,
                help_text='Value calculation rules for value fields', verbose_name='Unit type'
            ),
        ),
        migrations.AlterField(
            model_name='term',
            name='value',
            field=models.CharField(help_text='This value using with unit_type', max_length=50, verbose_name='Value'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentterm',
            unique_together={('company', 'code')},
        ),

        # account
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('company', 'code')},
        ),
    ]
