# Generated by Django 4.1.3 on 2023-05-23 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companyconfig'),
        ('space', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0001_initial'),
        ('process', '0001_initial'),
        ('tenant', '0001_initial'),
        ('saledata', '0018_alter_accounttype_account_type_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel')], default=0)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('posting_date', models.DateField(help_text='Posting date of request when user apply', verbose_name='Posting date')),
                ('product_list', models.JSONField(default=list, help_text='Product list detail of Good receipt format json', verbose_name='Line detail')),
                ('pretax_amount', models.FloatField(help_text='Amount before tax', verbose_name='Pretax amount')),
                ('taxes', models.FloatField(help_text='Tax amount total of all product. formula per product: (price * tax) / 100', verbose_name='Taxes')),
                ('total_amount', models.FloatField(help_text='pretax amount + taxes', verbose_name='Total amount')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='User modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
                ('space', models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='good_receipt_supplier', to='saledata.account', verbose_name='Supplier')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Good receipt',
                'verbose_name_plural': 'Good receipt',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GoodReceiptProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('product_data', models.JSONField(default=dict, help_text='{"id": "", "title": "", "code": ""}', verbose_name='')),
                ('warehouse_data', models.JSONField(default=dict, help_text='{"id": "", "title": "", "code": ""}', verbose_name='')),
                ('uom_data', models.JSONField(default=dict, help_text='{"id": "", "title": "", "code": ""}', verbose_name='')),
                ('quantity', models.IntegerField(help_text='quantity of product', verbose_name='Quantity')),
                ('unit_price', models.FloatField(help_text='price per product', verbose_name='unit price')),
                ('tax_data', models.JSONField(default=dict, help_text='{"id": "", "title": "", "code": ""}', verbose_name='')),
                ('subtotal_price', models.FloatField(help_text='total amount of unit price * quantity', verbose_name='Subtotal price')),
                ('order', models.IntegerField(blank=True, help_text='sort purpose', null=True, verbose_name='order')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='User modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to=settings.AUTH_USER_MODEL)),
                ('good_receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='good_receipt_product_good_receipt', to='saledata.goodreceipt', verbose_name='Good receipt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_receipt_product', to='saledata.product', verbose_name='Product')),
                ('tax', models.ForeignKey(help_text='Tax per product', on_delete=django.db.models.deletion.CASCADE, to='saledata.tax', verbose_name='Tax')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_receipt_uom', to='saledata.unitofmeasure', verbose_name='Unit of Measure')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_receipt_warehouse', to='saledata.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Good receipt',
                'verbose_name_plural': 'Good receipt',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
