# Generated by Django 4.2.8 on 2024-04-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0019_alter_salutation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type_selection',
            field=models.SmallIntegerField(choices=[(0, 'individual'), (1, 'organization')], default=1),
        ),
    ]
