# Generated by Django 4.1.3 on 2023-05-24 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_baseitemunit'),
        ('saledata', '0019_goodreceipt_goodreceiptproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountShippingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detail_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Detail address')),
                ('is_default', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.account')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.country')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.district')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ward')),
            ],
            options={
                'verbose_name': 'Account Shipping Address',
                'verbose_name_plural': 'Account Shipping Addresses',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AccountBillingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='account email')),
                ('tax_code', models.CharField(blank=True, max_length=150, null=True, verbose_name='tax code')),
                ('account_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Account address')),
                ('is_default', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.account')),
            ],
            options={
                'verbose_name': 'Account Billing Address',
                'verbose_name_plural': 'Account Billing Addresses',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
