# Generated by Django 4.1.3 on 2023-05-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0020_remove_accountaccounttypes_customer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='annual_revenue',
            field=models.SmallIntegerField(choices=[(1, '1-10 billions'), (2, '10-20 billions'), (3, '20-50 billions'), (4, '50-200 billions'), (5, '200-1000 billions'), (6, '> 1000 billions')], null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_employees',
            field=models.SmallIntegerField(choices=[(1, '< 20 people'), (2, '20-50 people'), (3, '50-200 people'), (4, '200-500 people'), (5, '> 500 people')], default=1),
        ),
    ]
