# Generated by Django 4.1.3 on 2023-05-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0020_accountshippingaddress_accountbillingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type_selection',
            field=models.SmallIntegerField(choices=[(0, 'individual'), (1, 'organization')], default=0),
        ),
    ]
