# Generated by Django 4.1.3 on 2023-05-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0020_remove_accountaccounttypes_customer_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conditionlocation',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'Condition Location', 'verbose_name_plural': 'Condition Locations'},
        ),
        migrations.AlterModelOptions(
            name='formulacondition',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'Formula Condition', 'verbose_name_plural': 'Formula Conditions'},
        ),
        migrations.AlterModelOptions(
            name='shippingcondition',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'Shipping Condition', 'verbose_name_plural': 'Shipping Conditions'},
        ),
    ]
