# Generated by Django 4.2.8 on 2024-05-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0022_productwarehouselot_raw_quantity_import'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subperiods',
            old_name='run_report',
            new_name='run_report_inventory',
        ),
        migrations.RemoveField(
            model_name='subperiods',
            name='run_report_detail',
        ),
        migrations.AddField(
            model_name='periods',
            name='definition_inventory_valuation',
            field=models.SmallIntegerField(choices=[(0, 'Perpetual inventory'), (1, 'Periodic inventory')], default=0),
        ),
    ]
