# Generated by Django 4.1.3 on 2023-05-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0022_remove_accountaccounttypes_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountshippingaddress',
            name='full_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Full address'),
        ),
    ]
