# Generated by Django 4.2.8 on 2024-05-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0023_rename_run_report_subperiods_run_report_inventory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale_cost',
        ),
    ]
