# Generated by Django 4.1.3 on 2023-05-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0023_accountshippingaddress_full_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbillingaddress',
            name='account_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Account address'),
        ),
    ]
