# Generated by Django 4.1.3 on 2023-05-25 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0024_alter_accountbillingaddress_account_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountBillingAddress',
        ),
    ]
