# Generated by Django 4.1.3 on 2023-06-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0024_warehousestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodreceiptproduct',
            name='quantity',
            field=models.FloatField(help_text='quantity of product', verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='stock',
            field=models.FloatField(help_text='Stock of product', verbose_name='Stock'),
        ),
    ]
