# Generated by Django 4.1.3 on 2023-06-09 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('company', '0004_companyconfig'),
        ('hr', '0001_initial'),
        ('saledata', '0025_alter_goodreceiptproduct_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWareHouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('unit_price', models.FloatField(default=0, verbose_name='Unit prices of Product')),
                ('stock_amount', models.FloatField(default=0, help_text='Stock of product', verbose_name='Stock')),
                ('available_amount', models.FloatField(default=0, verbose_name='Available Stock')),
                ('sold_amount', models.FloatField(default=0, verbose_name='Sold Amount')),
                ('product_data', models.JSONField(default=dict, verbose_name='Product backup data')),
                ('warehouse_data', models.JSONField(default=dict, verbose_name='WareHouse backup data')),
                ('uom_data', models.JSONField(default=dict, verbose_name='Unit Of Measure backup data')),
                ('tax_data', models.JSONField(default=dict, verbose_name='Tax backup data')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.product', verbose_name='Product of WareHouse')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.tax', verbose_name='Tax of Product')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.unitofmeasure', verbose_name='Unit Of Measure of Product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.warehouse', verbose_name='WareHouse of Product')),
            ],
            options={
                'verbose_name': 'Product mapping WareHouse',
                'verbose_name_plural': 'Product mapping WareHouse',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
                'unique_together': {('company_id', 'warehouse_id', 'product_id', 'uom_id')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='warehouses',
            field=models.ManyToManyField(blank=True, related_name='warehouses_of_product', through='saledata.ProductWareHouse', to='saledata.warehouse'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products_of_warehouse', through='saledata.ProductWareHouse', to='saledata.product'),
        ),
    ]
