# Generated by Django 4.2.8 on 2024-06-05 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remove_goodsreturn_data_item_and_more'),
        ('saledata', '0025_remove_productwarehouselot_goods_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwarehouselottransaction',
            name='goods_issue',
            field=models.ForeignKey(help_text='To know this lot was issued by which GoodsIssue', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pw_lot_transact_goods_issue', to='inventory.goodsissue', verbose_name='goods issue'),
        ),
        migrations.AddField(
            model_name='productwarehouselottransaction',
            name='goods_return',
            field=models.ForeignKey(help_text='To know this lot was returned by which GoodsReturn', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pw_lot_transact_goods_return', to='inventory.goodsreturn', verbose_name='goods return'),
        ),
        migrations.AddField(
            model_name='productwarehouselottransaction',
            name='goods_transfer',
            field=models.ForeignKey(help_text='To know this lot was transferred by which GoodsTransfer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pw_lot_transact_goods_transfer', to='inventory.goodstransfer', verbose_name='goods transfer'),
        ),
        migrations.AddField(
            model_name='productwarehouselottransaction',
            name='transfer_type',
            field=models.BooleanField(help_text='transfer type: 1 is IN, 0 is OUT', null=True),
        ),
        migrations.AlterField(
            model_name='productwarehouselottransaction',
            name='type_transaction',
            field=models.SmallIntegerField(default=0, help_text="choices= ((0, 'Goods receipt'), (1, 'Delivery'), (2, 'Goods return'), (3, 'Goods transfer'), (4, 'Goods issue'))"),
        ),
    ]
