# Generated by Django 4.1.3 on 2023-06-14 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('saledata', '0026_productwarehouse_product_warehouses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='owner_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='Contact owner mapped'),
        ),
        migrations.AddField(
            model_name='contact',
            name='report_to_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.contact', verbose_name='report to another contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='account_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_account_name', to='saledata.account', verbose_name='account name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='owner',
            field=models.UUIDField(help_text='employee is contact owner', null=True),
        ),
    ]
