# Generated by Django 4.1.3 on 2023-06-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0026_productwarehouse_product_warehouses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address_information',
            field=models.JSONField(default=dict, help_text='{"work_address": "", "home_address": ""}'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='True if it have a account owner; otherwise it is False', verbose_name='Account Owner Exist'),
        ),
    ]
