# Generated by Django 4.1.3 on 2023-05-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0026_accountbillingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountBillingAddress',
        ),
    ]
