# Generated by Django 4.1.3 on 2023-06-15 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0026_productwarehouse_product_warehouses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='owner',
            field=models.UUIDField(help_text='employee is contact owner', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='report_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.contact', verbose_name='report to another contact'),
        ),
    ]
