# Generated by Django 4.2.8 on 2024-07-12 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_purchaseorder_contact_data_and_more'),
        ('inventory', '0029_goodsregistrationgeneral_picked_ready'),
        ('saledata', '0027_remove_productwarehouselot_raw_quantity_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwarehouselottransaction',
            name='purchase_request',
            field=models.ForeignKey(help_text='To know this lot was receipted by which PurchaseRequest', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pw_lot_purchase_request', to='purchasing.purchaserequest', verbose_name='purchase request'),
        ),
        migrations.AddField(
            model_name='productwarehouseserial',
            name='purchase_request',
            field=models.ForeignKey(help_text='To know this serial was receipted by which PurchaseRequest', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pw_serial_purchase_request', to='purchasing.purchaserequest', verbose_name='purchase request'),
        ),
        migrations.AlterField(
            model_name='productwarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_warehouse_warehouse', to='saledata.warehouse', verbose_name='WareHouse of Product'),
        ),
        migrations.AlterField(
            model_name='productwarehouseserial',
            name='goods_receipt',
            field=models.ForeignKey(help_text='To know this serial was receipted by which GoodsReceipt', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pw_serial_goods_receipt', to='inventory.goodsreceipt', verbose_name='goods receipt'),
        ),
    ]
