# Generated by Django 4.1.3 on 2023-05-25 09:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0027_delete_accountbillingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBillingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='account email')),
                ('tax_code', models.CharField(blank=True, max_length=150, null=True, verbose_name='tax code')),
                ('account_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Account address')),
                ('is_default', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.account')),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_account_name', to='saledata.account')),
            ],
            options={
                'verbose_name': 'Account Billing Address',
                'verbose_name_plural': 'Account Billing Addresses',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
