# Generated by Django 4.2.8 on 2024-07-16 15:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_rename_cost_per_lot_batch_companyconfig_cost_per_lot_and_more'),
        ('tenant', '0001_initial'),
        ('hr', '0003_alter_group_unique_together_and_more'),
        ('saledata', '0028_productwarehouselottransaction_purchase_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseShelf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('shelf_title', models.CharField(max_length=100)),
                ('shelf_position', models.CharField(max_length=500)),
                ('shelf_order', models.IntegerField(default=0)),
                ('shelf_row', models.IntegerField(default=1)),
                ('shelf_column', models.IntegerField(default=1)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_shelf_position_warehouse', to='saledata.warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Shelf Position',
                'verbose_name_plural': 'Warehouse Shelves Positions',
                'ordering': ('shelf_order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
