# Generated by Django 4.1.3 on 2023-05-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0028_accountbillingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbillingaddress',
            name='full_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Full address'),
        ),
        migrations.AlterField(
            model_name='accountbillingaddress',
            name='account_address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Account address'),
        ),
    ]
