# Generated by Django 4.2.8 on 2024-07-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0029_warehouseshelf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periods',
            name='planned',
        ),
        migrations.AddField(
            model_name='periods',
            name='has_budget_planned',
            field=models.BooleanField(default=False, help_text='is True if has budget planned this period'),
        ),
        migrations.AddField(
            model_name='periods',
            name='has_revenue_planned',
            field=models.BooleanField(default=False, help_text='is True if has revenue planned this period'),
        ),
    ]
