# Generated by Django 4.1.3 on 2023-06-16 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_baseitemunit'),
        ('saledata', '0029_alter_contact_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='home_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_city', to='base.city'),
        ),
        migrations.AddField(
            model_name='contact',
            name='home_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_country', to='base.country'),
        ),
        migrations.AddField(
            model_name='contact',
            name='home_detail_address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Detail home address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='home_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_district', to='base.district'),
        ),
        migrations.AddField(
            model_name='contact',
            name='home_ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_ward', to='base.ward'),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_city', to='base.city'),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_country', to='base.country'),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_detail_address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Detail work address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_district', to='base.district'),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_ward', to='base.ward'),
        ),
    ]
