# Generated by Django 4.1.3 on 2023-06-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0030_contact_home_city_contact_home_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwarehouse',
            name='picked_ready',
            field=models.FloatField(default=0, verbose_name='Picked Amount'),
        ),
    ]
