# Generated by Django 4.2.8 on 2024-08-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0031_alter_accountactivity_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='production_amount',
            field=models.FloatField(default=0, help_text='Amount product that making by company - not purchase', verbose_name='Production Amount'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplied_by',
            field=models.SmallIntegerField(choices=[(0, 'Purchasing'), (1, 'Making')], default=0),
        ),
    ]
