# Generated by Django 4.1.3 on 2023-07-11 14:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_media_access_token_and_more'),
        ('saledata', '0031_productwarehouse_picked_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_type', to='saledata.expensetype', verbose_name='Type of Expense'),
        ),
        migrations.AddField(
            model_name='expense',
            name='price_list',
            field=models.ManyToManyField(blank=True, default=None, related_name='expenses_map_prices', through='saledata.ExpensePrice', to='saledata.price'),
        ),
        migrations.AddField(
            model_name='expense',
            name='uom',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_uom', to='saledata.unitofmeasure', verbose_name='Unit of Measure apply for expense'),
        ),
        migrations.AddField(
            model_name='expense',
            name='uom_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_uom_group', to='saledata.unitofmeasuregroup', verbose_name='Unit of Measure Group apply for expense'),
        ),
        migrations.AddField(
            model_name='expenseprice',
            name='expense',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='saledata.expense'),
        ),
        migrations.AlterField(
            model_name='expensegeneral',
            name='expense',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expense_1', to='saledata.expense'),
        ),
        migrations.AlterField(
            model_name='expensegeneral',
            name='expense_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_type_1', to='saledata.expensetype', verbose_name='Type of Expense'),
        ),
        migrations.AlterField(
            model_name='expensegeneral',
            name='price_list',
            field=models.ManyToManyField(blank=True, related_name='expenses_map_prices_1', through='saledata.ExpensePrice', to='saledata.price'),
        ),
        migrations.AlterField(
            model_name='expensegeneral',
            name='tax_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_tax_code_1', to='saledata.tax', verbose_name='Tax Code apply for expense'),
        ),
        migrations.AlterField(
            model_name='expensegeneral',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_uom_1', to='saledata.unitofmeasure', verbose_name='Unit of Measure apply for expense'),
        ),
        migrations.AlterField(
            model_name='expensegeneral',
            name='uom_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_uom_group_1', to='saledata.unitofmeasuregroup', verbose_name='Unit of Measure Group apply for expense'),
        ),
        migrations.AlterField(
            model_name='expenseprice',
            name='expense_general',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.expensegeneral'),
        ),
        migrations.CreateModel(
            name='ExpenseRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_role_expense', to='saledata.expense')),
                ('role', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_role_role', to='hr.role')),
            ],
            options={
                'verbose_name': 'Expense Role',
                'verbose_name_plural': 'Expense Roles',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='role',
            field=models.ManyToManyField(blank=True, default=None, related_name='expenses_map_roles', through='saledata.ExpenseRole', to='hr.role'),
        ),
    ]
