# Generated by Django 4.1.3 on 2023-07-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0032_expense_expense_type_expense_price_list_expense_uom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeasuregroup',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
