# Generated by Django 4.2.8 on 2024-08-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0033_alter_account_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='is_asset_tool',
            field=models.BooleanField(default=False, help_text='flag to know this type is asset tool of company'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='is_finished_goods',
            field=models.BooleanField(default=False, help_text='flag to know this type is finished goods (production) of company'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='is_goods',
            field=models.BooleanField(default=False, help_text='flag to know this type is goods (purchased) of company'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='is_material',
            field=models.BooleanField(default=False, help_text='flag to know this type is material of company'),
        ),
    ]
