# Generated by Django 4.1.3 on 2023-07-11 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0033_unitofmeasuregroup_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='general_information',
        ),
        migrations.RemoveField(
            model_name='expenseprice',
            name='expense_general',
        ),
        migrations.AlterField(
            model_name='expenseprice',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='saledata.expense'),
        ),
        migrations.DeleteModel(
            name='ExpenseGeneral',
        ),
    ]
