# Generated by Django 4.1.3 on 2023-07-19 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0034_remove_expense_general_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productinventory',
            name='uom',
        ),
        migrations.RemoveField(
            model_name='productsale',
            name='currency_using',
        ),
        migrations.RemoveField(
            model_name='productsale',
            name='default_uom',
        ),
        migrations.RemoveField(
            model_name='productsale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsale',
            name='tax_code',
        ),
        migrations.AddField(
            model_name='product',
            name='currency_using',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_currency', to='saledata.currency'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_uom',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_uom', to='saledata.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_level_max',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_level_min',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_uom',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_uom', to='saledata.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='saledata.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_choice',
            field=models.JSONField(default=list, help_text='product for sale: 0, inventory: 1, purchase:2'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='saledata.producttype'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_code',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax', to='saledata.tax'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uom_group', to='saledata.unitofmeasuregroup'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='ProductGeneral',
        ),
        migrations.DeleteModel(
            name='ProductInventory',
        ),
        migrations.DeleteModel(
            name='ProductSale',
        ),
    ]
