# Generated by Django 4.2.8 on 2024-09-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0035_product_has_bom_alter_product_product_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'default_permissions': (), 'ordering': ('-is_default', 'date_created'), 'permissions': (), 'verbose_name': 'ProductType', 'verbose_name_plural': 'ProductTypes'},
        ),
        migrations.AddField(
            model_name='producttype',
            name='is_service',
            field=models.BooleanField(default=False, help_text='flag to know this type is service of company'),
        ),
    ]
