# Generated by Django 4.1.3 on 2023-07-21 16:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
        ('saledata', '0035_remove_productinventory_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodreceipt',
            name='attachments',
            field=models.JSONField(default=list, help_text='["uuid4", "uuid4"]', null=True, verbose_name='attachment file'),
        ),
        migrations.AddField(
            model_name='goodreceipt',
            name='po_code',
            field=models.CharField(help_text='relate to PO code', max_length=50, null=True, verbose_name='PO code'),
        ),
        migrations.AddField(
            model_name='goodreceipt',
            name='po_data',
            field=models.JSONField(default=list, help_text='[{"id": "uuid4", "uom": "uuid4", "quantity": 1, "unit_price": 10.0, "tax": 1.2, "sub_total": 10.0}]', null=True, verbose_name='product list from PO'),
        ),
        migrations.CreateModel(
            name='GoodReceiptAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_file', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('attachment', models.OneToOneField(help_text='Good receipt had one/many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='good_receipt_attachment_file', to='attachments.files', verbose_name='Good receipt attachment files')),
                ('good_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.goodreceipt', verbose_name='good receipt')),
            ],
            options={
                'verbose_name': 'Good receipt Attachment',
                'verbose_name_plural': 'Good receipt Attachment',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
