# Generated by Django 4.2.8 on 2024-09-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0036_alter_producttype_options_producttype_is_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_competitor_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_customer_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_partner_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_supplier_account',
            field=models.BooleanField(default=False),
        ),
    ]
