# Generated by Django 4.1.3 on 2023-07-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0037_alter_unitofmeasure_rounding_delete_warehousestock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='total_employees',
            field=models.CharField(choices=[(1, '< 20 people'), (2, '20-50 people'), (3, '50-200 people'), (4, '200-500 people'), (5, '> 500 people')], max_length=150, null=True, verbose_name='total employees of account'),
        ),
    ]
