# Generated by Django 4.1.3 on 2023-08-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0038_alter_account_total_employees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'default_permissions': (), 'ordering': ('-date_created',), 'permissions': (), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
