# Generated by Django 4.2.8 on 2024-10-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0038_product_standard_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='valuation_method',
            field=models.SmallIntegerField(choices=[(0, 'FIFO'), (1, 'Cumulative weighted average'), (2, 'Weighted average'), (3, 'Specific identification method'), (4, 'Standard cost')], default=2),
        ),
    ]
