# Generated by Django 4.1.3 on 2023-08-10 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0039_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbillingaddress',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_mapped_billing_address', to='saledata.account'),
        ),
        migrations.AlterField(
            model_name='accountshippingaddress',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_mapped_shipping_address', to='saledata.account'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_list_type',
            field=models.SmallIntegerField(choices=[(0, 'For Sale'), (1, 'For Purchase'), (2, 'For Expense')]),
        ),
    ]
