# Generated by Django 4.2.8 on 2024-10-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0039_product_valuation_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplied_by',
            field=models.SmallIntegerField(choices=[(0, 'Purchasing'), (1, 'Making')], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='valuation_method',
            field=models.SmallIntegerField(choices=[(0, 'FIFO'), (1, 'Weighted average'), (2, 'Specific identification method')], default=1),
        ),
    ]
