# Generated by Django 4.2.8 on 2024-10-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0041_account_next_association_contact_next_association_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='create_from_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='import_data_row',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
