# Generated by Django 4.1.3 on 2023-08-21 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0041_alter_account_system_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeasuregroup',
            name='uom_reference',
            field=models.ForeignKey(help_text='unit of measure in this group which is reference', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uom_group_uom_reference', to='saledata.unitofmeasure', verbose_name='uom reference'),
        ),
    ]
