# Generated by Django 4.1.3 on 2023-08-22 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0042_unitofmeasuregroup_uom_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='credit_limit',
            new_name='credit_limit_customer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_category',
            new_name='general_product_category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='general_product_type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='uom_group',
            new_name='general_uom_group',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='general_information',
            new_name='volume',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='inventory_information',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='account',
            name='payment_term_mapped',
        ),
        migrations.RemoveField(
            model_name='product',
            name='currency_using',
        ),
        migrations.RemoveField(
            model_name='product',
            name='default_uom',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purchase_information',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_information',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_code',
        ),
        migrations.AddField(
            model_name='account',
            name='credit_limit_supplier',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='payment_term_customer_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_term_customer_mapped', to='saledata.paymentterm'),
        ),
        migrations.AddField(
            model_name='account',
            name='payment_term_supplier_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_term_supplier_mapped', to='saledata.paymentterm'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_default_uom',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_default_uom', to='saledata.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_tax',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_tax', to='saledata.tax'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_currency_using',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_currency_using_for_cost', to='saledata.currency'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_default_uom',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_default_uom', to='saledata.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_product_price_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_tax',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_tax', to='saledata.tax'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.FloatField(null=True),
        ),
    ]
