# Generated by Django 4.2.8 on 2024-10-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0042_product_create_from_import_product_import_data_row_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeasure',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
