# Generated by Django 4.1.3 on 2023-08-23 11:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0043_rename_credit_limit_account_credit_limit_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceListCurrency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_currency', to='saledata.currency')),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='saledata.price')),
            ],
            options={
                'verbose_name': 'PriceCurrency',
                'verbose_name_plural': 'PriceCurrencies',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='price',
            name='currency_current',
            field=models.ManyToManyField(blank=True, related_name='opportunity_mapped', through='saledata.PriceListCurrency', to='saledata.currency'),
        ),
    ]
