# Generated by Django 4.2.8 on 2024-11-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0044_documenttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'default_permissions': (), 'ordering': ('-is_default', 'code'), 'permissions': (), 'verbose_name': 'Document type', 'verbose_name_plural': 'Document types'},
        ),
        migrations.AddField(
            model_name='documenttype',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
