# Generated by Django 4.2.4 on 2023-08-28 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0044_pricelistcurrency_price_currency_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bank_accounts_information',
        ),
        migrations.RemoveField(
            model_name='account',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='account',
            name='credit_cards_information',
        ),
        migrations.RemoveField(
            model_name='account',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='account',
            name='parent_account_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.account'),
        ),
        migrations.AlterField(
            model_name='accountaccounttypes',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_account_types_mapped', to='saledata.account'),
        ),
        migrations.AlterField(
            model_name='accountbanks',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_banks_mapped', to='saledata.account'),
        ),
        migrations.AlterField(
            model_name='accountbillingaddress',
            name='account_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='billing account name'),
        ),
        migrations.AlterField(
            model_name='accountcreditcards',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards_mapped', to='saledata.account'),
        ),
        migrations.AlterField(
            model_name='accountcreditcards',
            name='credit_card_type',
            field=models.SmallIntegerField(choices=[(1, 'Mastercard'), (2, 'Visa'), (3, 'American express')], default=0, verbose_name='Credit card type'),
        ),
        migrations.AlterField(
            model_name='accountemployee',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_employees_mapped', to='saledata.account'),
        ),
    ]
