# Generated by Django 4.1.3 on 2023-09-06 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0045_remove_account_bank_accounts_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_list_mapped',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_parent', to='saledata.price'),
        ),
    ]
