# Generated by Django 4.2.8 on 2024-11-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0045_alter_documenttype_options_documenttype_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='warehouse_type',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_agency_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_bin_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='price',
            name='currency_current',
            field=models.ManyToManyField(blank=True, related_name='price_list_currency_current', through='saledata.PriceListCurrency', to='saledata.currency'),
        ),
    ]
