# Generated by Django 4.1.3 on 2023-09-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0046_alter_price_price_list_mapped'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='general_traceability_method',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Batch/Lot number'), (2, 'Serial number')], default=0),
        ),
    ]
