# Generated by Django 4.2.8 on 2024-12-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0047_account_process_stage_app_contact_process_stage_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
