# Generated by Django 4.2.8 on 2024-12-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0048_term_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='doc_type_category',
            field=models.CharField(choices=[('bidding', 'Bidding'), ('consulting', 'Consulting')], max_length=20, null=True, verbose_name='Document category'),
        ),
    ]
