# Generated by Django 4.2.4 on 2023-09-12 09:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0048_expenseitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='general_product_type',
        ),
        migrations.CreateModel(
            name='ProductProductType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_product_types', to='saledata.product')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.producttype')),
            ],
            options={
                'verbose_name': 'Product ProductTypes',
                'verbose_name_plural': 'Products ProductTypes',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='general_product_types_mapped',
            field=models.ManyToManyField(blank=True, related_name='product_map_product_types', through='saledata.ProductProductType', to='saledata.producttype'),
        ),
    ]
