# Generated by Django 4.2.8 on 2025-01-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0049_documenttype_doc_type_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='periods',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
