# Generated by Django 4.1.3 on 2023-09-18 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_application_app_depend_on_application_permit_mapping'),
        ('saledata', '0049_remove_product_general_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='agency',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_agency', to='saledata.account'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_city', to='base.city'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='district',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_district', to='base.district'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='full_address',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Drop Ship'), (2, 'Bin Location'), (3, 'Agency / Partner Location')], default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='ward',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_ward', to='base.ward'),
        ),
    ]
