# Generated by Django 4.1.3 on 2023-09-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0050_warehouse_address_warehouse_agency_warehouse_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tax',
            old_name='type',
            new_name='tax_type',
        ),
    ]
