# Generated by Django 4.2.8 on 2025-01-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0050_periods_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productwarehouseserial',
            options={'default_permissions': (), 'ordering': ('serial_number',), 'permissions': (), 'verbose_name': 'Product Warehouse Serial', 'verbose_name_plural': 'Product Warehouse Serials'},
        ),
    ]
