# Generated by Django 4.2.8 on 2025-01-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0051_alter_productwarehouseserial_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='avatar',
        ),
        migrations.AddField(
            model_name='contact',
            name='home_address_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='contact',
            name='work_address_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='contact',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.TextField(blank=True, null=True, verbose_name='contact email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='home_detail_address',
            field=models.TextField(blank=True, null=True, verbose_name='Detail home address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='job_title',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='contact job title'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='work_detail_address',
            field=models.TextField(blank=True, null=True, verbose_name='Detail work address'),
        ),
    ]
