# Generated by Django 4.1.3 on 2023-10-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0053_alter_productwarehouse_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
