# Generated by Django 4.1.3 on 2023-10-11 16:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_employee_permission_by_opp_and_more'),
        ('company', '0008_remove_company_language'),
        ('tenant', '0001_initial'),
        ('saledata', '0054_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productwarehouse',
            name='available_amount',
        ),
        migrations.AddField(
            model_name='product',
            name='available_amount',
            field=models.FloatField(default=0, help_text='Theoretical amount product in warehouse, =(stock_amount - wait_delivery + wait_receipt)', verbose_name='Available Stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_amount',
            field=models.FloatField(default=0, help_text='Total physical amount product in all warehouse', verbose_name='Stock Amount'),
        ),
        migrations.AddField(
            model_name='product',
            name='wait_delivery_amount',
            field=models.FloatField(default=0, help_text='Amount product that ordered but not delivered, update when delivery for sale order', verbose_name='Wait Delivery Amount'),
        ),
        migrations.AddField(
            model_name='product',
            name='wait_receipt_amount',
            field=models.FloatField(default=0, help_text='Amount product that purchased but not receipted, update when goods receipt for purchase order', verbose_name='Wait Receipt Amount'),
        ),
        migrations.AddField(
            model_name='productwarehouse',
            name='receipt_amount',
            field=models.FloatField(default=0, help_text='Amount product receipted, update when goods receipt', verbose_name='Receipt Amount'),
        ),
        migrations.AlterField(
            model_name='productwarehouse',
            name='sold_amount',
            field=models.FloatField(default=0, help_text='Amount product delivered, update when deliver', verbose_name='Sold Amount'),
        ),
        migrations.AlterField(
            model_name='productwarehouse',
            name='stock_amount',
            field=models.FloatField(default=0, help_text='Physical amount product in warehouse, =(receipt_amount - sold_amount)', verbose_name='Stock'),
        ),
        migrations.CreateModel(
            name='ProductWareHouseSerial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('vendor_serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expire_date', models.DateTimeField(null=True)),
                ('manufacture_date', models.DateTimeField(null=True)),
                ('warranty_start', models.DateTimeField(null=True)),
                ('warranty_end', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('product_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_warehouse_serial_product_warehouse', to='saledata.productwarehouse', verbose_name='product warehouse')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Product Warehouse Serial',
                'verbose_name_plural': 'Product Warehouse Serials',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProductWareHouseLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_import', models.FloatField(default=0)),
                ('expire_date', models.DateTimeField(null=True)),
                ('manufacture_date', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('product_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_warehouse_lot_product_warehouse', to='saledata.productwarehouse', verbose_name='product warehouse')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Product Warehouse Lot',
                'verbose_name_plural': 'Product Warehouse Lots',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
