# Generated by Django 4.2.8 on 2025-02-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0055_remove_producttype_is_asset_tool_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='lease_depreciation_price',
            new_name='depreciation_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='serial_data',
        ),
        migrations.AddField(
            model_name='product',
            name='date_first_delivery',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='depreciation_adjustment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='depreciation_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='depreciation_method',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='depreciation_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='depreciation_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='lease_time_previous',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='origin_cost',
            field=models.FloatField(default=0, help_text='the first cost of this product before depreciation'),
        ),
    ]
