# Generated by Django 4.1.3 on 2023-11-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0057_productvariantattribute_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantattribute',
            name='company',
        ),
        migrations.RemoveField(
            model_name='productvariantattribute',
            name='employee_created',
        ),
        migrations.RemoveField(
            model_name='productvariantattribute',
            name='employee_modified',
        ),
        migrations.RemoveField(
            model_name='productvariantattribute',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariantattribute',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='ProductVariantAttribute',
        ),
    ]
