# Generated by Django 4.2.8 on 2025-03-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0058_accountgroup_is_default_industry_is_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_first_delivery',
        ),
        migrations.RemoveField(
            model_name='product',
            name='depreciation_adjustment',
        ),
        migrations.RemoveField(
            model_name='product',
            name='depreciation_end_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='depreciation_method',
        ),
        migrations.RemoveField(
            model_name='product',
            name='depreciation_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='depreciation_start_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='depreciation_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lease_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lease_source',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lease_time_previous',
        ),
        migrations.RemoveField(
            model_name='product',
            name='origin_cost',
        ),
        migrations.AddField(
            model_name='productwarehouseserial',
            name='serial_status',
            field=models.SmallIntegerField(choices=[(0, 'Available'), (1, 'Delivered')], default=0, help_text='Flag to know current status'),
        ),
    ]
