# Generated by Django 4.2.8 on 2025-03-13 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_email_app_password_and_more'),
        ('base', '0018_applicationproperty_is_filter_condition'),
        ('company', '0016_companyconfig_accounting_policies_and_more'),
        ('tenant', '0001_initial'),
        ('saledata', '0059_remove_product_date_first_delivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('abbreviation', models.CharField(max_length=150)),
                ('vietnamese_name', models.CharField(max_length=150)),
                ('english_name', models.CharField(max_length=150)),
                ('is_default', models.BooleanField(default=False)),
                ('address', models.TextField(null=True)),
                ('full_address', models.TextField(null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_banks', to='base.city')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_banks', to='base.country')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_banks', to='base.district')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_banks', to='base.ward')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Bank',
                'ordering': ('abbreviation',),
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('bank_name', models.CharField(max_length=150)),
                ('bank_account_number', models.CharField(max_length=150)),
                ('bank_owner', models.CharField(max_length=150)),
                ('is_brand', models.BooleanField(default=False)),
                ('brand_name', models.CharField(max_length=150, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('brand_address', models.TextField(null=True)),
                ('brand_full_address', models.TextField(null=True)),
                ('bank_abbreviation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='saledata.bank')),
                ('brand_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_bank_accounts', to='base.city')),
                ('brand_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_bank_accounts', to='base.country')),
                ('brand_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_bank_accounts', to='base.district')),
                ('brand_ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_bank_accounts', to='base.ward')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_bank_accounts', to='saledata.currency')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'BankAccount',
                'verbose_name_plural': 'BankAccountS',
                'ordering': ('bank_account_number',),
            },
        ),
    ]
