# Generated by Django 4.2.8 on 2025-03-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0060_bank_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplied_by',
            field=models.SmallIntegerField(choices=[(0, 'Purchasing'), (1, 'Making')], default=0),
        ),
    ]
