# Generated by Django 4.2.8 on 2025-03-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0061_alter_product_supplied_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ('-date_created',), 'verbose_name': 'Bank', 'verbose_name_plural': 'Banks'},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ('-date_created',), 'verbose_name': 'Bank Account', 'verbose_name_plural': 'Bank Accounts'},
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='abbreviation',
            new_name='bank_abbreviation',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='bank_name',
            new_name='bank_account_owner',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='bank_abbreviation',
            new_name='bank_mapped',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='city',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='country',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='district',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='english_name',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='vietnamese_name',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_owner',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='brand_city',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='brand_country',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='brand_district',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='brand_full_address',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='brand_ward',
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_foreign_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='bank',
            name='head_office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='head_office_address_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='bank',
            name='vietqr_json_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_mapped_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='brand_address_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='currency_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='bom_sum_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='brand_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='brand_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
