# Generated by Django 4.2.8 on 2025-03-25 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0063_remove_product_bom_sum_price_product_bom_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='parent_account',
        ),
        migrations.AddField(
            model_name='account',
            name='account_group_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='account',
            name='account_types_mapped_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='account',
            name='currency_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='account',
            name='employee_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='account',
            name='industry_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='account',
            name='owner_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='account',
            name='parent_account_mapped_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='account',
            name='payment_term_customer_mapped_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='account',
            name='payment_term_supplier_mapped_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='account',
            name='price_list_mapped_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='account',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.industry'),
        ),
    ]
