# Generated by Django 4.2.8 on 2025-05-21 11:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0065_periods_currency_mapped'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountContacts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_contacts_account', to='saledata.account')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_contacts_contact', to='saledata.contact')),
            ],
            options={
                'verbose_name': 'Account Contact',
                'verbose_name_plural': 'Accounts Contacts',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='account',
            name='contacts_mapped',
            field=models.ManyToManyField(blank=True, related_name='account_map_contacts', through='saledata.AccountContacts', to='saledata.contact'),
        ),
    ]
