# Generated by Django 4.2.8 on 2025-06-19 20:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('company', '0022_company_function_number_data'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('saledata', '0067_productcomponent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWModified',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('modified_number', models.CharField(max_length=100)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('product_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pw_modified_pw', to='saledata.productwarehouse')),
                ('product_warehouse_lot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pw_modified_pw_lot', to='saledata.productwarehouselot')),
                ('product_warehouse_serial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pw_modified_pw_serial', to='saledata.productwarehouseserial')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Product Warehouse Modified',
                'verbose_name_plural': 'Products Warehouses Modified',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PWModifiedComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=1)),
                ('component_text_data', models.JSONField(default=dict)),
                ('component_product_data', models.JSONField(default=dict)),
                ('component_quantity', models.FloatField()),
                ('component_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.product')),
                ('pw_modified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pw_modified_components', to='saledata.pwmodified')),
            ],
            options={
                'verbose_name': 'Product Warehouse Modified Component',
                'verbose_name_plural': 'Products Warehouses Modified Component',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PWModifiedComponentDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_prd_wh_quantity', models.FloatField(default=0)),
                ('component_prd_wh_lot_data', models.JSONField(default=dict)),
                ('component_prd_wh_lot_quantity', models.FloatField(default=0)),
                ('component_prd_wh_serial_data', models.JSONField(default=dict)),
                ('component_prd_wh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.productwarehouse')),
                ('component_prd_wh_lot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.productwarehouselot')),
                ('component_prd_wh_serial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.productwarehouseserial')),
                ('pw_modified_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pw_modified_component_detail', to='saledata.pwmodifiedcomponent')),
            ],
            options={
                'verbose_name': 'Product Warehouse Modified Component Detail',
                'verbose_name_plural': 'Products Warehouses Modified Component Detail',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
