# Generated by Django 4.2.8 on 2025-06-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0068_pwmodified_pwmodifiedcomponent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pwmodified',
            options={'default_permissions': (), 'ordering': ('-modified_number',), 'permissions': (), 'verbose_name': 'Product Warehouse Modified', 'verbose_name_plural': 'Products Warehouses Modified'},
        ),
        migrations.AddField(
            model_name='productwarehouseserial',
            name='use_for_modification',
            field=models.BooleanField(default=False),
        ),
    ]
