# Generated by Django 4.2.8 on 2025-07-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0069_alter_pwmodified_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'default_permissions': (), 'ordering': ('-code',), 'permissions': (), 'verbose_name': 'WareHouse storage', 'verbose_name_plural': 'WareHouse storage'},
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='is_agency_location',
            new_name='is_virtual',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='agency',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='use_for',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'For Equipment Loan')], default=0),
        ),
    ]
