# Generated by Django 4.2.8 on 2025-07-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0070_alter_warehouse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwmodified',
            name='new_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
