# Generated by Django 4.2.8 on 2025-07-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0071_pwmodified_new_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountshippingaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='accountshippingaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='accountshippingaddress',
            name='detail_address',
        ),
        migrations.RemoveField(
            model_name='accountshippingaddress',
            name='district',
        ),
        migrations.RemoveField(
            model_name='accountshippingaddress',
            name='ward',
        ),
        migrations.AddField(
            model_name='accountshippingaddress',
            name='address_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='accountshippingaddress',
            name='full_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Full address'),
        ),
    ]
