# Generated by Django 4.2.8 on 2025-07-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0072_remove_accountshippingaddress_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='home_city',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='home_country',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='home_district',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='home_ward',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='work_city',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='work_country',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='work_district',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='work_ward',
        ),
        migrations.AlterField(
            model_name='accountshippingaddress',
            name='full_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='head_office_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='home_detail_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='work_detail_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
