# Generated by Django 4.2.8 on 2025-09-11 10:55

import apps.core.attachments.storages.aws.storages_backend
import apps.masterdata.saledata.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0076_product_duration_unit_product_duration_unit_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avatar_img',
            field=models.ImageField(null=True, storage=apps.core.attachments.storages.aws.storages_backend.PublicMediaStorage, upload_to=apps.masterdata.saledata.models.product.generate_product_avatar_path),
        ),
    ]
