# Generated by Django 4.2.8 on 2025-10-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0081_productspecificidentificationserialnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecificidentificationserialnumber',
            name='product_warehouse_serial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_spec_product_warehouse_serial', to='saledata.productwarehouseserial', verbose_name='product warehouse serial'),
        ),
    ]
