# Generated by Django 4.2.8 on 2025-10-15 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productmodification', '0003_productmodification_new_description'),
        ('saledata', '0082_productspecificidentificationserialnumber_product_warehouse_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avatar',
        ),
        migrations.AddField(
            model_name='productspecificidentificationserialnumber',
            name='from_pm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productspecificidentificationserialnumber',
            name='product_modification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_si_pm', to='productmodification.productmodification'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_pm_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
