# Generated by Django 4.2.8 on 2025-10-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0083_remove_product_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='address',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='city',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='district',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='ward',
        ),
    ]
