# Generated by Django 4.2.8 on 2025-10-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0084_remove_warehouse_address_remove_warehouse_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='is_pm_warehouse',
        ),
    ]
