# Generated by Django 4.2.8 on 2025-10-27 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0085_remove_warehouse_is_pm_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_representative_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='representative_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_representative_product', to='saledata.product'),
        ),
    ]
