# Generated by Django 4.1.3 on 2023-11-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagebuilder',
            name='project_data',
            field=models.JSONField(default=dict),
        ),
    ]
