# Generated by Django 4.1.3 on 2023-12-05 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_builder', '0002_pagebuilder_project_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.TextField(blank=True)),
                ('project_data', models.JSONField(blank=True)),
            ],
            options={
                'verbose_name': 'Page Template',
                'verbose_name_plural': 'Page Template',
                'ordering': ('title',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
