# Generated by Django 4.1.3 on 2023-11-11 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('kind', models.IntegerField(choices=[(0, 'Cloud'), (1, 'Private'), (2, 'On-prem')], default=0)),
                ('private_block', models.CharField(blank=True, max_length=100)),
                ('sub_domain', models.CharField(max_length=20, unique=True)),
                ('sub_domain_suffix', models.CharField(default='.quantrimis.com.vn', max_length=25)),
                ('representative_fullname', models.CharField(max_length=100)),
                ('representative_phone_number', models.CharField(max_length=50)),
                ('plan', jsonfield.fields.JSONField(default={})),
                ('auto_create_company', models.BooleanField(default=True)),
                ('company_quality_max', models.IntegerField(default=5)),
                ('admin_info', jsonfield.fields.JSONField(default={'email': '', 'fullname': '', 'phone_number': '', 'username': ''})),
                ('admin_created', models.BooleanField(default=False)),
                ('user_request_created', jsonfield.fields.JSONField(default={}, verbose_name='This is information of user request created.')),
                ('company_total', models.IntegerField(default=0)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenant',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
                'unique_together': {('code',)},
            },
        ),
        migrations.CreateModel(
            name='TenantPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.CharField(blank=True, max_length=200, null=True)),
                ('date_active', models.DateTimeField(null=True)),
                ('date_end', models.DateTimeField(null=True)),
                ('is_limited', models.BooleanField(null=True)),
                ('license_quantity', models.IntegerField(null=True)),
                ('license_used', models.IntegerField(null=True)),
                ('is_expired', models.BooleanField(default=False, null=True)),
                ('license_buy_type', models.SmallIntegerField(choices=[(0, 'Auto Renew'), (1, 'One Time')], default=0, help_text='Choose in (0, "Auto Renew"), (1, "One Time")', verbose_name='license buy type')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_plan_plan', to='base.subscriptionplan')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_plan_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Plan',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
