# Generated by Django 4.1.3 on 2023-02-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='delete'),
        ),
        migrations.AddField(
            model_name='tenantplan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='tenantplan',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='delete'),
        ),
    ]
