# Generated by Django 4.1.3 on 2022-12-14 14:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('user_created', models.UUIDField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_modified', models.UUIDField(null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Application',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('user_created', models.UUIDField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_modified', models.UUIDField(null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('extras', jsonfield.fields.JSONField(default={})),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'ordering': ('title',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.CreateModel(
            name='TenantPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('user_created', models.UUIDField(null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_modified', models.UUIDField(null=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('extras', jsonfield.fields.JSONField(default={})),
                ('purchase_order', models.CharField(blank=True, max_length=200, null=True)),
                ('date_active', models.DateTimeField(null=True)),
                ('date_end', models.DateTimeField(null=True)),
                ('is_limited', models.BooleanField(null=True)),
                ('license_quantity', models.IntegerField(null=True)),
                ('license_used', models.IntegerField(null=True)),
                ('is_expired', models.BooleanField(default=False, null=True)),
                ('license_buy_type', models.SmallIntegerField(choices=[(0, 'Auto Renew'), (1, 'One Time')], default=0, help_text='Choose in (0, "Auto Renew"), (1, "One Time")', verbose_name='license buy type')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_plan_plan', to='tenant.subscriptionplan')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_plan_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Plan',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
