# Generated by Django 4.1.3 on 2023-11-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenant',
            unique_together={('code',)},
        ),
    ]
