# Generated by Django 4.1.3 on 2022-12-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_application_subscriptionplan_tenant_plan_tenantplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='sub_domain',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
