# Generated by Django 4.1.3 on 2023-01-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_alter_tenant_sub_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='representative_address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='representative_email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='representative_fullname',
            field=models.CharField(max_length=100, verbose_name='fullname'),
        ),
        migrations.AlterField(
            model_name='company',
            name='representative_phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='phone'),
        ),
    ]
