# Generated by Django 4.1.3 on 2023-01-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_company_representative_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='representative_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='representative_phone',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='phone'),
        ),
    ]
