# Generated by Django 4.1.3 on 2023-11-11 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
        ('hr', '0001_initial'),
        ('company', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_method', models.CharField(help_text='choices in: GET, POST, PUT, DELETE, ...', max_length=10, null=True, verbose_name='HTTP method of Log')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('doc_id', models.UUIDField(help_text="Null if it is log's general; otherwise, The value of ID field is required.", null=True, verbose_name='ID of Object')),
                ('doc_app', models.CharField(blank=True, help_text='Format: {app_label}.{model_name}; It is empty when doc_id is null, otherwise the value is required to match the format.', max_length=100, verbose_name='App Code of Object')),
                ('automated_logging', models.BooleanField(help_text='Correct if it is an automated system log; otherwise, the values of the user and employee fields must have a value.', verbose_name='Is automated logging')),
                ('msg', models.TextField(blank=True, help_text='Messages was translated before save', verbose_name='Message was logged')),
                ('data_change', models.JSONField(default=dict, help_text='JSON send from client for POST,PUT', verbose_name='Request Body')),
                ('change_partial', models.BooleanField(default=False, verbose_name='Flag partial of Mixins')),
                ('user_data', models.JSONField(default=dict, verbose_name='User backup data')),
                ('employee_data', models.JSONField(default=dict, verbose_name='Employee backup data')),
            ],
            options={
                'verbose_name': 'Log Activity',
                'verbose_name_plural': 'Log Activity',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='Title of BookMark')),
                ('kind', models.PositiveSmallIntegerField(choices=[(0, 'View Name'), (1, 'Custom URL')], help_text='[[0, "View Name"], [1, "Custom URL"]]', verbose_name='Type of Bookmarks')),
                ('view_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='View Name UI')),
                ('customize_url', models.TextField(blank=True, null=True, verbose_name='User URL Custom')),
                ('box_style', models.JSONField(default=dict, help_text='{"icon_cls": "", "bg_cls": "", "text_cls": ""}', verbose_name='Style of Box display')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order of BookMark Display')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
            ],
            options={
                'verbose_name': 'BookMark',
                'verbose_name_plural': 'BookMark',
                'ordering': ('order', '-date_created'),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Title of Doc')),
                ('msg', models.TextField(blank=True, verbose_name='Message of notify')),
                ('doc_id', models.UUIDField(help_text="Null if it is log's general; otherwise, The value of ID field is required.", null=True, verbose_name='ID of Object')),
                ('doc_app', models.CharField(blank=True, help_text='Format: {app_label}.{model_name}; It is empty when doc_id is null, otherwise the value is required to match the format.', max_length=100, verbose_name='App Code of Object')),
                ('automated_sending', models.BooleanField(default=True, help_text='Correct if it is an automated system log; otherwise, the values of the user and employee fields must have a value.', verbose_name='Is automated sending')),
                ('is_done', models.BooleanField(default=False, verbose_name='Is Read notify')),
                ('user_data', models.JSONField(default=dict, verbose_name='User backup data')),
                ('employee_data', models.JSONField(default=dict, verbose_name='Employee backup data')),
                ('employee_sender_data', models.JSONField(default=dict, verbose_name='Employee sender backup data')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifies_of_employee', to='hr.employee', verbose_name='This employee is performer')),
                ('employee_sender', models.ForeignKey(help_text='This employee sent notify', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifies_send_by_employee', to='hr.employee', verbose_name='Sender')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifies_of_user', to=settings.AUTH_USER_MODEL, verbose_name='This user is performer')),
            ],
            options={
                'verbose_name': 'Notifications',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('mail_template', models.TextField(verbose_name='Template Using')),
                ('mail_context', models.JSONField(verbose_name='Context Using')),
                ('mail_html', models.TextField(verbose_name='HTML Parsed')),
                ('mail_text', models.TextField(verbose_name='Text Parsed')),
                ('mail_to', models.JSONField(verbose_name='Receiver')),
                ('mail_cc', models.JSONField(verbose_name='Carbon Copy or Follower')),
                ('mail_bcc', models.JSONField(verbose_name='Blind Carbon Copy | Blind Follower')),
                ('mail_receiver_data', models.JSONField(default=dict, help_text='{"to": [], "cc": [], "bcc": []}', verbose_name='As Sum Receiver Data')),
                ('mail_id', models.CharField(max_length=50, verbose_name='Mail ID Returned')),
                ('mail_thread_id', models.CharField(max_length=50, verbose_name='Mail Thread ID Returned')),
                ('mail_label_ids', models.JSONField(default=list, verbose_name='Mail Label IDs returned')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Flag Status Sent')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_log_of_employee', to='hr.employee', verbose_name='This employee is performer')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Mail Log',
                'verbose_name_plural': 'Mail Log',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DocPined',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('title', models.TextField(blank=True, verbose_name='Title of BookMark')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pined_of_employee', to='hr.employee', verbose_name='This employee is performer')),
            ],
            options={
                'verbose_name': 'Document Pined',
                'verbose_name_plural': 'Document Pined',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
