# Generated by Django 4.1.3 on 2023-06-13 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0006_alter_runtimelog_options_remove_runtime_task_bg_id_and_more'),
        ('hr', '0001_initial'),
        ('tenant', '0001_initial'),
        ('company', '0004_companyconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_method', models.CharField(help_text='choices in: GET, POST, PUT, DELETE, ...', max_length=10, null=True, verbose_name='HTTP method of Log')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('doc_id', models.UUIDField(help_text="Null if it is log's general; otherwise, The value of ID field is required.", null=True, verbose_name='ID of Object')),
                ('doc_app', models.CharField(blank=True, help_text='Format: {app_label}.{model_name}; It is empty when doc_id is null, otherwise the value is required to match the format.', max_length=100, verbose_name='App Code of Object')),
                ('automated_logging', models.BooleanField(help_text='Correct if it is an automated system log; otherwise, the values of the user and employee fields must have a value.', verbose_name='Is automated logging')),
                ('msg', models.TextField(blank=True, help_text='Messages was translated before save', verbose_name='Message was logged')),
                ('data_change', models.JSONField(default=dict, help_text='JSON send from client for POST,PUT', verbose_name='Request Body')),
                ('change_partial', models.BooleanField(default=False, verbose_name='Flag partial of Mixins')),
                ('user_data', models.JSONField(default=dict, verbose_name='User backup data')),
                ('employee_data', models.JSONField(default=dict, verbose_name='Employee backup data')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee', verbose_name='This employee is performer')),
                ('task_workflow', models.ForeignKey(help_text='It is None when update in doc; Otherwise, Update have exist Zone WF', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimeassignee', verbose_name='Task Workflow ID')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='This user is performer')),
            ],
            options={
                'verbose_name': 'Log Activity',
                'verbose_name_plural': 'Log Activity',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['doc_id'], name='log_activit_doc_id_fb0866_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['doc_app'], name='log_activit_doc_app_bc7a81_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['doc_id', 'doc_app'], name='log_activit_doc_id_c3346b_idx'),
        ),
    ]
