# Generated by Django 4.1.3 on 2023-11-11 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0001_initial'),
        ('tenant', '0001_initial'),
        ('workflow', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docpined',
            name='runtime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_pined_of_runtime', to='workflow.runtime', verbose_name='Runtime Object'),
        ),
        migrations.AddField(
            model_name='docpined',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmarks_of_employee', to='hr.employee', verbose_name='This employee is performer'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee', verbose_name='This employee is performer'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='task_workflow',
            field=models.ForeignKey(help_text='It is None when update in doc; Otherwise, Update have exist Zone WF', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimeassignee', verbose_name='Task Workflow ID'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='This user is performer'),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['tenant_id', 'company_id', 'employee_id'], name='log_notific_tenant__b47013_idx'),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['tenant_id', 'company_id', 'employee_id', 'is_done'], name='log_notific_tenant__d01a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['doc_id'], name='log_activit_doc_id_fb0866_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['doc_app'], name='log_activit_doc_app_bc7a81_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['doc_id', 'doc_app'], name='log_activit_doc_id_c3346b_idx'),
        ),
    ]
