# Generated by Django 4.1.3 on 2023-06-22 16:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_alter_runtimelog_options_remove_runtime_task_bg_id_and_more'),
        ('company', '0004_companyconfig'),
        ('tenant', '0001_initial'),
        ('hr', '0001_initial'),
        ('log', '0002_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocPined',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('title', models.TextField(blank=True, verbose_name='Title of BookMark')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pined_of_employee', to='hr.employee', verbose_name='This employee is performer')),
                ('runtime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_pined_of_runtime', to='workflow.runtime', verbose_name='Runtime Object')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Document Pined',
                'verbose_name_plural': 'Document Pined',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20, verbose_name='Title of BookMark')),
                ('kind', models.PositiveSmallIntegerField(choices=[(0, 'View Name'), (1, 'Custom URL')], help_text='[[0, "View Name"], [1, "Custom URL"]]', verbose_name='Type of Bookmarks')),
                ('view_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='View Name UI')),
                ('customize_url', models.TextField(blank=True, null=True, verbose_name='User URL Custom')),
                ('box_style', models.JSONField(default=dict, help_text='{"icon_cls": "", "bg_cls": "", "text_cls": ""}', verbose_name='Style of Box display')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order of BookMark Display')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmarks_of_employee', to='hr.employee', verbose_name='This employee is performer')),
            ],
            options={
                'verbose_name': 'BookMark',
                'verbose_name_plural': 'BookMark',
                'ordering': ('order', '-date_created'),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
