# Generated by Django 4.2.8 on 2024-01-23 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comments_mentions'),
        ('base', '0004_applicationproperty_code_related'),
        ('log', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.application'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='comment_mentions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comment.comments'),
        ),
    ]
