# Generated by Django 4.2.8 on 2024-09-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_notifications_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notify_type',
            field=models.PositiveSmallIntegerField(choices=[(0, ''), (10, 'WF_NEW_TASK'), (11, 'WF_RETURN'), (12, 'WF_END'), (20, 'MENTION')], default=0),
        ),
    ]
