# Generated by Django 4.2.8 on 2025-11-06 09:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_companyconfig_shift_companyconfig_shift_data_and_more'),
        ('tenant', '0001_initial'),
        ('log', '0004_notifications_notify_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('snapshot', models.JSONField(help_text='The data of document')),
                ('app_model_code', models.CharField(max_length=100, null=True)),
                ('app_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
        ),
    ]
