# Generated by Django 4.2.8 on 2024-03-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arinvoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arinvoiceitems',
            old_name='discount_quantity',
            new_name='product_discount_rate',
        ),
        migrations.RenameField(
            model_name='arinvoiceitems',
            old_name='discount_subtotal',
            new_name='product_discount_value',
        ),
        migrations.RenameField(
            model_name='arinvoiceitems',
            old_name='discount_unit_price',
            new_name='product_subtotal_final',
        ),
        migrations.RemoveField(
            model_name='arinvoiceitems',
            name='discount_name',
        ),
        migrations.RemoveField(
            model_name='arinvoiceitems',
            name='discount_uom',
        ),
        migrations.AddField(
            model_name='arinvoiceitems',
            name='product_tax_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='arinvoiceitems',
            name='product_tax_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
