# Generated by Django 4.2.8 on 2024-03-27 17:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_software_start_using_time'),
        ('saledata', '0015_accountactivity'),
        ('tenant', '0001_initial'),
        ('saleorder', '0012_remove_saleorderpaymentstage_date_type_and_more'),
        ('arinvoice', '0002_rename_discount_quantity_arinvoiceitems_product_discount_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arinvoiceitems',
            name='product_tax_rate',
        ),
        migrations.RemoveField(
            model_name='arinvoiceitems',
            name='product_tax_title',
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='customer_bank_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='customer_bank_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='customer_billing_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='customer_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='customer_tax_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='invoice_method',
            field=models.SmallIntegerField(choices=[(1, 'TM'), (2, 'CK'), (3, 'TM/CK')], default=3),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='is_created_einvoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='is_free_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='arinvoiceitems',
            name='product_tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.tax'),
        ),
        migrations.AlterField(
            model_name='arinvoice',
            name='document_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='arinvoice',
            name='invoice_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='arinvoice',
            name='invoice_example',
            field=models.SmallIntegerField(choices=[(0, '01GTKT0'), (1, '01GTKT3'), (2, '02GTTT0'), (3, '02GTTT3'), (4, '03XKNB3'), (5, '04HGDL3'), (6, '07KPTQ3')]),
        ),
        migrations.AlterField(
            model_name='arinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='arinvoice',
            name='invoice_sign',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='arinvoice',
            name='posting_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='arinvoice',
            name='sale_order_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saleorder.saleorder'),
        ),
        migrations.CreateModel(
            name='ARInvoiceSign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(choices=[(0, 'VAT invoice')], default=0)),
                ('one_vat_sign', models.CharField(blank=True, max_length=50, null=True)),
                ('many_vat_sign', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'AR Invoice Sign',
                'verbose_name_plural': 'AR Invoice Signs',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
