# Generated by Django 4.2.8 on 2024-03-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arinvoice', '0003_remove_arinvoiceitems_product_tax_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arinvoicesign',
            name='type',
        ),
        migrations.AddField(
            model_name='arinvoicesign',
            name='sale_invoice_sign',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
