# Generated by Django 4.2.8 on 2024-04-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arinvoice', '0004_remove_arinvoicesign_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arinvoice',
            name='invoice_status',
            field=models.SmallIntegerField(choices=[(0, 'Created'), (1, 'Published'), (2, 'Enumerated'), (3, 'Replaced'), (4, 'Adjusted')], default=0),
        ),
    ]
