# Generated by Django 4.2.8 on 2024-11-28 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recurrence', '0001_initial'),
        ('arinvoice', '0009_arinvoice_process_stage_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='arinvoice',
            name='is_recurrence_template',
            field=models.BooleanField(default=False, help_text='flag to know this record is set as recurrence template'),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='flag to know this record is recurring'),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='recurrence_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_recurrence_task', to='recurrence.recurrencetask'),
        ),
    ]
