# Generated by Django 4.2.8 on 2025-02-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arinvoice', '0011_arinvoiceitems_ar_product_des'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arinvoice',
            name='customer_bank_code',
        ),
        migrations.RemoveField(
            model_name='arinvoice',
            name='customer_bank_number',
        ),
        migrations.RemoveField(
            model_name='arinvoice',
            name='customer_billing_address',
        ),
        migrations.RemoveField(
            model_name='arinvoice',
            name='customer_code',
        ),
        migrations.RemoveField(
            model_name='arinvoice',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='arinvoice',
            name='customer_tax_number',
        ),
        migrations.RemoveField(
            model_name='arinvoice',
            name='is_free_input',
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='sum_after_tax_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='sum_discount_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='sum_pretax_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='sum_tax_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='arinvoice',
            name='invoice_method',
            field=models.SmallIntegerField(choices=[(1, 'TM'), (2, 'CK')], default=3),
        ),
    ]
