# Generated by Django 4.2.8 on 2025-04-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arinvoice', '0014_arinvoice_cash_inflow_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arinvoiceitems',
            name='product_discount_rate',
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='arinvoiceitems',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
