# Generated by Django 4.2.8 on 2025-07-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arinvoice', '0016_arinvoice_company_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arinvoiceitems',
            options={'default_permissions': (), 'ordering': ('order',), 'permissions': (), 'verbose_name': 'AR Invoice Item', 'verbose_name_plural': 'AR Invoice Items'},
        ),
        migrations.RenameField(
            model_name='arinvoiceitems',
            old_name='item_index',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='arinvoiceitems',
            name='ar_product_des',
            field=models.TextField(blank=True, null=True),
        ),
    ]
