# Generated by Django 4.2.8 on 2025-12-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arinvoice', '0017_alter_arinvoiceitems_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arinvoiceitems',
            name='product_quantity',
            field=models.FloatField(default=1),
        ),
    ]
