# Generated by Django 4.2.8 on 2025-12-12 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0033_rename_has_ar_invoice_already_orderdeliverysub_is_done_ar_invoice_and_more'),
        ('leaseorder', '0016_remove_leaseorderproduct_offset_and_more'),
        ('arinvoice', '0018_alter_arinvoiceitems_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arinvoice',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='arinvoiceitems',
            name='ar_product_des',
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='buyer_information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='lease_order_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leaseorder.leaseorder'),
        ),
        migrations.AddField(
            model_name='arinvoice',
            name='lease_order_mapped_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='arinvoiceitems',
            name='delivery_item_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.orderdeliveryproduct'),
        ),
        migrations.AddField(
            model_name='arinvoiceitems',
            name='product_discount_percent',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='arinvoiceitems',
            name='product_payment_percent',
            field=models.FloatField(default=100, null=True),
        ),
        migrations.AddField(
            model_name='arinvoiceitems',
            name='product_payment_value',
            field=models.FloatField(default=0),
        ),
    ]
