# Generated by Django 4.2.8 on 2025-12-12 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0033_rename_has_ar_invoice_already_orderdeliverysub_is_done_ar_invoice_and_more'),
        ('arinvoice', '0019_remove_arinvoice_buyer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arinvoiceitems',
            name='delivery_item_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_delivery_items_mapped', to='delivery.orderdeliveryproduct'),
        ),
    ]
