# Generated by Django 4.2.8 on 2025-12-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arinvoice', '0020_alter_arinvoiceitems_delivery_item_mapped'),
    ]

    operations = [
        migrations.AddField(
            model_name='arinvoiceitems',
            name='product_quantity_time',
            field=models.FloatField(default=0),
        ),
    ]
