# Generated by Django 4.1.3 on 2023-09-12 22:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchasing', '0011_remove_purchaseorderrequestproduct_quantity_remain'),
        ('tenant', '0001_initial'),
        ('space', '0001_initial'),
        ('workflow', '0008_runtime_doc_employee_inherit_and_more'),
        ('saledata', '0049_remove_product_general_product_type_and_more'),
        ('process', '0002_salefunction_process_code_process_company_and_more'),
        ('hr', '0006_alter_employee_code_alter_employee_unique_together'),
        ('company', '0006_alter_company_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('goods_receipt_type', models.SmallIntegerField(default=0, help_text="choices= ((0, 'For purchase order'), (1, 'For inventory adjustment'), (2, 'For production'))")),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Description of this records')),
                ('date_received', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
                ('purchase_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_po', to='purchasing.purchaseorder', verbose_name='purchase order')),
            ],
            options={
                'verbose_name': 'Goods Receipt',
                'verbose_name_plural': 'Goods Receipts',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_import', models.FloatField(default=0)),
                ('product_title', models.CharField(blank=True, max_length=100, null=True)),
                ('product_code', models.CharField(blank=True, max_length=100, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_unit_price', models.FloatField(default=0)),
                ('product_subtotal_price', models.FloatField(default=0)),
                ('product_subtotal_price_after_tax', models.FloatField(default=0)),
                ('order', models.IntegerField(default=1)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_product_goods_receipt', to='inventory.goodsreceipt', verbose_name='goods receipt')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_product_product', to='saledata.product', verbose_name='product')),
                ('purchase_order_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_product_po_product', to='purchasing.purchaseorderproduct', verbose_name='po product')),
                ('tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_product_tax', to='saledata.tax', verbose_name='tax')),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_product_uom', to='saledata.unitofmeasure', verbose_name='unit of measure')),
            ],
            options={
                'verbose_name': 'Goods Receipt Product',
                'verbose_name_plural': 'Goods Receipt Products',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptRequestProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_import', models.FloatField(default=0)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_request_product_goods_receipt', to='inventory.goodsreceipt', verbose_name='goods receipt')),
                ('goods_receipt_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_request_product_gr_product', to='inventory.goodsreceiptproduct', verbose_name='goods receipt product')),
                ('purchase_request_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_request_product_pr_product', to='purchasing.purchaserequestproduct', verbose_name='purchase request product')),
            ],
            options={
                'verbose_name': 'Goods Receipt Request Product',
                'verbose_name_plural': 'Goods Receipt Request Products',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptWarehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_import', models.FloatField(default=0)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_warehouse_goods_receipt', to='inventory.goodsreceipt', verbose_name='goods receipt')),
                ('goods_receipt_request_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_warehouse_request_product', to='inventory.goodsreceiptrequestproduct', verbose_name='goods receipt request product')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_warehouse_warehouse', to='saledata.warehouse', verbose_name='warehouse')),
            ],
            options={
                'verbose_name': 'Goods Receipt Warehouse',
                'verbose_name_plural': 'Goods Receipt Warehouses',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptSerial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expire_date', models.DateTimeField(null=True)),
                ('manufacture_date', models.DateTimeField(null=True)),
                ('warranty_start', models.DateTimeField(null=True)),
                ('warranty_end', models.DateTimeField(null=True)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_serial_goods_receipt', to='inventory.goodsreceipt', verbose_name='goods receipt')),
                ('goods_receipt_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_serial_gr_warehouse', to='inventory.goodsreceiptwarehouse', verbose_name='goods receipt warehouse')),
            ],
            options={
                'verbose_name': 'Goods Receipt Serial',
                'verbose_name_plural': 'Goods Receipt Serials',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptPurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_pr_goods_receipt', to='inventory.goodsreceipt', verbose_name='goods receipt')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_pr_pr', to='purchasing.purchaserequest', verbose_name='purchase request')),
            ],
            options={
                'verbose_name': 'Goods Receipt Purchase Request',
                'verbose_name_plural': 'Goods Receipt Purchase Requests',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_import', models.FloatField(default=0)),
                ('expire_date', models.DateTimeField(null=True)),
                ('manufacture_date', models.DateTimeField(null=True)),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_lot_goods_receipt', to='inventory.goodsreceipt', verbose_name='goods receipt')),
                ('goods_receipt_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_lot_gr_warehouse', to='inventory.goodsreceiptwarehouse', verbose_name='goods receipt warehouse')),
            ],
            options={
                'verbose_name': 'Goods Receipt Lot',
                'verbose_name_plural': 'Goods Receipt Lots',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_requests',
            field=models.ManyToManyField(blank=True, related_name='goods_receipt_map_pr', through='inventory.GoodsReceiptPurchaseRequest', to='purchasing.purchaserequest'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='supplier',
            field=models.ForeignKey(help_text='sale data Accounts have type supplier', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_supplier', to='saledata.account', verbose_name='supplier'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
    ]
