# Generated by Django 4.1.3 on 2023-11-11 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0001_initial'),
        ('company', '0002_initial'),
        ('inventory', '0001_initial'),
        ('tenant', '0001_initial'),
        ('space', '0001_initial'),
        ('workflow', '0001_initial'),
        ('hr', '0001_initial'),
        ('saledata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryadjustmentwarehouse',
            name='warehouse_mapped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.warehouse'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='inventory_adjustment_mapped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustment_item_mapped', to='inventory.inventoryadjustment'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='product_mapped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.product'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='product_warehouse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='saledata.productwarehouse'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='uom_mapped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='warehouse_mapped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.warehouse'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentemployeeincharge',
            name='employee_mapped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentemployeeincharge',
            name='inventory_adjustment_mapped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryadjustment'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='current_stage',
            field=models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='employees_in_charge_mapped',
            field=models.ManyToManyField(blank=True, related_name='employees_in_charge_mapped_ia', through='inventory.InventoryAdjustmentEmployeeInCharge', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='warehouses_mapped',
            field=models.ManyToManyField(blank=True, related_name='warehouses_mapped_ia', through='inventory.InventoryAdjustmentWarehouse', to='saledata.warehouse'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
        migrations.AddField(
            model_name='goodstransferproduct',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='goodstransferproduct',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='goodstransferproduct',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='goodstransferproduct',
            name='end_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_warehouse_goods_transfer', to='saledata.warehouse'),
        ),
        migrations.AddField(
            model_name='goodstransferproduct',
            name='goods_transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_transfer', to='inventory.goodstransfer'),
        ),
        migrations.AddField(
            model_name='goodstransferproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_goods_transfer', to='saledata.product'),
        ),
        migrations.AddField(
            model_name='goodstransferproduct',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='goodstransferproduct',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uom_goods_transfer', to='saledata.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='goodstransferproduct',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_goods_transfer', to='saledata.warehouse'),
        ),
        migrations.AddField(
            model_name='goodstransferproduct',
            name='warehouse_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_warehouse_goods_transfer', to='saledata.productwarehouse'),
        ),
        migrations.AddField(
            model_name='goodstransfer',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_transfer_agency', to='saledata.account'),
        ),
        migrations.AddField(
            model_name='goodstransfer',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='goodstransfer',
            name='current_stage',
            field=models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc'),
        ),
        migrations.AddField(
            model_name='goodstransfer',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='goodstransfer',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='goodstransfer',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='goodstransfer',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='goodstransfer',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='goodstransfer',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='goodstransfer',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
        migrations.AddField(
            model_name='goodsreceiptwarehouse',
            name='goods_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_warehouse_goods_receipt', to='inventory.goodsreceipt', verbose_name='goods receipt'),
        ),
        migrations.AddField(
            model_name='goodsreceiptwarehouse',
            name='goods_receipt_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_warehouse_gr_product', to='inventory.goodsreceiptproduct', verbose_name='goods receipt product'),
        ),
        migrations.AddField(
            model_name='goodsreceiptwarehouse',
            name='goods_receipt_request_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_warehouse_request_product', to='inventory.goodsreceiptrequestproduct', verbose_name='goods receipt request product'),
        ),
        migrations.AddField(
            model_name='goodsreceiptwarehouse',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_warehouse_warehouse', to='saledata.warehouse', verbose_name='warehouse'),
        ),
        migrations.AddField(
            model_name='goodsreceiptserial',
            name='goods_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_serial_goods_receipt', to='inventory.goodsreceipt', verbose_name='goods receipt'),
        ),
        migrations.AddField(
            model_name='goodsreceiptserial',
            name='goods_receipt_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_serial_gr_warehouse', to='inventory.goodsreceiptwarehouse', verbose_name='goods receipt warehouse'),
        ),
        migrations.AddField(
            model_name='goodsreceiptrequestproduct',
            name='goods_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_request_product_goods_receipt', to='inventory.goodsreceipt', verbose_name='goods receipt'),
        ),
        migrations.AddField(
            model_name='goodsreceiptrequestproduct',
            name='goods_receipt_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_request_product_gr_product', to='inventory.goodsreceiptproduct', verbose_name='goods receipt product'),
        ),
    ]
