# Generated by Django 4.1.3 on 2023-11-11 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('company', '0002_initial'),
        ('tenant', '0001_initial'),
        ('space', '0001_initial'),
        ('workflow', '0001_initial'),
        ('hr', '0001_initial'),
        ('inventory', '0002_initial'),
        ('saledata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptrequestproduct',
            name='purchase_order_request_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gr_request_product_po_request_product', to='purchasing.purchaseorderrequestproduct', verbose_name='purchase order request product'),
        ),
        migrations.AddField(
            model_name='goodsreceiptrequestproduct',
            name='purchase_request_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_request_product_pr_product', to='purchasing.purchaserequestproduct', verbose_name='purchase request product'),
        ),
        migrations.AddField(
            model_name='goodsreceiptpurchaserequest',
            name='goods_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_pr_goods_receipt', to='inventory.goodsreceipt', verbose_name='goods receipt'),
        ),
        migrations.AddField(
            model_name='goodsreceiptpurchaserequest',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_pr_pr', to='purchasing.purchaserequest', verbose_name='purchase request'),
        ),
        migrations.AddField(
            model_name='goodsreceiptproduct',
            name='goods_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_product_goods_receipt', to='inventory.goodsreceipt', verbose_name='goods receipt'),
        ),
        migrations.AddField(
            model_name='goodsreceiptproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_product_product', to='saledata.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='goodsreceiptproduct',
            name='purchase_order_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_product_po_product', to='purchasing.purchaseorderproduct', verbose_name='po product'),
        ),
        migrations.AddField(
            model_name='goodsreceiptproduct',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_product_tax', to='saledata.tax', verbose_name='tax'),
        ),
        migrations.AddField(
            model_name='goodsreceiptproduct',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_product_uom', to='saledata.unitofmeasure', verbose_name='unit of measure'),
        ),
        migrations.AddField(
            model_name='goodsreceiptproduct',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_product_warehouse', to='saledata.warehouse', verbose_name='warehouse'),
        ),
        migrations.AddField(
            model_name='goodsreceiptlot',
            name='goods_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_lot_goods_receipt', to='inventory.goodsreceipt', verbose_name='goods receipt'),
        ),
        migrations.AddField(
            model_name='goodsreceiptlot',
            name='goods_receipt_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_lot_gr_warehouse', to='inventory.goodsreceiptwarehouse', verbose_name='goods receipt warehouse'),
        ),
        migrations.AddField(
            model_name='goodsreceiptlot',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_lot_lot', to='saledata.productwarehouselot', verbose_name='product warehouse lot'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='current_stage',
            field=models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='inventory_adjustment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_ia', to='inventory.inventoryadjustment', verbose_name='inventory adjustment'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_po', to='purchasing.purchaseorder', verbose_name='purchase order'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_requests',
            field=models.ManyToManyField(blank=True, related_name='goods_receipt_map_pr', through='inventory.GoodsReceiptPurchaseRequest', to='purchasing.purchaserequest'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='supplier',
            field=models.ForeignKey(help_text='sale data Accounts have type supplier', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_supplier', to='saledata.account', verbose_name='supplier'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
        migrations.AddField(
            model_name='goodsissueproduct',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='goodsissueproduct',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='goodsissueproduct',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='goodsissueproduct',
            name='goods_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_issue_product', to='inventory.goodsissue'),
        ),
        migrations.AddField(
            model_name='goodsissueproduct',
            name='inventory_adjustment_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ia_item_goods_issue', to='inventory.inventoryadjustmentitem'),
        ),
        migrations.AddField(
            model_name='goodsissueproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_goods_issue', to='saledata.product'),
        ),
        migrations.AddField(
            model_name='goodsissueproduct',
            name='product_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_warehouse_goods_issue', to='saledata.productwarehouse'),
        ),
        migrations.AddField(
            model_name='goodsissueproduct',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='goodsissueproduct',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uom_goods_issue', to='saledata.unitofmeasure'),
        ),
        migrations.AddField(
            model_name='goodsissueproduct',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_goods_issue', to='saledata.warehouse'),
        ),
        migrations.AddField(
            model_name='goodsissue',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='goodsissue',
            name='current_stage',
            field=models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc'),
        ),
        migrations.AddField(
            model_name='goodsissue',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='goodsissue',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='goodsissue',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='goodsissue',
            name='inventory_adjustment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_issue_ia', to='inventory.inventoryadjustment'),
        ),
        migrations.AddField(
            model_name='goodsissue',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='goodsissue',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='goodsissue',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='goodsissue',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
    ]
