# Generated by Django 4.1.3 on 2023-09-25 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_goodstransfer_goodstransferproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptwarehouse',
            name='goods_receipt_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_warehouse_gr_product', to='inventory.goodsreceiptproduct', verbose_name='goods receipt product'),
        ),
    ]
