# Generated by Django 4.1.3 on 2023-09-26 17:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0051_rename_type_tax_tax_type'),
        ('tenant', '0001_initial'),
        ('company', '0008_remove_company_language'),
        ('hr', '0006_alter_employee_code_alter_employee_unique_together'),
        ('inventory', '0004_goodsreceiptwarehouse_goods_receipt_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryadjustmentitem',
            options={'default_permissions': (), 'ordering': ('-date_created',), 'permissions': (), 'verbose_name': 'Inventory Adjustment Item', 'verbose_name_plural': 'Inventory Adjustment Items'},
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='action_type',
            field=models.SmallIntegerField(choices=[(0, 'Equal'), (1, 'Decreasing'), (2, 'Increasing')], default=0, verbose_name='check increase, decrease or equal stock amount'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='product_warehouse',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='saledata.productwarehouse'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
