# Generated by Django 4.1.3 on 2023-09-27 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0051_rename_type_tax_tax_type'),
        ('inventory', '0005_alter_inventoryadjustmentitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='inventory_adjustment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_ia', to='inventory.inventoryadjustment', verbose_name='inventory adjustment'),
        ),
        migrations.AddField(
            model_name='goodsreceiptproduct',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_product_warehouse', to='saledata.warehouse', verbose_name='warehouse'),
        ),
    ]
