# Generated by Django 4.2.8 on 2024-02-19 09:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0005_publicfiles_relate_app_publicfiles_relate_app_code_and_more'),
        ('inventory', '0005_goodsreturn_goodsreturnproductdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReturnAttachmentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('attachment', models.OneToOneField(help_text='Many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_files', to='attachments.files', verbose_name='Attachment files')),
                ('goods_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_return_attachments', to='inventory.goodsreturn')),
            ],
            options={
                'verbose_name': 'Goods Return attachment',
                'verbose_name_plural': 'Goods Return attachments',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
