# Generated by Django 4.1.3 on 2023-10-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_goodsissue_goodsissueproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsissue',
            name='note',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
