# Generated by Django 4.2.8 on 2024-04-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_goodsissue_document_change_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsissueproduct',
            name='lot_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='goodsissueproduct',
            name='sn_data',
            field=models.JSONField(default=list),
        ),
    ]
