# Generated by Django 4.1.3 on 2023-10-16 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0014_remove_purchasequotationproduct_description_and_more'),
        ('inventory', '0008_alter_goodsissue_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptrequestproduct',
            name='is_stock',
            field=models.BooleanField(default=False, help_text='True if GR direct to stock, stock is created from PO when quantity order > quantity request'),
        ),
        migrations.AddField(
            model_name='goodsreceiptrequestproduct',
            name='purchase_order_request_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gr_request_product_po_request_product', to='purchasing.purchaseorderrequestproduct', verbose_name='purchase order request product'),
        ),
    ]
