# Generated by Django 4.1.3 on 2023-10-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0056_alter_productwarehouse_tax_and_more'),
        ('inventory', '0009_goodsreceiptrequestproduct_is_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptlot',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_lot_lot', to='saledata.productwarehouselot', verbose_name='product warehouse lot'),
        ),
    ]
