# Generated by Django 4.2.8 on 2024-04-22 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_goodsreceiptproduct_is_additional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptproduct',
            name='ia_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipt_product_ia_item', to='inventory.inventoryadjustmentitem'),
        ),
        migrations.AddField(
            model_name='inventoryadjustment',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
