# Generated by Django 4.2.8 on 2024-04-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_goodsreceiptproduct_is_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='gr_completed_quantity',
            field=models.FloatField(default=0, help_text='this is quantity of product which is goods receipted, update when GR finish'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='gr_remain_quantity',
            field=models.FloatField(default=0, help_text='this is quantity of product which is not goods receipted yet, update when GR finish'),
        ),
    ]
