# Generated by Django 4.2.8 on 2024-04-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_inventoryadjustmentitem_gr_completed_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsissue',
            options={'default_permissions': (), 'ordering': ('-date_created',), 'permissions': (), 'verbose_name': 'Goods Issue', 'verbose_name_plural': 'Goods Issue'},
        ),
    ]
