# Generated by Django 4.2.8 on 2024-05-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_goodsissue_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstransferproduct',
            name='lot_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='goodstransferproduct',
            name='sn_data',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='goodsissue',
            name='goods_issue_datas',
            field=models.JSONField(help_text='[{"warehouse": {"id": "warehouse_id", "title": "warehouse_title"}, "product": {"id": "id", "product_data": {"id": "product_id", "title": "product_title"}}, "uom": {"id": "uom_id", "title": "uom_title"}, "quantity": 2, "product_warehouse_id": "product_warehouse_id", "inventory_adjustment_item_id": "inventory_adjustment_item_id", "description": "xxx", "unit_cost": 500000, "subtotal_cost": 1000000, "lot_changes": [], "sn_changes": []}]'),
        ),
        migrations.AlterField(
            model_name='goodstransfer',
            name='goods_transfer_datas',
            field=models.JSONField(help_text='[{"warehouse": {"id": "warehouse_id", "title": "warehouse_title"}, "warehouse_product": {"id": "id", "product_data": {"id": "product_id", "title": "product_title"}}, "uom": {"id": "uom_id", "title": "uom_title"}, "quantity": 2, "end_warehouse": {"id": "end_warehouse_id", "title": "end_warehouse_title"}, "unit_cost": 500000, "subtotal_cost": 1000000, "lot_changes": [], "sn_changes": []}]'),
        ),
        migrations.AlterField(
            model_name='goodstransfer',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
