# Generated by Django 4.2.8 on 2024-05-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_goodstransferproduct_lot_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreturn',
            name='data_item',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='goodsreturn',
            name='product_detail_list',
            field=models.JSONField(default=list),
        ),
    ]
