# Generated by Django 4.2.8 on 2024-05-10 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_orderdelivery_document_change_order_and_more'),
        ('inventory', '0016_goodsreturn_data_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreturnproductdetail',
            name='default_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.orderdeliveryproduct'),
        ),
    ]
