# Generated by Django 4.2.8 on 2024-05-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_rename_default_item_goodsreturnproductdetail_delivery_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreturnproductdetail',
            name='cost_for_periodic',
            field=models.FloatField(default=0),
        ),
    ]
