# Generated by Django 4.2.8 on 2024-05-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_goodsreturnproductdetail_cost_for_periodic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsreceiptproduct',
            options={'default_permissions': (), 'ordering': ('order',), 'permissions': (), 'verbose_name': 'Goods Receipt Product', 'verbose_name_plural': 'Goods Receipt Products'},
        ),
    ]
