# Generated by Django 4.2.8 on 2024-06-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_goodsreceiptproduct_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreturn',
            name='data_item',
        ),
        migrations.AddField(
            model_name='goodsreturn',
            name='data_line_detail',
            field=models.JSONField(default=list, help_text='to_quick_load_Line_detail_tab'),
        ),
    ]
