# Generated by Django 4.2.8 on 2024-06-07 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0027_remove_productwarehouselot_raw_quantity_import'),
        ('inventory', '0021_remove_goodsreturn_data_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreturn',
            name='data_line_detail',
        ),
        migrations.RemoveField(
            model_name='goodsreturn',
            name='product',
        ),
        migrations.RemoveField(
            model_name='goodsreturn',
            name='return_to_warehouse',
        ),
        migrations.RemoveField(
            model_name='goodsreturn',
            name='uom',
        ),
        migrations.AddField(
            model_name='goodsreturn',
            name='data_line_detail_table',
            field=models.JSONField(default=list, help_text='to_quick_load_line_detail_table'),
        ),
        migrations.AddField(
            model_name='goodsreturnproductdetail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.product'),
        ),
        migrations.AddField(
            model_name='goodsreturnproductdetail',
            name='return_to_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.warehouse'),
        ),
        migrations.AddField(
            model_name='goodsreturnproductdetail',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='goodsreturn',
            name='product_detail_list',
            field=models.JSONField(default=list, help_text='data to create mapped items'),
        ),
    ]
