# Generated by Django 4.2.8 on 2024-06-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_goodsregistration_goodsregistrationlinedetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsregistrationlinedetail',
            name='registered_data',
            field=models.JSONField(default=list),
        ),
    ]
