# Generated by Django 4.2.8 on 2024-06-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_goodsregistrationlinedetail_registered_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsregistrationlinedetail',
            old_name='registered_quantity',
            new_name='out_delivered',
        ),
        migrations.AddField(
            model_name='goodsregistrationlinedetail',
            name='out_delivered_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsregistrationlinedetail',
            name='out_registered',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsregistrationlinedetail',
            name='out_registered_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsregistrationlinedetail',
            name='out_remain',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsregistrationlinedetail',
            name='out_remain_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsregistrationlinedetail',
            name='this_available',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsregistrationlinedetail',
            name='this_available_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsregistrationlinedetail',
            name='this_others',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsregistrationlinedetail',
            name='this_others_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsregistrationlinedetail',
            name='this_registered',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsregistrationlinedetail',
            name='this_registered_value',
            field=models.FloatField(default=0),
        ),
    ]
