# Generated by Django 4.2.8 on 2024-07-02 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("saledata", "0027_remove_productwarehouselot_raw_quantity_import"),
        ("inventory", "0026_remove_goodsregistrationlot_lot_registered_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsregistrationlot",
            name="warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods_registration_lot_warehouse",
                to="saledata.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="goodsregistrationserial",
            name="warehouse",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods_registration_serial_warehouse",
                to="saledata.warehouse",
            ),
        ),
    ]
