# Generated by Django 4.2.8 on 2024-07-12 09:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0027_remove_productwarehouselot_raw_quantity_import'),
        ('inventory', '0027_rename_warehouse_product_goodstransferproduct_product_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsregistrationitem',
            name='out_available',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsregistrationitem',
            name='out_registered',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsregistrationitem',
            name='this_registered_borrowed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsregistrationitem',
            name='this_registered_value_borrowed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsregistrationitemsub',
            name='lot_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.productwarehouselot'),
        ),
        migrations.CreateModel(
            name='GoodsRegistrationItemBorrow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField(default=0)),
                ('goods_registration_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gre_des', to='inventory.goodsregistration')),
                ('goods_registration_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gre_src', to='inventory.goodsregistration')),
                ('gre_item_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gre_item_borrow_des', to='inventory.goodsregistrationitem')),
                ('gre_item_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gre_item_borrow_src', to='inventory.goodsregistrationitem')),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gre_item_borrow_uom', to='saledata.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Goods Registration Item Borrow',
                'verbose_name_plural': 'Goods Registration Item Borrow',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
