# Generated by Django 4.2.8 on 2024-07-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_goodsregistrationitem_out_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsregistrationgeneral',
            name='picked_ready',
            field=models.FloatField(default=0, help_text='quantity of products which were picked to delivery from total quantity registered'),
        ),
    ]
