# Generated by Django 4.2.8 on 2024-07-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_goodsregistrationitemborrow_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsregistrationitemborrow',
            name='base_available',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsregistrationitemborrow',
            name='base_quantity',
            field=models.FloatField(default=0),
        ),
    ]
