# Generated by Django 4.2.8 on 2024-08-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_goodsissueproduct_date_modified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsregistrationgeneral',
            options={'default_permissions': (), 'ordering': ('goods_registration__code',), 'permissions': (), 'verbose_name': 'Goods Registration General', 'verbose_name_plural': 'Goods Registration General'},
        ),
        migrations.AlterModelOptions(
            name='goodsregistrationlot',
            options={'default_permissions': (), 'ordering': ('goods_registration__code',), 'permissions': (), 'verbose_name': 'Goods Registration Lot', 'verbose_name_plural': 'Goods Registration Lot'},
        ),
        migrations.AlterModelOptions(
            name='goodsregistrationserial',
            options={'default_permissions': (), 'ordering': ('goods_registration__code',), 'permissions': (), 'verbose_name': 'Goods Registration Serial', 'verbose_name_plural': 'Goods Registration Serial'},
        ),
    ]
