# Generated by Django 4.2.8 on 2024-08-01 10:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0008_alter_files_date_modified_alter_folder_date_modified_and_more'),
        ('inventory', '0033_alter_goodsregistrationgeneral_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceiptAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('attachment', models.OneToOneField(help_text='Many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_files', to='attachments.files', verbose_name='Attachment files')),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_attachment_gr', to='inventory.goodsreceipt', verbose_name='goods receipt')),
            ],
            options={
                'verbose_name': 'Goods receipt attachments',
                'verbose_name_plural': 'Goods receipt attachments',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='attachment_m2m',
            field=models.ManyToManyField(blank=True, related_name='file_of_goods_receipt', through='inventory.GoodsReceiptAttachment', to='attachments.files'),
        ),
    ]
