# Generated by Django 4.2.8 on 2024-08-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_goodsreceiptattachment_goodsreceipt_attachment_m2m'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsregistrationitem',
            old_name='this_available_value',
            new_name='out_delivered',
        ),
        migrations.RemoveField(
            model_name='goodsregistrationitem',
            name='this_registered_value',
        ),
        migrations.RemoveField(
            model_name='goodsregistrationitem',
            name='this_registered_value_borrowed',
        ),
        migrations.AddField(
            model_name='goodsregistrationitemborrow',
            name='base_delivered',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsregistrationitemborrow',
            name='delivered',
            field=models.FloatField(default=0),
        ),
    ]
