# Generated by Django 4.2.8 on 2024-08-06 16:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0031_alter_accountactivity_date_modified_and_more'),
        ('inventory', '0035_rename_this_available_value_goodsregistrationitem_out_delivered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GReItemBorrow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField(default=0)),
                ('delivered', models.FloatField(default=0)),
                ('available', models.FloatField(default=0)),
                ('base_quantity', models.FloatField(default=0)),
                ('base_delivered', models.FloatField(default=0)),
                ('base_available', models.FloatField(default=0)),
                ('gre_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gre_des_borrow', to='inventory.goodsregistration')),
                ('gre_item_destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gre_item_des_borrow', to='inventory.goodsregistrationitem')),
                ('gre_item_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gre_item_src_borrow', to='inventory.goodsregistrationitem')),
                ('gre_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gre_src_borrow', to='inventory.goodsregistration')),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gre_item_borrow_uom', to='saledata.unitofmeasure')),
            ],
            options={
                'verbose_name': 'GRe Item Borrow',
                'verbose_name_plural': 'GRe Items Borrow',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GReItemProductWarehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField(default=0)),
                ('picked_ready', models.FloatField(default=0, help_text='quantity of products which were picked to delivery from total quantity registered')),
                ('goods_registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.goodsregistration')),
                ('gre_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gre_item_prd_wh', to='inventory.goodsregistrationitem')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gre_item_prd_wh_warehouse', to='saledata.warehouse')),
            ],
            options={
                'verbose_name': 'GRe Item Product Warehouse',
                'verbose_name_plural': 'GRe Items Product Warehouse',
                'ordering': ('goods_registration__code',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GReItemProductWarehouseLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goods_registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.goodsregistration')),
                ('gre_item_prd_wh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gre_item_prd_wh_lot', to='inventory.greitemproductwarehouse')),
                ('lot_registered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gre_item_prd_wh_lot_registered', to='saledata.productwarehouselot')),
            ],
            options={
                'verbose_name': 'GRe Item Product Warehouse Lot',
                'verbose_name_plural': 'GRe Items Product Warehouse Lot',
                'ordering': ('goods_registration__code',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='GReItemProductWarehouseSerial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goods_registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.goodsregistration')),
                ('gre_item_prd_wh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gre_item_prd_wh_serial', to='inventory.greitemproductwarehouse')),
                ('sn_registered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gre_item_prd_wh_serial_registered', to='saledata.productwarehouseserial')),
            ],
            options={
                'verbose_name': 'GRe Item Product Warehouse Serial',
                'verbose_name_plural': 'GRe Items Product Warehouse Serial',
                'ordering': ('goods_registration__code',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='NoneGReItemBorrow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField(default=0)),
                ('delivered', models.FloatField(default=0)),
                ('available', models.FloatField(default=0)),
                ('base_quantity', models.FloatField(default=0)),
                ('base_delivered', models.FloatField(default=0)),
                ('base_available', models.FloatField(default=0)),
                ('gre_item_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='none_gre_item_src_borrow', to='inventory.goodsregistrationitem')),
                ('gre_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='none_gre_src_borrow', to='inventory.goodsregistration')),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gre_item_src_borrow_uom', to='saledata.unitofmeasure')),
                ('warehouse_mapped', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gre_item_src_borrow_warehouse_mapped', to='saledata.warehouse')),
            ],
            options={
                'verbose_name': 'None GRe Item Borrow',
                'verbose_name_plural': 'None GRe Items Borrow',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='NoneGReItemProductWarehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField(default=0)),
                ('picked_ready', models.FloatField(default=0, help_text='quantity of products which were picked to delivery from total quantity registered')),
                ('keep_for_project', models.FloatField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='none_gre_item_product', to='saledata.product')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='none_gre_item_warehouse', to='saledata.warehouse')),
            ],
            options={
                'verbose_name': 'None GRe Item Product Warehouse',
                'verbose_name_plural': 'None GRe Items Product Warehouse',
                'ordering': ('product__code',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='NoneGReItemProductWarehouseLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='none_gre_item_prd_wh_lot_mapped', to='saledata.productwarehouselot')),
                ('none_gre_item_prd_wh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='none_gre_item_prd_wh_lot', to='inventory.nonegreitemproductwarehouse')),
            ],
            options={
                'verbose_name': 'None GRe Item Product Warehouse Lot',
                'verbose_name_plural': 'None GRe Items Product Warehouse Lot',
                'ordering': ('lot_mapped__lot_number',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='NoneGReItemProductWarehouseSerial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('none_gre_item_prd_wh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='none_gre_item_prd_wh_serial', to='inventory.nonegreitemproductwarehouse')),
                ('sn_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='none_gre_item_prd_wh_serial_mapped', to='saledata.productwarehouseserial')),
            ],
            options={
                'verbose_name': 'None GRe Item Product Warehouse Serial',
                'verbose_name_plural': 'None GRe Items Product Warehouse Serial',
                'ordering': ('sn_mapped__serial_number',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='goodsregistrationitemborrow',
            name='goods_registration_destination',
        ),
        migrations.RemoveField(
            model_name='goodsregistrationitemborrow',
            name='goods_registration_source',
        ),
        migrations.RemoveField(
            model_name='goodsregistrationitemborrow',
            name='gre_item_destination',
        ),
        migrations.RemoveField(
            model_name='goodsregistrationitemborrow',
            name='gre_item_source',
        ),
        migrations.RemoveField(
            model_name='goodsregistrationitemborrow',
            name='uom',
        ),
        migrations.RemoveField(
            model_name='goodsregistrationlot',
            name='goods_registration',
        ),
        migrations.RemoveField(
            model_name='goodsregistrationlot',
            name='gre_general',
        ),
        migrations.RemoveField(
            model_name='goodsregistrationlot',
            name='lot_registered',
        ),
        migrations.RemoveField(
            model_name='goodsregistrationserial',
            name='goods_registration',
        ),
        migrations.RemoveField(
            model_name='goodsregistrationserial',
            name='gre_general',
        ),
        migrations.RemoveField(
            model_name='goodsregistrationserial',
            name='sn_registered',
        ),
        migrations.DeleteModel(
            name='GoodsRegistrationGeneral',
        ),
        migrations.DeleteModel(
            name='GoodsRegistrationItemBorrow',
        ),
        migrations.DeleteModel(
            name='GoodsRegistrationLot',
        ),
        migrations.DeleteModel(
            name='GoodsRegistrationSerial',
        ),
    ]
