# Generated by Django 4.2.8 on 2024-09-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_alter_goodsissue_date_modified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsissueproduct',
            options={'default_permissions': (), 'ordering': ('product__code',), 'permissions': (), 'verbose_name': 'Goods Issue Product', 'verbose_name_plural': 'Goods Issue Products'},
        ),
        migrations.AlterModelOptions(
            name='inventoryadjustmentitem',
            options={'default_permissions': (), 'ordering': ('product_mapped__code',), 'permissions': (), 'verbose_name': 'Inventory Adjustment Item', 'verbose_name_plural': 'Inventory Adjustment Items'},
        ),
        migrations.RemoveField(
            model_name='goodsissue',
            name='date_issue',
        ),
        migrations.RemoveField(
            model_name='goodsissue',
            name='goods_issue_datas',
        ),
        migrations.RemoveField(
            model_name='goodsissueproduct',
            name='code',
        ),
        migrations.RemoveField(
            model_name='goodsissueproduct',
            name='company',
        ),
        migrations.RemoveField(
            model_name='goodsissueproduct',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='goodsissueproduct',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='goodsissueproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='goodsissueproduct',
            name='employee_created',
        ),
        migrations.RemoveField(
            model_name='goodsissueproduct',
            name='employee_modified',
        ),
        migrations.RemoveField(
            model_name='goodsissueproduct',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='goodsissueproduct',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='goodsissueproduct',
            name='product_title',
        ),
        migrations.RemoveField(
            model_name='goodsissueproduct',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='goodsissueproduct',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='goodsissueproduct',
            name='title',
        ),
        migrations.RemoveField(
            model_name='goodsissueproduct',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='goodsissueproduct',
            name='uom_title',
        ),
        migrations.RemoveField(
            model_name='goodsissueproduct',
            name='warehouse_title',
        ),
        migrations.AddField(
            model_name='goodsissueproduct',
            name='limit_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='issued_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='receipted_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='goodsissue',
            name='goods_issue_type',
            field=models.SmallIntegerField(choices=[(0, 'For Inventory Adjustment'), (1, 'Liquidation'), (2, 'For Production Order')], default=0, help_text="choices= ((0, 'For Inventory Adjustment'), (1, 'Liquidation'), (2, 'For Production Order'))"),
        ),
        migrations.AlterField(
            model_name='goodsissue',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='goodsissueproduct',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentitem',
            name='book_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentitem',
            name='count',
            field=models.FloatField(default=0),
        ),
    ]
