# Generated by Django 4.2.8 on 2024-09-11 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_bom_for_outsourcing_alter_bommaterialcomponent_uom_and_more'),
        ('inventory', '0041_alter_goodsissueproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsissue',
            name='production_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_issue_po', to='production.productionorder'),
        ),
        migrations.AddField(
            model_name='goodsissueproduct',
            name='production_order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_item_goods_issue', to='production.productionordertask'),
        ),
    ]
