# Generated by Django 4.2.8 on 2024-09-13 10:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_bom_for_outsourcing_alter_bommaterialcomponent_uom_and_more'),
        ('inventory', '0042_goodsissue_production_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceiptProductionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Goods Receipt Production Report',
                'verbose_name_plural': 'Goods Receipt Production Reports',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='inventoryadjustmentitem',
            name='gr_completed_quantity',
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='gr_products_data',
            field=models.JSONField(default=list, help_text='data JSON of gr products, records in GoodsReceiptProduct'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='production_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_production_order', to='production.productionorder', verbose_name='production order'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='production_order_data',
            field=models.JSONField(default=dict, help_text='read data production_order, use for get list or detail'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='production_reports_data',
            field=models.JSONField(default=list, help_text='data json of production report, records in GoodsReceiptProductionReport'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_requests_data',
            field=models.JSONField(default=list, help_text='data json of purchase request, records in GoodsReceiptPurchaseRequest'),
        ),
        migrations.AddField(
            model_name='goodsreceiptproduct',
            name='gr_warehouse_data',
            field=models.JSONField(default=list, help_text='data JSON of gr warehouse, records in GoodsReceiptWarehouse'),
        ),
        migrations.AddField(
            model_name='goodsreceiptproduct',
            name='pr_products_data',
            field=models.JSONField(default=list, help_text='data JSON of pr products, records in GoodsReceiptRequestProduct'),
        ),
        migrations.AddField(
            model_name='goodsreceiptproduct',
            name='product_data',
            field=models.JSONField(default=dict, help_text='data JSON of product'),
        ),
        migrations.AddField(
            model_name='goodsreceiptproduct',
            name='product_quantity_order_actual',
            field=models.FloatField(default=0, help_text='quantity order'),
        ),
        migrations.AddField(
            model_name='goodsreceiptproduct',
            name='production_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_product_production_order', to='production.productionorder', verbose_name='production order'),
        ),
        migrations.AddField(
            model_name='goodsreceiptproduct',
            name='tax_data',
            field=models.JSONField(default=dict, help_text='data JSON of tax'),
        ),
        migrations.AddField(
            model_name='goodsreceiptproduct',
            name='uom_data',
            field=models.JSONField(default=dict, help_text='data JSON of uom'),
        ),
        migrations.AddField(
            model_name='goodsreceiptproduct',
            name='warehouse_data',
            field=models.JSONField(default=dict, help_text='data JSON of warehouse'),
        ),
        migrations.AddField(
            model_name='goodsreceiptrequestproduct',
            name='gr_warehouse_data',
            field=models.JSONField(default=list, help_text='data JSON of gr warehouse, records in GoodsReceiptWarehouse'),
        ),
    ]
