# Generated by Django 4.2.8 on 2024-09-13 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_goodsreceiptproductionreport_and_more'),
        ('production', '0006_productionreport_productionorder_gr_remain_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptrequestproduct',
            name='production_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gr_request_product_production_report', to='production.productionreport', verbose_name='production report'),
        ),
        migrations.AddField(
            model_name='goodsreceiptrequestproduct',
            name='production_report_data',
            field=models.JSONField(default=dict, help_text='data JSON of production report'),
        ),
        migrations.AddField(
            model_name='goodsreceiptrequestproduct',
            name='purchase_request_data',
            field=models.JSONField(default=dict, help_text='data JSON of purchase request'),
        ),
        migrations.AddField(
            model_name='goodsreceiptrequestproduct',
            name='quantity_order',
            field=models.FloatField(default=0, help_text='quantity purchase order'),
        ),
        migrations.AddField(
            model_name='goodsreceiptrequestproduct',
            name='uom_data',
            field=models.JSONField(default=dict, help_text='data JSON of uom request'),
        ),
        migrations.AddField(
            model_name='goodsreceiptwarehouse',
            name='lot_data',
            field=models.JSONField(default=list, help_text='data JSON of lots, records in GoodsReceiptLot'),
        ),
        migrations.AddField(
            model_name='goodsreceiptwarehouse',
            name='serial_data',
            field=models.JSONField(default=list, help_text='data JSON of serials, records in GoodsReceiptSerial'),
        ),
        migrations.AddField(
            model_name='goodsreceiptwarehouse',
            name='uom_data',
            field=models.JSONField(default=dict, help_text='data JSON of uom'),
        ),
        migrations.AddField(
            model_name='goodsreceiptwarehouse',
            name='warehouse_data',
            field=models.JSONField(default=dict, help_text='data JSON of warehouse'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptproduct',
            name='quantity_import',
            field=models.FloatField(default=0, help_text='quantity goods receipt this time'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptrequestproduct',
            name='quantity_import',
            field=models.FloatField(default=0, help_text='quantity goods receipt'),
        ),
        migrations.AddField(
            model_name='goodsreceiptproductionreport',
            name='goods_receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_production_report_receipt', to='inventory.goodsreceipt', verbose_name='goods receipt'),
        ),
        migrations.AddField(
            model_name='goodsreceiptproductionreport',
            name='production_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_production_report_report', to='production.productionreport', verbose_name='production report'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='production_reports',
            field=models.ManyToManyField(blank=True, related_name='goods_receipt_map_production_report', through='inventory.GoodsReceiptProductionReport', to='production.productionreport'),
        ),
    ]
