# Generated by Django 4.2.8 on 2024-09-14 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0037_account_is_competitor_account_and_more'),
        ('inventory', '0044_goodsreceiptrequestproduct_production_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptrequestproduct',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gr_request_product_uom', to='saledata.unitofmeasure', verbose_name='unit of measure'),
        ),
        migrations.AlterField(
            model_name='goodsreceiptrequestproduct',
            name='uom_data',
            field=models.JSONField(default=dict, help_text='data JSON of uom'),
        ),
    ]
