# Generated by Django 4.2.8 on 2024-09-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_goodsreceiptrequestproduct_uom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsissueproduct',
            old_name='limit_quantity',
            new_name='before_quantity',
        ),
        migrations.RenameField(
            model_name='goodsissueproduct',
            old_name='quantity',
            new_name='issued_quantity',
        ),
        migrations.RemoveField(
            model_name='goodsissueproduct',
            name='product_warehouse',
        ),
        migrations.AddField(
            model_name='goodsissueproduct',
            name='product_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='goodsissueproduct',
            name='remain_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsissueproduct',
            name='uom_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='goodsissueproduct',
            name='warehouse_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='product_mapped_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='uom_mapped_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentitem',
            name='warehouse_mapped_data',
            field=models.JSONField(default=dict),
        ),
    ]
