# Generated by Django 4.2.8 on 2024-09-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0046_rename_limit_quantity_goodsissueproduct_before_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='total_pretax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='total_revenue_before_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='total_tax',
            field=models.FloatField(default=0),
        ),
    ]
