# Generated by Django 4.2.8 on 2024-09-25 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_productionreport_production_report_type_and_more'),
        ('inventory', '0047_goodsreceipt_total_goodsreceipt_total_pretax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='production_report_type',
            field=models.SmallIntegerField(default=0, help_text="choices= ((0, 'For production order'), (1, 'For work order'))"),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='work_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_work_order', to='production.workorder', verbose_name='work order'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='work_order_data',
            field=models.JSONField(default=dict, help_text='read data work_order, use for get list or detail'),
        ),
        migrations.AddField(
            model_name='goodsreceiptproduct',
            name='work_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_product_work_order', to='production.workorder', verbose_name='work order'),
        ),
    ]
