# Generated by Django 4.2.8 on 2024-09-30 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_workorder_done_issue_workordertask_issued_quantity'),
        ('inventory', '0048_goodsreceipt_production_report_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsissue',
            name='work_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_issue_wo', to='production.workorder'),
        ),
        migrations.AddField(
            model_name='goodsissueproduct',
            name='work_order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wo_item_goods_issue', to='production.workordertask'),
        ),
        migrations.AlterField(
            model_name='goodsissue',
            name='goods_issue_type',
            field=models.SmallIntegerField(choices=[(0, 'For Inventory Adjustment'), (1, 'Liquidation'), (2, 'For Production')], default=0, help_text="choices= ((0, 'For Inventory Adjustment'), (1, 'Liquidation'), (2, 'For Production'))"),
        ),
    ]
