# Generated by Django 4.2.8 on 2024-10-01 17:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0009_alter_files_file_type_alter_publicfiles_file_type'),
        ('inventory', '0049_goodsissue_work_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsIssueAttachmentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('attachment', models.OneToOneField(help_text='Many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_files', to='attachments.files', verbose_name='Attachment files')),
                ('goods_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_issue_attachments', to='inventory.goodsissue')),
            ],
            options={
                'verbose_name': 'Goods issue attachment',
                'verbose_name_plural': 'Goods issue attachments',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
