# Generated by Django 4.2.8 on 2024-11-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_goodsissue_next_association_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryadjustmentitem',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
    ]
