# Generated by Django 4.2.8 on 2024-12-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0055_goodsdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsdetail',
            options={'default_permissions': (), 'ordering': ('-date_created',), 'permissions': (), 'verbose_name': 'Goods Detail', 'verbose_name_plural': 'Goods Detail'},
        ),
    ]
