# Generated by Django 4.2.8 on 2025-01-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0057_goodsrecovery_recoverydelivery_recoveryproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryleasegenerate',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='remark'),
        ),
        migrations.AddField(
            model_name='recoveryproduct',
            name='delivery_data',
            field=models.JSONField(default=list, help_text='data json of product delivery'),
        ),
        migrations.AddField(
            model_name='recoveryproduct',
            name='product_depreciation_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recoveryproduct',
            name='product_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recoveryproduct',
            name='product_quantity_depreciation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recoveryproduct',
            name='product_quantity_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recoveryproduct',
            name='product_subtotal_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recoveryproduct',
            name='product_unit_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recoveryproduct',
            name='quantity_delivered',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recoveryproduct',
            name='quantity_ordered',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recoveryproduct',
            name='quantity_recovered',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recoveryproduct',
            name='quantity_recovery',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recoverywarehouse',
            name='quantity_recovery',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recoverywarehouse',
            name='warehouse_data',
            field=models.JSONField(default=dict, help_text='data json of warehouse'),
        ),
    ]
