# Generated by Django 4.2.8 on 2025-02-26 12:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_email_app_password_and_more'),
        ('saledata', '0056_rename_lease_depreciation_price_product_depreciation_price_and_more'),
        ('tenant', '0001_initial'),
        ('company', '0016_companyconfig_accounting_policies_and_more'),
        ('inventory', '0058_recoveryproduct_product_depreciation_adjustment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recoveryproduct',
            old_name='product_quantity_depreciation',
            new_name='product_depreciation_time',
        ),
        migrations.RemoveField(
            model_name='recoveryproduct',
            name='quantity_delivered',
        ),
        migrations.RemoveField(
            model_name='recoveryproduct',
            name='quantity_ordered',
        ),
        migrations.RemoveField(
            model_name='recoveryproduct',
            name='quantity_recovered',
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='is_no_warehouse',
            field=models.BooleanField(default=False, help_text='flag to know goods receipts to warehouse or not'),
        ),
        migrations.AddField(
            model_name='goodsrecovery',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsrecovery',
            name='total_pretax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsrecovery',
            name='total_revenue_before_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='goodsrecovery',
            name='total_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recoveryproduct',
            name='product_lease_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='recoveryproduct',
            name='product_lease_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='recoveryproduct',
            name='product_quantity_leased',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recoveryproduct',
            name='product_quantity_leased_data',
            field=models.JSONField(default=list, help_text='read data products leased'),
        ),
        migrations.AddField(
            model_name='recoveryproduct',
            name='product_quantity_new',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='RecoveryProductLeased',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('product_data', models.JSONField(default=dict, help_text='data json of product')),
                ('quantity_recovery', models.FloatField(default=0)),
                ('delivery_data', models.JSONField(default=list, help_text='data json of product delivery')),
                ('product_warehouse_data', models.JSONField(default=list, help_text='data json of product warehouses')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_product_leased_product', to='saledata.product', verbose_name='product leased')),
                ('recovery_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_product_leased_recovery_product', to='inventory.recoveryproduct', verbose_name='recovery product')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Recovery Product Leased',
                'verbose_name_plural': 'Recovery Products Leased',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='recoverywarehouse',
            name='recovery_product_leased',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_warehouse_rp_leased', to='inventory.recoveryproductleased', verbose_name='recovery product leased'),
        ),
    ]
