# Generated by Django 4.2.8 on 2025-06-16 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productmodification', '0002_productmodification_created_goods_issue_and_more'),
        ('inventory', '0063_goodsissue_product_modification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='product_modification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_product_modification', to='productmodification.productmodification', verbose_name='product modification'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='product_modification_data',
            field=models.JSONField(default=dict, help_text='read data product_modification, use for get list or detail'),
        ),
        migrations.AddField(
            model_name='goodsreceiptproduct',
            name='product_modification_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipt_product_pm_product', to='productmodification.removedcomponent', verbose_name='pm product'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='goods_receipt_type',
            field=models.SmallIntegerField(default=0, help_text="choices= ((0, 'For purchase order'), (1, 'For inventory adjustment'), (2, 'For production'), (3, 'For product modification'))"),
        ),
    ]
