# Generated by Django 4.2.8 on 2025-10-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0066_goodstransfer_equipment_return_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreturnproductdetail',
            name='is_return',
        ),
    ]
