# Generated by Django 4.2.8 on 2025-10-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0067_remove_goodsreturnproductdetail_is_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptproduct',
            name='product_title',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
