# Generated by Django 4.2.8 on 2025-12-19 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_fixedassetapinvoicepurchaseitem_and_more'),
        ('inventory', '0068_alter_goodsreceiptproduct_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsissue',
            name='fixed_asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_issue_fa', to='asset.fixedasset'),
        ),
        migrations.AddField(
            model_name='goodsissueproduct',
            name='fixed_asset_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fa_item_goods_issue', to='asset.fixedassetinventoryitem'),
        ),
        migrations.AlterField(
            model_name='goodsissue',
            name='goods_issue_type',
            field=models.SmallIntegerField(choices=[(0, 'For Inventory Adjustment'), (1, 'Liquidation'), (2, 'For Production'), (3, 'For Product Modification'), (4, 'For Fixed Asset')], default=0, help_text="choices= ((0, 'For Inventory Adjustment'), (1, 'Liquidation'), (2, 'For Production'), (3, 'For Product Modification'), (4, 'For Fixed Asset'))"),
        ),
    ]
