# Generated by Django 4.2.8 on 2025-10-27 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0008_alter_collabinworkflow_position_choice'),
        ('company', '0023_companyconfig_shift_companyconfig_shift_data_and_more'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('space', '0001_initial'),
        ('process', '0009_processmembers_is_system_and_more'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('is_change', models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents')),
                ('document_root_id', models.UUIDField(help_text='this is id of root document of the changed documents', null=True)),
                ('document_change_order', models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('department_applied_data', models.JSONField(default=list, help_text='[{"id": "uuid", "title": "name", "code": "COD"}, {"id": "uuid", "title": "name", "code": "COD"}]', null=True, verbose_name='Save department data')),
                ('remarks', models.TextField(blank=True)),
                ('attribute_list', models.JSONField(default=list, help_text='[{"name": "attr name", "code": "attr_code", "type": [[0, "number"], [1, "text"], [2, "date"], [3, "boolean"], [4, "formula"]], "source": [[0, "system"], [1, "manual"], [2, "formula"], [3, "import"]], "formula": "str", "mandatory": true, "order": 0}, {"name": "attr name", "code": "attr_code", "type": [[0, "number"], [1, "text"], [2, "date"], [3, "boolean"], [4, "formula"]], "source": [[0, "system"], [1, "manual"], [2, "formula"], [3, "import"]], "formula": "str", "mandatory": true, "order": 1}]', null=True, verbose_name='Save department data')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('current_stage', models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc')),
            ],
            options={
                'verbose_name': 'Payroll template',
                'verbose_name_plural': 'Payroll template',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SalaryTemplateEmployeeGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_applied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_map_salarytemplate', to='hr.group')),
                ('salary_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salarytemplate_map_employee_group', to='payrolltemplate.payrolltemplate')),
            ],
            options={
                'verbose_name': 'Salary template map group',
                'verbose_name_plural': 'Salary template map with employee group',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='payrolltemplate',
            name='department_applied',
            field=models.ManyToManyField(related_name='group_payrolltemplate_department_applied', through='payrolltemplate.SalaryTemplateEmployeeGroup', to='hr.group'),
        ),
        migrations.AddField(
            model_name='payrolltemplate',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='payrolltemplate',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='payrolltemplate',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='payrolltemplate',
            name='next_association',
            field=models.ForeignKey(help_text='next association after check condition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_next_association', to='workflow.association'),
        ),
        migrations.AddField(
            model_name='payrolltemplate',
            name='next_node_collab',
            field=models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='payrolltemplate',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='payrolltemplate',
            name='process_stage_app',
            field=models.ForeignKey(help_text='The process stage app claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.processstageapplication'),
        ),
        migrations.AddField(
            model_name='payrolltemplate',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='payrolltemplate',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='payrolltemplate',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
        migrations.CreateModel(
            name='PayrollAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('column_name', models.CharField(max_length=250, verbose_name='Column name')),
                ('column_code', models.CharField(max_length=250, verbose_name='Column code')),
                ('data_type', models.IntegerField(choices=[(0, 'number'), (1, 'text'), (2, 'date'), (3, 'boolean'), (4, 'formula')], verbose_name='Data type')),
                ('data_source', models.IntegerField(choices=[(0, 'system'), (1, 'manual'), (2, 'formula'), (3, 'import')], verbose_name='Data source')),
                ('data_source_component_data', models.JSONField(blank=True, default=dict, help_text='{"id": "uuid", "component_name": "name", "component_code": "code"}', null=True, verbose_name='Save data_source selected')),
                ('formula', models.CharField(blank=True, max_length=500, null=True, verbose_name='expression (if type = formula)')),
                ('mandatory', models.BooleanField(default=True, verbose_name='Whether input is required')),
                ('order', models.IntegerField(verbose_name='Column position in payroll')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Payroll attribute',
                'verbose_name_plural': 'list Payroll attribute',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AttributeComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Component title')),
                ('component_name', models.CharField(max_length=250, verbose_name='Component name')),
                ('component_code', models.CharField(max_length=250, verbose_name='Component code')),
                ('component_type', models.IntegerField(verbose_name='Component type')),
                ('component_formula', models.CharField(blank=True, max_length=500, null=True, verbose_name='expression (if type = formula)')),
                ('component_mandatory', models.BooleanField(default=True, verbose_name='Component whether input is required')),
                ('is_system', models.BooleanField(default=False, null=True, verbose_name='Component is system')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_attribute_component', to='company.company')),
            ],
            options={
                'verbose_name': 'Payroll attribute component',
                'verbose_name_plural': 'list Payroll attribute component system and user created',
                'ordering': ('component_name',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
