# Generated by Django 4.2.8 on 2025-11-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrolltemplate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributecomponent',
            name='component_code',
            field=models.CharField(max_length=250, unique=True, verbose_name='Component code'),
        ),
        migrations.AlterField(
            model_name='payrollattribute',
            name='column_code',
            field=models.CharField(max_length=250, unique=True, verbose_name='Column code'),
        ),
    ]
