# Generated by Django 4.2.8 on 2024-01-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='mentions',
            field=models.JSONField(default=list),
        ),
    ]
