# Generated by Django 4.2.8 on 2024-01-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comments_mentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='mentions_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='comments',
            name='replies_latest',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='replies_persons',
            field=models.JSONField(default=dict),
        ),
    ]
