# Generated by Django 4.2.8 on 2024-07-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_comments_contents_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
    ]
