# Generated by Django 4.2.8 on 2023-12-26 10:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('company', '0005_remove_company_cost_per_lot_batch_and_more'),
        ('saledata', '0005_product_available_notify_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetToolsConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_tool_company', to='company.company')),
            ],
            options={
                'verbose_name': 'Asset tools config',
                'verbose_name_plural': 'Asset tools config of company',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AssetToolsConfigWarehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_tools_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assettools.assettoolsconfig', verbose_name='WareHouse of product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.warehouse', verbose_name='WareHouse of product')),
            ],
            options={
                'verbose_name': 'Asset tools config map warehouse',
                'verbose_name_plural': 'Asset tools config map warehouse',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AssetToolsConfigEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_tools_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assettools.assettoolsconfig', verbose_name='asset tool config')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='Asset tools map employee')),
            ],
            options={
                'verbose_name': 'Asset tools config map warehouse',
                'verbose_name_plural': 'Asset tools config map warehouse',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='assettoolsconfig',
            name='employee_tools_list_access',
            field=models.ManyToManyField(blank=True, related_name='asset_config_map_employee', through='assettools.AssetToolsConfigEmployee', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='assettoolsconfig',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.producttype', verbose_name='product type of product'),
        ),
        migrations.AddField(
            model_name='assettoolsconfig',
            name='warehouse',
            field=models.ManyToManyField(blank=True, related_name='asset_config_map_warehouse', through='assettools.AssetToolsConfigWarehouse', to='saledata.warehouse'),
        ),
    ]
