# Generated by Django 4.2.8 on 2023-12-28 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_runtime_state'),
        ('attachments', '0004_remove_files_belong_to_publicfiles'),
        ('company', '0006_company_logo'),
        ('tenant', '0001_initial'),
        ('hr', '0002_employee_avatar_img'),
        ('saledata', '0006_productvariantattribute_productvariant'),
        ('space', '0001_initial'),
        ('process', '0001_initial'),
        ('assettools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetToolsProvide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('remark', models.CharField(max_length=500, null=True, verbose_name='descriptions')),
                ('pretax_amount', models.FloatField(null=True, verbose_name='Pretax amount')),
                ('taxes', models.FloatField(null=True, verbose_name='Taxes')),
                ('total_amount', models.FloatField(null=True, verbose_name='Total amount')),
            ],
            options={
                'verbose_name': 'Asset tools provide',
                'verbose_name_plural': 'provide asset, tools of employee',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AssetToolsProvideProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=1)),
                ('product_remark', models.CharField(max_length=500, null=True, verbose_name='descriptions')),
                ('product_data', models.JSONField(default=dict, help_text='[{"id": "", "title": "", "code": "", "remarks": ""}]', verbose_name='Product Data backup')),
                ('uom_data', models.JSONField(default=dict, help_text='{"id": "", "title": "", "code": ""}', verbose_name='Unit of Measure backup')),
                ('quantity', models.FloatField(verbose_name='Quantity need pickup of SaleOrder')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('tax_data', models.JSONField(default=dict, help_text='{"id": "", "title": "", "code": "", "rate": ""}', verbose_name='Tax backup')),
                ('subtotal', models.FloatField(default=0, verbose_name='Subtotal price')),
                ('asset_tools_provide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_provide_map_product', to='assettools.assettoolsprovide', verbose_name='Product of Asset, Tools provide')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_map_asset_provide', to='saledata.product', verbose_name='Product need provide')),
                ('tax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.tax', verbose_name='')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.unitofmeasure', verbose_name='')),
            ],
            options={
                'verbose_name': 'Asset, Tools Provide Product',
                'verbose_name_plural': 'Asset, Tools Provide Product',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AssetToolsProvideAttachmentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('asset_tools_provide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assettools.assettoolsprovide', verbose_name='Attachment file of Asset, Tools provide')),
                ('attachment', models.OneToOneField(help_text='Many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_files', to='attachments.files', verbose_name='Attachment files')),
            ],
            options={
                'verbose_name': 'Asset, Tools provide attachments',
                'verbose_name_plural': 'Asset, Tools provide attachments',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='assettoolsprovide',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='file_of_asset_provide', through='assettools.AssetToolsProvideAttachmentFile', to='attachments.files'),
        ),
        migrations.AddField(
            model_name='assettoolsprovide',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='assettoolsprovide',
            name='current_stage',
            field=models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc'),
        ),
        migrations.AddField(
            model_name='assettoolsprovide',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='assettoolsprovide',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='assettoolsprovide',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='assettoolsprovide',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='assettoolsprovide',
            name='products',
            field=models.ManyToManyField(related_name='products_of_asset_provide', through='assettools.AssetToolsProvideProduct', to='saledata.product'),
        ),
        migrations.AddField(
            model_name='assettoolsprovide',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='assettoolsprovide',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='assettoolsprovide',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
    ]
