# Generated by Django 4.2.8 on 2024-01-12 17:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_avatar_img'),
        ('process', '0001_initial'),
        ('attachments', '0005_publicfiles_relate_app_publicfiles_relate_app_code_and_more'),
        ('company', '0008_company_email_app_password_status_and_more'),
        ('space', '0001_initial'),
        ('saledata', '0008_revenueplanconfig_revenueplanconfigroles_periods'),
        ('tenant', '0001_initial'),
        ('workflow', '0005_collabinworkflow_is_edit_all_zone_and_more'),
        ('assettools', '0003_assettoolsprovide_next_node_collab'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetToolsDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('provide_data', models.JSONField(default=dict, help_text='[{"id": "", "title": "", "code": ""}]', verbose_name='Request provide of employee backup data')),
                ('employee_inherit_data', models.JSONField(default=dict, help_text='[{"id": "", "full_name": "", "code": "", "group": {"id": "", "title": "", "code": ""}}]', verbose_name='Request provide of employee backup data')),
                ('remark', models.CharField(max_length=500, null=True, verbose_name='Descriptions')),
            ],
            options={
                'verbose_name': 'Asset, Tools Delivery',
                'verbose_name_plural': 'Asset, Tools Delivery',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='assettoolsprovide',
            name='complete_delivered',
            field=models.BooleanField(default=False, help_text='request has complete delivered', null=True, verbose_name='Complete Delivered'),
        ),
        migrations.AddField(
            model_name='assettoolsprovideproduct',
            name='delivered',
            field=models.FloatField(default=0, verbose_name='Product is delivered'),
        ),
        migrations.CreateModel(
            name='ProductDeliveredMapProvide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('product_data', models.JSONField(default=dict, help_text='[{"id": "", "title": "", "code": "", "uom": {"id": "", "code": ""}}]', verbose_name='Product data backup')),
                ('warehouse_data', models.JSONField(default=dict, help_text='[{"id": "", "title": "", "code": ""}]', verbose_name='Warehouse info backup')),
                ('employee_inherit_data', models.JSONField(default=dict, help_text='[{"id": "", "full_name": "", "code": "", "group": {"id": "", "title": ""}}]', verbose_name='Employee info backup')),
                ('request_number', models.IntegerField(default=0, verbose_name='Request number')),
                ('delivered_number', models.IntegerField(default=0, verbose_name='Delivered number')),
                ('done', models.IntegerField(default=0, verbose_name='Done')),
                ('date_delivered', models.DateTimeField(default=django.utils.timezone.now, help_text='Date delivered asset, tools')),
                ('product_using', models.IntegerField(default=0, help_text='total product had provided for employee', verbose_name='Product using')),
                ('order', models.IntegerField(default=1, verbose_name='Order')),
                ('is_inventory', models.BooleanField(default=False, verbose_name='Has Inventory')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('current_stage', models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provide_map_delivery', to='assettools.assettoolsdelivery', verbose_name='Product map delivery')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('next_node_collab', models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee')),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_map_asset_tools_delivery', to='saledata.product', verbose_name='Product provide map with request delivery')),
                ('space', models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_provided_at_warehouse', to='saledata.warehouse', verbose_name='Product had provided at warehouse')),
                ('workflow_runtime', models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc')),
            ],
            options={
                'verbose_name': 'Asset, Tools Delivery Map product',
                'verbose_name_plural': 'Asset, Tools Delivery Map product',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AssetToolsDeliveryAttachmentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('asset_tools_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assettools.assettoolsdelivery', verbose_name='Attachment file of Asset, Tools delivery')),
                ('attachment', models.OneToOneField(help_text='Many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_files', to='attachments.files', verbose_name='Attachment files')),
            ],
            options={
                'verbose_name': 'Asset, Tools delivery attachments',
                'verbose_name_plural': 'Asset, Tools delivery attachments',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='assettoolsdelivery',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='file_of_asset_delivery', through='assettools.AssetToolsDeliveryAttachmentFile', to='attachments.files'),
        ),
        migrations.AddField(
            model_name='assettoolsdelivery',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='assettoolsdelivery',
            name='current_stage',
            field=models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc'),
        ),
        migrations.AddField(
            model_name='assettoolsdelivery',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='assettoolsdelivery',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='assettoolsdelivery',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='assettoolsdelivery',
            name='next_node_collab',
            field=models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='assettoolsdelivery',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='assettoolsdelivery',
            name='products',
            field=models.ManyToManyField(related_name='products_asset_tools_delivery', through='assettools.ProductDeliveredMapProvide', to='saledata.product'),
        ),
        migrations.AddField(
            model_name='assettoolsdelivery',
            name='provide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provide_asset_tools_delivery', to='assettools.assettoolsprovide', verbose_name='request provide of employee'),
        ),
        migrations.AddField(
            model_name='assettoolsdelivery',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='assettoolsdelivery',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='assettoolsdelivery',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
    ]
