# Generated by Django 4.2.8 on 2024-01-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_avatar_img'),
        ('assettools', '0004_assettoolsdelivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdeliveredmapprovide',
            name='product_using',
        ),
        migrations.AddField(
            model_name='assettoolsdelivery',
            name='provide_inheritor',
            field=models.ForeignKey(help_text='Provide inheritor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inheritor', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='assettoolsdelivery',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descriptions'),
        ),
        migrations.AlterField(
            model_name='assettoolsprovide',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descriptions'),
        ),
        migrations.AlterField(
            model_name='assettoolsprovideproduct',
            name='quantity',
            field=models.FloatField(verbose_name='Quantity of user request'),
        ),
    ]
