# Generated by Django 4.2.8 on 2024-01-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assettools', '0005_remove_productdeliveredmapprovide_product_using_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettoolsprovideproduct',
            name='product_remark',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='descriptions'),
        ),
    ]
