# Generated by Django 4.2.8 on 2024-01-26 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assettools', '0006_alter_assettoolsprovideproduct_product_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettoolsconfigemployee',
            name='asset_tools_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_config_employee_map_asset_config', to='assettools.assettoolsconfig', verbose_name='asset tool config'),
        ),
    ]
