# Generated by Django 4.2.8 on 2024-01-30 14:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_collabinworkflow_is_edit_all_zone_and_more'),
        ('tenant', '0001_initial'),
        ('process', '0001_initial'),
        ('space', '0001_initial'),
        ('company', '0008_company_email_app_password_status_and_more'),
        ('hr', '0002_employee_avatar_img'),
        ('saledata', '0012_warehouse_is_dropship_alter_warehouse_full_address'),
        ('attachments', '0005_publicfiles_relate_app_publicfiles_relate_app_code_and_more'),
        ('assettools', '0007_alter_assettoolsconfigemployee_asset_tools_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetToolsReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('employee_inherit_data', models.JSONField(default=dict, help_text='[{"id": "", "full_name": "", "code": "", "group": {"id": "", "title": "", "code": ""}}]', verbose_name='Employee inherit backup data')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descriptions')),
                ('return_info_list', models.JSONField(default=dict, help_text='[{"product": {"id": "", "title": "", "code": ""}, "return_number": 0, "reason": "error message"}]', verbose_name='Log info when return asset')),
                ('date_return', models.DateTimeField(default=django.utils.timezone.now, help_text='Date Return asset, tools')),
            ],
            options={
                'verbose_name': 'Asset return',
                'verbose_name_plural': 'Assets return',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AssetToolsReturnMapProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('product_data', models.JSONField(default=dict, help_text='[{"id": "", "title": "", "code": "", "uom": {"id": "", "code": ""}}]', verbose_name='Product data backup')),
                ('warehouse_sp_data', models.JSONField(default=dict, help_text='[{"id": "", "title": "", "code": ""}]', verbose_name='warehouse info backup')),
                ('employee_inherit_data', models.JSONField(default=dict, help_text='[{"id": "", "full_name": "", "code": ""}]', verbose_name='Employee info backup')),
                ('return_number', models.IntegerField(default=0, verbose_name='Return number')),
                ('order', models.IntegerField(default=1, verbose_name='Order')),
                ('asset_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_return_map_product', to='assettools.assettoolsreturn', verbose_name='Asset return map product')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('current_stage', models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('next_node_collab', models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee')),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_map_asset_return', to='saledata.product', verbose_name='Product map asset return')),
                ('space', models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('warehouse_stored_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stored_product', to='saledata.warehouse', verbose_name='Warehouse stored product')),
                ('workflow_runtime', models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc')),
            ],
            options={
                'verbose_name': 'Asset, Tools Return Map product',
                'verbose_name_plural': 'Asset, Tools Return Map product',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AssetToolsReturnAttachmentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('asset_tools_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assettools.assettoolsreturn', verbose_name='Attachment file of Asset, Tools return')),
                ('attachment', models.OneToOneField(help_text='Many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_files', to='attachments.files', verbose_name='Attachment files')),
            ],
            options={
                'verbose_name': 'Asset, Tools return attachments',
                'verbose_name_plural': 'Asset, Tools return attachments',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='assettoolsreturn',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='file_of_asset_return', through='assettools.AssetToolsReturnAttachmentFile', to='attachments.files'),
        ),
        migrations.AddField(
            model_name='assettoolsreturn',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='assettoolsreturn',
            name='current_stage',
            field=models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc'),
        ),
        migrations.AddField(
            model_name='assettoolsreturn',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='assettoolsreturn',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='assettoolsreturn',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='assettoolsreturn',
            name='next_node_collab',
            field=models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='assettoolsreturn',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='assettoolsreturn',
            name='products',
            field=models.ManyToManyField(related_name='products_asset_return', through='assettools.AssetToolsReturnMapProduct', to='saledata.product'),
        ),
        migrations.AddField(
            model_name='assettoolsreturn',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='assettoolsreturn',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='assettoolsreturn',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
    ]
