# Generated by Django 4.2.8 on 2024-02-27 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assettools', '0009_assettoolsprovideproduct_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettoolsconfigwarehouse',
            name='asset_tools_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_config_warehouse_map_asset_config', to='assettools.assettoolsconfig', verbose_name='WareHouse of product'),
        ),
    ]
