# Generated by Django 4.2.8 on 2025-03-27 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0064_remove_account_parent_account_and_more'),
        ('assettools', '0014_assettoolsdelivery_process_stage_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettoolsprovideproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_map_asset_provide', to='saledata.product', verbose_name='Product need provide'),
        ),
    ]
