# Generated by Django 4.2.8 on 2025-04-10 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_instrumenttool_allocated_quantity'),
        ('assettools', '0015_alter_assettoolsprovideproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assettoolsconfigemployee',
            name='asset_tools_config',
        ),
        migrations.RemoveField(
            model_name='assettoolsconfigemployee',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='assettoolsconfigwarehouse',
            name='asset_tools_config',
        ),
        migrations.RemoveField(
            model_name='assettoolsconfigwarehouse',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='assettoolsdelivery',
            name='products',
        ),
        migrations.RemoveField(
            model_name='assettoolsprovide',
            name='products',
        ),
        migrations.RemoveField(
            model_name='assettoolsprovideproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='assettoolsprovideproduct',
            name='uom_data',
        ),
        migrations.RemoveField(
            model_name='assettoolsreturn',
            name='products',
        ),
        migrations.RemoveField(
            model_name='assettoolsreturnmapproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='assettoolsreturnmapproduct',
            name='warehouse_sp_data',
        ),
        migrations.RemoveField(
            model_name='assettoolsreturnmapproduct',
            name='warehouse_stored_product',
        ),
        migrations.RemoveField(
            model_name='productdeliveredmapprovide',
            name='is_inventory',
        ),
        migrations.RemoveField(
            model_name='productdeliveredmapprovide',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productdeliveredmapprovide',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='productdeliveredmapprovide',
            name='warehouse_data',
        ),
        migrations.AddField(
            model_name='assettoolsdelivery',
            name='prod_in_tools',
            field=models.ManyToManyField(related_name='prod_asset_tools_delivery', through='assettools.ProductDeliveredMapProvide', to='asset.instrumenttool'),
        ),
        migrations.AddField(
            model_name='assettoolsprovide',
            name='prod_in_tools',
            field=models.ManyToManyField(related_name='products_of_asset_provide', through='assettools.AssetToolsProvideProduct', to='asset.instrumenttool'),
        ),
        migrations.AddField(
            model_name='assettoolsprovideproduct',
            name='is_returned',
            field=models.FloatField(default=0, verbose_name='Product is returned'),
        ),
        migrations.AddField(
            model_name='assettoolsprovideproduct',
            name='prod_in_tools',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_map_asset_provide', to='asset.instrumenttool', verbose_name='Product need provide'),
        ),
        migrations.AddField(
            model_name='assettoolsreturn',
            name='prod_in_tools',
            field=models.ManyToManyField(related_name='prod_in_tools_asset_return', through='assettools.AssetToolsReturnMapProduct', to='asset.instrumenttool'),
        ),
        migrations.AddField(
            model_name='assettoolsreturnmapproduct',
            name='prod_in_tools',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_map_asset_return', to='asset.instrumenttool', verbose_name='Product map asset return'),
        ),
        migrations.AddField(
            model_name='assettoolsreturnmapproduct',
            name='product_remark',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Product title buy new'),
        ),
        migrations.AddField(
            model_name='productdeliveredmapprovide',
            name='prod_buy_new',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Title of Product buy new'),
        ),
        migrations.AddField(
            model_name='productdeliveredmapprovide',
            name='prod_in_tools',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_map_asset_tools_delivery', to='asset.instrumenttool', verbose_name='Product provide map with request delivery'),
        ),
        migrations.AddField(
            model_name='productdeliveredmapprovide',
            name='uom',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Unit of Measure'),
        ),
        migrations.AlterField(
            model_name='assettoolsprovideproduct',
            name='uom',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.DeleteModel(
            name='AssetToolsConfig',
        ),
        migrations.DeleteModel(
            name='AssetToolsConfigEmployee',
        ),
        migrations.DeleteModel(
            name='AssetToolsConfigWarehouse',
        ),
    ]
