# Generated by Django 4.2.8 on 2025-10-30 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_instrumenttool_quantity_leased'),
        ('assettools', '0016_remove_assettoolsconfigemployee_asset_tools_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettoolsprovideproduct',
            name='prod_in_fixed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_fixed_map_asset_provide', to='asset.fixedasset', verbose_name='Product need provide'),
        ),
    ]
