# Generated by Django 4.2.8 on 2025-11-14 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_instrumenttool_quantity_leased'),
        ('assettools', '0017_assettoolsprovideproduct_prod_in_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettoolsreturnmapproduct',
            name='prod_in_fixed',
            field=models.JSONField(default=dict, help_text='[{"id": "", "title": "", "code": ""}]', null=True, verbose_name='Fixed asset map with return request'),
        ),
        migrations.AddField(
            model_name='productdeliveredmapprovide',
            name='prod_in_fixed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_asset_map_delivery', to='asset.fixedasset', verbose_name='Product fixed map with request delivery'),
        ),
    ]
