# Generated by Django 4.1.3 on 2023-05-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdeliverysub',
            name='date_done',
            field=models.DateTimeField(help_text='The record done at value', null=True),
        ),
        migrations.AlterField(
            model_name='orderpicking',
            name='delivery_option',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Full'), (1, 'Partial')], default=0, help_text='Delivery option when change in this records', verbose_name='Delivery Option'),
        ),
        migrations.AlterField(
            model_name='orderpicking',
            name='picked_quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantity was picked'),
        ),
        migrations.AlterField(
            model_name='orderpicking',
            name='picked_quantity_before',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantity was picked before'),
        ),
        migrations.AlterField(
            model_name='orderpicking',
            name='pickup_quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Quantity need pickup of SaleOrder'),
        ),
        migrations.AlterField(
            model_name='orderpicking',
            name='remaining_quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantity need pick'),
        ),
        migrations.AlterField(
            model_name='orderpicking',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ready'), (1, 'Done')], default=0),
        ),
    ]
