# Generated by Django 4.1.3 on 2023-11-11 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0001_initial'),
        ('company', '0002_initial'),
        ('delivery', '0001_initial'),
        ('tenant', '0001_initial'),
        ('space', '0001_initial'),
        ('workflow', '0001_initial'),
        ('hr', '0001_initial'),
        ('saledata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpickingsub',
            name='current_stage',
            field=models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc'),
        ),
        migrations.AddField(
            model_name='orderpickingsub',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderpickingsub',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderpickingsub',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderpickingsub',
            name='order_picking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.orderpicking', verbose_name='Order Product of Picking'),
        ),
        migrations.AddField(
            model_name='orderpickingsub',
            name='previous_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.orderpickingsub', verbose_name='Previous Picking'),
        ),
        migrations.AddField(
            model_name='orderpickingsub',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='orderpickingsub',
            name='products',
            field=models.ManyToManyField(related_name='products_of_order_picking', through='delivery.OrderPickingProduct', to='saledata.product'),
        ),
        migrations.AddField(
            model_name='orderpickingsub',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='orderpickingsub',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='orderpickingsub',
            name='ware_house',
            field=models.ForeignKey(help_text='Auto select first ware house in list', null=True, on_delete=django.db.models.deletion.SET_NULL, to='saledata.warehouse', verbose_name='Ware-House selected for picking'),
        ),
        migrations.AddField(
            model_name='orderpickingsub',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
        migrations.AddField(
            model_name='orderpickingproduct',
            name='picking_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picking_product_picking_sub', to='delivery.orderpickingsub', verbose_name='Order Picking Sub of Product'),
        ),
        migrations.AddField(
            model_name='orderpickingproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.product', verbose_name='Product need Picking'),
        ),
        migrations.AddField(
            model_name='orderpickingproduct',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.unitofmeasure', verbose_name=''),
        ),
        migrations.AddField(
            model_name='orderpicking',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='orderpicking',
            name='current_stage',
            field=models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc'),
        ),
        migrations.AddField(
            model_name='orderpicking',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderpicking',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderpicking',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderpicking',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
    ]
