# Generated by Django 4.1.3 on 2023-11-11 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0001_initial'),
        ('company', '0002_initial'),
        ('attachments', '0002_initial'),
        ('tenant', '0001_initial'),
        ('space', '0001_initial'),
        ('workflow', '0001_initial'),
        ('hr', '0001_initial'),
        ('saledata', '0001_initial'),
        ('saleorder', '0001_initial'),
        ('delivery', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpicking',
            name='sale_order',
            field=models.OneToOneField(help_text='The Sale Order had one/many Order Picking', on_delete=django.db.models.deletion.CASCADE, related_name='picking_of_sale_order', to='saleorder.saleorder', verbose_name='Order Picking of Sale Order'),
        ),
        migrations.AddField(
            model_name='orderpicking',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='orderpicking',
            name='sub',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.orderpickingsub', verbose_name='Only one sub in the current'),
        ),
        migrations.AddField(
            model_name='orderpicking',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='orderpicking',
            name='ware_house',
            field=models.ForeignKey(help_text='Auto select first ware house in list', null=True, on_delete=django.db.models.deletion.SET_NULL, to='saledata.warehouse', verbose_name='Ware-House selected for picking'),
        ),
        migrations.AddField(
            model_name='orderpicking',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
        migrations.AddField(
            model_name='orderdeliverysub',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='orderdeliverysub',
            name='current_stage',
            field=models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc'),
        ),
        migrations.AddField(
            model_name='orderdeliverysub',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderdeliverysub',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderdeliverysub',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderdeliverysub',
            name='order_delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.orderdelivery', verbose_name='Order Delivery'),
        ),
        migrations.AddField(
            model_name='orderdeliverysub',
            name='previous_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.orderdeliverysub', verbose_name='Previous Delivery'),
        ),
        migrations.AddField(
            model_name='orderdeliverysub',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='orderdeliverysub',
            name='products',
            field=models.ManyToManyField(related_name='products_of_order_delivery', through='delivery.OrderDeliveryProduct', to='saledata.product'),
        ),
        migrations.AddField(
            model_name='orderdeliverysub',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='orderdeliverysub',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='orderdeliverysub',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
        migrations.AddField(
            model_name='orderdeliveryserial',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='orderdeliveryserial',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_serial_delivery', to='delivery.orderdelivery', verbose_name='delivery'),
        ),
        migrations.AddField(
            model_name='orderdeliveryserial',
            name='delivery_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_serial_delivery_product', to='delivery.orderdeliveryproduct', verbose_name='delivery product'),
        ),
        migrations.AddField(
            model_name='orderdeliveryserial',
            name='delivery_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_serial_delivery_sub', to='delivery.orderdeliverysub', verbose_name='delivery sub'),
        ),
        migrations.AddField(
            model_name='orderdeliveryserial',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderdeliveryserial',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderdeliveryserial',
            name='product_warehouse_serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_serial_product_warehouse_serial', to='saledata.productwarehouseserial', verbose_name='product warehouse serial'),
        ),
        migrations.AddField(
            model_name='orderdeliveryserial',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='delivery_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_product_delivery_sub', to='delivery.orderdeliverysub', verbose_name='Order Delivery of Product'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.product', verbose_name='Product need Picking'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.unitofmeasure', verbose_name=''),
        ),
        migrations.AddField(
            model_name='orderdeliverylot',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='orderdeliverylot',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_lot_delivery', to='delivery.orderdelivery', verbose_name='delivery'),
        ),
        migrations.AddField(
            model_name='orderdeliverylot',
            name='delivery_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_lot_delivery_product', to='delivery.orderdeliveryproduct', verbose_name='delivery product'),
        ),
        migrations.AddField(
            model_name='orderdeliverylot',
            name='delivery_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_lot_delivery_sub', to='delivery.orderdeliverysub', verbose_name='delivery sub'),
        ),
        migrations.AddField(
            model_name='orderdeliverylot',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderdeliverylot',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderdeliverylot',
            name='product_warehouse_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_lot_product_warehouse_lot', to='saledata.productwarehouselot', verbose_name='product warehouse lot'),
        ),
        migrations.AddField(
            model_name='orderdeliverylot',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='orderdeliveryattachment',
            name='delivery_sub',
            field=models.ForeignKey(help_text='foreigner key to order delivery sub', on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery_attachment', to='delivery.orderdeliverysub', verbose_name='delivery attachment file'),
        ),
        migrations.AddField(
            model_name='orderdeliveryattachment',
            name='files',
            field=models.OneToOneField(help_text='Delivery sub had one/many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery_attachment_files', to='attachments.files', verbose_name='Order delivery attachment files'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery_contact', to='saledata.contact', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='current_stage',
            field=models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='customer',
            field=models.ForeignKey(help_text='sale data Accounts have type customer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery_customer', to='saledata.account', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='sale_order',
            field=models.OneToOneField(help_text='The Sale Order had one/many Order Picking', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_of_sale_order', to='saleorder.saleorder', verbose_name='Order Picking of Sale Order'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='sub',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.orderdeliverysub', verbose_name='Only one sub in the current'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
        migrations.AddField(
            model_name='deliveryconfig',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_delivery_config_detail', to='company.company'),
        ),
        migrations.AddField(
            model_name='deliveryconfig',
            name='lead_delivery',
            field=models.ForeignKey(default=None, help_text='Picking leadership', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_config_lead_delivery', to='hr.employee', verbose_name='lead_delivery'),
        ),
        migrations.AddField(
            model_name='deliveryconfig',
            name='lead_picking',
            field=models.ForeignKey(default=None, help_text='Picking leadership', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_config_lead_picking', to='hr.employee', verbose_name='leader_picking'),
        ),
    ]
