# Generated by Django 4.1.3 on 2023-06-05 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('delivery', '0002_alter_orderdeliverysub_date_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='orderdeliverysub',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='orderpicking',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='orderpickingsub',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
    ]
