# Generated by Django 4.1.3 on 2023-06-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_orderdelivery_employee_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='delivery_data',
            field=models.JSONField(default=dict, help_text='{"warehouse_id": "stock number"}', null=True, verbose_name='data about product, warehouse, stock'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='picked_quantity',
            field=models.SmallIntegerField(default=0, verbose_name='Quantity was picked'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='state',
            field=models.SmallIntegerField(choices=[(0, 'Wait'), (1, 'Partial'), (2, 'Full'), (3, 'Done')], default=0),
        ),
        migrations.AlterField(
            model_name='orderdeliveryproduct',
            name='ready_quantity',
            field=models.SmallIntegerField(default=0, verbose_name='Quantity already for delivery'),
        ),
        migrations.AlterField(
            model_name='orderdeliverysub',
            name='delivery_data',
            field=models.JSONField(default=dict, help_text='{"{ID Product}": {"delivery_quantity": "(Total delivery quantity need delivery)", "delivered_quantity_before": "(Total delivered quantity before)", "remaining_quantity": "(Quantity need delivery in this record)", "ready_quantity": "(Delivery quantity was delivered in this record)"}}', null=True, verbose_name='Delivery Info'),
        ),
    ]
