# Generated by Django 4.2.8 on 2023-12-21 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliveryconfig_code_deliveryconfig_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdeliveryattachment',
            options={'default_permissions': (), 'ordering': ('-date_created',), 'permissions': (), 'verbose_name': 'Order Delivery Attachment', 'verbose_name_plural': 'Order Delivery Attachment'},
        ),
        migrations.RemoveField(
            model_name='orderdeliveryattachment',
            name='media_file',
        ),
        migrations.AddField(
            model_name='orderdeliveryattachment',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value'),
        ),
    ]
