# Generated by Django 4.2.8 on 2024-02-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_orderdelivery_next_node_collab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliverylot',
            name='returned_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='returned_quantity_default',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderdeliveryserial',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
