# Generated by Django 4.1.3 on 2023-06-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_orderpicking_sub_list_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdeliveryproduct',
            options={'default_permissions': (), 'ordering': ('order',), 'permissions': (), 'verbose_name': 'Delivery Product', 'verbose_name_plural': 'Delivery Product'},
        ),
        migrations.AlterModelOptions(
            name='orderpickingproduct',
            options={'default_permissions': (), 'ordering': ('order',), 'permissions': (), 'verbose_name': 'Product of Order Picking', 'verbose_name_plural': 'Product of Order Picking'},
        ),
        migrations.RemoveField(
            model_name='orderdelivery',
            name='sub_list',
        ),
        migrations.RemoveField(
            model_name='orderpicking',
            name='sub_list',
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='is_promotion',
            field=models.BooleanField(default=False, help_text='flag to know this product is for promotion (discount, gift,...)'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='product_subtotal_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='product_tax_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='product_unit_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderpickingproduct',
            name='is_promotion',
            field=models.BooleanField(default=False, help_text='flag to know this product is for promotion (discount, gift,...)'),
        ),
        migrations.AddField(
            model_name='orderpickingproduct',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderpickingproduct',
            name='product_subtotal_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderpickingproduct',
            name='product_tax_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderpickingproduct',
            name='product_unit_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='delivery_data',
            field=models.JSONField(default=list, help_text='{"{ID Product}": {"delivery_quantity": "(Total delivery quantity need delivery)", "delivered_quantity_before": "(Total delivered quantity before)", "remaining_quantity": "(Quantity need delivery in this record)", "ready_quantity": "(Delivery quantity was delivered in this record)"}}', verbose_name='Delivery Info'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryproduct',
            name='delivery_data',
            field=models.JSONField(default=list, help_text='[{"warehouse_id": "stock number"}]', null=True, verbose_name='data about product, warehouse, stock'),
        ),
        migrations.AlterField(
            model_name='orderdeliverysub',
            name='delivery_data',
            field=models.JSONField(default=list, help_text='{"{ID Product}": {"delivery_quantity": "(Total delivery quantity need delivery)", "delivered_quantity_before": "(Total delivered quantity before)", "remaining_quantity": "(Quantity need delivery in this record)", "ready_quantity": "(Delivery quantity was delivered in this record)"}}', null=True, verbose_name='Delivery Info'),
        ),
    ]
