# Generated by Django 4.1.3 on 2023-07-14 14:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
        ('delivery', '0008_alter_orderdeliveryproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliverysub',
            name='attachments',
            field=models.JSONField(default=list, help_text='["uuid4", "uuid4"]', null=True, verbose_name='order delivery attachment'),
        ),
        migrations.AddField(
            model_name='orderdeliverysub',
            name='config_at_that_point',
            field=models.JSONField(default=dict, help_text='{"is_picking": true, "is_partial_ship": false}', verbose_name='this is config was created at that time'),
        ),
        migrations.AddField(
            model_name='orderpickingsub',
            name='config_at_that_point',
            field=models.JSONField(default=dict, help_text='{"is_picking": true, "is_partial_ship": false}', verbose_name='this is config was created at that time'),
        ),
        migrations.CreateModel(
            name='OrderDeliveryAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_file', models.UUIDField(unique=True)),
                ('delivery_sub', models.ForeignKey(help_text='foreigner key to order delivery sub', on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery_attachment', to='delivery.orderdeliverysub', verbose_name='delivery attachment file')),
                ('files', models.OneToOneField(help_text='Delivery sub had one/many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery_attachment_files', to='attachments.files', verbose_name='Order delivery attachment files')),
            ],
            options={
                'verbose_name': 'Order Delivery Attachment',
                'verbose_name_plural': 'Order Delivery Attachment',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
