# Generated by Django 4.1.3 on 2023-08-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_orderdeliverysub_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliverysub',
            name='delivery_logistic',
            field=models.JSONField(default=list, help_text='{"shipping_address": "lorem ipsum dolor sit amet", "billing_address": "consectetur adipiscing elit."}', null=True, verbose_name='delivery shipping and billing address'),
        ),
    ]
