# Generated by Django 4.2.8 on 2024-08-01 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0008_alter_files_date_modified_alter_folder_date_modified_and_more'),
        ('delivery', '0010_alter_orderdeliveryproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdeliveryattachment',
            options={'default_permissions': (), 'ordering': ('-date_created',), 'permissions': (), 'verbose_name': 'Delivery attachments', 'verbose_name_plural': 'Delivery attachments'},
        ),
        migrations.RemoveField(
            model_name='orderdeliveryattachment',
            name='files',
        ),
        migrations.AddField(
            model_name='orderdeliveryattachment',
            name='attachment',
            field=models.OneToOneField(default='', help_text='Many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_files', to='attachments.files', verbose_name='Attachment files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdeliveryattachment',
            name='order',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderdeliverysub',
            name='attachment_m2m',
            field=models.ManyToManyField(blank=True, related_name='file_of_delivery', through='delivery.OrderDeliveryAttachment', to='attachments.files'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryattachment',
            name='delivery_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attachment_delivery', to='delivery.orderdeliverysub', verbose_name='delivery attachment file'),
        ),
    ]
