# Generated by Django 4.1.3 on 2023-09-11 17:10

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_runtime_doc_employee_inherit_and_more'),
        ('hr', '0006_alter_employee_code_alter_employee_unique_together'),
        ('process', '0002_salefunction_process_code_process_company_and_more'),
        ('space', '0001_initial'),
        ('delivery', '0011_orderdeliverysub_employee_inherit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryconfig',
            name='lead_delivery',
            field=models.ForeignKey(default=None, help_text='Picking leadership', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_config_lead_delivery', to='hr.employee', verbose_name='lead_delivery'),
        ),
        migrations.AddField(
            model_name='deliveryconfig',
            name='lead_picking',
            field=models.ForeignKey(default=None, help_text='Picking leadership', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_config_lead_picking', to='hr.employee', verbose_name='leader_picking'),
        ),
        migrations.AddField(
            model_name='deliveryconfig',
            name='person_delivery',
            field=models.JSONField(default=dict, null=True, verbose_name='list of employee can pick package'),
        ),
        migrations.AddField(
            model_name='deliveryconfig',
            name='person_picking',
            field=models.JSONField(default=dict, null=True, verbose_name='list of employee can pick package'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='system_remarks',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='system_status',
            field=models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))"),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
        migrations.AddField(
            model_name='orderpicking',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderpicking',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='orderpicking',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='orderpicking',
            name='system_remarks',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='orderpicking',
            name='system_status',
            field=models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))"),
        ),
        migrations.AddField(
            model_name='orderpicking',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
        migrations.AddField(
            model_name='orderpickingsub',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderpickingsub',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='orderpickingsub',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='orderpickingsub',
            name='system_remarks',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='orderpickingsub',
            name='system_status',
            field=models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))"),
        ),
        migrations.AddField(
            model_name='orderpickingsub',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
    ]
