# Generated by Django 4.1.3 on 2023-10-23 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_deliveryconfig_lead_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdeliveryproduct',
            name='delivery_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_product_delivery_sub', to='delivery.orderdeliverysub', verbose_name='Order Delivery of Product'),
        ),
        migrations.AlterField(
            model_name='orderpickingproduct',
            name='picking_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picking_product_picking_sub', to='delivery.orderpickingsub', verbose_name='Order Picking Sub of Product'),
        ),
    ]
