# Generated by Django 4.2.8 on 2024-08-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_orderpickingproduct_picking_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
        migrations.AlterField(
            model_name='orderdeliverysub',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
        migrations.AlterField(
            model_name='orderpicking',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
        migrations.AlterField(
            model_name='orderpickingsub',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
    ]
