# Generated by Django 4.1.3 on 2023-10-25 15:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_remove_company_language'),
        ('saledata', '0055_remove_productwarehouse_available_amount_and_more'),
        ('tenant', '0001_initial'),
        ('hr', '0008_distributionapplication_and_more'),
        ('delivery', '0013_alter_orderdeliveryproduct_delivery_sub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDeliverySerial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_serial_delivery', to='delivery.orderdelivery', verbose_name='delivery')),
                ('delivery_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_serial_delivery_product', to='delivery.orderdeliveryproduct', verbose_name='delivery product')),
                ('delivery_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_serial_delivery_sub', to='delivery.orderdeliverysub', verbose_name='delivery sub')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('product_warehouse_serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_serial_product_warehouse_serial', to='saledata.productwarehouseserial', verbose_name='product warehouse serial')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Order Delivery Serial',
                'verbose_name_plural': 'Order Delivery Serials',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OrderDeliveryLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('quantity_initial', models.FloatField(default=0, help_text='quantity in ProductWarehouseLot at the time create this record')),
                ('quantity_delivery', models.FloatField(default=0)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_lot_delivery', to='delivery.orderdelivery', verbose_name='delivery')),
                ('delivery_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_lot_delivery_product', to='delivery.orderdeliveryproduct', verbose_name='delivery product')),
                ('delivery_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_lot_delivery_sub', to='delivery.orderdeliverysub', verbose_name='delivery sub')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('product_warehouse_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_lot_product_warehouse_lot', to='saledata.productwarehouselot', verbose_name='product warehouse lot')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Order Delivery Lot',
                'verbose_name_plural': 'Order Delivery Lots',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
