# Generated by Django 4.2.8 on 2024-12-18 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseorder', '0001_initial'),
        ('saledata', '0049_documenttype_doc_type_category'),
        ('saleorder', '0027_saleordercost_code_saleordercost_company_and_more'),
        ('delivery', '0015_orderdelivery_process_stage_app_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='lease_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_of_lease_order', to='leaseorder.leaseorder', verbose_name='Order Delivery of Lease Order'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='lease_order_data',
            field=models.JSONField(default=dict, help_text='data json of lease order', verbose_name='Lease Order data'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='offset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_product_offset', to='saledata.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='offset_data',
            field=models.JSONField(default=dict, help_text='data json of offset'),
        ),
        migrations.AddField(
            model_name='orderdeliverysub',
            name='lease_order_data',
            field=models.JSONField(default=dict, help_text='data json of lease order', verbose_name='Lease Order data'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='sale_order',
            field=models.OneToOneField(help_text='The Sale Order had one/many Order Picking', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_of_sale_order', to='saleorder.saleorder', verbose_name='Order Delivery of Sale Order'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='sale_order_data',
            field=models.JSONField(default=dict, help_text='data json of sale order', verbose_name='Sale Order data'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryproduct',
            name='product_data',
            field=models.JSONField(default=dict, help_text='data json of product', verbose_name='Product Data backup'),
        ),
        migrations.AlterField(
            model_name='orderdeliverysub',
            name='sale_order_data',
            field=models.JSONField(default=dict, help_text='data json of sale order', verbose_name='Sale Order data'),
        ),
    ]
