# Generated by Django 4.2.8 on 2024-12-26 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseorder', '0002_leaseorderpaymentstage_date_type_and_more'),
        ('delivery', '0016_orderdelivery_lease_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliveryproductwarehouse',
            name='lease_order',
            field=models.ForeignKey(help_text='main lease order of this delivery or lease order from other project (borrow)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_pw_lease_order', to='leaseorder.leaseorder', verbose_name='lease order'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproductwarehouse',
            name='lease_order_data',
            field=models.JSONField(default=dict, help_text='data json of lease order'),
        ),
    ]
