# Generated by Django 4.2.8 on 2025-01-08 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0051_alter_productwarehouseserial_options'),
        ('delivery', '0018_orderdeliverylot_product_warehouse_lot_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='product_depreciation_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='product_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='product_quantity_depreciation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='product_quantity_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdeliveryproduct',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_product_uom', to='saledata.unitofmeasure', verbose_name='uom'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryproduct',
            name='uom_data',
            field=models.JSONField(default=dict, help_text='data json of uom'),
        ),
    ]
