# Generated by Django 4.2.8 on 2025-01-16 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0053_product_lease_code_product_lease_depreciation_price_and_more'),
        ('delivery', '0019_orderdeliveryproduct_product_depreciation_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='product_depreciation_adjustment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='product_depreciation_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='product_depreciation_method',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='product_depreciation_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='product_depreciation_subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='uom_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_product_uom_time', to='saledata.unitofmeasure', verbose_name='uom time'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='uom_time_data',
            field=models.JSONField(default=dict, help_text='data json of uom time'),
        ),
    ]
