# Generated by Django 4.2.8 on 2025-02-26 12:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_email_app_password_and_more'),
        ('saledata', '0056_rename_lease_depreciation_price_product_depreciation_price_and_more'),
        ('tenant', '0001_initial'),
        ('company', '0016_companyconfig_accounting_policies_and_more'),
        ('delivery', '0020_orderdeliveryproduct_product_depreciation_adjustment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdeliveryproduct',
            old_name='product_quantity_depreciation',
            new_name='product_depreciation_time',
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='company',
            field=models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date modified this record in last'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='product_quantity_leased',
            field=models.FloatField(default=0, help_text='quantity need delivery of leased products'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='product_quantity_leased_data',
            field=models.JSONField(default=list, help_text='read data products leased'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='product_quantity_new',
            field=models.FloatField(default=0, help_text='quantity need delivery of new products'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='quantity_new_remain_recovery',
            field=models.FloatField(default=0, help_text='minus when recovery'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='quantity_remain_recovery',
            field=models.FloatField(default=0, help_text='minus when recovery'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='remaining_quantity_new',
            field=models.FloatField(default=0, help_text='quantity remain of new products'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='OrderDeliveryProductLeased',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('product_data', models.JSONField(default=dict, help_text='data json of product')),
                ('remaining_quantity_leased', models.FloatField(default=0, help_text='quantity remain of leased products')),
                ('picked_quantity', models.FloatField(default=0, help_text='quantity delivery leased products')),
                ('delivery_data', models.JSONField(default=list, help_text='data delivery of leased products')),
                ('quantity_leased_remain_recovery', models.FloatField(default=0, help_text='minus when recovery')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('delivery_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_product_leased_delivery_product', to='delivery.orderdeliveryproduct', verbose_name='delivery product')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_product_leased_product', to='saledata.product', verbose_name='product leased')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Delivery Product Leased',
                'verbose_name_plural': 'Delivery Products Leased',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='orderdeliverylot',
            name='delivery_product_leased',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_lot_delivery_product_leased', to='delivery.orderdeliveryproductleased', verbose_name='delivery product leased'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproductwarehouse',
            name='delivery_product_leased',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_pw_delivery_product_leased', to='delivery.orderdeliveryproductleased', verbose_name='delivery product leased'),
        ),
        migrations.AddField(
            model_name='orderdeliveryserial',
            name='delivery_product_leased',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_serial_delivery_product_leased', to='delivery.orderdeliveryproductleased', verbose_name='delivery product leased'),
        ),
    ]
