# Generated by Django 4.2.8 on 2025-03-13 10:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0059_remove_product_date_first_delivery_and_more'),
        ('tenant', '0001_initial'),
        ('company', '0016_companyconfig_accounting_policies_and_more'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('asset', '0006_alter_fixedasset_status'),
        ('delivery', '0021_rename_product_quantity_depreciation_orderdeliveryproduct_product_depreciation_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDeliveryProductAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('product_data', models.JSONField(default=dict, help_text='data json of product')),
                ('asset_data', models.JSONField(default=dict, help_text='data json of asset')),
                ('uom_time_data', models.JSONField(default=dict, help_text='data json of uom time')),
                ('product_quantity_time', models.FloatField(default=0)),
                ('picked_quantity', models.FloatField(default=0, verbose_name='Quantity was delivered')),
                ('product_depreciation_subtotal', models.FloatField(default=0)),
                ('product_depreciation_price', models.FloatField(default=0)),
                ('product_depreciation_method', models.SmallIntegerField(default=0)),
                ('product_depreciation_adjustment', models.FloatField(default=0)),
                ('product_depreciation_time', models.FloatField(default=0)),
                ('product_depreciation_start_date', models.DateField(null=True)),
                ('product_depreciation_end_date', models.DateField(null=True)),
                ('product_lease_start_date', models.DateField(null=True)),
                ('product_lease_end_date', models.DateField(null=True)),
                ('depreciation_data', models.JSONField(default=list, help_text='data json of depreciation')),
                ('quantity_remain_recovery', models.FloatField(default=0, help_text='minus when recovery')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_pa_asset', to='asset.fixedasset', verbose_name='asset')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
            ],
            options={
                'verbose_name': 'Delivery Product Asset',
                'verbose_name_plural': 'Delivery Products Asset',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.RenameField(
            model_name='orderdeliveryproduct',
            old_name='product_unit_price',
            new_name='product_cost',
        ),
        migrations.RenameField(
            model_name='orderdeliveryproduct',
            old_name='product_subtotal_price',
            new_name='product_subtotal_cost',
        ),
        migrations.RemoveField(
            model_name='orderdeliverylot',
            name='delivery_product_leased',
        ),
        migrations.RemoveField(
            model_name='orderdeliveryproduct',
            name='product_quantity_leased',
        ),
        migrations.RemoveField(
            model_name='orderdeliveryproduct',
            name='product_quantity_leased_data',
        ),
        migrations.RemoveField(
            model_name='orderdeliveryproduct',
            name='product_quantity_new',
        ),
        migrations.RemoveField(
            model_name='orderdeliveryproduct',
            name='quantity_new_remain_recovery',
        ),
        migrations.RemoveField(
            model_name='orderdeliveryproduct',
            name='remaining_quantity_new',
        ),
        migrations.RemoveField(
            model_name='orderdeliveryproductwarehouse',
            name='delivery_product_leased',
        ),
        migrations.RemoveField(
            model_name='orderdeliveryserial',
            name='delivery_product_leased',
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='asset_data',
            field=models.JSONField(default=list, help_text='data json of asset'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='depreciation_data',
            field=models.JSONField(default=list, help_text='data json of depreciation'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='product_lease_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='product_lease_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdeliveryproduct',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_product_uom', to='saledata.unitofmeasure', verbose_name='uom'),
        ),
        migrations.DeleteModel(
            name='OrderDeliveryProductLeased',
        ),
        migrations.AddField(
            model_name='orderdeliveryproductasset',
            name='delivery_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_pa_delivery_product', to='delivery.orderdeliveryproduct', verbose_name='delivery product'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproductasset',
            name='delivery_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_pa_delivery_sub', to='delivery.orderdeliverysub', verbose_name='delivery sub'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproductasset',
            name='employee_created',
            field=models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproductasset',
            name='employee_modified',
            field=models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproductasset',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_pa_product', to='saledata.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproductasset',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproductasset',
            name='uom_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_pa_uom_time', to='saledata.unitofmeasure', verbose_name='uom time'),
        ),
    ]
