# Generated by Django 4.2.8 on 2025-04-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0024_alter_orderdeliveryproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliverysub',
            name='has_ar_invoice_already',
            field=models.BooleanField(default=False, help_text='is true if this Delivery has AR invoice'),
        ),
    ]
