# Generated by Django 4.2.8 on 2025-08-20 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseorder', '0014_leaseorderproduct_offset_show'),
        ('saledata', '0074_alter_product_description_alter_product_title'),
        ('saleorder', '0033_alter_saleorder_date_created'),
        ('delivery', '0027_alter_orderdeliverysub_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_product_tax', to='saledata.tax', verbose_name='tax'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='tax_data',
            field=models.JSONField(default=dict, help_text='data json of tax'),
        ),
        migrations.AddField(
            model_name='orderdeliverysub',
            name='lease_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_sub_lease_order', to='leaseorder.leaseorder', verbose_name='lease order'),
        ),
        migrations.AddField(
            model_name='orderdeliverysub',
            name='sale_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_sub_sale_order', to='saleorder.saleorder', verbose_name='sale order'),
        ),
    ]
