# Generated by Django 4.2.8 on 2025-08-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0028_orderdeliveryproduct_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
