# Generated by Django 4.2.8 on 2025-10-27 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceorder', '0008_rename_subtotal_price_serviceorderexpense_expense_subtotal_price_and_more'),
        ('delivery', '0030_orderdeliveryproduct_product_specific'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='service_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_of_service_order', to='serviceorder.serviceorder', verbose_name='Order Delivery of Service Order'),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='service_order_data',
            field=models.JSONField(default=dict, help_text='data json of service order', verbose_name='Service Order data'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='contribution_data',
            field=models.JSONField(default=dict, help_text='data json of contribution(service order)'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='work_data',
            field=models.JSONField(default=dict, help_text='data json of work(service order)'),
        ),
        migrations.AddField(
            model_name='orderdeliverysub',
            name='service_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_sub_service_order', to='serviceorder.serviceorder', verbose_name='service order'),
        ),
        migrations.AddField(
            model_name='orderdeliverysub',
            name='service_order_data',
            field=models.JSONField(default=dict, help_text='data json of service order', verbose_name='Service Order data'),
        ),
    ]
