# Generated by Django 4.2.8 on 2025-11-03 17:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('serviceorder', '0009_serviceorder_contact_serviceorder_contact_data_and_more'),
        ('saledata', '0086_product_is_representative_product_and_more'),
        ('tenant', '0001_initial'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('company', '0023_companyconfig_shift_companyconfig_shift_data_and_more'),
        ('delivery', '0031_orderdelivery_service_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdeliveryproduct',
            name='offset',
        ),
        migrations.AddField(
            model_name='orderdeliveryproductwarehouse',
            name='service_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_pw_service_order', to='serviceorder.serviceorder', verbose_name='service order'),
        ),
        migrations.AddField(
            model_name='orderdeliveryproductwarehouse',
            name='service_order_data',
            field=models.JSONField(default=dict, help_text='data json of service order'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='actual_delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='contact_data',
            field=models.JSONField(default=dict, verbose_name='Contact Data backup'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='customer_data',
            field=models.JSONField(default=dict, verbose_name='Customer Data backup'),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='estimated_delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdeliveryproduct',
            name='offset_data',
            field=models.JSONField(default=list, help_text='data json of offset'),
        ),
        migrations.AlterField(
            model_name='orderdeliverysub',
            name='actual_delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdeliverysub',
            name='contact_data',
            field=models.JSONField(default=dict, null=True, verbose_name='Contact Data backup'),
        ),
        migrations.AlterField(
            model_name='orderdeliverysub',
            name='customer_data',
            field=models.JSONField(default=dict, null=True, verbose_name='Customer Data backup'),
        ),
        migrations.AlterField(
            model_name='orderdeliverysub',
            name='delivery_logistic',
            field=models.JSONField(default=list, null=True, verbose_name='delivery shipping and billing address'),
        ),
        migrations.AlterField(
            model_name='orderdeliverysub',
            name='estimated_delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdeliverysub',
            name='is_updated',
            field=models.BooleanField(default=False, verbose_name='Sub is update'),
        ),
        migrations.CreateModel(
            name='OrderDeliveryProductOffset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('product_data', models.JSONField(default=dict, help_text='data json of product')),
                ('offset_data', models.JSONField(default=dict, help_text='data json of offset')),
                ('uom_time_data', models.JSONField(default=dict, help_text='data json of uom time')),
                ('delivery_data', models.JSONField(default=list)),
                ('product_quantity', models.FloatField(default=0)),
                ('product_quantity_time', models.FloatField(default=0)),
                ('remaining_quantity', models.FloatField(default=0, verbose_name='Quantity remain delivery')),
                ('picked_quantity', models.FloatField(default=0, verbose_name='Quantity was delivered')),
                ('product_cost', models.FloatField(default=0)),
                ('product_subtotal_cost', models.FloatField(default=0)),
                ('product_depreciation_subtotal', models.FloatField(default=0)),
                ('product_depreciation_price', models.FloatField(default=0)),
                ('product_depreciation_method', models.SmallIntegerField(default=0)),
                ('product_depreciation_adjustment', models.FloatField(default=0)),
                ('product_depreciation_time', models.FloatField(default=0)),
                ('product_depreciation_start_date', models.DateField(null=True)),
                ('product_depreciation_end_date', models.DateField(null=True)),
                ('product_lease_start_date', models.DateField(null=True)),
                ('product_lease_end_date', models.DateField(null=True)),
                ('depreciation_data', models.JSONField(default=list, help_text='data json of depreciation')),
                ('product_convert_into', models.SmallIntegerField(choices=[(1, 'Tool'), (2, 'Fixed asset')], null=True)),
                ('asset_type_data', models.JSONField(default=dict, help_text='data json of asset_type')),
                ('asset_group_manage_data', models.JSONField(default=dict, help_text='data json of asset_group_manage')),
                ('asset_group_using_data', models.JSONField(default=list, help_text='data json of asset_group_using')),
                ('tool_type_data', models.JSONField(default=dict, help_text='data json of tool_type')),
                ('tool_group_manage_data', models.JSONField(default=dict, help_text='data json of tool_group_manage')),
                ('tool_group_using_data', models.JSONField(default=list, help_text='data json of tool_group_using')),
                ('quantity_remain_recovery', models.FloatField(default=0, help_text='minus when recovery')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('delivery_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_po_delivery_product', to='delivery.orderdeliveryproduct', verbose_name='delivery product')),
                ('delivery_sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_po_delivery_sub', to='delivery.orderdeliverysub', verbose_name='delivery sub')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('offset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_po_offset', to='saledata.product', verbose_name='offset')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_po_product', to='saledata.product', verbose_name='product')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('uom_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_po_uom_time', to='saledata.unitofmeasure', verbose_name='uom time')),
            ],
            options={
                'verbose_name': 'Delivery Product Offset',
                'verbose_name_plural': 'Delivery Products Offsets',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='orderdeliveryproductwarehouse',
            name='delivery_offset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_pw_delivery_offset', to='delivery.orderdeliveryproductoffset', verbose_name='delivery offset'),
        ),
    ]
