# Generated by Django 4.2.8 on 2025-12-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0032_remove_orderdeliveryproduct_offset_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdeliverysub',
            old_name='has_ar_invoice_already',
            new_name='is_done_ar_invoice',
        ),
        migrations.AddField(
            model_name='orderdeliveryproduct',
            name='ar_value_done',
            field=models.FloatField(default=0),
        ),
    ]
