# Generated by Django 4.1.3 on 2023-12-18 09:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('businesstrip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrequest',
            name='is_clone',
            field=models.BooleanField(default=False, help_text='true if employee inherit is in other request member list', null=True, verbose_name='is clone'),
        ),
        migrations.CreateModel(
            name='BusinessRequestEmployeeOnTrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesstrip.businessrequest')),
                ('employee_on_trip_mapped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='businessrequest',
            name='employee_on_trip_list',
            field=models.ManyToManyField(related_name='all_employee_on_trip', through='businesstrip.BusinessRequestEmployeeOnTrip', to='hr.employee'),
        ),
    ]
