# Generated by Django 4.1.3 on 2023-12-18 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0005_product_available_notify_and_more'),
        ('businesstrip', '0002_businessrequest_is_clone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseitemmapbusinessrequest',
            name='tax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.tax', verbose_name=''),
        ),
    ]
