# Generated by Django 4.2.8 on 2023-12-27 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0004_remove_files_belong_to_publicfiles'),
        ('businesstrip', '0004_alter_businessrequestattachmentfile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessrequestattachmentfile',
            name='code',
        ),
        migrations.RemoveField(
            model_name='businessrequestattachmentfile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='businessrequestattachmentfile',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='businessrequestattachmentfile',
            name='employee_created',
        ),
        migrations.RemoveField(
            model_name='businessrequestattachmentfile',
            name='employee_modified',
        ),
        migrations.RemoveField(
            model_name='businessrequestattachmentfile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='businessrequestattachmentfile',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='businessrequestattachmentfile',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='businessrequestattachmentfile',
            name='title',
        ),
        migrations.AlterField(
            model_name='businessrequestattachmentfile',
            name='attachment',
            field=models.OneToOneField(help_text='Many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_files', to='attachments.files', verbose_name='Attachment files'),
        ),
    ]
