# Generated by Django 4.2.8 on 2025-12-10 11:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_companyconfig_shift_companyconfig_shift_data_and_more'),
        ('attendance', '0006_alter_attendance_shift'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('tenant', '0001_initial'),
        ('overtimerequest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtimerequest',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='overtimerequest',
            name='ot_type',
        ),
        migrations.RemoveField(
            model_name='overtimerequest',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='overtimerequest',
            name='start_date',
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='date_list',
            field=models.JSONField(default=list, help_text='[{"date": "2025-12-22", "type": "0", "shift": {}}, {"date": "2025-12-18", "type": "1", "shift": {}}, {"date": "2025-12-16", "type": "1", "shift": {}}]', verbose_name='date list of employee selected for OT'),
        ),
        migrations.AlterField(
            model_name='overtimerequest',
            name='employee_inherit_data',
            field=models.JSONField(default=dict, help_text='{"id": "uuid", "full_name": "Nguyen Van A", "group": {"id": "uuid", "title": "group aaa"}}', verbose_name='employee inherit data'),
        ),
        migrations.CreateModel(
            name='OTMapWithEmployeeShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('date', models.DateField(help_text='Date ot selected')),
                ('type', models.IntegerField(choices=[(0, 'post_shift'), (1, 'weekend'), (2, 'holiday'), (3, 'other')], default=0, verbose_name='type of overtime')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_map_with_otmap', to='hr.employee')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('overtime_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ot_map_with_employee_shift', to='overtimerequest.overtimerequest')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ot_map_with_shift_info', to='attendance.shiftinfo', verbose_name='shift')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Overtime request map with employee',
                'verbose_name_plural': 'Overtime request map with employee',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
