# Generated by Django 4.2.8 on 2025-07-12 23:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0071_pwmodified_new_description'),
        ('equipmentloan', '0002_equipmentloanitem_sum_returned_quantity_and_more'),
        ('attachments', '0012_alter_filepermission_options_and_more'),
        ('equipmentreturn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentreturn',
            name='lot_loan_items_detail',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='equipmentreturn',
            name='none_loan_items_detail',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='equipmentreturn',
            name='serial_loan_items_detail',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='EquipmentReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=1)),
                ('return_product_data', models.JSONField(default=dict)),
                ('return_product_pw_quantity', models.FloatField(default=0)),
                ('return_product_pw_lot_data', models.JSONField(default=dict)),
                ('return_product_pw_lot_quantity', models.FloatField(default=0)),
                ('return_product_pw_serial_data', models.JSONField(default=dict)),
                ('before_warehouse_data', models.JSONField(default=dict)),
                ('return_to_warehouse_data', models.JSONField(default=dict)),
                ('before_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='er_item_before_warehouse', to='saledata.warehouse')),
                ('equipment_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_return_items', to='equipmentreturn.equipmentreturn')),
                ('loan_item_detail_mapped', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipmentloan.equipmentloanitemdetail')),
                ('return_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.product')),
                ('return_product_pw', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.productwarehouse')),
                ('return_product_pw_lot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.productwarehouselot')),
                ('return_product_pw_serial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.productwarehouseserial')),
                ('return_to_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='er_item_return_to_warehouse', to='saledata.warehouse')),
            ],
            options={
                'verbose_name': 'Equipment Return Item',
                'verbose_name_plural': 'Equipment Return Items',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EquipmentLoanAttachmentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('attachment', models.OneToOneField(help_text='Many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_files', to='attachments.files', verbose_name='Attachment files')),
                ('equipment_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_return_attachments', to='equipmentreturn.equipmentreturn')),
            ],
            options={
                'verbose_name': 'Equipment Return attachment',
                'verbose_name_plural': 'Equipment Return attachments',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
