# Generated by Django 4.2.8 on 2024-08-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bommaterialcomponent',
            name='subtotal_price',
        ),
        migrations.RemoveField(
            model_name='bommaterialcomponent',
            name='unit_price',
        ),
    ]
