# Generated by Django 4.2.8 on 2024-08-29 10:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_remove_company_email_app_password_and_more'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('saledata', '0034_producttype_is_asset_tool_and_more'),
        ('space', '0001_initial'),
        ('saleorder', '0019_saleordercost_supplied_by'),
        ('tenant', '0001_initial'),
        ('workflow', '0006_alter_association_date_modified_and_more'),
        ('process', '0002_alter_salefunction_date_modified'),
        ('production', '0003_alter_bom_date_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('is_change', models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents')),
                ('document_root_id', models.UUIDField(help_text='this is id of root document of the changed documents', null=True)),
                ('document_change_order', models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('bom_data', models.JSONField(default=dict, help_text='data json of bom')),
                ('type_production', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Production'), (1, 'Assembly'), (2, 'Disassembly'))")),
                ('product_data', models.JSONField(default=dict, help_text='data json of product')),
                ('quantity', models.FloatField(default=0, help_text='quantity order')),
                ('uom_data', models.JSONField(default=dict, help_text='data json of uom')),
                ('warehouse_data', models.JSONField(default=dict, help_text='data json of warehouse')),
                ('sale_order_data', models.JSONField(default=list, help_text='data json of SO, records in ProductionOrderSaleOrder')),
                ('status_production', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Planned'), (1, 'In production'), (2, 'Done'))")),
                ('date_start', models.DateField(null=True)),
                ('date_end', models.DateField(null=True)),
                ('group_data', models.JSONField(default=dict, help_text='data json of group')),
                ('time', models.FloatField(default=0, help_text='total time for production')),
                ('task_data', models.JSONField(default=list, help_text='data json of task, records in ProductionOrderTask')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_order_bom', to='production.bom', verbose_name='bom')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('current_stage', models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_order_group', to='hr.group', verbose_name='group')),
                ('next_node_collab', models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee')),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_order_product', to='saledata.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Production order',
                'verbose_name_plural': 'Production orders',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_task', models.BooleanField(default=False, help_text='flag to know this record is task')),
                ('task_title', models.CharField(blank=True, max_length=100)),
                ('task_order', models.IntegerField(default=1)),
                ('product_data', models.JSONField(default=dict, help_text='data json of product')),
                ('uom_data', models.JSONField(default=dict, help_text='data json of uom')),
                ('quantity_bom', models.FloatField(default=0)),
                ('quantity', models.FloatField(default=0)),
                ('is_all_warehouse', models.BooleanField(default=False, help_text='flag to know can use this product of all warehouse')),
                ('warehouse_data', models.JSONField(default=dict, help_text='data json of warehouse')),
                ('stock', models.FloatField(default=0)),
                ('available', models.FloatField(default=0)),
                ('tool_data', models.JSONField(default=list, help_text='data json of tool, records in ProductionOrderTaskTool')),
                ('order', models.IntegerField(default=1)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_task_product', to='saledata.product', verbose_name='product')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_task_production_order', to='production.productionorder', verbose_name='production order')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Production Order Task',
                'verbose_name_plural': 'Production Order Tasks',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderTaskTool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_task_tool_task', to='production.productionordertask', verbose_name='production order task')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_task_tool_tool', to='saledata.product', verbose_name='tool')),
            ],
            options={
                'verbose_name': 'Production Order Task Tool',
                'verbose_name_plural': 'Production Order Task Tools',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='productionordertask',
            name='tool',
            field=models.ManyToManyField(blank=True, related_name='production_order_map_so', through='production.ProductionOrderTaskTool', to='saledata.product'),
        ),
        migrations.AddField(
            model_name='productionordertask',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_task_uom', to='saledata.unitofmeasure', verbose_name='uom'),
        ),
        migrations.AddField(
            model_name='productionordertask',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_task_warehouse', to='saledata.warehouse', verbose_name='warehouse'),
        ),
        migrations.CreateModel(
            name='ProductionOrderSaleOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_sale_order_production', to='production.productionorder', verbose_name='production order')),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_sale_order_so', to='saleorder.saleorder', verbose_name='sale order')),
            ],
            options={
                'verbose_name': 'Production Sale Order',
                'verbose_name_plural': 'Production Sale Orders',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='productionorder',
            name='sale_order',
            field=models.ManyToManyField(blank=True, related_name='production_order_map_so', through='production.ProductionOrderSaleOrder', to='saleorder.saleorder'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_order_uom', to='saledata.unitofmeasure', verbose_name='uom'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_order_warehouse', to='saledata.warehouse', verbose_name='warehouse'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
    ]
