# Generated by Django 4.2.8 on 2024-09-13 10:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_email_app_password_and_more'),
        ('saledata', '0037_account_is_competitor_account_and_more'),
        ('space', '0001_initial'),
        ('process', '0002_alter_salefunction_date_modified'),
        ('tenant', '0001_initial'),
        ('workflow', '0006_alter_association_date_modified_and_more'),
        ('company', '0011_remove_company_email_app_password_and_more'),
        ('production', '0005_bom_for_outsourcing_alter_bommaterialcomponent_uom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))")),
                ('date_approved', models.DateTimeField(help_text='The record created when WF of document is finished', null=True)),
                ('current_stage_title', models.CharField(blank=True, help_text='Title of WF current stage of document', max_length=100)),
                ('is_change', models.BooleanField(default=False, help_text='flag to know this document is the changed, include root document and change documents')),
                ('document_root_id', models.UUIDField(help_text='this is id of root document of the changed documents', null=True)),
                ('document_change_order', models.IntegerField(help_text='this is order of changed document from root document, start from 1,2,3...', null=True)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('production_order_data', models.JSONField(default=dict, help_text='data json of production order')),
                ('product_data', models.JSONField(default=dict, help_text='data json of product')),
                ('quantity', models.FloatField(default=0, help_text='quantity from production order')),
                ('uom_data', models.JSONField(default=dict, help_text='data json of uom')),
                ('warehouse_data', models.JSONField(default=dict, help_text='data json of warehouse')),
                ('quantity_finished', models.FloatField(default=0, help_text='quantity finished')),
                ('quantity_ng', models.FloatField(default=0, help_text='quantity not good')),
                ('task_data', models.JSONField(default=list, help_text='data json of task, records in ProductionReportTask')),
                ('gr_remain_quantity', models.FloatField(default=0, help_text='this is quantity of product which is not goods receipted yet, update when GR finish')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('current_stage', models.ForeignKey(help_text='Relate to RuntimeStage Model is running WF of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtimestage', verbose_name='Current WF stage of Doc')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('next_node_collab', models.ForeignKey(help_text='employee that selected for next node defined as type out form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_collab_out_form', to='hr.employee')),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_report_product', to='saledata.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Production report',
                'verbose_name_plural': 'Production reports',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='productionorder',
            name='gr_remain_quantity',
            field=models.FloatField(default=0, help_text='this is quantity of product which is not goods receipted yet, update when GR finish'),
        ),
        migrations.CreateModel(
            name='ProductionReportTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_task', models.BooleanField(default=False, help_text='flag to know this record is task')),
                ('task_title', models.CharField(blank=True, max_length=100)),
                ('task_order', models.IntegerField(default=1)),
                ('product_data', models.JSONField(default=dict, help_text='data json of product')),
                ('uom_data', models.JSONField(default=dict, help_text='data json of uom')),
                ('quantity', models.FloatField(default=0)),
                ('quantity_actual', models.FloatField(default=0)),
                ('order', models.IntegerField(default=1)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_task_product', to='saledata.product', verbose_name='product')),
                ('production_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr_task_production_report', to='production.productionreport', verbose_name='production report')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_task_uom', to='saledata.unitofmeasure', verbose_name='uom')),
            ],
            options={
                'verbose_name': 'Production Report Task',
                'verbose_name_plural': 'Production Report Tasks',
                'ordering': ('order',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='productionreport',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_report_production_order', to='production.productionorder', verbose_name='production order'),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_report_uom', to='saledata.unitofmeasure', verbose_name='uom'),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_report_warehouse', to='saledata.warehouse', verbose_name='warehouse'),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='workflow_runtime',
            field=models.ForeignKey(help_text='Relate to Runtime Model is running flow of doc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.runtime', verbose_name='Runtime Obj of Doc'),
        ),
    ]
