# Generated by Django 4.2.8 on 2024-09-14 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0011_alter_opportunity_date_modified'),
        ('production', '0006_productionreport_productionorder_gr_remain_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='opportunity_mapped',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_opportunity_mapped', to='opportunity.opportunity'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='bom_type',
            field=models.SmallIntegerField(choices=[(0, 'For production'), (1, 'For service'), (2, 'For sale'), (3, 'For internal expense'), (4, 'For project')], default=0),
        ),
    ]
