# Generated by Django 4.2.8 on 2024-09-17 13:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0037_account_is_competitor_account_and_more'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('opportunity', '0011_alter_opportunity_date_modified'),
        ('tenant', '0001_initial'),
        ('company', '0012_company_icon'),
        ('production', '0007_bom_opportunity_mapped_alter_bom_bom_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='opportunity_mapped',
        ),
        migrations.AddField(
            model_name='bom',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_opportunity', to='opportunity.opportunity'),
        ),
        migrations.CreateModel(
            name='BOMReplacementMaterialComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('quantity', models.FloatField(default=0)),
                ('disassemble', models.BooleanField(default=False)),
                ('note', models.TextField()),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_replacement_material_component_bom', to='production.bom')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_replacement_material_component_material', to='saledata.product')),
                ('replace_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_replacement_replace_for', to='production.bommaterialcomponent')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_replacement_material_component_uom', to='saledata.unitofmeasure')),
            ],
            options={
                'verbose_name': 'BOM replacement material component',
                'verbose_name_plural': 'BOM replacement materials components',
                'ordering': (),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
