# Generated by Django 4.2.8 on 2024-09-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_bommaterialcomponent_replacement_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='done_issue',
            field=models.BooleanField(default=False),
        ),
    ]
