# Generated by Django 4.2.8 on 2024-09-24 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_workorder_workordertask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreport',
            name='production_report_type',
            field=models.SmallIntegerField(default=0, help_text="choices= ((0, 'For production order'), (1, 'For work order'))"),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='work_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_report_work_order', to='production.workorder', verbose_name='work order'),
        ),
        migrations.AddField(
            model_name='productionreport',
            name='work_order_data',
            field=models.JSONField(default=dict, help_text='data json of work order'),
        ),
        migrations.AlterField(
            model_name='productionreport',
            name='production_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_report_production_order', to='production.productionorder', verbose_name='production order'),
        ),
    ]
