# Generated by Django 4.2.8 on 2024-10-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_workorder_done_issue_workordertask_issued_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='done_issue',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='done_issue',
        ),
    ]
