# Generated by Django 4.2.8 on 2024-10-02 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_remove_productionorder_done_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bommaterialcomponent',
            name='bom_process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_material_component_bom_process', to='production.bomprocess'),
        ),
    ]
