# Generated by Django 4.2.8 on 2024-11-18 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0045_alter_documenttype_options_documenttype_is_default'),
        ('purchasing', '0011_purchaseorder_next_association_and_more'),
        ('production', '0018_bom_next_association_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='purchase_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_order_purchase_order', to='purchasing.purchaseorder', verbose_name='purchase order'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='purchase_order_data',
            field=models.JSONField(default=dict, help_text='data json of purchase order'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_order_account', to='saledata.account', verbose_name='account'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='supplier_data',
            field=models.JSONField(default=dict, help_text='data json of supplier'),
        ),
    ]
