# Generated by Django 4.2.8 on 2024-11-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_productionorder_purchase_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='bom_type',
            field=models.SmallIntegerField(choices=[(0, 'For production'), (1, 'For service'), (2, 'For sale'), (3, 'For internal expense'), (4, 'For opportunity')], default=0),
        ),
    ]
