# Generated by Django 4.2.8 on 2025-01-09 10:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0004_employee_email_app_password_and_more'),
        ('tenant', '0001_initial'),
        ('saledata', '0050_periods_end_date'),
        ('lead', '0009_alter_leadopportunity_options'),
        ('company', '0015_companybankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerPageToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('token', models.TextField(blank=True, help_text='Facebook Token was encrypted', null=True)),
                ('category', models.TextField(blank=True, help_text='Category response')),
                ('name', models.TextField(blank=True, help_text='Name response')),
                ('account_id', models.CharField(max_length=50)),
                ('tasks', models.JSONField(default=list, help_text='Task response')),
                ('picture', models.JSONField(default=dict, help_text='Pictures of page', null=True)),
                ('link', models.TextField(help_text='Link to page', null=True)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Messenger Account Token',
                'verbose_name_plural': 'Messenger Account Token',
                'ordering': ('-name',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MessengerToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('token', models.TextField(blank=True, help_text='Facebook Token was encrypted', null=True)),
                ('expires', models.DateTimeField(help_text='Time expired of token', null=True)),
                ('is_syncing', models.BooleanField(default=False)),
                ('is_sync_accounts', models.BooleanField(default=False)),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messenger_token_of_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Messenger Token',
                'verbose_name_plural': 'Messenger Token',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MessengerPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('account_id', models.CharField(max_length=50)),
                ('name', models.TextField(blank=True, help_text='Name of sender')),
                ('avatar', models.TextField(blank=True, help_text='Avatar of sender')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('link', models.TextField(blank=True, help_text='Link to Profile')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='saledata.contact')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lead.lead')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat3rd.messengerpagetoken')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Messenger Account Server',
                'verbose_name_plural': 'Messenger Account Server',
                'ordering': ('-last_updated',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='messengerpagetoken',
            name='parent',
            field=models.ForeignKey(help_text='Account Token from parent token', on_delete=django.db.models.deletion.CASCADE, to='chat3rd.messengertoken'),
        ),
        migrations.AddField(
            model_name='messengerpagetoken',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
        migrations.CreateModel(
            name='MessengerMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('sender', models.CharField(blank=True, help_text='Sender ID', max_length=50)),
                ('recipient', models.CharField(blank=True, help_text='Recipient ID', max_length=50)),
                ('mid', models.TextField(help_text='Message ID')),
                ('text', models.TextField(blank=True, help_text='Message')),
                ('attachments', models.JSONField(default=list, help_text='Attachments')),
                ('is_echo', models.BooleanField(default=False, help_text='True is send from page')),
                ('timestamp', models.BigIntegerField(help_text='Epoch unix time')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat3rd.messengerpagetoken')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat3rd.messengerperson')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Messenger Sender Message',
                'verbose_name_plural': 'Messenger Sender Message',
                'ordering': ('-timestamp',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
