# Generated by Django 4.1.3 on 2023-03-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttype',
            options={'default_permissions': (), 'ordering': ('code',), 'permissions': (), 'verbose_name': 'AccountType', 'verbose_name_plural': 'AccountTypes'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'default_permissions': (), 'ordering': ('code',), 'permissions': (), 'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterModelOptions(
            name='interest',
            options={'default_permissions': (), 'ordering': ('code',), 'permissions': (), 'verbose_name': 'Interest', 'verbose_name_plural': 'Interests'},
        ),
        migrations.AlterModelOptions(
            name='salutation',
            options={'default_permissions': (), 'ordering': ('code',), 'permissions': (), 'verbose_name': 'Salutation', 'verbose_name_plural': 'Salutations'},
        ),
    ]
