# Generated by Django 4.1.3 on 2023-03-02 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='account_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='saledata.account', verbose_name='account_name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='report_to',
            field=models.UUIDField(blank=True, help_text='employee', null=True),
        ),
    ]
