# Generated by Django 4.1.3 on 2023-04-14 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
        ('process', '0001_initial'),
        ('hr', '0001_initial'),
        ('tenant', '0001_initial'),
        ('company', '0003_alter_companyuseremployee_employee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saledata', '0002_taxcategory_tax_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('system_status', models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel')], default=0)),
                ('system_remarks', jsonfield.fields.JSONField(default={})),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('auto_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('factor', models.FloatField()),
                ('currency', models.JSONField(default=list)),
                ('price_list_type', models.IntegerField()),
                ('price_list_mapped', models.UUIDField(null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_inherit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='User modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
                'ordering': ('date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='employee_inherit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_inherit', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='product',
            name='process',
            field=models.ForeignKey(help_text='The process claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_process', to='process.process'),
        ),
        migrations.AddField(
            model_name='product',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='product',
            name='system_remarks',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='product',
            name='system_status',
            field=models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel')], default=0),
        ),
        migrations.CreateModel(
            name='ProductPriceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('get_price_from_source', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('currency_using', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.currency')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.product')),
                ('uom_group_using', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.unitofmeasuregroup')),
                ('uom_using', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.unitofmeasure')),
            ],
            options={
                'verbose_name': 'ProductPriceList',
                'verbose_name_plural': 'ProductsPriceList',
                'ordering': ('date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='price_map_product', through='saledata.ProductPriceList', to='saledata.product'),
        ),
        migrations.AddField(
            model_name='price',
            name='space',
            field=models.ForeignKey(help_text='The space claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_space', to='space.space'),
        ),
        migrations.AddField(
            model_name='price',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant'),
        ),
    ]
