# Generated by Django 4.1.3 on 2023-04-18 11:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saledata', '0004_paymentterm_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency_using', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.currency')),
                ('default_uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.unitofmeasure')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.product')),
                ('tax_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.tax')),
            ],
            options={
                'verbose_name': 'Product Sale',
                'verbose_name_plural': 'Products Sale',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inventory_min', models.IntegerField(null=True)),
                ('inventory_max', models.IntegerField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.product')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Product Inventory',
                'verbose_name_plural': 'Products Inventory',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProductGeneral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.product')),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.productcategory')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.producttype')),
                ('uom_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.unitofmeasuregroup')),
            ],
            options={
                'verbose_name': 'Product General',
                'verbose_name_plural': 'Products General',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
