# Generated by Django 4.1.3 on 2023-03-21 16:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_alter_employee_managers_alter_group_managers_and_more'),
        ('saledata', '0004_remove_accounttype_user_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='additional_infor',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address_infor',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='bio',
        ),
        migrations.AddField(
            model_name='contact',
            name='additional_information',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_information',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='contact',
            name='biography',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='annual_revenue',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='annual revenue of account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='billing_address',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='account code'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='account email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='manager',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='account name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent_account',
            field=models.CharField(max_length=150, null=True, verbose_name='parent account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='account phone number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='shipping_address',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='account',
            name='tax_code',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='tax code'),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_employees',
            field=models.CharField(max_length=150, verbose_name='total employees of account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='website',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='account website'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='account_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_account_name', to='saledata.account', verbose_name='account name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='contact email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fullname',
            field=models.CharField(max_length=150, verbose_name='contact fullname'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='is account owner'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='job_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='contact job title'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='contact mobile'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='owner',
            field=models.UUIDField(help_text='employee is contact owner'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='contact phone number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='report_to',
            field=models.UUIDField(blank=True, help_text='report to a contact', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='salutation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='saledata.salutation'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='interest',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='salutation',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='AccountEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.account')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='account',
            name='employee',
            field=models.ManyToManyField(blank=True, related_name='account_map_employee', through='saledata.AccountEmployee', to='hr.employee'),
        ),
    ]
