# Generated by Django 4.1.3 on 2023-05-04 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant', '0001_initial'),
        ('company', '0004_companyconfig'),
        ('hr', '0001_initial'),
        ('saledata', '0005_productsale_productinventory_productgeneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('general_information', models.JSONField(default=dict, help_text='information of tab general for Expense')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='User modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ExpenseGeneral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='saledata.expense')),
                ('expense_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_type', to='saledata.expensetype', verbose_name='Type of Expense')),
            ],
            options={
                'verbose_name': 'Expense General',
                'verbose_name_plural': 'Expenses General',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='price',
            name='valid_time_end',
            field=models.DateTimeField(default='9999-01-01 00:00:00.00', null=True, verbose_name='price list will be end at valid_time_end'),
        ),
        migrations.AddField(
            model_name='price',
            name='valid_time_start',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='price list will be apply since valid_time_start'),
        ),
        migrations.CreateModel(
            name='ExpensePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_auto_update', models.BooleanField(default=False)),
                ('price_value', models.FloatField()),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_price_currency', to='saledata.currency', verbose_name='Currency using for expense in price list')),
                ('expense_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.expensegeneral')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saledata.price')),
                ('uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_price_uom', to='saledata.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Expense Price',
                'verbose_name_plural': 'Expense Prices',
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='expensegeneral',
            name='price_list',
            field=models.ManyToManyField(blank=True, related_name='expenses_map_prices', through='saledata.ExpensePrice', to='saledata.price'),
        ),
        migrations.AddField(
            model_name='expensegeneral',
            name='tax_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_tax_code', to='saledata.tax', verbose_name='Tax Code apply for expense'),
        ),
        migrations.AddField(
            model_name='expensegeneral',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_uom', to='saledata.unitofmeasure', verbose_name='Unit of Measure apply for expense'),
        ),
        migrations.AddField(
            model_name='expensegeneral',
            name='uom_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_uom_group', to='saledata.unitofmeasuregroup', verbose_name='Unit of Measure Group apply for expense'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='User modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
