# Generated by Django 4.2.8 on 2024-11-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_processactivity_processconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processdoc',
            name='date_status',
            field=models.JSONField(default=list, help_text='[{"status": 0, "datetime": ""},]'),
        ),
        migrations.AddField(
            model_name='processdoc',
            name='system_status',
            field=models.SmallIntegerField(default=0, help_text="choices= ((0, 'Draft'), (1, 'Created'), (2, 'Added'), (3, 'Finish'), (4, 'Cancel'))"),
        ),
        migrations.AddField(
            model_name='processstageapplication',
            name='amount_approved',
            field=models.SmallIntegerField(default=0),
        ),
    ]
