# Generated by Django 4.2.8 on 2024-11-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_processdoc_date_status_processdoc_system_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstageapplication',
            name='order_number',
            field=models.SmallIntegerField(default=1),
        ),
    ]
