# Generated by Django 4.2.8 on 2024-11-27 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_processstageapplication_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='global_app',
            field=models.JSONField(default=list, verbose_name='Cross-Stage Applications'),
        ),
        migrations.AddField(
            model_name='processconfiguration',
            name='global_app',
            field=models.JSONField(default=list, verbose_name='Cross-Stage Applications'),
        ),
        migrations.AlterField(
            model_name='processstageapplication',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='process.processstage'),
        ),
    ]
