# Generated by Django 4.2.8 on 2024-12-02 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_alter_processmembers_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='processactivity',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='process.processstageapplication'),
        ),
    ]
