# Generated by Django 4.2.8 on 2024-12-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_processactivity_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='processmembers',
            name='is_system',
            field=models.BooleanField(default=False, help_text='End users cannot act on this if this field is enabled. Only the system can change it.'),
        ),
        migrations.AddField(
            model_name='processstageapplication',
            name='created_full',
            field=models.BooleanField(default=False, help_text='Status: Maximum number of creations allowed has been reached'),
        ),
    ]
