# Generated by Django 4.2.8 on 2025-01-08 15:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0018_applicationproperty_is_filter_condition'),
        ('company', '0015_companybankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.application')),
            ],
            options={
                'permissions': (),
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('filter_condition', models.JSONField(default=list)),
                ('num_of_records', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.company')),
                ('data_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnercenter.dataobject')),
            ],
            options={
                'verbose_name': 'Partner List',
                'verbose_name_plural': 'Partner Lists',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
