# Generated by Django 4.2.8 on 2025-01-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_applicationproperty_is_filter_condition'),
        ('partnercenter', '0002_list_code_list_date_modified_list_employee_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.application'),
        ),
        migrations.AlterField(
            model_name='list',
            name='data_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partnercenter.dataobject'),
        ),
    ]
