# Generated by Django 4.2.8 on 2024-11-18 15:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0017_application_allow_recurrence'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('tenant', '0001_initial'),
        ('company', '0013_alter_companyconfig_default_inventory_value_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now_add=True, help_text='Date modified this record in last')),
                ('citizen_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='citizen identification')),
                ('date_of_issue', models.DateField(blank=True, null=True, verbose_name='Date of issue')),
                ('place_of_issue', models.CharField(blank=True, help_text='The place of issue refers to the city where the passport processing took place', max_length=150, null=True, verbose_name='place of issue')),
                ('ethnicity', models.CharField(blank=True, help_text='a group of people who identify with each other', max_length=50, null=True)),
                ('religion', models.CharField(blank=True, help_text='the belief in the existence of a god or gods', max_length=50, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Man'), (1, 'Woman'), (2, 'Other')], null=True)),
                ('marital_status', models.IntegerField(blank=True, choices=[(0, 'Married'), (1, 'Widowed'), (2, 'Separated'), (3, 'Divorced'), (4, 'Single'), (5, 'Engaged')], null=True)),
                ('bank_acc_no', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Bank account number')),
                ('acc_name', models.CharField(blank=True, help_text='account name', max_length=50, null=True)),
                ('bank_name', models.IntegerField(blank=True, choices=[(0, 'VBSP'), (1, 'VDP'), (3, 'Agribank'), (4, 'CB'), (5, 'Oceanbank'), (6, 'GPBank'), (7, 'BIDV'), (8, 'Vietcombank'), (9, 'Vietinbank'), (10, 'VPBank'), (11, 'MB'), (12, 'ACB'), (13, 'SHB'), (14, 'Techcombank'), (15, 'HDBank'), (16, 'LPBank'), (17, 'VIB'), (18, 'SeABank'), (19, 'TPBank'), (20, 'OCB'), (21, 'SCB'), (22, 'MSB'), (23, 'Sacombank'), (24, 'Eximbank'), (25, 'NCB'), (26, 'NamABank'), (27, 'ABBank'), (28, 'PVComBank'), (29, 'BacABank'), (30, 'VietBank'), (31, 'VAB'), (32, 'BVBank'), (33, 'DongABank'), (34, 'KLB'), (35, 'SaigonBank'), (36, 'Baoviet'), (37, 'PGBank'), (38, 'ShinhanBank'), (39, 'HSBC'), (40, 'StanChart'), (41, 'WooriBank'), (42, 'CIMB'), (43, 'PublicBank'), (44, 'HongLeongBank'), (45, 'UOB'), (46, 'Citibank'), (47, 'KBank'), (48, 'BangkokBank'), (49, 'DeutscheBank')], null=True)),
                ('tax_code', models.CharField(blank=True, help_text='tax identification numbers', max_length=50, null=True)),
                ('permanent_address', models.CharField(blank=True, help_text='frequently lived address', max_length=50, null=True)),
                ('current_resident', models.CharField(blank=True, help_text='Means the person who resides here currently', max_length=50, null=True)),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_info', to='hr.employee')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nationality_employee_info_set', to='base.country', verbose_name='Nationality')),
                ('place_of_birth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pob_employee_info', to='base.city', verbose_name='Place of birth')),
                ('place_of_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.city')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Employee Info',
                'verbose_name_plural': 'Employee Info',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('effected_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start date')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Employee contract',
                'verbose_name_plural': 'Employee contract',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EmployeeHRNotMapEmployeeHRM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_mapped', models.BooleanField(default=False, verbose_name='company employee mapped to employee HRM')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_hr', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Employee HR Map Employee HRM',
                'verbose_name_plural': 'Employee HR Map Employee HRM',
                'ordering': ('is_mapped',),
                'permissions': (),
                'default_permissions': (),
                'unique_together': {('company', 'employee')},
            },
        ),
    ]
