# Generated by Django 4.2.8 on 2024-11-27 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0009_alter_files_file_type_alter_publicfiles_file_type'),
        ('hr', '0004_employee_email_app_password_and_more'),
        ('employeeinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontract',
            name='attachment',
            field=models.JSONField(default=list, help_text='["uuid4", "uuid4"]', null=True, verbose_name='Attachment file'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='contract_type',
            field=models.SmallIntegerField(choices=[(0, 'Probationary contract'), (1, 'Labor contract'), (2, 'Addendum contract')], default=0),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='employee_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_map_employee_info', to='employeeinfo.employeeinfo'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='expired_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expired date'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='file_type',
            field=models.SmallIntegerField(default=0, help_text='0: attach file, 1: online file'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='limit_time',
            field=models.BooleanField(default=True, verbose_name='limited time of contract'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='represent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_represent', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='sign_status',
            field=models.SmallIntegerField(default=0, help_text='0: unsigned, 1: signed'),
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='signing_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='signing date'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='effected_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='effected date'),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='current_resident',
            field=models.CharField(blank=True, help_text='Means the person who resides here currently', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='permanent_address',
            field=models.CharField(blank=True, help_text='frequently lived address', max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeContractMapAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('attachment', models.OneToOneField(help_text='Many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_files', to='attachments.files', verbose_name='Attachment files')),
                ('employee_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.employeecontract', verbose_name='Attachment file of Employee contract')),
            ],
            options={
                'verbose_name': 'Employee info attachments',
                'verbose_name_plural': 'Employee info attachments',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='employeecontract',
            name='attachment_m2m',
            field=models.ManyToManyField(blank=True, related_name='file_of_employee_contract', through='employeeinfo.EmployeeContractMapAttachment', to='attachments.files'),
        ),
    ]
