# Generated by Django 4.2.8 on 2024-12-11 16:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0009_alter_files_file_type_alter_publicfiles_file_type'),
        ('employeeinfo', '0002_employeecontract_attachment_employeecontract_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfo',
            name='attachment',
            field=models.JSONField(default=list, help_text='["uuid4", "uuid4"]', null=True, verbose_name='Attachment file'),
        ),
        migrations.CreateModel(
            name='EmployeeMapSignatureAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.SmallIntegerField(default=1)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('attachment', models.OneToOneField(help_text='Many attachment file', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_files', to='attachments.files', verbose_name='Attachment files')),
                ('employee_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.employeeinfo', verbose_name='Employee info')),
            ],
            options={
                'verbose_name': 'Employee info attachments',
                'verbose_name_plural': 'Employee info attachments',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='attachment_m2m',
            field=models.ManyToManyField(blank=True, related_name='signature_of_employee_info', through='employeeinfo.EmployeeMapSignatureAttachment', to='attachments.files'),
        ),
    ]
