# Generated by Django 4.2.8 on 2025-03-06 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_email_app_password_and_more'),
        ('tenant', '0001_initial'),
        ('company', '0016_companyconfig_accounting_policies_and_more'),
        ('employeeinfo', '0003_employeeinfo_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontract',
            name='content_info',
            field=models.JSONField(default=dict, help_text='{"sign_01": ["emp_01_id", "emp_02_id"], "sign_02": ["emp_01_id", "emp_02_id"]}', verbose_name='contract info via config'),
        ),
        migrations.AlterField(
            model_name='employeecontract',
            name='sign_status',
            field=models.SmallIntegerField(default=0, help_text='0: unsigned, 1: signing, 2: signed'),
        ),
        migrations.CreateModel(
            name='EmployeeContractRuntime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The record created at value')),
                ('date_modified', models.DateTimeField(auto_now=True, help_text='Date modified this record in last')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('members', models.JSONField(default=list, help_text='["employee_01_id", "employee_01_id"]', verbose_name='members assignee')),
                ('contract', models.TextField(blank=True)),
                ('signatures', models.JSONField(default=dict, help_text='{"sign_01": {"assignee": ["emp_01_id", "emp_02_id"], "stt": "boolean", "signed_by": "employee_id", "sign_image": "base64 code"}, "sign_02": {"assignee": ["emp_01_id", "emp_02_id"], "stt": "boolean", "signed_by": "employee_id", "sign_image": "base64 code"}}', verbose_name='signatures parameter of contract')),
                ('contract_status', models.SmallIntegerField(default=0, help_text='0: Signing, 1: Finished')),
                ('company', models.ForeignKey(help_text='The company claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_company', to='company.company')),
                ('employee_contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runtime_of_contract', to='employeeinfo.employeecontract')),
                ('employee_created', models.ForeignKey(help_text='Employee created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_creator', to='hr.employee')),
                ('employee_modified', models.ForeignKey(help_text='Employee modified this record in last', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_employee_modifier', to='hr.employee')),
                ('tenant', models.ForeignKey(help_text='The tenant claims that this record belongs to them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_belong_to_tenant', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Contract runtime',
                'verbose_name_plural': 'Contract runtime',
                'ordering': ('-date_created',),
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
