# Generated by Django 4.2.8 on 2025-10-27 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_nprovince_nward'),
        ('employeeinfo', '0005_employeecontract_employee_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='place_of_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pob_employee_info', to='base.nprovince', verbose_name='Place of birth'),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='place_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.nprovince'),
        ),
    ]
